### ISSUE TITLE
Large differences in amount of sessions with "moloch-capture -R"

### ISSUE THREAD

**Issue by G1tClub** [aol/moloch#1002]
**Moloch version**: 1.7.0 
**OS name and version**: Ubuntu 18.04
**How was Moloch built/installed:**  Deb
**Provide logs, stack traces and steps to reproduce**:

I am importing files from a mounted directory (59 pcap files, about 1Gb size each). If I use this command "sudo /data/moloch/bin/moloch-capture -R /mnt/pcapdata/" for importing static pcap files, I have different results each time (very unreliable results). I ran this test three times to make a comparison. Between the tests I ofcourse deleted the input of the ES database with: "sudo /data/moloch/db/db.pl localhost:9200 wipe". 

After each test I compared the results, shown below:
 
**Query 1 (a query with timeframe ALL and a specific filter)**
Result 1: 7 entries
Result 2: 8 entries
Result 3: 8 entries
 
**Query 2(a query with timeframe ALL and a specific filter)**
Result 1: 158 entries
Result 2: 161 entries
Result 3: 162 entries
 
**Query 3 (a query with timeframe ALL and NO filter)**
Result 1: 259.704 entries
Result 2: 266.444 entries
Result 3: 263.653 entries
 
After that I tried to import with my own script the exact same files:

```
#!/bin/bash
counter=0
file=()
for f in $(find /mnt/pcapdata/ -name '*.pcap' | sort); do
        file[$counter]=$f
        ((counter++))
done
 
for f in $(curl -s 'localhost:9200/files_v5/_search?q=*&pretty&size=10000' | jq -r '.hits.hits[]._source.name' | sort); do
        file[$counter]=$f
        ((counter++))
done
 
unique_file=($(echo "${file[@]}" | tr ' ' '\n' | sort | uniq --unique | tr '\n' ' '))
 
for f in "${unique_file[@]}"; do
        sudo /data/moloch/bin/moloch-capture -r $f >> /data/moloch/logs/auto_add_files_log.txt 2>&1;
done
```

I did this three times and in the results below you can see that they are totally different from "Moloch-capture -R", but that they are the same three times:

**Query 1 (a query with timeframe ALL and a specific filter)**
Result 1: 10 entries
Result 2: 10 entries
Result 3: 10 entries
 
**Query 2(a query with timeframe ALL and a specific filter)**
Result 1: 165 entries
Result 2: 165 entries
Result 3: 165 entries
 
**Query 3 (a query with timeframe ALL and NO filter)**
Result 1: 447.969 entries
Result 2: 447.969 entries
Result 3: 447.969 entries

**Comment by awick** [comment]
What is in the capture log file?  No errors?  Can you include the last few instances of lines with `moloch_packet_log` in it.

**Comment by G1tClub** [comment]
I didn't see any log files in /data/moloch/logs except for viewer.log. So there is no capture.log in this directory available. I did reran the test "sudo /data/moloch/bin/moloch-capture -R /mnt/pcapdata/"(again different results) and saved the last output of the verbose shown in the console . I assume this is the same as the data that will be otherwise available in capture.log. I followed the whole import (takes about 10  - 15 minus time for all the data) on the screen and didn't see any error.

Here are the last asked rules from what I saw on the verbose, including `moloch_packet_log` in it:

```Jan 24 07:55:57 packet.c:1133 moloch_packet_log(): packets: 85000000 current sessions: 64171/76317 oldest: 0 - recv: 85000000 drop: 0 (0.00) queue: 1 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 84999999/0/0/0/1078/0
Jan 24 07:55:57 packet.c:1133 moloch_packet_log(): packets: 85100000 current sessions: 640/76446 oldest: 0 - recv: 85100000 drop: 0 (0.00) queue: 2 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 85099999/0/0/0/1078/0
Jan 24 07:55:58 packet.c:1133 moloch_packet_log(): packets: 85200000 current sessions: 64278/76497 oldest: 0 - recv: 85200000 drop: 0 (0.00) queue: 3 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 85199999/0/0/0/1080/0
Jan 24 07:55:58 packet.c:1133 moloch_packet_log(): packets: 85300000 current sessions: 64412/76768 oldest: 0 - recv: 85300000 drop: 0 (0.00) queue: 3 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 85299999/0/0/0/1080/0
Jan 24 07:55:59 packet.c:1133 moloch_packet_log(): packets: 85400000 current sessions: 64475/76859 oldest: 0 - recv: 85400000 drop: 0 (0.00) queue: 3 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 85399999/0/0/0/1082/0
Jan 24 07:56:00 packet.c:1133 moloch_packet_log(): packets: 85500000 current sessions: 64606/77088 oldest: 0 - recv: 85500000 drop: 0 (0.00) queue: 2 disk: 0 packet: 0 close: 6 ns: 0 frags: 0/0 pstats: 85499999/0/0/0/1084/0
Jan 24 07:56:00 packet.c:1133 moloch_packet_log(): packets: 85600000 current sessions: 64632/77144 oldest: 0 - recv: 85600000 drop: 0 (0.00) queue: 3 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 85599999/0/0/0/1084/0
Jan 24 07:56:01 packet.c:1133 moloch_packet_log(): packets: 85700000 current sessions: 64664/77186 oldest: 0 - recv: 85700000 drop: 0 (0.00) queue: 3 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 85699999/0/0/0/1086/0
Jan 24 07:56:02 packet.c:1133 moloch_packet_log(): packets: 85800000 current sessions: 64734/77326 oldest: 0 - recv: 85800000 drop: 0 (0.00) queue: 2 disk: 0 packet: 0 close: 1 ns: 0 frags: 0/0 pstats: 85799999/0/0/0/1086/0
Jan 24 07:56:02 packet.c:1133 moloch_packet_log(): packets: 85900000 current sessions: 64770/77389 oldest: 0 - recv: 85900000 drop: 0 (0.00) queue: 3 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 85899999/0/0/0/1086/0
Jan 24 07:56:03 packet.c:1133 moloch_packet_log(): packets: 86000000 current sessions: 64794/77437 oldest: 0 - recv: 86000000 drop: 0 (0.00) queue: 3 disk: 0 packet: 0 close: 2 ns: 0 frags: 0/0 pstats: 85999999/0/0/0/1088/0
Jan 24 07:56:04 packet.c:1133 moloch_packet_log(): packets: 86100000 current sessions: 64844/77553 oldest: 0 - recv: 86100000 drop: 0 (0.00) queue: 2 disk: 0 packet: 0 close: 3 ns: 0 frags: 0/0 pstats: 86099999/0/0/0/1088/0
Jan 24 07:56:04 packet.c:1133 moloch_packet_log(): packets: 86200000 current sessions: 64896/77680 oldest: 0 - recv: 86200000 drop: 0 (0.00) queue: 5 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 86199999/0/0/0/1088/0
Jan 24 07:56:05 packet.c:1133 moloch_packet_log(): packets: 86300000 current sessions: 64933/77723 oldest: 0 - recv: 86300000 drop: 0 (0.00) queue: 3 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 86299999/0/0/0/1090/0
Jan 24 07:56:05 packet.c:1133 moloch_packet_log(): packets: 86324369 current sessions: 64945/77736 oldest: 0 - recv: 86324369 drop: 0 (0.00) queue: 2 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/0 pstats: 86324369/0/0/0/1090/0```

**Comment by awick** [comment]
Yep if you run from the command line you have to capture your own log files.

So how are you exiting capture, are you just letting it finish or are you control-c?

**Comment by G1tClub** [comment]
I let it finish ofcourse :)

**Comment by awick** [comment]
It doesn't seem to be finishing though, the current sessions should be at 0.  Can you DM me the full log on slack

**Comment by awick** [comment]
So first note, as mentioned on slack, if you want to compare `-R` and loading individual files, you need to use `--flush` with the `-R` version

**Comment by G1tClub** [comment]
As commented on Slack. If I run my script and compare it with `moloch-capture -R --flush` I have exact the same results. 

Only find it strange that if I run moloch-capture -R on multiple static PCAP files I have different results each time.

**Comment by awick** [comment]
I've tried multiple times and can no reproduce.  Can you please
1) run db init
2) run your moloch-capture with --debug and save to logfile1
3) run the query that is different and export the pcap to pcapfile1
4) run db init
5) run your same moloch-capture with --debug and save to logfile2
6) run the query that is different and export the pcap to pcapfile2

DM me the two log files and the packet counts in pcapfile1 and pcapfile2

**Comment by G1tClub** [comment]
Will DM it tomorrow

**Comment by awick** [comment]
So I believe we figured out all the issues, feel free to reopen if not.
1) if you want to compare `-R` and loading individual files, you need to use `--flush` with the `-R` version
2) You need to make sure your ES cluster is not rejecting inserts or generally overloaded
