### ISSUE TITLE
Feature request: Individual packets data in a session

### ISSUE THREAD

**Issue by andersonreloaded** [aol/moloch#1008]
Hi Folks,

I am relatively new to Moloch and recently installed the latest version available for CentOS 7.
I was wondering if we can see the individual packet's data in a captured session. 
By default complete session data is displayed with no packet boundaries.

Does Moloch supports this or we have to use WIreshark by importing/downloading pcap data ?

Thanks!

**Comment by awick** [comment]
Duplicate of #805

**Comment by andersonreloaded** [comment]
Okay. There is already a feature request!
