### ISSUE TITLE
 something wrong with parser ldap bindRequest

### ISSUE THREAD

**Issue by qlb7707** [aol/moloch#1016]
when I care about bindRequest and bindResponse, I write some log for bindRequest , I think protocolOp == 0 is bindReqest,but there is nothing about my log in capture.log, Is there something wrong with this?

**Comment by awick** [comment]
Not sure what you are looking for, please attach a sample pcap that is failing.

**Comment by qlb7707** [comment]
I mean I write some logs in ldap_process,but I can not find the code run in if(protocolOp == 0){ },
and i can find protocolOp == 1 and others
