### ISSUE TITLE
Incorrect remaining value passed to classification function of parsers

### ISSUE THREAD

**Issue by aminlatifi** [aol/moloch#1018]
**Elasticsearch version**: 

**Moloch version**:1.7.0

**OS name and version**:

**How was Moloch built/installed:** easybutton

**Provide logs, stack traces and steps to reproduce**:

Hi,

There is a problem in computing the remaining bytes of session data and it makes some trouble at parsers' classification and possibly parse functions. It happens when Moloch processes a malformed packet which frame length is less than expected value obtained by IP header payload length.

Example is the second packet of below pcap file. Here, the tcp packet payload is 128 (as Wireshark gets) but Moloch pass 152 as remaining parameter to classification function of parsers.

[SCCP-IPv6.zip](https://github.com/aol/moloch/files/2871732/SCCP-IPv6.zip)

**Comment by awick** [comment]
I think this was already fixed in 1.7.1, can you check?

**Comment by aminlatifi** [comment]
> I think this was already fixed in 1.7.1, can you check?

Not now, but I will.
Thanks.

**Comment by aminlatifi** [comment]
> I think this was already fixed in 1.7.1, can you check?

Moloch v1.7.1 assumes such kind of packets corrupted and does not process them.
