### ISSUE TITLE
Improve Db.update for tags,hunts,...

### ISSUE THREAD

**Issue by awick** [aol/moloch#1028]
Once we require ES 6 change add tags/hunts/... updates to do a retry and to actually do appending instead of replacement.  So something like

<pre>"script": "if (ctx._source.containsKey(\"tags\")) {ctx._source.tag += tags;ctx._source.tagsCnt++} else {ctx._source.tags = [tag]; ctx._source.tagsCnt = 1}"
</pre>

Even better if it checks if the element is in there or not before adding.

**Comment by awick** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html  has some examples of the retry on conflict

**Comment by 31453** [comment]
@awick reopen if you find other places where this will be useful.
