### ISSUE TITLE
Systemd service contains invalid option for CentOS 7

### ISSUE THREAD

**Issue by joneswac** [aol/moloch#1033]
**Elasticsearch version**: 6.6.2

**Moloch version**: 1.7.1

**OS name and version**: CentOS Linux release 7.6.1810 (Core)

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) rpm

**Provide logs, stack traces and steps to reproduce**: 

I was unable to start either the `molochcapture` or `molochviwer` service. I noticed the following messages in the syslog:
```(bash)
Mar 21 19:44:53 localhost systemd: Starting Moloch Capture...
Mar 21 19:44:53 localhost systemd: Failed at step STDOUT spawning /data/moloch/bin/moloch_config_interfaces.sh: Inappropriate ioctl for device
```
And referring to the contents of `/etc/systemd/system/molochcapture.service` I was able to comment out the line for `StandardOutput=tty` and then successfully start the service. I did a little more [research](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) and ended up subbing what I think might be the right option...`journal+console`. I'm not sure -- my first time working with editing a systemd service object.

The service file is now:
```(bash)
[Unit]
Description=Moloch Capture
After=network.target

[Service]
Type=simple
Restart=on-failure
StandardOutput=journal+console
EnvironmentFile=-/data/moloch/etc/molochcapture.env
ExecStartPre=-/data/moloch/bin/moloch_config_interfaces.sh
ExecStart=/bin/sh -c '/data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini ${OPTIONS} >> /data/moloch/logs/capture.log 2>&1'
WorkingDirectory=/data/moloch
LimitCORE=infinity
LimitMEMLOCK=infinity

[Install]
WantedBy=multi-user.target
```

**Comment by awick** [comment]
tty is supported, I think you must have another issue.  
Does /data/moloch/bin/moloch_config_interfaces.sh exist
Does it have the right interface in it?
What happens if you run it manually?

**Comment by joneswac** [comment]
Yes, I have that file with the correct interface. Heres the output when I run `/data/moloch/bin/moloch_config_interfaces.sh`:

```
/data/moloch/bin/moloch_config_interfaces.sh
rx unmodified, ignoring
tx unmodified, ignoring
no ring parameters changed, aborting
Cannot change udp-fragmentation-offload
Cannot change large-receive-offload
```

When I run the ExecStart line manually, the service works.

**Comment by awick** [comment]
Very strange, we run on centos 7 with no issues.

**Comment by joneswac** [comment]
Ok, I installed this on the machine I was intending to have it on for production and it worked as intended. I was trying to install this on a Vagrant VM. I'm not really sure why it failed, but seems more likely there's an issue with Vagrant tty setup.
Anyway this is resolved for me.
