### ISSUE TITLE
Give more stats on sum of host byte counts

### ISSUE THREAD

**Issue by benjimons** [aol/moloch#1038]
It would be great if we could get some statistics like sum of src/dst bytes over a given time period.

This would make for hunting out noisy data transfers much easier.

Eg based off the given session search
- top 10 hosts total bytes src 
- top 10 hosts total bytes dest

**Comment by awick** [comment]
Can you explain what you want different than how spigraph tab already does this?

**Comment by benjimons** [comment]
I want to get a sum of the total dest or src bytes by Src or dest.

**Comment by awick** [comment]
But is it really the total you are after the or the top X that you are after.  Spigraph gives you the top X already for bytes, packets, sessions.  What would you do with total?

**Comment by benjimons** [comment]
Yeap, I had a problem where i had to determine within a specific VLAN who was the top usage by bytes. currently Moloch has no Summing of any host or src byes when searching sessions.

**Comment by awick** [comment]
So next time just use spigraph for this
* Click spigraph tab
* search would be "vlan == 1234"
* click the packets or databytes above the first graph (or just leave on session)
* set the spigraph pull down to either Dst IP or Src IP.

You'll get the top X hosts.

If you really need src or dst host and totals, and don't want the visual representation then you can use Kibana or an Elasticsearch query directly.  We have a high level plan to add dashboards someday, but not really sure what that will be yet.
