### ISSUE TITLE
Build failed on docker with easybutton(both ubuntu 16.04 and 18.04 image) 

### ISSUE THREAD

**Issue by Seumi** [aol/moloch#1041]
**Elasticsearch version**:

**Moloch version**:master branch

**OS name and version**:Ubuntu 16.04 and 18.04 official image pull from docker

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)easybutton

**Provide logs, stack traces and steps to reproduce**:

writer-disk.c: In function 'writer_disk_output_thread':
writer-disk.c:252:17: warning: ignoring return value of 'ftruncate', declared with attribute warn_unused_result [-Wunused-result]
                 (void)ftruncate(outputFd, filelen);
                 ^
gcc -rdynamic -ggdb main.o db.o yara.o http.o config.o parsers.o plugins.o field.o trie.o writers.o writer-inplace.o writer-disk.o writer-null.o writer-simple.o readers.o reader-libpcap-file.o reader-libpcap.o reader-tpacketv3.o reader-null.o packet.o session.o rules.o drophash.o -o moloch-capture \
            -u g_checksum_update -u g_hmac_update -u g_uri_unescape_segment \
    /data/moloch/thirdparty/libpcap-1.9.0/libpcap.a -libverbs  \
    /data/moloch/thirdparty/glib-2.56.2/glib/.libs/libglib-2.0.a /data/moloch/thirdparty/glib-2.56.2/gio/.libs/libgio-2.0.a /data/moloch/thirdparty/glib-2.56.2/gobject/.libs/libgobject-2.0.a /data/moloch/thirdparty/glib-2.56.2/gthread/.libs/libgthread-2.0.a /data/moloch/thirdparty/glib-2.56.2/gmodule/.libs/libgmodule-2.0.a /data/moloch/thirdparty/glib-2.56.2/glib/.libs/libglib-2.0.a /data/moloch/thirdparty/yara/yara-3.8.1/libyara/.libs/libyara.a /data/moloch/thirdparty/libmaxminddb-1.3.2/src/.libs/libmaxminddb.a /data/moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a -lrt -luuid -lpcre thirdparty/http_parser.o thirdparty/js0n.o thirdparty/patricia.o -ldl -lpthread -lssl -lcrypto -lyaml \
    -lm -lresolv -lmagic -lffi -lz
**/usr/bin/ld: cannot find -libverbs**
collect2: error: ld returned 1 exit status
Makefile:40: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/data/moloch/capture'
Makefile:329: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
MOLOCH: make failed

**Comment by Seumi** [comment]
I just run a new container of ubuntu 16.04 or 18.04, update apt and install git, then clone the repo and run easybutton script. Did I miss some steps？
Thanks.

**Comment by awick** [comment]
looks like you need to install ibverbs, not sure why.  Did you try that?

**Comment by Seumi** [comment]
i install libibverbs-dev, it does not report this mistake again, but there is a new problem

/data/moloch/thirdparty/yara/yara-3.8.1/libyara/.libs/libyara.a(pe.o): In function `pe_parse_certificates':
pe.c:(.text+0x3af1): undefined reference to `OPENSSL_sk_num'
pe.c:(.text+0x3b14): undefined reference to `OPENSSL_sk_value'
pe.c:(.text+0x3c9e): undefined reference to `X509_get_version'
pe.c:(.text+0x3d19): undefined reference to `X509_getm_notBefore'
pe.c:(.text+0x3d4c): undefined reference to `X509_getm_notAfter'
pe.c:(.text+0x3db2): undefined reference to `OPENSSL_sk_free'
/data/moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_sha256sum':
openssl.c:(.text+0x13c): undefined reference to `EVP_MD_CTX_new'
openssl.c:(.text+0x177): undefined reference to `EVP_MD_CTX_free'
/data/moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_md5sum':
openssl.c:(.text+0x1cc): undefined reference to `EVP_MD_CTX_new'
openssl.c:(.text+0x207): undefined reference to `EVP_MD_CTX_free'
/data/moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_version':
openssl.c:(.text+0xea4): undefined reference to `OpenSSL_version_num'
/data/moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `ossl_connect_step1':
openssl.c:(.text+0x1781): undefined reference to `TLS_client_method'
openssl.c:(.text+0x1a26): undefined reference to `SSL_CTX_set_options'
openssl.c:(.text+0x27c8): undefined reference to `OPENSSL_sk_pop'
openssl.c:(.text+0x280a): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x2836): undefined reference to `OPENSSL_sk_pop_free'
openssl.c:(.text+0x2bfd): undefined reference to `OPENSSL_sk_pop_free'
/data/moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `ossl_connect_step2':
openssl.c:(.text+0x2eb2): undefined reference to `SSL_get_client_random'
openssl.c:(.text+0x2ec7): undefined reference to `SSL_SESSION_get_master_key'
/data/moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `servercert':
openssl.c:(.text+0x388b): undefined reference to `X509_get0_notBefore'
openssl.c:(.text+0x38e7): undefined reference to `X509_get0_notAfter'
openssl.c:(.text+0x3aa4): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x3af0): undefined reference to `OPENSSL_sk_value'
openssl.c:(.text+0x3bf6): undefined reference to `X509_get_X509_PUBKEY'
openssl.c:(.text+0x3c31): undefined reference to `X509_get_X509_PUBKEY'
openssl.c:(.text+0x3d28): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x3d8b): undefined reference to `OPENSSL_sk_value'
openssl.c:(.text+0x3e65): undefined reference to `X509_get_version'
openssl.c:(.text+0x400b): undefined reference to `X509_get0_extensions'
openssl.c:(.text+0x4018): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x4034): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x4051): undefined reference to `OPENSSL_sk_value'
openssl.c:(.text+0x417c): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x4197): undefined reference to `X509_get0_notBefore'
openssl.c:(.text+0x41f9): undefined reference to `X509_get0_notAfter'
openssl.c:(.text+0x4283): undefined reference to `EVP_PKEY_get0_RSA'
openssl.c:(.text+0x429d): undefined reference to `RSA_get0_key'
openssl.c:(.text+0x49fb): undefined reference to `EVP_PKEY_get0_DSA'
openssl.c:(.text+0x4a1e): undefined reference to `DSA_get0_pqg'
openssl.c:(.text+0x4a30): undefined reference to `DSA_get0_key'
openssl.c:(.text+0x4ad8): undefined reference to `ASN1_STRING_get0_data'
openssl.c:(.text+0x4b04): undefined reference to `EVP_PKEY_get0_DH'
openssl.c:(.text+0x4b27): undefined reference to `DH_get0_pqg'
openssl.c:(.text+0x4b39): undefined reference to `DH_get0_key'
openssl.c:(.text+0x4be1): undefined reference to `ASN1_STRING_get0_data'
openssl.c:(.text+0x4c5e): undefined reference to `ASN1_STRING_get0_data'
openssl.c:(.text+0x50f0): undefined reference to `ASN1_STRING_get0_data'
collect2: error: ld returned 1 exit status
Makefile:40: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/data/moloch/capture'
Makefile:329: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
MOLOCH: make failed

**Comment by awick** [comment]
strange, there is something in your bae images that is trigger extra libraries for libpcap and other, i'll have to figure out how to disable them.  for now i suggest you just use the prebuilt binaries.

**Comment by awick** [comment]
We are using the base images to build too, so are you sure you aren't doing something else?  you can see how they are created in release/build16 and release/build18 dir

**Comment by Seumi** [comment]
I have solved this problem, how stupid i am.I bound the thirdparty directory of the host to the container, so those third-party libraries will not be compiled again. They are all old files on my host. But there is still a small problem
make[1]: Entering directory '/data/moloch'
make[2]: Entering directory '/data/moloch'
npm ci
/bin/bash: npm: command not found
Makefile:752: recipe for target 'install-exec-local' failed
make[2]: *** [install-exec-local] Error 127
make[2]: Leaving directory '/data/moloch'
Makefile:644: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/data/moloch'
Makefile:329: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
MOLOCH: Installed, now type sudo make config'

Looks like the npm path caused it. I will try to solve this problem.
Thanks for your help and your great works!

**Comment by Seumi** [comment]
just ln -s /YOUR MOLOCH DIR/bin/node /usr/bin/node and ln -s /YOUR MOLOCH DIR/bin/npm /usr/bin/npm without --nonode ,all thing done

**Comment by awick** [comment]
or easier is just add /data/moloch/bin to your path.   next time these are probably better questions on slack
