### ISSUE TITLE
Install fail with gyp&npm error

### ISSUE THREAD

**Issue by modentcitizen** [aol/moloch#1046]
**Elasticsearch version**:6.4.2

**Moloch version**:lastest git pull

**OS name and version**:ubuntu1804

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
 Easybutton
**Provide logs, stack traces and steps to reproduce**:
After easybutton build, make install on npm&gyp fails:
npm WARN prepare removing existing node_modules/ before installation

> iptrie@0.0.7 install /data/moloch/wiseService/node_modules/iptrie
> node-gyp rebuild

make[2]: Entering directory '/data/moloch/wiseService/node_modules/iptrie/build'
  CXX(target) Release/obj.target/iptrie/src/iptrie.o
../src/iptrie.cc: In static member function ‘static void IPTrie::Add(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/iptrie.cc:180:54: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       String::Utf8Value ipaddress(args[0]->ToString());
                                                      ^
In file included from /root/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from ../src/iptrie.cc:35:
/root/.node-gyp/10.15.3/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/iptrie.cc:181:42: error: no matching function for call to ‘v8::Value::ToUint32()’
       int prefix_len = args[1]->ToUint32()->Value();
                                          ^
In file included from ../src/iptrie.cc:35:0:
/root/.node-gyp/10.15.3/include/node/v8.h:2435:44: note: candidate: v8::MaybeLocal<v8::Uint32> v8::Value::ToUint32(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
                                            ^~~~~~~~
/root/.node-gyp/10.15.3/include/node/v8.h:2435:44: note:   candidate expects 1 argument, 0 provided
../src/iptrie.cc: In static member function ‘static void IPTrie::Del(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/iptrie.cc:209:54: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       String::Utf8Value ipaddress(args[0]->ToString());
                                                      ^
In file included from /root/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from ../src/iptrie.cc:35:
/root/.node-gyp/10.15.3/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/iptrie.cc:210:42: error: no matching function for call to ‘v8::Value::ToUint32()’
       int prefix_len = args[1]->ToUint32()->Value();
                                          ^
In file included from ../src/iptrie.cc:35:0:
/root/.node-gyp/10.15.3/include/node/v8.h:2435:44: note: candidate: v8::MaybeLocal<v8::Uint32> v8::Value::ToUint32(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
                                            ^~~~~~~~
/root/.node-gyp/10.15.3/include/node/v8.h:2435:44: note:   candidate expects 1 argument, 0 provided
../src/iptrie.cc: In static member function ‘static void IPTrie::Find(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/iptrie.cc:228:54: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       String::Utf8Value ipaddress(args[0]->ToString());
                                                      ^
In file included from /root/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from ../src/iptrie.cc:35:
/root/.node-gyp/10.15.3/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
iptrie.target.mk:100: recipe for target 'Release/obj.target/iptrie/src/iptrie.o' failed
make[2]: *** [Release/obj.target/iptrie/src/iptrie.o] Error 1
make[2]: Leaving directory '/data/moloch/wiseService/node_modules/iptrie/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-48-generic
gyp ERR! command "/usr/local/node-v10.15.3-linux-x64/bin/node" "/usr/local/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/moloch/wiseService/node_modules/iptrie
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iptrie@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iptrie@0.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-11T06_08_42_373Z-debug.log
Makefile:15: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/download/suricata-4.1.2/moloch/wiseService'
Makefile:329: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
MOLOCH: Installed, now type sudo make config'

**Comment by awick** [comment]
node 10 isn't supported yet
