### ISSUE TITLE
error 4

### ISSUE THREAD

**Issue by tomrin** [aol/moloch#1050]
**Elasticsearch version**:
6.0.0
**Moloch version**:
1.6.1
**OS name and version**:
centos7
**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm
**Provide logs, stack traces and steps to reproduce**:

Running moloch-captrue, generating a failure, reporting an error message:
moloch-pkt0[26409]:segfault at 110001 ip 000000000049ab7 sp 00007fe4358e9750 error 4 in moloch-capture[400000+23700]

**Comment by awick** [comment]
Please try 1.8.0.  If you still have issues see https://molo.ch/faq#moloch-capture-crashes on how to get a useful stack trace.
