### ISSUE TITLE
Install Error 127 in make config step

### ISSUE THREAD

**Issue by throro** [aol/moloch#1057]
**Moloch version**: idk i just clone with git

**OS name and version**: ubuntu server 19.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...): easybutton

root@thunting:~/moloch# make config
/data/moloch/bin/Configure
/bin/bash: /data/moloch/bin/Configure: No such file or directory
make: *** [Makefile:763: config] Error 127
root@thunting:~/moloch#

**Comment by awick** [comment]
There must have been errors in the previous build steps, can you provide those?

**Comment by awick** [comment]
master was broken for a while, which might have been the issue, feel free to reopen with more info after updating

**Comment by throro** [comment]
Hello, I just try to install but I have the same problem, I copy more lines of the installation, so I want this to be enough to identify the problem


make[1]: Leaving directory '/moloch/tests'
cc --shared -o ../lua.so -g -O2 -Wall -Wextra -D_GNU_SOURCE -fPIC -I../.. -I../../thirdparty -I/moloch/thirdparty/glib-2.56.2/glib -I/moloch/thirdparty/glib-2.56.2 -I/moloch/thirdparty/glib-2.56.2/gmodule -I/moloch/thirdparty/glib-2.56.2/gobject -I/moloch/thirdparty/lua-5.3.5/src session.c molua.c httpService.c data.c /moloch/thirdparty/lua-5.3.5/src/liblua.a
MOLOCH: Installing node 8.15.0
--2019-05-19 01:35:52--  https://nodejs.org/download/release/v8.15.0/node-v8.15.0-linux-x64.tar.xz
Resolving nodejs.org (nodejs.org)... 104.20.22.46, 104.20.23.46, 2606:4700:10::6814:162e, ...
Connecting to nodejs.org (nodejs.org)|104.20.22.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11322992 (11M) [application/x-xz]
Saving to: ‘node-v8.15.0-linux-x64.tar.xz’

node-v8.15.0-linux-x 100%[===================>]  10.80M  3.76MB/s    in 2.9s

2019-05-19 01:35:55 (3.76 MB/s) - ‘node-v8.15.0-linux-x64.tar.xz’ saved [11322992/11322992]

MOLOCH: Now type 'sudo make install' and 'sudo make config'
root@lab0:/moloch# ^C
root@lab0:/moloch# sudo make install
Making install in .
make[1]: Entering directory '/moloch'
make[2]: Entering directory '/moloch'
npm ci
/bin/bash: npm: command not found
make[2]: *** [Makefile:752: install-exec-local] Error 127
make[2]: Leaving directory '/moloch'
make[1]: *** [Makefile:644: install-am] Error 2
make[1]: Leaving directory '/moloch'
make: *** [Makefile:329: install-recursive] Error 1
root@lab0:/moloch# sudo make condig
make: *** No rule to make target 'condig'.  Stop.
root@lab0:/moloch# sudo make config
/data/moloch/bin/Configure
/bin/bash: /data/moloch/bin/Configure: No such file or directory
make: *** [Makefile:763: config] Error 127

**Comment by awick** [comment]
you need to put /data/moloch/bin in your path

**Comment by awick** [comment]
Committed a fix, please update and make sure you are using --install with easybutton
