### ISSUE TITLE
 moloch unable to be associated with suricata alarms? 

### ISSUE THREAD

**Issue by Canon88** [aol/moloch#1058]
I have a question. Why is moloch unable to be associated with suricata alarms? Suricata. so has been configured

more config.ini | grep suricata
plugins=suricata.so
suricataAlertFile=/var/log/suricata/eve.json
suricataExpireMinutes=60

**Elasticsearch version**:
elasticsearch:6.7.1

**Moloch version**:
moloch-capture 2.0.0-GIT/v1.8.0-59-g5911bcbf session size=392 packet size=80 api=160

**Suricata version**:
This is Suricata version 4.1.3 RELEASE

**OS name and version**:
Ubuntu 18.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
deb

**Comment by awick** [comment]
* run capture with --debug and make sure its actually loading the suricata plugin
* How are you testing its not working

**Comment by Canon88** [comment]
First, I looked at the capture log, but there were no permissions errors for the eve.json file. Then, I manually trigger the alarm for suricata and see the alarm in eve.json, but I don't see the alarm description in the suricata field in the Web UI.

Now that I've rolled back to moloch-capture 1.8.0/v1.8.0, it's working fine with Suricata.

**Comment by ZZMarquis** [comment]
I have met the same problem, and I've also solved it by roll back version to v1.8.0

**Comment by awick** [comment]
Can you provide a sample line that is causing issues?  Any errors in capture.log?

**Comment by ZZMarquis** [comment]
Oh, I'm sorroy, I did not save the detail information, I can only tell you it is Ubuntu 19.04 and Suricata 4.1.4 RELEASE.

**Comment by zhy0830** [comment]
I have same problem too,and I can not find a way to slove it,there is no errors in capture.log

**Comment by awick** [comment]
Without more information we can't help.  Please provide 
* moloch version, if not >= 2.0 please upgrade
* sample from eve.json that isn't being matched

**Comment by zhy0830** [comment]
Moloch version:2.0.0
eve.json:
{"timestamp":"2019-09-17T14:28:12.804025+0800","flow_id":190411546,"in_iface":"eth1","event_type":"alert","src_ip":"1.1.0.87","src_port":23634,"dest_ip":"1.2.0.110","dest_port":80,"proto":"TCP","tx_id":0,"alert":{"action":"allowed","gid":1,"signature_id":2221027,"rev":1,"signature":"SURICATA HTTP Host part of URI is invalid","category":"Generic Protocol Command Decode","severity":3},"http":{"http_method":"GET","protocol":"HTTP\/1.0","length":0}}

**Comment by zhy0830** [comment]
It is empty in the webUI of suricata

**Comment by zhy0830** [comment]
should I need any additional configuration?

**Comment by awick** [comment]
Please make sure you are using 2.0.1 and have set suricataExpireMinutes to 120 minutes

**Comment by scuba-st3v3** [comment]
I am having this problem as well running Moloch v2.1.0 and Suricata v4.1.5.  The plugin worked before upgrading > v1.8.0.  Here's my config.ini file:

```
# Semicolon ';' seperated list of plugins to load and the order to load in
plugins=tagger.so; suricata.so

suricataAlertFile=/var/log/suricata/eve.json
suricataExpireMinutes=120
```

Here's one of the latest signatures firing (misc traffic between my capture box and elasticsearch).
```
{"timestamp":"2020-01-01T16:27:01.076622-0500","flow_id":2219731599597957,"in_iface":"ens224","event_type":"alert","src_ip":"192.168.4.130","src_port":56526,"dest_ip":"192.168.4.131","dest_port":9200,"proto":"TCP","community_id":"1:o3pw2ux\/6fdp\/bZ47S2HUhc9MMs=","alert":{"action":"allowed","gid":1,"signature_id":2210010,"rev":2,"signature":"SURICATA STREAM 3way handshake wrong seq wrong ack","category":"Generic Protocol Command Decode","severity":3},"flow":{"pkts_toserver":127,"pkts_toclient":288,"bytes_toserver":14267,"bytes_toclient":355714,"start":"2020-01-01T16:05:01.041349-0500"}}
```
The following query shows empty results in the Moloch UI:
`suricata.signature == EXISTS!`

**Comment by xx-zhang** [comment]
I have tried ok with env like down-showing
- env
   - centos7.6.1810
  - suricata 4.1.5  deployed by yum install 
  - es 7.5.0 
  - moloch 2.1.4 

work ok!

**Comment by 31453** [comment]
Looks like this issue has been solved by using Moloch 2.x, ES, 7.5+ and Suricata 4.1+.

If you run into this issue, please comment with version information and logs.
