### ISSUE TITLE
configure can't find yara on intel (seems identical to #581)

### ISSUE THREAD

**Issue by bf228** [aol/moloch#1059]
**Elasticsearch version**:
probably irrelevant but here's the version info:

curl http://localhost:9200/
{
  "name" : "Kc86Vl8",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "mnJiA66gSamMP-x34P7e0A",
  "version" : {
    "number" : "5.6.16",
    "build_hash" : "3a740d1",
    "build_date" : "2019-03-13T15:33:36.565Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}

**Moloch version**:
NA-- error is during ./configure

**OS name and version**:

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
trying to build moloch.  

**Provide logs, stack traces and steps to reproduce**:
root@moloch:~/moloch# sudo apt-get install libyara-dev yara
Reading package lists... Done
Building dependency tree
Reading state information... Done
libyara-dev is already the newest version (3.4.0+dfsg-2build1).
yara is already the newest version (3.4.0+dfsg-2build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@moloch:~/moloch# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking for git... git
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/inotify.h usability... yes
checking sys/inotify.h presence... yes
checking for sys/inotify.h... yes
checking for main in -lpcre... yes
checking for main in -luuid... yes
checking for main in -lrt... yes
checking for main in -lnet... no
checking for main in -ldl... yes
checking for main in -lresolv... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for pfring... no
checking for libpcap... yes
checking for nl_socket_alloc in -lnl-3... no
checking for nl_socket_alloc in -lnl... no
checking for nl_handle_alloc in -lnl... no
checking for yara... configure: error: yara not found

**Comment by awick** [comment]
github is for bugs or feature requests, please come to slack for support.  I would suggest either using the pre compiled .deb, the easybutton script, or installing yara.
