### ISSUE TITLE
How to delete custom fields and group?

### ISSUE THREAD

**Issue by Canon88** [aol/moloch#1063]
**Moloch version**: moloch-capture 1.8.0/v1.8.0

**OS name and version**: Ubuntu 18.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) deb

I'm using wise and trying to customize some fields and groups, but now I want to delete fields and groups, and I don't know what method to use? Can anyone tell me? thanks!

e.g:

[file:honeypot]
file=/data/moloch/etc/wise/wise_honeypot.json
tags=honeypot
type=ip
keyColumn=ip
format=json
fields=field:asset;shortcut:asset\nfield:honeypot;kind:termfield;count:true;group:honeypot_group;friendly:honeypot;db:honeypot;help:Help for Honeypot;shortcut:honeypot\n

i want delete field: honeypot; group: honeypot_group

**Comment by awick** [comment]
there is no way to delete fields in the actual SPI data, it just has to age out.  To delete fields showing up in UI you need to delete any spi data view that references it and if you don't want it to be searchable you need to delete from elasticsearch /fields/field/[the-field-name]
