### ISSUE TITLE
Custom theme is not honored in Help Fields list

### ISSUE THREAD

**Issue by mmguero** [aol/moloch#1068]
**Elasticsearch version**: 6.7.2

**Moloch version**: 1.8.0

**OS name and version**: Debian 10.0 "buster"

**How was Moloch built/installed:** easybutton

The other day I was chatting with @31453 in the Slack channel about custom themes. I shared the following dark theme I had created with the custom theme editor in Moloch's themes setting.

`#222222,#E2E2E2,#FFFFFF,#00789E,#004A79,#017D73,#092B40,#42b7c5,#2A7580,#ecb30a,#333333,#89ADCC,#6D6D6D,#FFE7E7,#ECFEFF`

Navigating to the Help by clicking on the owl icon, then clicking Fields to display the fields list, you'll see that the custom text color is not applied to the list, making it unreadable.

![screenshot-20190523_150353](https://user-images.githubusercontent.com/13872653/58286470-0bd59f00-7d6c-11e9-9246-30b93792f995.png)

**Comment by 31453** [comment]
Fixed in this commit: 8d482f8
