### ISSUE TITLE
http.referer is enabled but no data is found

### ISSUE THREAD

**Issue by brandonfrick** [aol/moloch#1070]
Problem:
Trying to get Moloch to show http.referer information.

Attempt:
Followed the steps here: https://github.com/aol/moloch/wiki/Settings#headershttprequest
Edited moloch config as per below:

Old config:
#[headers-http-request]
#referer=type:string;count:true;unique:true

New config:
[headers-http-request]
referer=type:string;count:true;unique:true

The field http.referer now shows up in search, however no data is populating into the field.
If we download a PCAP and open it in Wireshark, the referer information is visible. 
Any idea what could be causing the referer field not to be populated through Moloch?

**Elasticsearch version**:
6.7.1
**Moloch version**:
1.7.0
**OS name and version**:
ubuntu-16.04
**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
deb
**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
github is for issues and new feature requests, please ask questions on slack.
