### ISSUE TITLE
Feature request with -m and -R options for reading pcaps from directory.

### ISSUE THREAD

**Issue by Nimdy** [aol/moloch#1079]
I am using the following command /data/moloch/bin/moloch-capture -m -R /mnt/log/pcap/ but moloch does not want to read the pcap files that end with timestamps from Suricata. 

For example: whatever.pcap.123456789 

Requesting possible option to treat all files (or *.pcap.*) as pcap files.

Thank you

**Comment by awick** [comment]
Change https://molo.ch/settings#advanced-offlinefilenameregex to something that matches your files
