### ISSUE TITLE
Feature Request: keep graph but enable scrolling of table contents

### ISSUE THREAD

**Issue by bf31415** [aol/moloch#1081]
the feature request is to adjust or augment how scrolling works.   on the session page, would it be possible to keep the graph and table header (and the info above like search bar etc.) and just scroll the table contents.

**Comment by 31453** [comment]
This would require that all users have a tall screen so there's enough room for the sessions table content. However, I'll look into adding a button to toggle locking the graph and table header.

Thanks!

**Comment by 31453** [comment]
I created a separate issue for fixing the table header: https://github.com/aol/moloch/issues/1416
