### ISSUE TITLE
Feature Request: Allow multi-process capture with tpacketv3

### ISSUE THREAD

**Issue by schenksj** [aol/moloch#1085]
We have some very large boxes that are used with moloch.  These boxes have upwards of 20x-40x CPU's (each with 2 threads) vs. capture interfaces.  The capture process is unable to leverage the full CPU footprint on the box due to normal linux process CPU consumption limitations...   I'd be interested in exploring the possibility of having moloch offer FANOUT/FANOUT_HASH for multi-process capture on a single interface.

... Happy to help if this seems like a reasonable feature request ...

**Comment by awick** [comment]
I have yet to see the issue with moloch be the tpacket threads.  Usually its either the packet processing threads or disk writing thread.  So if you want to submit a PR that would be fine, but I doubt that is the issue you are seeing.

* What Gbps are you trying to do?
* Have you increased tpacketv3NumThreads to the max of 6?
* Have you increased tpacketv3BlockSize to the max that works on your box?
* When you run top -H (or your favorite tool) what percent cpu are the moloch-af3 at vs the moloch-pkt thread

**Comment by schenksj** [comment]
@awick getting access to some way bigger machines with about 1.5M packets/sec of traffic in a few days.  Our big machines see about 16 GBPS each.   And I'll report in whether those changes make a difference.  I don't think the issue is in the tpacket threads, I think its that the process is scaling up to about 10 cores, and linux (using traditional programming methodologies) generally can't efficiently schedule a single process beyond that in my experience.   I'm planning on introducing some more functionality (yara, etc), and I'm feeling pretty certain that will aggravate the general multithread problem.

It is a pretty easy PR, so i'll queue it up if you're cool with it.

**Comment by awick** [comment]
Yep, which is part of the reason I suggest increasing threads slowly and not just max out.  As you probably know be careful with which kernel you use, there has been many FANOUT bugs.  You may see issues with moloch duplicating sessions depending on if you use any encapsulation.

**Comment by schenksj** [comment]
Opened https://github.com/aol/moloch/pull/1086
