### ISSUE TITLE
Feature Request: Support ES xPack SSL Security w/Client-Auth

### ISSUE THREAD

**Issue by schenksj** [aol/moloch#1089]
In ES 6.8.0+, TLS with client-auth is supported for free without a commercial xPack license.  This seems like a safer scheme than relying solely on IP-chains to secure elastic search.  I don't trust myself to keep those in good shape over the long term.  I'd like explore adding support for sending client certificates to at least the viewer, es-multi, and capture processes.

Would appreciate some community feedback before I start working on a PR.

**Comment by awick** [comment]
You can already do user/pass, but yes client certs would be cool.  db.pl also needs to support with capture/viewer/multies
