### ISSUE TITLE
case 228 (raw ipv4) missing from Pcap.prototype.pcap in viewer/pcap.js

### ISSUE THREAD

**Issue by bf31415** [aol/moloch#1097]
**Elasticsearch version**:

**Moloch version**:
2.0.0

**OS name and version**:
ubuntu 16.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

easybutton

**Provide logs, stack traces and steps to reproduce**:

it looks like support for ipv4 raw (pcap type 228) was added to capture/packet.c but there wasn't a corresponding change to support decode of these packet types in viewer/pcap.js specifically in Pcap.prototype.pcap = function (buffer, obj) {

  case 127: // radiotap
    this.radiotap(buffer.slice(16, obj.pcap.incl_len + 16), obj, 16);
    break;
  case 239: // NFLOG
    this.nflog(buffer.slice(16, obj.pcap.incl_len + 16), obj, 16);
    break;

it looks like the fix would be to simply copy what's already defined for 101 and add a case for 228:

copy this
  case 101: // RAW
    this.ip4(buffer.slice(16, obj.pcap.incl_len + 16), obj, 16);
    break;

and change to this:
  case 228: // RAW
    this.ip4(buffer.slice(16, obj.pcap.incl_len + 16), obj, 16);
    break;

but i don't have a pcap with these packets to test against.

**Comment by awick** [comment]
yep, seems correct, you gonna do a PR?

**Comment by awick** [comment]
looks fixed now
