### ISSUE TITLE
Feature Request: Add Option To Show Milliseconds In Timestamps

### ISSUE THREAD

**Issue by 31453** [aol/moloch#1102]
Add an option on the user settings page to display milliseconds on all timestamps.

**Comment by zelol** [comment]
I can work on this! Can you describe exactly where to add this option?

**Comment by 31453** [comment]
Thanks @zelol!

This option should be added on the Settings page. I'd add it next to the timezone setting, making sure to show the ms (or not) in the example date time.

All date times are displayed using the `timezoneDateString` filter (`viewer/vueapp/src/filters.js`). This filter formats all date times and applies the user specified timezone. Notice that this filter takes seconds, but now will need to take milliseconds.

**Comment by zelol** [comment]
Thanks for the details, let's go!

**Comment by zelol** [comment]
Moloch is not available for Windows 10 and I'm running W10. That's problematic.
