### ISSUE TITLE
Minor settings documentation bug: _stopYara vs. _dontCheckYara

### ISSUE THREAD

**Issue by schenksj** [aol/moloch#1109]
In https://molo.ch/settings#high-performance-settings, the sample high-performance rule for ` "Dont write tls packets or check yara after 10 packets, still save SPI"` uses `_stopYara` (which prevents capture from starting) instead of `_dontCheckYara`.

This is also misstated in https://github.com/aol/moloch/wiki/settings

**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
fixed, thanks.  You can do PRs against the repo aol/molochweb if interested.
