### ISSUE TITLE
Moloch fails to build on Gentoo 

### ISSUE THREAD

**Issue by muke101** [aol/moloch#1113]
Cloned the sources right off master and trying to build Moloch on my Gentoo install using the command 
`sudo ./easybutton-build.sh --install`
which fails to build with the error:
`collect2: error: ld returned 1 exit status`
With the following error occuring multiple times further up:
`error: undefined reference to 'BrotliDecoderGetErrorCode'`

Here are the rest of the logs from the relevant part of the build:
> `MOLOCH: Installing Dependencies
MOLOCH: Downloading and building static thirdparty libraries
MOLOCH: Not rebuilding glib
MOLOCH: Not rebuilding yara
MOLOCH: Not rebuilding libmaxmind
MOLOCH: NOT rebuilding libpcap
MOLOCH: Not rebuilding curl
MOLOCH: Not rebuilding lua
MOLOCH: Building capture
./configure --prefix=/data/moloch --with-libpcap=/home/muke/Programming/C/Moloch/thirdparty/libpcap-1.9.0 --with-yara=thirdparty/yara/yara-3.8.1 --with-maxminddb=thirdparty/libmaxminddb-1.3.2 --with-glib2=thirdparty/glib-2.56.2 --with-curl=thirdparty/curl-7.61.1 --with-lua=thirdparty/lua-5.3.5
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking for git... git
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/inotify.h usability... yes
checking sys/inotify.h presence... yes
checking for sys/inotify.h... yes
checking for main in -lpcre... yes
checking for main in -luuid... yes
checking for main in -lrt... yes
checking for main in -lnet... no
checking for main in -ldl... yes
checking for main in -lresolv... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for pfring... no
checking for libpcap... /home/muke/Programming/C/Moloch/thirdparty/libpcap-1.9.0
checking for nl_socket_alloc in -lnl-3... yes
checking for yara... thirdparty/yara/yara-3.8.1
checking for maxminddb... thirdparty/libmaxminddb-1.3.2
checking for glib2... thirdparty/glib-2.56.2
checking for curl... thirdparty/curl-7.61.1
checking for lua... thirdparty/lua-5.3.5
checking for magic... checking for main in -lmagic... yes
yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating capture/Makefile
config.status: creating capture/plugins/Makefile
config.status: creating capture/plugins/daq/Makefile
config.status: creating capture/plugins/pfring/Makefile
config.status: creating capture/plugins/snf/Makefile
config.status: creating capture/plugins/lua/Makefile
config.status: creating capture/parsers/Makefile
config.status: creating db/Makefile
config.status: creating tests/plugins/Makefile
config.status: creating viewer/Makefile
config.status: creating viewer/version.js
config.status: creating parliament/Makefile
config.status: creating release/Makefile
config.status: creating wiseService/Makefile
config.status: creating capture/molochconfig.h
config.status: capture/molochconfig.h is unchanged
config.status: executing depfiles commands
Making all in .
make[1]: Entering directory '/home/muke/Programming/C/Moloch'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/muke/Programming/C/Moloch'
Making all in capture
make[1]: Entering directory '/home/muke/Programming/C/Moloch/capture'
gcc -fno-strict-aliasing -fPIC -g -O2 -Wall -Wextra -D_GNU_SOURCE -std=gnu99 -c main.c db.c yara.c http.c config.c parsers.c plugins.c field.c trie.c writers.c writer-inplace.c writer-disk.c writer-null.c writer-simple.c readers.c reader-libpcap-file.c reader-libpcap.c reader-tpacketv3.c reader-null.c packet.c session.c rules.c drophash.c \
    -I/home/muke/Programming/C/Moloch/thirdparty/libpcap-1.9.0 \
    -Ithirdparty -I/home/muke/Programming/C/Moloch/thirdparty/glib-2.56.2/glib -I/home/muke/Programming/C/Moloch/thirdparty/glib-2.56.2 -I/home/muke/Programming/C/Moloch/thirdparty/glib-2.56.2/gmodule -I/home/muke/Programming/C/Moloch/thirdparty/glib-2.56.2/gobject -I/home/muke/Programming/C/Moloch/thirdparty/yara/yara-3.8.1/libyara/include -I/home/muke/Programming/C/Moloch/thirdparty/libmaxminddb-1.3.2/include -I/home/muke/Programming/C/Moloch/thirdparty/curl-7.61.1/include \
    -DBUILD_VERSION='"v1.8.0-165-g3500a915"'
yara.c: In function ‘moloch_yara_load’:
yara.c:95:35: warning: cast between incompatible function types from ‘int (*)(YR_RULES *)’ {aka ‘int (*)(struct YR_RULES *)’} to ‘void (*)(void *)’ [-Wcast-function-type]
         moloch_free_later(yRules, (GDestroyNotify) yr_rules_destroy);
                                   ^
yara.c: In function ‘moloch_yara_load_email’:
yara.c:114:40: warning: cast between incompatible function types from ‘int (*)(YR_RULES *)’ {aka ‘int (*)(struct YR_RULES *)’} to ‘void (*)(void *)’ [-Wcast-function-type]
         moloch_free_later(yEmailRules, (GDestroyNotify) yr_rules_destroy);
                                        ^
writer-disk.c: In function ‘writer_disk_output_thread’:
writer-disk.c:252:23: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
                 (void)ftruncate(outputFd, filelen);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -rdynamic -ggdb main.o db.o yara.o http.o config.o parsers.o plugins.o field.o trie.o writers.o writer-inplace.o writer-disk.o writer-null.o writer-simple.o readers.o reader-libpcap-file.o reader-libpcap.o reader-tpacketv3.o reader-null.o packet.o session.o rules.o drophash.o -o moloch-capture \
            -u g_checksum_update -u g_hmac_update -u g_uri_unescape_segment \
    /home/muke/Programming/C/Moloch/thirdparty/libpcap-1.9.0/libpcap.a  -lnl-genl-3 -lnl-3  -lnl-genl-3 -lnl-3 \
    /home/muke/Programming/C/Moloch/thirdparty/glib-2.56.2/glib/.libs/libglib-2.0.a /home/muke/Programming/C/Moloch/thirdparty/glib-2.56.2/gio/.libs/libgio-2.0.a /home/muke/Programming/C/Moloch/thirdparty/glib-2.56.2/gobject/.libs/libgobject-2.0.a /home/muke/Programming/C/Moloch/thirdparty/glib-2.56.2/gthread/.libs/libgthread-2.0.a /home/muke/Programming/C/Moloch/thirdparty/glib-2.56.2/gmodule/.libs/libgmodule-2.0.a /home/muke/Programming/C/Moloch/thirdparty/glib-2.56.2/glib/.libs/libglib-2.0.a /home/muke/Programming/C/Moloch/thirdparty/yara/yara-3.8.1/libyara/.libs/libyara.a /home/muke/Programming/C/Moloch/thirdparty/libmaxminddb-1.3.2/src/.libs/libmaxminddb.a /home/muke/Programming/C/Moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a -lrt -luuid -lpcre thirdparty/http_parser.o thirdparty/js0n.o thirdparty/patricia.o -ldl -lpthread -lssl -lcrypto -lyaml \
    -lm -lresolv -lmagic -lffi -lz
/home/muke/Programming/C/Moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-version.o):version.c:function brotli_version: error: undefined reference to 'BrotliDecoderVersion'
/home/muke/Programming/C/Moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-version.o):version.c:function curl_version_info: error: undefined reference to 'BrotliDecoderVersion'
/home/muke/Programming/C/Moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_close_writer: error: undefined reference to 'BrotliDecoderDestroyInstance'
/home/muke/Programming/C/Moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_init_writer: error: undefined reference to 'BrotliDecoderCreateInstance'
/home/muke/Programming/C/Moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_unencode_write: error: undefined reference to 'BrotliDecoderDecompressStream'
/home/muke/Programming/C/Moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_unencode_write: error: undefined reference to 'BrotliDecoderDestroyInstance'
/home/muke/Programming/C/Moloch/thirdparty/curl-7.61.1/lib/.libs/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_unencode_write: error: undefined reference to 'BrotliDecoderGetErrorCode'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:41: all] Error 1
make[1]: Leaving directory '/home/muke/Programming/C/Moloch/capture'
make: *** [Makefile:329: all-recursive] Error 1
MOLOCH: make failed
`

**Comment by awick** [comment]
easybutton only supports deb/rpm,  you will have to use configure manually.
