### ISSUE TITLE
Installation: cannot add user admin

### ISSUE THREAD

**Issue by icepaule** [aol/moloch#1114]
Hello,
first of all thx a lot for this great tool, that I'd love to try in connection with my cuckoo 2.0 as I have heard to be a fantasic addition.
Could you please help me with below error while trying to install (add the initial admin user) to it?

Thx a lot
Marcus

**Elasticsearch version**:
6.5.1 

**Moloch version**:
moloch_1.8.0-1_amd64

**OS name and version**:
ubuntu xenial

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
wget https://files.molo.ch/builds/ubuntu-16.04/moloch_1.8.0-1_amd64.deb
sudo gdebi moloch_1.8.0-1_amd64.deb
sudo /data/moloch/bin/Configure

**Provide logs, stack traces and steps to reproduce**:

2:/data/moloch/bin# node /data/moloch/viewer/addUser.js - c ../etc/config.ini admin "Admin" admin -admin
module.js:328
    throw err;
    ^

Error: Cannot find module './db.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/moloch/viewer/addUser.js:26:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

I thought adding it to the path would do, as I can see that db.js IS installed in 
echo $PATH /data/moloch/viewer, but it did not help.

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/data/moloch/viewer

**Comment by icepaule** [comment]
I've just tried the easysetup version with the same result....

**Comment by awick** [comment]
Please ask questions on slack, we use github for feature requests and bugs.  See the /data/moloch/README.txt for how to add users.
