### ISSUE TITLE
icmp+icmpv6 missing databytes calculation

### ISSUE THREAD

**Issue by bf31415** [aol/moloch#1115]
**Elasticsearch version**:

6.7.1

**Moloch version**:

2.0

**OS name and version**:

ubuntu 16.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

easybuttong

**Provide logs, stack traces and steps to reproduce**:

the databytes calculation is missing for icmp.  further, there's no case statement to catch icmpv6 so no databytes calc for that protocol.  might need to have a discussion as to whether the 8 byte icmp protocol header should be included as databytes (and shown in the viewer output).  my $0.02 is that these bytes should be included as databyte count and shown as part of viewer output.

relevant code showing the issue in moloch_packet_process ()

    case IPPROTO_UDP:
        udphdr = (struct udphdr *)(packet->pkt + packet->payloadOffset);
        packet->direction = (dir &&
                             session->port1 == ntohs(udphdr->uh_sport) &&
                             session->port2 == ntohs(udphdr->uh_dport))?0:1;
        session->databytes[packet->direction] += (packet->pktlen - 8);
        break;
    case IPPROTO_SCTP:
        udphdr = (struct udphdr *)(packet->pkt + packet->payloadOffset);
        packet->direction = (dir &&
                             session->port1 == ntohs(udphdr->uh_sport) &&
                             session->port2 == ntohs(udphdr->uh_dport))?0:1;
        session->databytes[packet->direction] += (packet->pktlen - 8);
        break;

[snip]

    case IPPROTO_ICMP:
    case IPPROTO_ESP:
        packet->direction = (dir)?0:1;
        break;
    }

**Comment by awick** [comment]
fixed by #1129
