### ISSUE TITLE
databytes calc for UDP is incorrect

### ISSUE THREAD

**Issue by bf31415** [aol/moloch#1117]
**Elasticsearch version**:

6.7.1

**Moloch version**:

2.0

**OS name and version**:

ubuntu 16.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

easybutton

**Provide logs, stack traces and steps to reproduce**:

databytes calc for UDP appears to be incorrect.

code now is :

    case IPPROTO_UDP:
        udphdr = (struct udphdr *)(packet->pkt + packet->payloadOffset);
        packet->direction = (dir &&
                             session->port1 == ntohs(udphdr->uh_sport) &&
                             session->port2 == ntohs(udphdr->uh_dport))?0:1;
        session->databytes[packet->direction] += (packet->pktlen - 8);
        break;

should be:

        session->databytes[packet->direction] += (packet->pktlen - packet->payloadOffset - 8);

**Comment by awick** [comment]
Fixed by #1125
