### ISSUE TITLE
Bug: Suricata ingestion fails if protocol is expressed as IANA number

### ISSUE THREAD

**Issue by schenksj** [aol/moloch#1123]
Suricata allows expressing the protocol field as an IANA number (001=ICMP, 006=tcp, 017=UDP).  If in this format, the suricata plugin silent discards the alerts.

I plan to submit a PR to address this issue.

**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

**Comment by schenksj** [comment]
Fixed by https://github.com/aol/moloch/pull/1124

**Comment by HACKHNATON01** [comment]
Have any issue to bug gmail me founderhackhnaton@gmail.com
