### ISSUE TITLE
Bug: Myricom SNF statistics are incorrect in clustered mode

### ISSUE THREAD

**Issue by schenksj** [aol/moloch#1126]
Myricom SNF statistics are being reported only for "process-1"'s owned Myricom rings across all processes when using cluster mode.  This was introduced (by me) in https://github.com/aol/moloch/pull/1121.  The fix is easy, though I'm having some trouble putting in the PR from my fork.  This is the fix that I'll submit once I can straighten out whats going on with my git repo.

in reader.snf.c
```
/******************************************************************************/
int reader_snf_stats(MolochReaderStats_t *stats)
{
    struct snf_ring_stats ss;

    stats->dropped = 0;
    stats->total = 0;

    int i, r;
    int ringStartOffset = (snfProcNum-1)*snfNumRings;
    for (i = 0; i < MAX_INTERFACES && config.interface[i]; i++) {
        for (r = ringStartOffset; r < (ringStartOffset+snfNumRings); r++) {
            int err = snf_ring_getstats(rings[i][r], &ss);

            if (err)
                continue;
            stats->dropped += ss.ring_pkt_overflow;
            stats->total += ss.ring_pkt_recv;
        }
    }
    return 0;
}

```

**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
Still planning on adding this?

**Comment by schenksj** [comment]
Thanks!  This was addressed by https://github.com/aol/moloch/pull/1262/files
