### ISSUE TITLE
Feature Request: Defense against yara-induced thread starvation

### ISSUE THREAD

**Issue by schenksj** [aol/moloch#1128]
In our testing on high-volume networks, there are occasions where moloch will see a very large unencrypted stream (like in the case of a network backup).  This causes Yara to take an uncharastically long time on the packet thread, causing high CPU utilization, backups, and a number of other downstream issues.

I think it would be useful to have a mechanism to bound how long yara is allowed to run for a particular conversation and what percentage of total packet thread time is consumed by running yara.  This would allow users to use spare cycles for running yara on a best-effort basis, but would allow systems to scale beyond what is possible with full packet scanning.   

One potential mitigant/alternate implementation for the risk this proposes might be to provide a mechanism to dynamically switch between `yaraEveryPacket=TRUE` and `yaraEveryPacket=FALSE` based on system load.

I am very interested in the communities thoughts on this.

**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
Does the rule solution already do what you want?  https://github.com/aol/moloch/wiki/RulesFormat . You could set some protocols to not check yara at all and you could use max packets for other protocols.

```
 - name: "don't yara tls"
    when: "fieldSet"
    fields:
      protocols:
         - tls
    ops:
      _dontCheckYara: 1
```

**Comment by schenksj** [comment]
We do have this set, however while it does make the steady-state utilization more predictable I think it actually makes the spikes far worse.  Consider where there is a large amount of data transferred by non-TLS batch transfers (backups, large data loads, etc...) where the mix of TLS and non-TLS is non-characteristic for the "average" load of the system.  Worse, these things typically happen off-hours at companies when whoever installed the system isn't really watching or doing optimization.  To add to the ugliness, this isn't a function of escalated packet counts or bandwidth its just a function of traffic flavor.  The advise given by the logged message about increasing buffers or threads doesn't really help either given that the large transfers tend to hash to just a couple of 6-part keys (hot spots) so you end up with a small number really busy queues and the rest are as idle as normal (or more given it tends to be off-hours).

The only way I was able to figure out that this is what was going on (other than guess-and-check) was to grab process stacks (`pstack <pid>`) from each process when they were "troubled" and inspect the threads.     The vast majority of my strongest developers either wouldn't have thought of inspecting threads, or would lack the experience to diagnose things this way.  I imagine the typical engineer installing moloch is far more operations or system-engineering oriented that my developers and likely would just end up either buying gobs of hardware or simply giving up...

At the very least its probably worthwhile at least logging when yara is getting in you way and documenting steps to diagnose and remediate, but having the system keep it self healthy while it screams that there is a problem would be the best IMO (and probably allow suppression of the screaming if the user just wants to keep a best-effort Yara-every-packet.

**Comment by awick** [comment]
Can you share what rule you are using to turn off yara for max packets?  I don't think most people use yara anyway, so I'm guessing this isn't an issue for many folks.

With 2.0 we are hoping to provide a sample set of rules that help tune moloch.

**Comment by schenksj** [comment]
Hi @awick sorry for the delay.  The config is `yaraEveryPacket=false` . It yara's the data while the protocol handlers are active, but stops after that...

**Comment by awick** [comment]
Ok, so above I was suggesting that you create a rule that matches against the maxPackets you want to compare and use the _dontCheckYara operation.

**Comment by 31453** [comment]
This issue has not received any more information for a while. Please reopen if @awick's last comment does not solve the issue.

**Comment by schenksj** [comment]
Thanks, we ended up fully disabling YARA because it made for such incredibly unpredictable behavior on networks where there is lots of unencrypted traffic.
