### ISSUE TITLE
TLS 1.3 pcap shows up as TLS 1.2

### ISSUE THREAD

**Issue by randy98** [aol/moloch#1137]
**Elasticsearch version**:n/a

**Moloch version**: 2.0.0-GIT

**OS name and version**: Ubuntu 18.04

**How was Moloch built/installed:** built from source from Github 

Use any curl (docker run -itd alpine sh) with OpenSSL 1.1.x and go to https://enabled.tls13.com/
Then look at the pcap from moloch.  It says it’s 1.2

Easiest way to reproduce:
Run moloch
docker run --net=host -it alpine sh
apk add curl
curl --tlsv1.3 https://enabled.tls13.com
Then go see that packet and you’ll see it says it’s TLS 1.2

**Comment by randy98** [comment]
Here's the diff to make this work.  Could someone familiar with the code base make this more compatible with the current code base and push it?  The issue here is most TLS 1.3 clients right now still start with 1.2 and negotiate 1.3 in the extensions.  Moloch isn't catching this.

$ git diff
diff --git a/capture/parsers/tls.c b/capture/parsers/tls.c
index 9378be91..88257be4 100644
--- a/capture/parsers/tls.c
+++ b/capture/parsers/tls.c
@@ -152,6 +152,8 @@ LOCAL void tls_process_server_hello(MolochSession_t *session, const unsigned cha
     BSB_IMPORT_u16(bsb, ver);
     BSB_IMPORT_skip(bsb, 32);     // Random
 
+    int add_12_later = 0;
+
     if(BSB_IS_ERROR(bsb))
         return;
 
@@ -169,7 +171,8 @@ LOCAL void tls_process_server_hello(MolochSession_t *session, const unsigned cha
         moloch_field_string_add(verField, session, "TLSv1.1", 7, TRUE);
         break;
     case 0x0303:
-        moloch_field_string_add(verField, session, "TLSv1.2", 7, TRUE);
+        //moloch_field_string_add(verField, session, "TLSv1.2", 7, TRUE);
+        add_12_later = 1;
         break;
     case 0x0304:
         moloch_field_string_add(verField, session, "TLSv1.3", 7, TRUE);
@@ -232,7 +235,7 @@ LOCAL void tls_process_server_hello(MolochSession_t *session, const unsigned cha
 
         BSB ebsb;
         BSB_INIT(ebsb, BSB_WORK_PTR(bsb), etotlen);
-
+       
         while (BSB_REMAINING(ebsb) > 0) {
             int etype = 0, elen = 0;
 
@@ -240,7 +243,18 @@ LOCAL void tls_process_server_hello(MolochSession_t *session, const unsigned cha
             BSB_IMPORT_u16 (ebsb, elen);
 
             BSB_EXPORT_sprintf(eja3bsb, "%d-", etype);
-
+           
+           if (etype == 0x2b && elen == 2) { // etype 0x2b is supported version
+               int supported_version = 0;
+               BSB_IMPORT_u16(ebsb, supported_version);
+               
+               if (supported_version == 0x0304) {
+                   moloch_field_string_add(verField, session, "TLSv1.3", 7, TRUE);
+                   add_12_later = 0;
+
+               }
+               elen -= 2;  // or rewind??
+           }
             if (elen > BSB_REMAINING(ebsb))
                 break;
 
@@ -248,6 +262,8 @@ LOCAL void tls_process_server_hello(MolochSession_t *session, const unsigned cha
         }
         BSB_EXPORT_rewind(eja3bsb, 1); // Remove last -
     }
+    if (add_12_later)
+        moloch_field_string_add(verField, session, "TLSv1.2", 7, TRUE);
 
     BSB_EXPORT_sprintf(ja3bsb, "%d,%d,%.*s", ver, cipher, (int)BSB_LENGTH(eja3bsb), eja3);

**Comment by awick** [comment]
Thanks! I started to look at the spec but got side tracked.
