### ISSUE TITLE
web show nothing , when disk full 

### ISSUE THREAD

**Issue by ovovco** [aol/moloch#1139]
**Elasticsearch version**:6.7.2

**Moloch version**:2.0.0

**OS name and version**:ubuntu server 18.04.2

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) easybutton

**Provide logs, stack traces and steps to reproduce**: where to see log?

disk full , web show nothing

**Comment by awick** [comment]
https://molo.ch/faq#pcap-deletion

**Comment by ovovco** [comment]
thx, all default configuration and viewer is runing ,but web show nothing ,disk full
