### ISSUE TITLE
Couldn't run viewer as viewer/README.md said, maybe package.json needs to be updated?

### ISSUE THREAD

**Issue by JackLiar** [aol/moloch#1142]
After run `npm install` and `npm build`, everything is fine, nothing wrong happened.

Then I run `npm start:test` it said

 > ERROR - Couldn't load some dependancies, maybe need to 'npm update' inside viewer directory { Error: Cannot find module 'iniparser'

Then I found the iniparser package in the upper folder's package.json, and get all confused......

Why there are two package.json in source code directory? And both of them are kept being updated. Does the readme still works?

And by the way, the iniparser package uses http protocol, which is invalid in public internet environment.

**Comment by awick** [comment]
Please use slack for questions.  We use github for feature requests and bug reports.  I would suggest using one of the prebuilt packages if you are having issues building yourself.
