### ISSUE TITLE
Strange behaviour with field "file"

### ISSUE THREAD

**Issue by ZikyHD** [aol/moloch#1144]
**Elasticsearch version**: 6.8.2

**Moloch version**: 2.0.0

**OS name and version**: Ubuntu 16.04

**How was Moloch built/installed**: deb

**Provide logs, stack traces and steps to reproduce**:

* The query "file == test.pcap" display events from this pcap files but the query "file != test.pcap" or "file == EXISTS!" always returns "no results" even if there are other offline pcap on ES.

* "Filename" column is always empty if i display it

* "Export Unique Files" and "Export Unique Files with counts" commands both return a blank page

I encounter same problems on version 1.8.0

**Comment by awick** [comment]
Yes, file is not a real field, it is made from a join

* We should fix file != and == EXISTs
* We should disable the filename column display
* We should disable export unique files

**Comment by ZikyHD** [comment]
Thanks for your quick reply!
In fact "File" unique values with counts was interesting, is it possible to fix it someday instead of removing it?

**Comment by 31453** [comment]
- file != x.pcap works
- file == EXISTS! works
- disabled filename display in sessions table
- unique.txt works for filenames
- spigraph works for filenames

✨
