### ISSUE TITLE
Bug: stats are overflowing elasticsearch long

### ISSUE THREAD

**Issue by schenksj** [aol/moloch#1154]
**Elasticsearch version**:
7.3.1

**Moloch version**:
2.0.1
**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

I recently upgraded my non-prod env to the latest master branch and re-initialized ES.  I'm seeing the below error and am curious if there is a schema update that didn't get checked in?

```Sep  3 17:21:36 http.c:410 moloch_http_curlm_check_multi_info(): Response length=693 :>
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse field [deltaDropped] of type [long] in document with id 'rXXXXX9'. Preview of field's value: '18446744070197755928'"}],"type":"mapper_parsing_exception","reason":"failed to parse field [deltaDropped] of type [long] in document with id 'rXXXXX9'. Preview of field's value: '18446744070197755928'","caused_by":{"type":"i_o_exception","reason":"Numeric value (18446744070197755928) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@475c7184; line: 1, column: 819]"}},"status":400}```

**Comment by awick** [comment]
ya long is 2^63 -1 or 9223372036854775807
Stop dropping so many packets.  :) I guess capture should be changed to wrap.

**Comment by schenksj** [comment]
Is there a non-initialized variable somewhere?  I'm definitely not dropping lots of traffic!  this is using the snf plugin...

**Comment by awick** [comment]
ya not sure how snf calculates the dropped packets, I would start with adding debugging in reader_snf_stats and print out the results maybe from each call.  Anyway to get you on slack?

**Comment by awick** [comment]
Put in a check in 2.0.1 for this
