### ISSUE TITLE
session action to view underlying elasticsearch document as JSON

### ISSUE THREAD

**Issue by mmguero** [aol/moloch#1155]
I think it would be handy to be able to click the "Action" dropdown when a session is expanded and have an option for "View Document" or something like that. Essentially just opening another tab (similar to what you do for CSV) and show the raw Elasticsearch document in JSON format that was used to populate the session.

**Comment by mmguero** [comment]
Minus the PCAP stuff, of course. Just the `sessions2` indexed document.

**Comment by ahodgen** [comment]
You can add a right-click for it in your config.ini:

[right-click]
ESVIEW=url:http://eshost:9200/sessions2-*/_search?q=_id:%TEXT%&pretty;name:Raw Elasticsearch View;fields:id

**Comment by awick** [comment]
@ahodgen  if that works that means your ES cluster isnt locked down :)  But you could do that with moloch too using a similar sessions.json?expression=id=%TEXT%   (Correct encoding left to the implementation)

**Comment by mmguero** [comment]
Ah, this is very cool, thank you. I can make that work. Thanks.

**Comment by mmguero** [comment]
FWIW, this works great:

```
[right-click]
JSON=url:sessions.json?expression=id=%TEXT%&fields=*;name:JSON Document;fields:id
```
