### ISSUE TITLE
writer-simple.c:327 writer_simple_thread(): ERROR writing - - No space left on device

### ISSUE THREAD

**Issue by bigsea520** [aol/moloch#1156]
**Elasticsearch version**:
6.6.2
**Moloch version**:
moloch-nightly.x86_64.rpm
**OS name and version**:
centos7.4
**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm
**Provide logs, stack traces and steps to reproduce**:

Sep  6 13:57:45 http.c:369 moloch_http_curlm_check_multi_info(): 3/11 ASYNC 200 http://localhost:9200/stats/stat/localhost?version_type=external&version=1310 789/148 0ms 14ms
Sep  6 13:57:45 http.c:369 moloch_http_curlm_check_multi_info(): 2/11 ASYNC 200 http://localhost:9200/_bulk 299354/4246 0ms 277ms
Sep  6 13:57:45 http.c:369 moloch_http_curlm_check_multi_info(): 1/11 ASYNC 200 http://localhost:9200/_bulk 80446/1226 0ms 181ms
Sep  6 13:57:45 packet.c:1103 moloch_packet_log(): packets: 66400000 current sessions: 76602/85459 oldest: 0 - recv: 71906525 drop: 0 (0.00) queue: 0 disk: 0 packet: 0 close: 1407 ns: 0 frags: 0/4452 pstats: 77106925/0/0/0/68161/0
Sep  6 13:57:45 writer-simple.c:327 writer_simple_thread(): ERROR writing - -1 No space left on device
Sep  6 13:57:46 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/_template/sessions2_template?filter_path=**._meta 0/80 6ms 8ms
Sep  6 13:57:46 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/sequence/sequence/fn-localhost 0/122 0ms 1ms
Sep  6 13:57:46 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/sequence/sequence/fn-localhost 2/176 0ms 5ms
Sep  6 13:57:46 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/stats/stat/localhost 0/916 0ms 1ms
Sep  6 13:57:46 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/fields/field/_search?size=3000 0/71259 0ms 11ms
Sep  6 13:57:46 field.c:260 moloch_field_define(): WARNING - Field kind in db date doesn't match field kind seconds in capture for field cert.notbefore
Sep  6 13:57:46 field.c:260 moloch_field_define(): WARNING - Field kind in db date doesn't match field kind seconds in capture for field cert.notafter
Sep  6 13:57:46 http.c:563 moloch_http_curl_watch_open_callback(): Connected 1/0 - http://localhost:9200   49012->[::1]:9200 - fd:7
Sep  6 13:57:46 http.c:369 moloch_http_curlm_check_multi_info(): 1/1 ASYNC 200 http://localhost:9200/_cat/health?format=json 0/198 50ms 101ms
Sep  6 13:57:46 writer-simple.c:450 writer_simple_init(): INFO: Reseting pcapWriteSize to 262144 since it must be a multiple of 4096
Sep  6 13:57:46 packet.c:1114 moloch_packet_ip(): Initial Packet = 1567749466
Sep  6 13:57:46 packet.c:1115 moloch_packet_ip(): 0 Initial Dropped = 4055
Sep  6 13:57:46 packet.c:1114 moloch_packet_ip(): Initial Packet = 1567749466
Sep  6 13:57:46 packet.c:1115 moloch_packet_ip(): 57 Initial Dropped = 4055
Sep  6 13:57:46 db.c:1719 moloch_db_create_file_full(): Creating file 43 with key >/files/file/localhost-43?refresh=true< using >{"num":43, "name":"/data/moloch-nightly/raw/localhost-190906-00000043.pcap", "first":1567749466, "node":"localhost", "locked":0}<
Sep  6 13:57:46 http.c:563 moloch_http_curl_watch_open_callback(): Connected 2/1 - http://localhost:9200   49014->[::1]:9200 - fd:9
Sep  6 13:57:46 writer-simple.c:327 writer_simple_thread(): ERROR writing - -1 No space left on device

[capture.log](https://github.com/aol/moloch/files/3582821/capture.log)

Please check the attachment for the detailed log; I hope to get your reply.

**Comment by awick** [comment]
It means there is no disk space to write the pcap to.  See https://molo.ch/faq#pcap-deletion
