### ISSUE TITLE
"baseline comparison" for Connections visualization

### ISSUE THREAD

**Issue by mmguero** [aol/moloch#1162]
At several deployments we've done (and in demos/conversations with others) those using Moloch for analysis have asked for the ability to see "what's changed in my network?", particularly in very static/fixed networks like ICS/SCADA environments.

I would like to enhance the Connections visualization by adding a "baseline comparison" option. Here's my pitch:

- somewhere in the controls on the Connections view (probably to the right of the existing connections controls, although space might get tight) there's a checkbox (unchecked by default) that says "Baseline Comparison" or "Compare Against Baseline" or something like that
- upon checking this option, another Start/End time picker pair become enabled or visible. the user is able to specify a time frame prior to the main query time frame currently selected (so this won't work with `all` obviously). This could either be automatically pre-populated upon enabling with the previous time interval, or maybe you've got a "quick" dropdown with similar options to your "Last hour" "Last day" etc. options although it would be "previous" instead of "last", or maybe they just have to manually enter the time frame they're interested in
- when the query runs, the connections.json API runs twice: once like it does currently for the main time frame, and again for the "baseline" time frame
- the two node lists are compared, and any nodes not in both lists are drawn accordingly.

There are some details we'd need to work out, and I'd love your feedback and advice:

1. Would we want to only indicate added nodes ("something has been introduced into my network") or would we want to include both added and removed nodes ("something has disappeared from my network")?
2. Would we want to highlight only changed nodes? Or would you want to highlight links as well? (My opinion on this is that it would get a little too cluttered trying to do both, and that we only diff the nodes and not the links.)
3. What's the best way to represent these changed nodes? You're already using 3 colors for source/dest/both, so coloring might not be the best way to introduce a change. Maybe different icons (eg., 🞧 icon for added nodes, 🚫 for removed nodes?)? Or maybe some sort of different border/outline around the icons? You'd know better than me what our options would be.

Naturally running the connections view with this baseline feature turned on would take longer (possibly more than 2x longer), but I think it could be done without cluttering up the controls and resulting graph too much and would be a very valuable way to compare network changes over time. This would be valuable with a *lot* of the fields Moloch knows about: not only Src/Dst IP addresses, but protocols/services, GeoIP values, OUI values, etc.

I would be happy to implement this feature in my fork and submit it as a pull request for you guys upstream. I just wanted to have a discussion about your thoughts/advice before I start working on it.

**Comment by mmguero** [comment]
After getting pulled off on a bunch of other stuff, I've started to work on this.

I've got one commit in so far: https://github.com/mmguero-dev/moloch/commit/1eb11d7c44bdbce9ae065edd9521825ee2dbe829

The commit's changes are not as severe as the github side-by-side makes it look: the biggest change is factoring some code out of `buildSessionQuery` into a `determineQueryTimes` function for reuse.


To copy the comments from that commit:

```
consisting of (all in viewer.js):

1. factored out some code from buildSessionQuery into a determineQueryTimes
    function for calculating startTime, stopTime, and interval values
    given a req, and modified buildSessionQuery to call that function
    instead, as well as a new bit of code in buildConnections

2. In buildConnections, if network graph baseline is enabled
    (enabled: req.query.baseline=1, disabled:req.query.baseline=0 or undefined)
    then two queries will be run (ie., run buildSessionQuery->searchPrimary->process twice):
    first for the original specified time frame and second for the same time frame
    immediately preceding it.
  Nodes have an .inresult attribute where:
    Dec Bin  Description
    0 = 00 = not in either result set (although you'll never see these, obviously)
    1 = 01 = seen during the "current" time frame but not in the "baseline" time frame (ie., "new")
    2 = 10 = seen during the "baseline" time frame but not in the "current" time frame (ie., "old")
    3 = 11 = seen during both the "current" time frame and the "baseline" time frame
  This is only performed where startTime/startTime are defined, and never for "all" time range (date=-1).
```

 I'm not to the point yet of putting in UI functionality, but I think this is working the way I'm
 envisioning it on the API side of things. I'll add a test case when I'm done, for now I'm using
 a PCAP here (https://github.com/idaholab/Malcolm/tree/development/moloch/network_diff) which
 only has two packets, one on one day and the other on the next day. 

When running the API with the default (baseline off):

https://localhost/connections.json?date=0&startTime=1582614000&stopTime=1582700399&expression=zeek.logType==EXISTS!&baseline=0
```
{
    "health": {
...
    },
    "nodes": [
        {
            "id": "192.168.1.109",
            "cnt": 1,
            "sessions": 2,
            "inresult": 1,
            "type": 1,
            "totBytes": 1378,
            "totDataBytes": 0,
            "totPackets": 1,
            "node": [
                "filebeat"
            ],
            "pos": 0
        },
        {
            "id": "203.66.169.19",
            "cnt": 1,
            "sessions": 2,
            "inresult": 1,
            "type": 2,
            "totBytes": 1378,
            "totDataBytes": 0,
            "totPackets": 1,
            "node": [
                "filebeat"
            ],
            "pos": 1
        }
    ],
    "links": [
        {
            "value": 2,
            "source": 0,
            "target": 1,
            "totBytes": 1378,
            "totDataBytes": 0,
            "totPackets": 1,
            "node": [
                "filebeat"
            ]
        }
    ],
    "recordsFiltered": 2
}
```

When running it with the baseline on:
https://localhost/connections.json?date=0&startTime=1582614000&stopTime=1582700399&expression=zeek.logType==EXISTS!&baseline=1
```
{
    "health": {
...
    },
    "nodes": [
        {
            "id": "192.168.1.109",
            "cnt": 2,
            "sessions": 3,
            "inresult": 3,
            "type": 1,
            "totBytes": 2756,
            "totDataBytes": 0,
            "totPackets": 2,
            "node": [
                "filebeat"
            ],
            "pos": 0
        },
        {
            "id": "203.66.169.19",
            "cnt": 1,
            "sessions": 2,
            "inresult": 1,
            "type": 2,
            "totBytes": 1378,
            "totDataBytes": 0,
            "totPackets": 1,
            "node": [
                "filebeat"
            ],
            "pos": 1
        },
        {
            "id": "216.58.212.101",
            "cnt": 1,
            "sessions": 1,
            "inresult": 2,
            "type": 2,
            "totBytes": 1378,
            "totDataBytes": 0,
            "totPackets": 1,
            "node": [
                "filebeat"
            ],
            "pos": 2
        }
    ],
    "links": [
        {
            "value": 2,
            "source": 0,
            "target": 1,
            "totBytes": 1378,
            "totDataBytes": 0,
            "totPackets": 1,
            "node": [
                "filebeat"
            ]
        },
        {
            "value": 1,
            "source": 0,
            "target": 2,
            "totBytes": 1378,
            "totDataBytes": 0,
            "totPackets": 1,
            "node": [
                "filebeat"
            ]
        }
    ],
    "recordsFiltered": 3
}
```

So you'll notice that with baselining on, I get the node from the previous day as well. Take note of the `inresult` field which is how we're distinguishing between old/new/both.

I'd love you guys' feedback on this, if you think it's going in the right direction.

So far everything I'm doing just revolves around new nodes, not new links between existing nodes. Baby steps.

Also for now baselining just automatically calculates the immediate previous time frame. It would be easy enough to specify a start/stop time for the baseline instead of automatically calculating it, as long as they don't overlap.

**Comment by mmguero** [comment]
Easiest way to compare what I'm doing as I work on this is compare these branches ([aol/moloch/tags/v2.2.2 vs. mmguero-dev/moloch/topic/netdiff_2.2.2](https://github.com/aol/moloch/compare/v2.2.2...mmguero-dev:topic/netdiff_2.2.2)).

**Comment by mmguero** [comment]
I feel like good progress is being made, here are a couple of screenshots to see what it looks like so far:

![screenshot-20200227_150023](https://user-images.githubusercontent.com/13872653/75490988-67bffa80-5972-11ea-8aed-1832e9e3e668.png)
![screenshot-20200227_150019](https://user-images.githubusercontent.com/13872653/75490987-67276400-5972-11ea-8722-6c9640aad0c5.png)

Here are things to look for in the screenshots:

- the **Compare against baseline** checkbox (immediately to the right of **Query Size**) which enables/disables the feature
- the `baseline=` parameter in the URL
- the **Result Set** value in the selected node popup on the left (possible values are **Actual**, **Baseline**, or **Both**)

As far as indicating for the nodes themselves, I didn't want to mess with node fill color (since the colors already mean src/dst/both) and I didn't want to mess with icon/shape (since @awick mentioned he has future plans for that), so so far I've gone with a combination of node border and label weight/style. Here's how it breaks down:

**When baseline is disabled**

- no changes from the way the nodes look in previous versions

**When baseline is enabled**

- "new* nodes (exist in actual but not baseline results)
  - label font is bold
  - node outline is thicker and uses `--color-primary-lighter` color
- "old" nodes (exist only in baseline results):
  - label font is lighter and italic
  - node outline uses `--color-tertiary-lighter` color
- "both" nodes (exist in both actual and baseline results):
  - label font is normal
  - node outline is normal and uses `--color-foreground` as it has in previous versions

I looked into some other things (hatching, "glow" effects, etc.) but it either made things too busy or added CPU strain. I feel like at the moment these values make enough of a difference between the types of nodes while still leaving the chart readable.

Still to do are making nodes visible/invisible based on their baseline state.

**Comment by 31453** [comment]
This looks awesome! ✨ Thanks coming up with this use case and implementation.

The API makes sense and seems to be well implemented (especially all the comments that make the code easier to understand at a glance). 

I like the node outline, but maybe it could be a pixel or two thicker? 

I think that distinguishing between old, new, and both nodes still needs some improvement. I think we could add some icons to the text itself in addition to what you've already done. Maybe add a "+" to new nodes, an "x" told old nodes and leave both alone? We could also modify the color of the text, but that might be more difficult considering themes.

Awesome work! I can't wait to see this in action.

**Comment by mmguero** [comment]
Thanks Elyse, I agree with your recommendations. I'll try some things out and post screenshots here to get your feedback.

**Comment by mmguero** [comment]
@31453 here are some possibilities for icons. Of course, we could mix and match any of them (if you like one for the "new" and another one for the "missing/old" nodes). 

I just went to http://www.amp-what.com/unicode/search/plus and searched for different things (plus, minus, check, flag, prohibited, question, star, circle, etc.) and tried a few out.

I think you are right, though, I think this is a good way to see things. The screenshots I attached are probably heavier with icons than they would be since I'm comparing unrelated data sets. 

What do you think, if we used the icons would we want to get rid of the font weighting (the bold and/or italic) or leave it?

![connections_circles_plus_minus](https://user-images.githubusercontent.com/13872653/75697277-13ff2b00-5c6a-11ea-8a93-935eccaa472e.png)
![connections_eye_no_1](https://user-images.githubusercontent.com/13872653/75697281-1497c180-5c6a-11ea-9115-13ea1267e5bf.png)
![connections_eye_no_2](https://user-images.githubusercontent.com/13872653/75697282-1497c180-5c6a-11ea-9793-fe706af2869a.png)
![connections_flag_question](https://user-images.githubusercontent.com/13872653/75697283-15305800-5c6a-11ea-9e62-e0bbabae6ffd.png)
![connections_new_no](https://user-images.githubusercontent.com/13872653/75697285-15305800-5c6a-11ea-9a19-b829d0df4109.png)
![connections_sparkles_no](https://user-images.githubusercontent.com/13872653/75697286-15c8ee80-5c6a-11ea-9d9e-5e47441f9fda.png)
![connections_star_x](https://user-images.githubusercontent.com/13872653/75697287-15c8ee80-5c6a-11ea-9124-989bd429fe38.png)
![connections_superscript_plus_minus](https://user-images.githubusercontent.com/13872653/75697289-16618500-5c6a-11ea-97b5-af1719e1d44f.png)

**Comment by mmguero** [comment]
Probably the least visually intrusive one (whether that's a pro or a con) is the last one, with the superscripted plus/minus signs. But the other icons might be more visible?

**Comment by amaddalena** [comment]
fwiw I enjoy https://user-images.githubusercontent.com/13872653/75697286-15c8ee80-5c6a-11ea-9d9e-5e47441f9fda.png the best. Or perhaps a Red styled Minus for the old connections. A User setting for icon choice would be even better as it would not interfere with custom theming as much (color palette etc)

**Comment by 31453** [comment]
I like the one that @amaddalena likes! I think it provides good contrast and is not super intrusive.

I love where this feature is going. Awesome work!

**Comment by mmguero** [comment]
K I'll go that way for now then and if we want to elaborate on it later (make it user-selectable or whatever) we can do that. thanks for the feedback.

**Comment by mmguero** [comment]
Here's an update on the stuff I'm working on right now:

I've added a "Baseline Node Visibility" selector with 5 options. When "Compare Against Baseline" is enabled, this selector takes effect. It has the following options

- All Nodes (all nodes are visible)
- Actual Nodes (nodes present in the "current" timeframe query results are visible)
- Baseline Nodes (nodes present in the "baseline" timeframe query results are visible)
- New Nodes Only (nodes present in the "current" but NOT the "baseline" timeframe are visible)
- Baseline Nodes Only (nodes present in the "baseline" but NOT the "current" timeframe are visible)

Changing this selection causes nodes/links to become visible/hidden based on the result set(s) the node has membership in (see screenshots).

I opted not to change node weighting or re-force the graph physics as these nodes are made visible/hidden as I think it is easier to follow when the positions of the nodes don't change as I'm clicking between the options.

![screenshot-20200304_075411](https://user-images.githubusercontent.com/13872653/75891930-ba276e00-5ded-11ea-9c94-10b7a2dfb7b2.png)

![screenshot-20200304_075309](https://user-images.githubusercontent.com/13872653/75891928-b98ed780-5ded-11ea-900f-2feb3181472c.png)

**Comment by 31453** [comment]
This is awesome! 👍 

Like you said previously, the options in the sub-nav bar are getting super long and are now wrapping onto the next line. Maybe we can put some of these options directly on the connections graph itself (like the zoom, node distance, and font size). Maybe the last 4 options (unlock, export, node/link config). Thoughts?

**Comment by mmguero** [comment]
That might be a good idea... as I'm thinking probably before I'm done I should add another start/end date picker so that you can specify a specific baseline range rather than just the hard-coded "immediately prior to your current query date range" like it is right now.

**Comment by 31453** [comment]
Yes, good idea. Where do you think it might go? 

Maybe we can add a sub-sub-nav bar when the checkbox for Compare Against Baseline is checked? It'll only show when that checkbox is true and will show the Baseline Node Visibility dropdown as well as the additional start and stop time pickers.

**Comment by mmguero** [comment]
> Maybe we can add a sub-sub-nav bar ...

I like that idea. I actually had a similar thought a little while ago but hadn't got around to figuring out how to implement it. Maybe for now I'll put the date pickers in (and just let it wrap) and do the testing I need to do for that and then we can work out the finer points of the UI at that point.

I feel like we're not too far off from having this feature complete, but I've probably still got a few more days of work on it. Thanks

**Comment by awick** [comment]
* I think the compare against checkbox could go away and "off" could be the first option in the pull down.  The label could also be shortened to get more room.
* I'm not a huge fan of another nav bar, unless it disappears when your mouse isn't there :). I know Elyse will love that
* instead of another date picker, a pull down with common options might be better/easier.  Like I want to be able to say compare against an hour ago, a week ago, a month ago, etc.  And I would hate to have to pick that from a date picker

I would say you are close to getting a first version, don't worry about getting perfect because feedback will help

**Comment by 31453** [comment]
- I like the idea of combining the compare against and baseline node visibility inputs. Good idea!
- I hate the idea of a disappearing sub-nav bar! :)
- I think doing a time range instead of two date pickers is also a good idea. I think this would fit in with most people's use cases and if not, people with speak up and we can rethink it.

**Comment by mmguero** [comment]
- I'm fine with that idea as well. The only thing that might be slightly weird is that choosing between "off" and some other value will re-run the query (as baselining runs two queries, rather than just one, which you don't always want to do), while just choosing between the different baseline visibility modes doesn't need to re-run the query. I don't think that's a big deal, though.
- That works for me. We can start there improve it later if you think we need to, like you said.

**Comment by mmguero** [comment]
I'm very close to creating a pull request. I have a little bit of cleanup to do, but I've got the async/promises stuff working correctly now.

I've also removed the checkbox and consolidated things now into two drop-downs:

- a time frame picker (with `disabled` to disable baselining and time range options ortherwise)
- the node visibility picker

Changing the first one re-runs the query, while changing the second one is client-side only.

I think this is much clearer. I'll do the last cleanup I need to do, see if I can add some QA tests, then get with you guys about a PR.

**Comment by mmguero** [comment]
Here's an update of where things are at with this feature:

graphically:

![Screenshot_2020-03-17 docker-cluster - Connections](https://user-images.githubusercontent.com/13872653/76898285-08f7ed80-685b-11ea-8838-284fa2bce0d4.png)

There are two new GUI controls which deal with this baseline feature:

- Baseline Time Frame
  - disabled
  - 1 × actual time frame
  - 2 × actual time frame
  - 4 × actual time frame
  - 6 × actual time frame
  - 8 × actual time frame
  - 10 × actual time frame
  - 1 hour
  - 6 hours
  - 24 hours
  - 48 hours
  - 72 hours
  - 1 week
  - 2 weeks
  - 1 month
  - 2 months
  - 6 months
  - 1 year

- Baseline Node Visibility
  - All nodes
  - Actual nodes
  - Baseline nodes
  - New nodes only
  - Baseline nodes only

The first item of each of those dropdowns is selected by default, which results in the old behavior for the connections graph.

When **Baseline Time Frame**'s selection changes, the `cancelAndLoad` so that the query is re-run. Changing the **Baseline Node Visibility** doesn't re-run anything, as the existing data is enough (node/link visibility is just modified).

I've [added to the `api-connections.t` test](https://github.com/aol/moloch/blob/9fc3450502cbc68cd5b076283875afd3627585e8/tests/api-connections.t#L71-L100). Tests 1-8 run fine. The new tests (comprising test 9-10) get a `PASS` status. However, for the `multiGet` version of that test, although it gives the right output and reports `PASS`, generates this error/debug output from the `tests.pl` script:

```
moloch@alien:~/tests$ ./tests.pl --viewerhang --debug
Skipping ES Init and PCAP load
Starting viewer
Connecting 127.0.0.1:8081
Success
(node:5035) UnhandledPromiseRejectionWarning: Error: Not Found
    at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/data/moloch/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at emitWarning (internal/process/promises.js:97:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
    at process._tickCallback (internal/process/next_tick.js:69:34)
(node:5035) Error: Not Found
    at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/data/moloch/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:5035) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:111:13)
    at emitWarning (internal/process/promises.js:104:3)
    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
    at process._tickCallback (internal/process/next_tick.js:69:34)
(node:5035) UnhandledPromiseRejectionWarning: Error: Not Found
    at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/data/moloch/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at emitWarning (internal/process/promises.js:97:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
    at process._tickCallback (internal/process/next_tick.js:69:34)
(node:5035) Error: Not Found
    at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/data/moloch/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I'm still trying to figure it out, but haven't made much headway yet as it seems to give the "right" answer in both the `viewerGet` and `multiGet` scenarios, but only the `multiGet` throws this error.

PR #1392 has been created against the master branch. As far as I am concerned I think the only thing left besides figuring out this multis error would be to do a final code review before it would be ready to be merged.

**Comment by mmguero** [comment]
I can reproduce it with a very simple test:

```
use Test::More tests => 2;
use Cwd;
use URI::Escape;
use MolochTest;
use JSON;
use Test::Differences;
use Data::Dumper;
use strict;

my $pwd = "*";
my $files_baseline = "(file=$pwd/smtp-originating.pcap)";

my ($json, $mjson);

# node to protocols with baseline
    $json = multiGet("/connections.json?date=0&startTime=1388559600&stopTime=1404194399&length=100000&dstField=protocol&baselineDate=1x&baselineVis=all&expression=" . uri_escape("$files_baseline"));
    delete $json->{health};
    eq_or_diff($json, from_json('{ "nodes": [], "links": [  ], "recordsFiltered": 62 }', {relaxed => 1}), "node to protocol baselined", { context => 3 });
```

Yes the results are wrong as well, I don't really care about that in this little example, it's just a simple way to get the errors.

**Comment by mmguero** [comment]
https://github.com/aol/moloch/pull/1392#issuecomment-600793739

**Comment by mmguero** [comment]
Close with PR #1392
