### ISSUE TITLE
Error in "First Date" display

### ISSUE THREAD

**Issue by ZikyHD** [aol/moloch#1164]
**Elasticsearch version**: 6.8.2

**Moloch version**: 2.0.1

**OS name and version**: Ubuntu 18.04.3 x64

**How was Moloch built/installed:** deb

**Provide logs, stack traces and steps to reproduce**:

The "Files" tab does not appear to display the real date in the "First Date".
However the timestamp is correctly indexed in files_v6 index.

**Comment by awick** [comment]
Can you provide a screenshot or more detail on what you mean?

**Comment by ZikyHD** [comment]
I've just added an offline PCAP file to moloch.
The capture start friday, the 7th june 2019 19h52:56 UTC (1559937176).
The "Files" tab displays 1970/01/19 01:18:57 UTC => NOK
The field "first" contains 1559937176 => OK
