### ISSUE TITLE
where is logout option in viewer?

### ISSUE THREAD

**Issue by imanviii** [aol/moloch#117]
Hi all
Maybe it exist and i could not find it, but the question is where is the log out button on Moloch viewer? 
thanks in advance

**Comment by paulfillmore** [comment]
I don't understand this response. Arkime doesn't support logging out?

**Comment by awick** [comment]
It depends what auth method you are using. If you are using http digest, which is a browser based auth, there is no standard way to log out across all browsers. The only standard solution across all browsers is restarting your browser or using private mode to start with.

If you are using another form of auth, you'll have to use whatever logout functionality that supports.

See #866 and #1963 where we've discussed some hack also.

Feel free to come on over to slack if you want to discuss more

**Comment by paulfillmore** [comment]
I don't want to use slack, I'm just trying to understand why there isn't an option to log out. This seems like an incredibly basic requirement.

**Comment by awick** [comment]
Yep it is terrible, you should complain to the creators of http digest/basic standard and every browser creator.

The majority of folks who use Arkime deploy it with their own auth with SSO, so logout doesn't make sense for them either.

![image](https://user-images.githubusercontent.com/427321/223551156-99e36463-468e-495f-a821-97b9989c60da.png)
