### ISSUE TITLE
Bug : moloch-capture:24868: GLib-ERROR **: gmem.c:105: failed to allocate 18446744073709551514 bytes

### ISSUE THREAD

**Issue by bigsea520** [aol/moloch#1170]
**Elasticsearch version**: 6.6

**Moloch version**: moloch-nightly.x86_64.rpm

**OS name and version**: centos 7.6

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm

**Provide logs, stack traces and steps to reproduce**:
(moloch-capture:24868): GLib-ERROR **: 13:03:00.022: gmem.c:105: failed to allocate 18446744073709551514 bytes
Sep 17 13:03:00 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/_template/sessions2_template?filter_path=**._meta 0/80 4ms 8ms
Sep 17 13:03:00 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/sequence/sequence/fn-localhost 0/120 0ms 2ms
Sep 17 13:03:00 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/sequence/sequence/fn-localhost 2/174 0ms 3ms
Sep 17 13:03:00 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/stats/stat/localhost 0/914 0ms 1ms
Sep 17 13:03:00 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/fields/field/_search?size=3000 0/74498 0ms 15ms
Sep 17 13:03:00 field.c:260 moloch_field_define(): WARNING - Field kind in db date doesn't match field kind seconds in capture for field cert.notbefore
Sep 17 13:03:00 field.c:260 moloch_field_define(): WARNING - Field kind in db date doesn't match field kind seconds in capture for field cert.notafter

**Comment by bigsea520** [comment]
I enabled the Suricata plug-in and then reported the problem. The allocation of memory is too large and completely unreasonable. I want to know how to solve this problem.

Please view the complete log.

[capture9.17.log](https://github.com/aol/moloch/files/3624078/capture9.17.log)

**Comment by awick** [comment]
Can you provide the output of `./moloch-capture --version`

**Comment by bigsea520** [comment]
moloch-capture 1.6.0/v1.6.0 session size=384 packet size=80 api=160
glib2: 2.56.2
libpcap: libpcap version 1.9.0-PRE-GIT (with TPACKET_V3)
curl: libcurl/7.61.1 OpenSSL/1.0.2k zlib/1.2.7
pcre: 8.31 2012-07-06
yara: 3.8.1
maxminddb: 1.3.2

and , I used  moloch versions 2.0 or 2.0.1 ，No error was reported
but had new problems , suricata generated warning information was not stored in elasticsearch, but elasticsearch established Suricata index.

**Comment by bigsea520** [comment]
I want to know the latest version of moloch, how to support the Suricata plug-in.

My configuration is as follows.
plugins=suricata.so
suricataAlertFile=/var/log/suricata/eve.json
suricataExpireMinutes=10

 Do you need to modify any configuration?

**Comment by awick** [comment]
I'm confused, what version did you use for the memory issue? You say nightly in the bug report but the output says 1.6.  If you are having issues with 2.0.1 then please describe those issues in #1058.  Change suricataExpireMinutes to 120 minutes.

**Comment by bigsea520** [comment]
moloch-capture 1.6.0 / v1.6.0 session size = 384 packet size = 80 api = 160
glib2：2.56.2
libpcap：libpcap version 1.9.0-PRE-GIT（with TPACKET_V3）
curl：libcurl / 7.61.1 OpenSSL / 1.0.2k zlib / 1.2.7
pcre：8.31 2012-07-06 yara：
3.8.1
maxminddb：1.3.2

**Comment by bigsea520** [comment]
moloch-capture 1.6.0 / v1.6.0 session size = 384 packet size = 80 api = 160
glib2：2.56.2
libpcap：libpcap version 1.9.0-PRE-GIT（with TPACKET_V3）
curl：libcurl / 7.61.1 OpenSSL / 1.0.2k zlib / 1.2.7
pcre：8.31 2012-07-06 yara：
3.8.1
maxminddb：1.3.2

**Comment by bigsea520** [comment]
ok， thank you .
