### ISSUE TITLE
 Moloch can't monitor virtual ports， Is Moloch unable to monitor virtual ports?

### ISSUE THREAD

**Issue by zhy0830** [aol/moloch#1171]
Moloch can't monitor virtual ports

config.ini:
interface=vethns0(vitual network port)

Tcpdump can display data，but moloch can not.

Is Moloch unable to monitor virtual ports?

**Comment by awick** [comment]
Please fill in the template for bugs

What version of moloch?
What is the error in capture.log?

**Comment by awick** [comment]
feel free to reopen with more info
