### ISSUE TITLE
Shrink Index UI

### ISSUE THREAD

**Issue by awick** [aol/moloch#1182]
On "ES Indices" tab add a new "Shrink" action menu option.  It should popup a UI in the sub nav bar with ok/cancel with two inputs

* Number of shards:  It should default to the lowest prime factor of the current shards count, and if such a number doesn't exist it should default to 1
* Temporary node: Should default randomly to a es data node.

The viewer.js end point should either call db.pl or implement the logic that db.pl has for shrink

**Comment by 31453** [comment]
implemented in 44a2cce
