### ISSUE TITLE
code cores if parsers aren't available

### ISSUE THREAD

**Issue by bf31415** [aol/moloch#1189]
**Elasticsearch version**:
7.mumble

**Moloch version**:

protocolrefactor branch (latest)

**OS name and version**:

ubuntu 16.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

easybutton

**Provide logs, stack traces and steps to reproduce**:

I fat fingered the dir for the parsers (in config.ini).   i was using parsers in the local build  dir and not in /data/moloch.  it looks like this results in the code core-ing at this line:

mProtocols[packet->mProtocol].createSessionId(sessionId, packet);

in the capture output i see this line:

Oct  9 18:31:37 parsers.c:671 moloch_parsers_init(): Error with /elastic/src/moloch-protocalrefactor-sllf/capture/parsers: Error opening directory “/elastic/src/moloch-protocalrefactor-sllf/capture/parsers”: No such file or directory

Maybe the LOG on parsers.c:671 should be changed to LOGEXIT?

**Comment by awick** [comment]
I couldn't reproduce this, but it now handles mProtocol not being set.
