### ISSUE TITLE
Bug: Permission denied error when searching for email attributes in Moloch Viewer

### ISSUE THREAD

**Issue by MoloSuri** [aol/moloch#1206]
Searching for email attributes causes permission denied error (Moloch Viewer).

**Elasticsearch version**: elasticsearch/now 5.6.0

**Moloch version**: moloch/now 1.8.0-1 amd64

**OS name and version**: Debian GNU/Linux 9.9

**How was Moloch built/installed:** deb

**Provide logs, stack traces and steps to reproduce**: Searching for email attributes in Moloch Viewer causes permission denied error message instead of showing the results. I use Moloch 1.8.0. The problem is the same with the version 2.0.1 (https://demo.molo.ch demo page). Screenshot attached.

![email_permission_denied](https://user-images.githubusercontent.com/56717512/67184406-fbd9ee00-f3e3-11e9-9590-407f1cc08c22.png)

**Comment by awick** [comment]
need to enable in users tab

**Comment by douglagm** [comment]
Hi,
 I Don't mean to hijack this thread, but I have the same issue with the Admin account. It was created as per [README.txt](https://raw.githubusercontent.com/aol/moloch/master/release/README.txt) 

> Add an admin user if a new install or after an init
      /data/moloch/bin/moloch_add_user.sh admin "Admin User" THEPASSWORD --admin

The Users Tab is more for managing new users, how do I change this for the above Admin.

Thanks

**Comment by awick** [comment]
The users tab is for managing all users, including admins.

**Comment by douglagm** [comment]
Admin is not listed under Users

![image](https://user-images.githubusercontent.com/5304858/67278447-4a14ed00-f4c9-11e9-948e-75b77fd25cad.png)

**Comment by awick** [comment]
You are running in anonymous mode probably, make sure passwordSecret is set.  Please come to slack for future questions.

**Comment by awick** [comment]
also make sure regressionTests isn't set to true.  I've added started up warnings for both these cases.
