### ISSUE TITLE
smtp email attachment filename non readable

### ISSUE THREAD

**Issue by zsn9170** [aol/moloch#1261]
**Elasticsearch version**: 5.6.0

**Moloch version**: 1.8.0-1

**OS name and version**: Debian 9.9

**How was Moloch built/installed:** deb

**Provide logs, stack traces and steps to reproduce**:

We sent an email, 
subject is: Árvíztűrő tükörfúrógép,
attachment name is: Árvíztűrő tükörfúrógép.txt

We downloaded pcap from moloch viewer, and this is the name of the attachment filename in pcap:

[...]
Content-Type: text/plain; charset="UTF-8"; name="=?UTF-8?B?w4FydsOtenTFsXLFkSB0w7xrw7ZyZsO6csOzZ8Op?=
                =?UTF-8?B?cC50eHQ=?="
Content-Disposition: attachment;
                filename="=?UTF-8?B?w4FydsOtenTFsXLFkSB0w7xrw7ZyZsO6csOzZ8OpcC50eHQ=?="
Content-Transfer-Encoding: base64
[...]
 
so the attachment filename is a: 
                filename="=?UTF-8?B?w4FydsOtenTFsXLFkSB0w7xrw7ZyZsO6csOzZ8OpcC50eHQ=?="

We decoded the filename with www.base64decode.org, and i set up the source charset is UTF-8.
Decoded format is: Árvíztűrő tükörfúrógép.txt

and if set up source charset is ISO-8859-2, it's decoded format is: ĂrvĂ­ztĹąrĹ tĂźkĂśrfĂşrĂłgĂŠp.txt 

The value of filename in the elastic database:
"filename" : [
              "Ã�rvÃ­ztÅ±rÅ� tÃ¼kÃ¶rfÃºrÃ³gÃ©p.txt"
],

This is the email attachment file:
[Árvíztűrő tükörfúrógép.txt](https://github.com/aol/moloch/files/3788634/Arvizturo.tukorfurogep.txt)

This is the elasticsearch data:
[elastic_data.txt](https://github.com/aol/moloch/files/3788635/elastic_data.txt)

How to configure molochcapture for email attachment filename charset to be UTC-8?

Best regards,
Zsolt Nagy

**Comment by zsn9170** [comment]
can anyone help?

**Comment by brezsny** [comment]
I found the same. Can anyone help us solving the issue described above?

Thanks,
Brezsny

**Comment by awick** [comment]
Please provide a sample pcap with the issue, either here or DM on slack

**Comment by brezsny** [comment]
> Please provide a sample pcap with the issue, either here or DM on slack


[191202_brezs.zip](https://github.com/aol/moloch/files/3931212/191202_brezs.zip)

Thanks for any advice.

**Comment by awick** [comment]
This sample doesn't have a content type with boundary.  Is this a real sample?

**Comment by zsn9170** [comment]
Please give me an email address where I can send it.

**Comment by awick** [comment]
andywick @ gmail

**Comment by zsn9170** [comment]
I sent the pcap file by mail.
Regards,

**Comment by zsn9170** [comment]
Did you find a solution to the problem?
Regards,
