### ISSUE TITLE
Allow WISE to use https

### ISSUE THREAD

**Issue by matoro** [aol/moloch#1269]
It would appear that the `wise.so` plugin is currently hardcoded to use http:  https://github.com/aol/moloch/blob/master/capture/plugins/wise.c#L909

Despite the fact that the actual service supports https just fine:  https://github.com/aol/moloch/blob/master/wiseService/wiseService.js#L816

I even verified myself that running WISE over https does not interfere with anything.  This could also be solved by setting the curl options in `wise.so` to follow redirects as well.  This seems pretty easy to fix.

**Comment by awick** [comment]
Set wiseURL instead of wiseHost/wisePort
