### ISSUE TITLE
Cyberchef doesn't automatically apply "fromhex" and is repeatably unresponsive

### ISSUE THREAD

**Issue by philhagen** [aol/moloch#1300]
**Elasticsearch version**: 7.x

**Moloch version**: 2.0.1

**OS name and version**: CentOS 7

**How was Moloch built/installed:** rpm

When selecting the Cyberchef option, the "fromhex" module is included but doesn't automatically apply to the hex input in the upper right.  However, copy-pasting the hex will apply the one-item recipe.

Additionally, when selecting some recipe items, such as "JSON Beautify" or "JPATH Expression", the recipe hangs, with the Bombe wheels showing in the lower right, but the operation never completes.

I've seen this on several installations of my own, and @ecapuano has noted this in the OpenSOC implementation as well.

**Comment by mmguero** [comment]
I've seen the same thing lately. If I move my cursor to the bottom of the hex and add then delete a character it will execute, or if I copy/paste, but until it notes a change event it doesn't execute the BAKE

**Comment by awick** [comment]
What browser and browser platform are you folks using?

**Comment by mmguero** [comment]
Debian Linux 64-bit, both Chromium and Firefox (latest stable versions).

**Comment by philhagen** [comment]
centos 7 host running Moloch for both test cases (not sure that matters for this bug though)

macOS (latest) with chrome as one client-side test case, Ubuntu 16.04 and 18.04 running chromium as two others.
