### ISSUE TITLE
configure: error: please install magic library

### ISSUE THREAD

**Issue by 307105141** [aol/moloch#1308]
checking for libpcap... /home/elastic/moloch-master/thirdparty/libpcap-1.9.1
checking for nl_socket_alloc in -lnl-3... no
checking for nl_socket_alloc in -lnl... no
checking for nl_handle_alloc in -lnl... no
checking for yara... thirdparty/yara/yara-3.10.0
checking for maxminddb... thirdparty/libmaxminddb-1.3.2
checking for glib2... thirdparty/glib-2.56.2
checking for curl... thirdparty/curl-7.66.0
checking for lua... thirdparty/lua-5.3.5
checking for magic... checking for main in -lmagic... no
configure: error: please install magic library
make: *** No targets specified and no makefile found.  Stop.
MOLOCH: make failed

**Comment by 307105141** [comment]
install moloch ，configure: error: please install magic library。

**Comment by awick** [comment]
Need to install the libmagic/libfile library
