### ISSUE TITLE
ES version column in ES Nodes tab

### ISSUE THREAD

**Issue by mosajjal** [aol/moloch#1309]
Hi,

It'd be nice to have ES version in ES Nodes tab inside Moloch viewer. It's particularly useful during an upgrade.

If this page already gets the "stats" from ES cluster, this shouldn't be much of an extra load on the service either.

Cheers,

**Comment by 31453** [comment]
This exists as of version 2.0 of Moloch. I have attached a gif showing how to add it to the ES Nodes table.
![es_version](https://user-images.githubusercontent.com/1235082/68957827-d64cc400-0798-11ea-8dae-7d0fa424335c.gif)
