### ISSUE TITLE
When using Wise and the Tagger file, cannot import UTF-8 strings

### ISSUE THREAD

**Issue by pjsg** [aol/moloch#1312]
**Elasticsearch version**:   git master

**Moloch version**: 2.1.0

**OS name and version**: ubuntu 18.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) easybutton

If the tagger file includes (say):

#field:bs.info;kind:termfield;friendly:bsinfo;db:bs.info;help:The IP Information;shortcut:i
1.2.3.4:i=女宇農系人女族本職味協動公。失浮枝真公室霊奪疑奮発販。

and then Wise tags 1.2.3.4 -- the string is not shown correctly. This is becuase the UTF8 flag is not set on the field.

**Comment by awick** [comment]
do you think it should be on by default and a new flag to turn off instead?

**Comment by pjsg** [comment]
I'm always nervous about making backwards-incompatible changes. I can't *think* of any use for the 8-bit mode -- it isn't 8-bit clean in that if you put in (say) 0xa8, you don't get that back.
