### ISSUE TITLE
When using Wise and tagger file, the views get duplicated on every file reload

### ISSUE THREAD

**Issue by pjsg** [aol/moloch#1314]
**Elasticsearch version**:  git master

**Moloch version**: 2.1.0

**OS name and version**: ubuntu 18.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) easybutton

Whenever wiseService reloads the tagger file, the tagger file view definition gets *appended* to the current view for that file.

**Comment by awick** [comment]
thanks
