### ISSUE TITLE
Improve HTTP callback integration into the lua plugin

### ISSUE THREAD

**Issue by pjsg** [aol/moloch#1318]
I'd like to see more of the http parsing hooks exposed to the lua plugin. I think that all of the hooks should be exposed into the lua code.

For example:

MolochSession.on_http_cb(cb_type, function)

cb_type is one of "header_value", "header_field", "headers_complete", "message_begin", "url", "body", "message_complete".

The callback function would be invoked with the session object, the direction (0/1), data (if relevant).

Note that this will duplicate  (in one case) the existing register_body_feed. 

I'd also like to add a "header_field_raw" that returns the header field string before it is lower-cased. 

I'd appreciate comments on this before starting work.

Does anybody use the lua integration?

**Comment by awick** [comment]
I'm not sure if anyone uses it.  We did do that sample creditcard.lua

**Comment by 31453** [comment]
Implemented in c43c659
