### ISSUE TITLE
Unable to install on Parrot OS

### ISSUE THREAD

**Issue by hackvice** [aol/moloch#1338]
Unable to install

**Elasticsearch version**:

**Moloch version**:
Latest release

**OS name and version**:
Parrot OS

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
easy button

**Provide logs, stack traces and steps to reproduce**

```
gdbusauth.c: In function ‘_g_dbus_auth_run_server’:
gdbusauth.c:1302:11: error: ‘%s’ directive argument is null **[-Werror=format-overflow**=]
 1302 |           debug_print ("SERVER: WaitingForBegin, read '%s'", line);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [Makefile:3882: libgio_2_0_la-gdbusauth.lo] Error 1
make[4]: Leaving directory '/home/user/moloch/thirdparty/glib-2.56.2/gio'
make[3]: *** [Makefile:4724: all-recursive] Error 1
make[3]: Leaving directory '/home/user/moloch/thirdparty/glib-2.56.2/gio'
make[2]: *** [Makefile:2296: all] Error 2
make[2]: Leaving directory '/home/user/moloch/thirdparty/glib-2.56.2/gio'
make[1]: *** [Makefile:1279: all-recursive] Error 1
make[1]: Leaving directory '/home/user/moloch/thirdparty/glib-2.56.2'
make: *** [Makefile:900: all] Error 2
MOLOCH: make failed

```

**Comment by awick** [comment]
There must be an error further up, please provide the log

**Comment by awick** [comment]
Looks like you'll either need to uninstall the dbus-1 library (not clue what it is) or call configure yourself and have it use the OS version of configure.  Doesn't look like with glib I can tell it not to use the dbus stuff from configure.

**Comment by hackvice** [comment]
Any idea how to on this matie? I have no clue as well what is **dbus-1 library**

**Comment by awick** [comment]
nope, I don't use that OS

**Comment by awick** [comment]
does the .deb not work?

**Comment by hackvice** [comment]
No, sadly it does not install.
