### ISSUE TITLE
only about  10%  packet  can be  captured

### ISSUE THREAD

**Issue by luojichen** [aol/moloch#1345]
**Elasticsearch version**: 5.6.1  or  7.5
**Moloch version**:       1.5  or 2.2
**OS name and version**:Centos7
**How was Moloch built/installed:**RPM
**Provide logs, stack traces and steps to reproduce**:

 HI dear support:
I find  the moloch capture  loss many  packet traffice  now.
 When I use  nload or  tcpdump  to test , I find the packet rate is  about 30MByte/s (about 300Mbps),  but when I use "service molochcapture start" or "./moloch-capture -c /data/moloch/etc/config.ini",  I  find  only   2MByte/S increased in   data/moloch/raw/xxx.pacp.    

I dont' know how to debug it .  I try  reinstall MOLOCH 2.2 with ELASTIC 7.5.1,  or   MOLOCH 1.5 with ELASTIC 5.6.1  for nearly  10 times,  the problem  still  here.

Before that ,  the moloch   has  work   OK for  1 year.
The problem  is appeard  after  I   update the  MOLOCH1.0(ES 5.6) to   MOLOCH2( ES7),  
(MAYBE  SOMETHING  YUM UPDATE).

When update to MOLOCH2, I  find the packet loss problem ,  then I return back  to moloch 1.0 or  moloch 1.5,  but  the problem is stall in.

Please help me find where could be the problem 

Thank you ~

here is  some capture log
Dec 27 10:44:44 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 299196/6626 0ms 1121ms
Dec 27 10:44:45 http.c:368 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://localhost:9200/dstats/dstat/localhost-537-5 783/143 0ms 49ms
Dec 27 10:44:45 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 298767/5814 0ms 1098ms
Dec 27 10:44:46 http.c:368 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://localhost:9200/_bulk 298885/6415 0ms 1005ms
Dec 27 10:44:46 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/139 0ms 52ms
Dec 27 10:44:47 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 299394/6671 0ms 1009ms
Dec 27 10:44:48 http.c:368 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/140 0ms 58ms
Dec 27 10:44:48 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 299259/6659 0ms 1140ms
Dec 27 10:44:49 http.c:368 moloch_http_curlm_check_multi_info(): 1/30 ASYNC 200 http://localhost:9200/_bulk 299302/6833 0ms 1054ms
Dec 27 10:44:50 http.c:368 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/139 0ms 32ms
Dec 27 10:44:50 http.c:368 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://localhost:9200/dstats/dstat/localhost-538-5 783/143 0ms 32ms
Dec 27 10:44:50 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 298483/6966 0ms 1105ms
Dec 27 10:44:50 http.c:368 moloch_http_curlm_check_multi_info(): 1/30 ASYNC 200 http://localhost:9200/_bulk 299113/6876 0ms 906ms
Dec 27 10:44:52 http.c:368 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/140 0ms 34ms
Dec 27 10:44:52 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 298650/6546 0ms 1154ms
Dec 27 10:44:53 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 299303/6896 0ms 1085ms
Dec 27 10:44:54 http.c:368 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/139 0ms 41ms
Dec 27 10:44:54 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 298654/6879 0ms 1128ms
Dec 27 10:44:55 http.c:368 moloch_http_curlm_check_multi_info(): 1/30 ASYNC 200 http://localhost:9200/_bulk 298632/6879 0ms 1016ms
Dec 27 10:44:55 http.c:368 moloch_http_curlm_check_multi_info(): 1/30 ASYNC 200 http://localhost:9200/dstats/dstat/localhost-539-5 783/143 0ms 50ms
Dec 27 10:44:56 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/140 0ms 22ms
Dec 27 10:44:57 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 299225/6901 0ms 1054ms
Dec 27 10:44:58 http.c:368 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/140 0ms 28ms
Dec 27 10:44:58 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 299049/6946 0ms 1121ms
Dec 27 10:44:59 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 299242/6574 0ms 999ms
Dec 27 10:45:00 http.c:368 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/139 0ms 34ms
Dec 27 10:45:00 http.c:368 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://localhost:9200/dstats/dstat/localhost-540-5 783/143 0ms 34ms
Dec 27 10:45:00 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 298777/5978 0ms 1184ms
Dec 27 10:45:00 http.c:368 moloch_http_curlm_check_multi_info(): 1/30 ASYNC 200 http://localhost:9200/_bulk 298993/6209 0ms 914ms
Dec 27 10:45:02 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/140 0ms 54ms
Dec 27 10:45:02 http.c:368 moloch_http_curlm_check_multi_info(): 1/30 ASYNC 200 http://localhost:9200/_bulk 298798/6456 0ms 1154ms
Dec 27 10:45:02 packet.c:1077 moloch_packet_log(): packets: 76900000 current sessions: 115129/115694 oldest: 0 - recv: 2308466330 drop: 0 (0.00) queue: 0 disk: 0 packet: 0 close: 0 ns: 0 frags: 0/4 pstats: 76901762/0/0/379409/2231184939
Dec 27 10:45:04 http.c:368 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/140 0ms 52ms
Dec 27 10:45:04 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 298722/6622 0ms 1153ms
Dec 27 10:45:05 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 298785/6657 0ms 1047ms
Dec 27 10:45:05 http.c:368 moloch_http_curlm_check_multi_info(): 1/30 ASYNC 200 http://localhost:9200/dstats/dstat/localhost-541-5 782/143 0ms 6ms
Dec 27 10:45:06 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 781/139 0ms 53ms
Dec 27 10:45:07 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/_bulk 298877/6917 0ms 1054ms
Dec 27 10:45:08 http.c:368 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://localhost:9200/stats/stat/localhost 782/140 0ms 9ms
Dec 27 10:45:08 http.c:368 moloch_http_curlm_check_multi_info(): 1/30 ASYNC 200 http://localhost:9200/_bulk 299202/6843 0ms 1106ms

**Comment by awick** [comment]
Are you using the high performance settings? https://molo.ch/settings#high-performance-settings

**Comment by luojichen** [comment]
> Are you using the high performance settings? https://molo.ch/settings#high-performance-settings

After  I   uncomment the high performance config  in  confi.ini,   it wokrs !

Thank you very much !
