### ISSUE TITLE
Configuration Basic Authen Elasticsearch for Moloch

### ISSUE THREAD

**Issue by pakjack79** [aol/moloch#1348]
**Elasticsearch version**: 7.0

**Moloch version**: 2.1

**OS name and version**: Ubuntu 18.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) deb

**Provide logs, stack traces and steps to reproduce**:  
Couldn't GET http://xxxx:9200/_cluster_health the http status is 401 are you sure elasticsearch is running/reachable

I have configured Elasticsearch with Basic Authentication. 
How can I configure the Moloch to pass this?

**Comment by awick** [comment]
Github is for bugs and feature requests.  Please see the elasticsearch setting in the settings doc https://molo.ch/
