### ISSUE TITLE
moloch_update_geo.sh no longer works.

### ISSUE THREAD

**Issue by pjsg** [aol/moloch#1350]
**Elasticsearch version**: N/A

**Moloch version**: master

**OS name and version**: ubuntu 16.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) easybutton

**Provide logs, stack traces and steps to reproduce**:

The `moloch_update_geo.sh` no longer works as maxmind now requires an account id.

**Comment by awick** [comment]
yep, still trying to decide what we are going to do.  such a pain.

**Comment by gmctl** [comment]
do you have the accounts of maxmind . i also catch the 401 of this problem with not build the geoip-datebase. and i have made the old geoip2 with it.

**Comment by awick** [comment]
Fixed in master and will be part of 2.2.  You'll have to sign up for an account :(

https://molo.ch/faq#maxmind

**Comment by Trolldemorted** [comment]
Can we tell moloch to operate without any geo data?
