### ISSUE TITLE
Elasticsearch parser error when doing bulk item index(Invalid UTF-8 start byte 0xb8)

### ISSUE THREAD

**Issue by prchiouatchts** [aol/moloch#1351]
**Elasticsearch version**:
6.8.4

**Moloch version**:
1.7.1
**OS name and version**:
Ubuntu 16.04 (4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)
**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
easybutton
**Provide logs, stack traces and steps to reproduce**:

Elasticsearch popped exception when doing certain bulk requst from moloch-capture. According to the exception log posted below, it seems to be related to invalid cert.alt value provided in JSON payload, and caused a parse error: 

(The source ip address was redacted.)

> Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte 0xb8

> 
> [2019-12-30T18:11:29,308][DEBUG][o.e.a.b.TransportShardBulkAction] [WZw7rTv] [sessions2-191230][0] failed to execute bulk item (index) index {[sessions2-191230][session][191230-LBzo1Uz7cT5NwYWjm9xT_7y5], source[{"firstPacket":1577700082202,"lastPacket":1577700082872,"length":669,"srcPort":42282,"dstPort":443,"ipProtocol":6,"communityId": "1:bWo5D4R55UHGFeqt7qaYGN6Yn8U=","tcpflags":{"syn": 0,"syn-ack": 1,"ack": 1,"psh": 1,"fin": 1,"rst": 0,"urg": 0,"srcZero": 0,"dstZero": 0},"dstPayload8":"1603031066020000","timestamp":1577700687834,"srcIp":"10.xx.xx.xx","dstIp":"52.114.128.43","dstGEO":"US","dstASN":"AS8075 Microsoft Corporation","dstRIR":"ARIN","totPackets":3,"srcPackets":0,"dstPackets":3,"totBytes":2091,"srcBytes":0,"dstBytes":2091,"totDataBytes":1460,"srcDataBytes":0,"dstDataBytes":1460,"segmentCnt":1,"node":"scxbox","packetPos":[-3045,468061722,468064415,468083928],"packetLen":[0,86,1534,519],"fileId":[3045],"srcMacCnt":1,"srcMac":["9c:30:5b:5a:04:61"],"dstMacCnt":1,"dstMac":["00:09:0f:09:00:12"],"srcOuiCnt":1,"srcOui":["Hon Hai Precision Ind. Co.,Ltd."],"dstOuiCnt":1,"dstOui":["Fortinet Inc."],"vlanCnt": 1,"vlan":[35],"certCnt":1,"cert":[{"hash":"1e:ff:0e:e7:26:40:51:ee:c6:78:f2:cb:49:7a:70:71:00:80:af:56","issuerCN":["microsoft it tls ca 4"],"issuerON":["Microsoft Corporation"],"subjectCN":["*.events.data.microsoft.com"],"serial":"16000abda3288a26acebf1785e0000000abda3","altCnt":5,"alt":["*.events.data.microsoft.com","events.data.microsoft.com","*.pipe.aria.microsoft.com","pipe.skype.com","*.pipe.s\u0017\u0003\u0003\u0001�"],"notBefore":1570744538000,"notAfter":1633902938000,"validDays":731,"remainingDays":650}],"tls": {"versionCnt":1,"version":["TLSv1.2"],"cipherCnt":1,"cipher":["TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"],"ja3sCnt":1,"ja3s":["ae4edc6faf64d08308082ad26be60767"],"dstSessionId":["591f00007cd7db96c8b192a9c1136ab83b095dee763509a3f70307b0391607c7"]},"tagsCnt":1,"tags":["acked-unseen-segment-dst"],"protocolCnt":2,"protocol":["tls","tcp"]}]}
> org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [cert.alt] of type [keyword] in document with id '191230-LBzo1Uz7cT5NwYWjm9xT_7y5'
> 	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:303) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:488) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:616) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseNonDynamicArray(DocumentParser.java:601) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseArray(DocumentParser.java:547) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:397) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:384) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:485) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:505) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseNonDynamicArray(DocumentParser.java:590) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseArray(DocumentParser.java:547) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:397) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:384) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:96) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:69) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:281) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:801) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:777) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:746) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.lambda$executeIndexRequestOnPrimary$3(TransportShardBulkAction.java:458) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeOnPrimaryWhileHandlingMappingUpdates(TransportShardBulkAction.java:481) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:456) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:220) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:164) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:156) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:143) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:82) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1059) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1037) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:104) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:433) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:374) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$14(IndexShard.java:2588) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:273) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:240) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2563) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:996) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:370) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:325) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:312) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:692) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.4.jar:6.8.4]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
> Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte 0xb8
>  at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@4fc1c634; line: 1, column: 1345]
> 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.11.jar:2.8.11]
> 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.11.jar:2.8.11]
> 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidInitial(UTF8StreamJsonParser.java:3544) ~[jackson-core-2.8.11.jar:2.8.11]
> 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidChar(UTF8StreamJsonParser.java:3538) ~[jackson-core-2.8.11.jar:2.8.11]
> 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2543) ~[jackson-core-2.8.11.jar:2.8.11]
> 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2469) ~[jackson-core-2.8.11.jar:2.8.11]
> 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:315) ~[jackson-core-2.8.11.jar:2.8.11]
> 	at org.elasticsearch.common.xcontent.json.JsonXContentParser.text(JsonXContentParser.java:83) ~[elasticsearch-x-content-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.textOrNull(AbstractXContentParser.java:279) ~[elasticsearch-x-content-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.KeywordFieldMapper.parseCreateField(KeywordFieldMapper.java:362) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:297) ~[elasticsearch-6.8.4.jar:6.8.4]
> 	... 49 more

**Comment by awick** [comment]
Please upgrade to 2.1.x or later and reopen if you are still having issues.
