### ISSUE TITLE
I have a thought about `suricata.so`

### ISSUE THREAD

**Issue by xx-zhang** [aol/moloch#1353]
**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

- CONTENT 
`suricata.so`  can parse the eve.json to pcap and then make all the data to es and show?. 
also the way that it must conbine the ether and only getting the alerts from eve.log?.

**Comment by awick** [comment]
Github is only for bugs and feature requests, please use slack for questions.
