### ISSUE TITLE
Couldn't connect ip:920(0

### ISSUE THREAD

**Issue by jsikarin** [aol/moloch#1354]
**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
For support questions use Slack (sign up at http://slackinvite.molo.ch/) instead of opening an issue.  Github is for bug reports and feature requests.
