### ISSUE TITLE
moloch_http_curl_close_callback(): Couldn't connect ip:9200

### ISSUE THREAD

**Issue by jsikarin** [aol/moloch#1355]
I use moloch on dozens of ids servers. Recently I noticed an error like the one in the title. What is happening is that moloch is failing at sending pcap meta data to an elasticsearch cluster.

Now I am wondering if I get the error in the title "Couldn't connect to ip:9200" will moloch simply retry to send the pcap meta data to elasticsearch or it will drop the metadata and not send it to elasticsearch? 

Also, why does the slack Invite Link Not work?

**Comment by awick** [comment]
Please try the slack invite link again.  If it can't connect to ES it will queue the meta data for a while, but will then start dropping it.  You should check why the ES server isn't working the Moloch FAQ might help you too.
