### ISSUE TITLE
-R not working to upload pcap directory

### ISSUE THREAD

**Issue by jdbliss1** [aol/moloch#1359]
**Elasticsearch version**:
Elasticsearch 8.3.0

**Moloch version**:
Moloch 2.1.2-1

**OS name and version**:
Ubuntu 18.04.3 LTS

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
Installed by deb file

**Provide logs, stack traces and steps to reproduce**

![image](https://user-images.githubusercontent.com/59978975/72632779-a5197d00-391c-11ea-9b8b-6928a840f305.png)

![image](https://user-images.githubusercontent.com/59978975/72632807-b95d7a00-391c-11ea-9f63-8e9c9be14f0d.png)

**Comment by awick** [comment]
Not sure what the screen shot is showing?  Are you saying there are files in that directory when you run the script?

**Comment by jdbliss1** [comment]
Yeah, there are files in the directory. For some reason, they don't get imported into Moloch

However, if I do a "-r" I can input files individually.

**Comment by awick** [comment]
do they have weird extensions? if so you need to set the offlineFilenameRegex. -R works, the CICD process uses it.

**Comment by jdbliss1** [comment]
the files are are .pcap files. Isn't that the correct extension?

**Comment by awick** [comment]
Please post here or DM me on slack the full output of running capture with --debug and the output of ls -l passiveCapture1/

**Comment by jdbliss1** [comment]
Hey man, problem solved. I grabbed pcaps from a assessment and put them ubuntu so I thought the extension would carry over. Once I renamed the file with a ".pcap" it works now
