### ISSUE TITLE
I want to check if a field exists without crashing moloch

### ISSUE THREAD

**Issue by hylcos** [aol/moloch#1362]
Both **moloch_field_by_db** and **moloch_field_by_exp** crash if a field doesn't exist. 

A better solution is to return -1/ any other negative number to indicate that a field hasn't been found instead of calling LOGEXIT.

`int moloch_field_by_db(const char *dbField, bool crashIfNonExistend = True)` would be a possibility as well
https://github.com/aol/moloch/blob/2abf592c9d6df50187c2344c25dff02058593016/capture/field.c#L433

**Comment by awick** [comment]
Neither of them should crash.  When are you having a problem?  I don't want to change the implementation because they find more issues that need to be fixed than problems they cause.  We could add new functions I guess if I understood the issue.

**Comment by hylcos** [comment]
Yeah, it doesn't crash, but is does exists by doing LOGEXIT.

A new function, or an extra parameter on both functions ( so that you can choose if the program exists whenever the field doesn't exist) would be a solution to my problem and some other problems that any other would have in the future

**Comment by awick** [comment]
When are you having a problem?  Can you provide more detail?

**Comment by 31453** [comment]
Reopen with more detail if this is still an issue.
