### ISSUE TITLE
Memory Use

### ISSUE THREAD

**Issue by sabre256** [aol/moloch#1364]
Moloch will startup and begin to grab memory.  It will continue to grab more memory until the service restarts.  Starts out around 1gb will run up until 100gb then restart

We have 128gb ram

**Elasticsearch version**:  6.2.4

**Moloch version**:   1.8.0

**OS name and version**:   RHEL 7.5

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)     RPM

**Provide logs, stack traces and steps to reproduce**:

Cannot provide these, system is located on classified network

**Comment by awick** [comment]
Please ask questions on slack, github is for bugs and feature requests.

* You should upgrade to at least 2.1.0, especially on a classified network, prior versions have security issues
* 2.0.1 has a new setting simpleMaxQ that will stop the disk q from maxing out.  This probably means you have disk performance issues.  Make sure you read the FAQ around disk speed and high performance settings.

**Comment by sabre256** [comment]
I thought what looks like a memory leak would be a bug, where do I go on slack, not familiar with it

**Comment by 31453** [comment]
Request a slack invite [here](https://slackinvite.molo.ch/)! Ask questions on the #moloch channel
