### ISSUE TITLE
viewer email notifier issues

### ISSUE THREAD

**Issue by awick** [aol/moloch#1365]
* Creating a new email notifier doesn't refresh the page, have to manually refresh.  Might only happen if no notifiers had ever exists.  (fresh db/user)

* Trying to update a setting says the notifier already exists

* looks like you can add a .then statement to the notifme send call and we could check for the status error/success and either and log it plus also return the right output to the UI.  Currently it always says success.

**Comment by 31453** [comment]
second bullet point fixed in 67ba35a
