### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [aol/moloch#1380]
Would you like to replace [more defines for constant values](https://github.com/aol/moloch/blob/664ffe25810380f12823941c210efad4e9881124/capture/moloch.h#L158 "MOLOCH_FIELD_TYPE_…") by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages "Description for the usage of enumerations") to stress their relationships?

**Comment by awick** [comment]
Feel free to submit to PRs, making sure the values stay the same.
