### ISSUE TITLE
Moloc libssl error

### ISSUE THREAD

**Issue by vizmur** [aol/moloch#1389]
I am getting error (listed at bottom) while starting packet capture using Moloc. Please advise?

elasticsearch/stable,now 6.8.7 all [installed]
moloch/now 2.2.2-1 amd64 [installed,local]

root@SELKS:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (stretch)
Release:	9.12
Codename:	stretch

root@SELKS:~# uname -a
Linux SELKS 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

**Error Message**
root@SELKS:~# /data/moloch/bin/moloch-capture
**/data/moloch/bin/moloch-capture: /usr/local/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /data/moloch/bin/moloch-capture)**

root@SELKS:~# ls -l /usr/local/lib/
total 3496
-rw-r--r-- 1 root staff 741934 Mar  7 03:51 libssl.a
-rwxr-xr-x 1 root staff 442984 Mar  7 03:51 libssl.so
-rw-r--r-- 1 root staff 431232 Mar  7 03:51 libssl.so.1.0.2
-rw-r--r-- 1 root staff 442984 Mar  7 03:51 libssl.so.1.1
-rw-r--r-- 1 root staff 442984 Mar  7 03:51 libssl.so.1.1.1
-rwxr-xr-x 1 root staff 691392 Mar  7 03:44 libssl.so.3
-rw-r--r-- 1 root staff 357024 Mar  7 03:51 libssl3.so
drwxrwsr-x 4 root staff   4096 Mar  6 17:45 python2.7
drwxrwsr-x 3 root staff   4096 Mar  7 01:54 python3.5

**Comment by awick** [comment]
If you are using the prebuilt binaries you most likely didn't download the correct one for your OS.
