### ISSUE TITLE
feature request - toggle between force-directed and circular for connections view

### ISSUE THREAD

**Issue by mmguero** [aol/moloch#1396]
Check out this demo: [Force Directed Graph Toggle to Circle](https://bl.ocks.org/bricof/5502b02332570c820e4a41db0b165089)

As we're already using D3 for the graph, I would imagine this would be pretty easy to adapt to the connections view. It is a pretty neat effect and would provide another way to visually represent the relationships between nodes.

**Comment by 31453** [comment]
I like it! What do you think @awick?

**Comment by 31453** [comment]
After thinking on this a bit more, I don't think it makes much sense to visualize our data in this way. Most connections graphs are going to be disjoint graphs This means that there are many clusters of connections where not all nodes end up connecting to each other. In the Force Directed Graph Toggle to Circle example, there is one cluster of connections where all the nodes end up connection to one another.

To make this work, we would have to calculate a center for every cluster of connections and draw each cluster in its own circle. While this is all doable, I'm not sure it provides enough benefit for the amount of work it would require.

What do you think @awick and @mmguero?

**Comment by mmguero** [comment]
Ooh, good call. I think you're right. It's not exactly the same type of graph. I think trying to draw multiple different circles would be more confusing than helpful. Yeah this probably isn't a good fit after all. Thanks for looking at it, anyway!

**Comment by 31453** [comment]
Yeah, I think it's a great idea if all the nodes connected! Keep the visualization ideas coming. We've added a few new ones but I have a limited understanding of what helps analysts do their jobs, so they might be too superficial and not useful enough.
