### ISSUE TITLE
Error when do db.bl init

### ISSUE THREAD

**Issue by pakjack79** [aol/moloch#1398]
**Elasticsearch version**: 7.1

**Moloch version**: 2.1.2

**OS name and version**: Ubuntu 18.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) deb

**Provide logs, stack traces and steps to reproduce**:

When i do init db i got this error: 
"type": "illegal_argument_exception",
        "reason": "Can't merge because of conflicts: [Cannot update enabled setting for [_source]]"
![image](https://user-images.githubusercontent.com/41767637/77046858-4e045700-69f6-11ea-9037-3f826329fb9f.png)

**Comment by awick** [comment]
This turn out to be other templates creating _doc ES type, so moloch couldn't create its ES types.
