### ISSUE TITLE
the problems of multiple moloch nodes  centralized display on multiviewer  

### ISSUE THREAD

**Issue by 2333** [aol/moloch#1402]
**Elasticsearch version**: 6.8.2 

**Moloch version**: 2.2.2 

**OS name and version**: centos7 

**How was Moloch built/installed:rpm 

**Provide logs, stack traces and steps to reproduce**:  
[multi-viewer] 
elasticsearch=IP of MultiES/MultiViewer:8200 
viewPort = 8009 
viewHost = IP of MultiES/MultiViewer 
multiES = true 
multiESPort = 8200 
multiESHost = IP of MultiES/MultiViewer 
multiESNodes = IP of ES1:9200;IP of ES2:9200 

-----------------------------------------------------------
Topology
![image](https://user-images.githubusercontent.com/6228675/77515084-e6954e00-6eb2-11ea-8e8e-a15d54911ea8.png)
 

Mirror the traffic of the development zone to moloch 1，and store the SPI data in ES1
Mirror the traffic of the production zone to moloch 2，and store the SPI data in ES2

Deploy the multiES/multiViewer for centralized display
Question1：On the multiViewer, I see that the moloch node of all sessions shows localhost, How should I set up to make Moloch node distinguish the traffic from development zone or production zone?
 
![image](https://user-images.githubusercontent.com/6228675/77515109-f0b74c80-6eb2-11ea-8aad-b5b44f0494ce.png)

Qestion2：In session detail, when you click download pcap，”Error talking to node 'localhost' using host 'localhost.localdomain:8005' check viewer logs on 'Moloch'” will be displayed. How to solve it?

multiViewer log:
ERROR - Couldn't proxy request= Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'localhost.localdomain:8005',
  port: '8005',
  hostname: 'localhost.localdomain',

If anybody need more information, plz let me know
many thans.

**Comment by awick** [comment]
We use github for bugs and feature requests, please ask questions on slack.  You may want to look at the capture --host option
