### ISSUE TITLE
Use any integer field in series visualization

### ISSUE THREAD

**Issue by 31453** [aol/moloch#1407]
In the timeline graph that is on the Sessions, SPI View, and SPI Graph pages, allow for any integer field to be used as the data set. Currently, we only support four fields: session, packet, byte, and databyte. 

One way to accomplish this is to turn the four buttons into a field typeahead that displays only integer fields.

**Comment by BryceV** [comment]
After review, we decided to allow the user to pick n items from a typeahead in their settings. This typeahead will show the integer types available in the sessions. The selected items will become visible over the timeline as data type buttons.
