### ISSUE TITLE
What does the incomplete-tcp tag mean?

### ISSUE THREAD

**Issue by zsn9170** [aol/moloch#1413]
Elasticsearch version: 5.6.0

Moloch version: 1.8.0-1

OS name and version: Debian 9.9

How was Moloch built/installed: deb

Dear Support,

This is not a bug, just a question.

What does the incomplete-tcp tag mean?
Why do you get this tag in a session?

source code:
moloch/capture/parsers/tcp.c
```
 if (DLL_COUNT(td_, tcpData) > maxTcpOutOfOrderPackets) {
        tcp_session_free(session);
        moloch_session_add_tag(session, "incomplete-tcp");
        session->stopTCP = 1;
```

Regards,
Zsolt Nagy

**Comment by awick** [comment]
Please ask future questions on slack, we use github for feature requests and bugs.

It means moloch stopped saving the packets for this session.

**Comment by zsn9170** [comment]
Sorry.
Thanks!

**Comment by awick** [comment]
actually means moloch stop trying to reassemble the tcp session, it still save the packets
