### ISSUE TITLE
Unable to deselect Pie chart in SPIGraph 

### ISSUE THREAD

**Issue by BryceV** [aol/moloch#1418]
Steps to reproduce: 

- Select "pie" from Graph Type
- Click the chart (notice you cannot deselect it)
- Select "timeline" from Graph Type (errors are now produced when you move the mouse)

Works for https://demo.molo.ch/spigraph?size=5&sort=graph&spiGraphType=pie&date=-1 so issue was introduced between versions

**Comment by BryceV** [comment]
Also effects the Connections.vue graph

**Comment by 31453** [comment]
fixed in a47850d
