### ISSUE TITLE
stats page gap between header/subheader

### ISSUE THREAD

**Issue by awick** [aol/moloch#1429]
On master branch, not sure if this has always been there or because of new collapse feature, there is a gap between the sub header and header. As you scroll you see what is underneath show up.  Possible to fix?

![image](https://user-images.githubusercontent.com/427321/80290498-521d4600-8713-11ea-9a21-9fc3eb1e1138.png)

**Comment by BryceV** [comment]
I found the commit here: 00e81c63c40247fa4c61e4c40ebe25fc1ef5af45. margin-top css was reduced but works better if its just removed from the .stats-tabs class

**Comment by BryceV** [comment]
Removed the margin
