### ISSUE TITLE
Prevent lastpass extension from throwing errors

### ISSUE THREAD

**Issue by BryceV** [aol/moloch#1444]
Lastpass adds hooks onto webforms. "Enter" keydown events can throw errors unless 'v-on:keydown.enter="$event.stopPropagation()"' is added. 

<img width="496" alt="Screen Shot 2020-05-08 at 12 17 53 PM" src="https://user-images.githubusercontent.com/9063864/81447522-a243d180-9131-11ea-860a-b8ee167bbfbe.png">

https://forums.lastpass.com/viewtopic.php?f=12&t=337065

**Comment by 31453** [comment]
@BryceV Which pages do you see this error? I used to see it too, but I can't reproduce it now.

**Comment by 31453** [comment]
The LastPass extension is no longer throwing errors in the console (as of version 4.55.0 for Chrome). However, it is still inserting an image onto some unnecessary fields.
