### ISSUE TITLE
about suricata

### ISSUE THREAD

**Issue by liwilling** [aol/moloch#1455]
moloch version 2.1.0 ,
suricata version 4.1.5,
both run well, and /var/log/suricata/eve.json is created , with read permission .
and in moloch config :  plugin is config, suricata fields already exist
plugins=suricata.so
suricataAlertFile=/var/log/suricata/eve.json
suricataExpireMinutes=60
dropUser=nobody
---------------------------------------------
eve.json already exists alert  event_type":"alert" , but in moloch sessions ,query like below
POST  http://192.168.0.18:9200/sessions2-*/_search 
{
  "query": {
    "exists": {
      "field": "suricata.*"
    }
  }
}
 there is no suricata data.

I don't know why there is no data , I checked all the config  , but don't know the problem.
somebody can help me  !! thank you very much

**Comment by awick** [comment]
We use github for feature requests and bugs, please use slack for questions.  I would try running capture with --debug and make sure no errors.

**Comment by liwilling** [comment]
> We use github for feature requests and bugs, please use slack for questions. I would try running capture with --debug and make sure no errors.

thanks very much , I didn't know --debug parameter before, I tried it shows suricataAlertFile no premission. I just chomd 777 
-R /var/log/suricata,  and query in moloch sessions , it success.
