### ISSUE TITLE
 easybutton-build.sh download x64 version nodejs packet in aarch64 system

### ISSUE THREAD

**Issue by MacrossZero** [aol/moloch#1458]
when i run   ./easybutton-build.sh --install in a aarch64 system, it download a x64 version nodejs packet node-v10.20.1-linux-x64.tar.xz. 
it should be node-v10.20.1-linux-arm64.tar.xz

i have installed  the arm64 version nodejs myself, and finished the installation  .

**Elasticsearch version**:

**Moloch version**:
2.3.0
**OS name and version**:

Linux kylin-os 4.4.58-20171215.kylin.server.YUN+-generic #kylin SMP Fri Dec 22 16:41:06 CST 2017 aarch64 aarch64 aarch64 GNU/Linux
 you can treat it as ubuntu 16.04  aarch64

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
source easybutton
**Provide logs, stack traces and steps to reproduce**:

**Comment by fj604** [comment]
I have a fix in #1456 that enables building on arm64 and fixes this issue as well, but it downloads ES 7.7.0 which has critical bugs so it is postponed for now.

**Comment by fj604** [comment]
#1456 is now updated to ES 7.7.1.

**Comment by awick** [comment]
this was merged
