### ISSUE TITLE
Use Moloch to filter TOR traffic

### ISSUE THREAD

**Issue by moowsje** [aol/moloch#1478]
I'm looking for a solution, using Moloch (capture or viewer) to be able to filter TOR traffic. The TOR status should be based on a check somewhere in the process where the IP is checked for it's TOR status in an (online) database.
I hope someone can help me find the solution!

**Comment by awick** [comment]
Hi, we use github for feature requests and bug reports. Please come to slack for questions. If you have a list of ips you could use either shortcuts if you want to filter in viewer or moloch rules if you want to not capture it.
