### ISSUE TITLE
Moloch doesn't generate filters for ipv6 ip urls correctly

### ISSUE THREAD

**Issue by Trolldemorted** [aol/moloch#1481]
**Elasticsearch version**:
7.6.0

**Moloch version**:
v2.3.0

**OS name and version**:
Mobylinux

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
deb

**Provide logs, stack traces and steps to reproduce**:
- Add an "and" filter for an url with an ipv6 address
- Notice that the input field doesn't like the brackets

![ipv6 moloch](https://user-images.githubusercontent.com/10261186/87294033-7236f700-c503-11ea-9bea-c542320ea374.PNG)

**Comment by awick** [comment]
Moloch doesn't support [] around ipv6, and we have no plans to. Instead moloch just swaps the : and . from ip4. So use fd66:66:682::2.12345 instead

**Comment by awick** [comment]
or if that is the actual url string then put quotes around it

**Comment by Trolldemorted** [comment]
Can you make the frontend use that encoding when you click on the "add to filter" button?

**Comment by Trolldemorted** [comment]
Thanks a lot! :tada:
