### ISSUE TITLE
Moloch capture does not work with IPv6 pcap

### ISSUE THREAD

**Issue by JasperJuergensen** [aol/moloch#1484]
**Elasticsearch version**: 7.7.1

**Moloch version**: 2.3.2-1

**OS name and version**: debian buster

**How was Moloch built/installed:** deb

**Provide logs, stack traces and steps to reproduce**:

When I use an IPv4 capture, it works as expected. Using the IPv6 capture, moloch reads the pcap file, but does not save any data. When I read the pcap file with tcpdump there is defenetly some data. 

Here is the log file: [moloch.log](https://github.com/aol/moloch/files/4915109/moloch.log)

**Comment by awick** [comment]
Without the pcap I'm guess its a dup of #1479 
You can try the last commit build
