### ISSUE TITLE
I want to find out long sessions. Is there a way to add a "duration" field?

### ISSUE THREAD

**Issue by Master-13** [aol/moloch#1503]
Since "Start time" and "End time" is available, is there a way to calculate and filter by the DELTA ?

Like, em, how to find out sessions longer than 3 minutes. ... Or something similar.

**Comment by awick** [comment]
We use github for feature requests and bug reports, please use slack for future questions. You can click on the Owl to get help and there is a list of fields for your cluster. You probably want session.length

**Comment by Master-13** [comment]
@awick OHHHHHHH, yes. session.length is what I exactly want. tks so much
