### ISSUE TITLE
When run "easybutton-build.sh" on Ubuntu 18.04, need to consider of meson version.

### ISSUE THREAD

**Issue by winnerineast** [aol/moloch#1511]
I hit the issue when I install moloch from the source in ubuntu 18.04. And the error is as below
"meson.build:837:36: ERROR: Expecting eol got id.
elif not cc_can_run and host_system in ['ios', 'darwin']"

I checked that the meson version is 0.45.1 with ubuntu 18.04. Which is outdated. So I solve this problem by doing the following steps.
sudo apt purge meson -y
sudo -H pip3 install meson
sudo ln -s /usr/local/bin/meson /usr/bin/meson
which meson && meson --version

if the version is 0.55.1, the problem will disappear. I don't know how to write a proper shell script to automate these in easybutton-build.sh. But I would like to leave this message if anyone could help enhance it accordingly.

**Comment by awick** [comment]
In general we prefer not to upgrade versions of things people have installed, and only install if not installed already.  A simple fix is you could have just removed it or done an upgrade and easybutton would have reinstalled or been happy.
