### ISSUE TITLE
[Feature Request] Save and edit common search queries

### ISSUE THREAD

**Issue by Juwon1405** [aol/moloch#1521]
Hello. I would like to ask for suggestions for additional features for development.

On the Sessions tab,

Please develop a function that can addon to frequently used search queries.

**Comment by 31453** [comment]
@Juwon1405 Can you use "views" to achieve your desired behavior? A view is a way to save Moloch search queries for future use. To learn more about views, click the owl on the top left of the Moloch UI, then click "Sessions" on the left nav, then scroll down to the "Views" section.

If that doesn't do what you are describing, can you explain a little bit more what you want to do?

**Comment by 31453** [comment]
More context: the request is to populate the search input with a common search expression, then edit its values.

Maybe this can be accomplished by adding a button to a view that populates the search input with it's search expression value.
