### ISSUE TITLE
easybutton-build.sh always recompiling nghttp2

### ISSUE THREAD

**Issue by HigorGabrielDCF** [aol/moloch#1523]
In line 250 have code: 

`  if [ ! -f "nghttp2-$NGHTTP2/lib/.libs/libcurl.a" ]; then`

but the correct compare is

`  if [ ! -f "nghttp2-$NGHTTP2/lib/.libs/libnghttp2.a" ]; then`

With this change, nghttp2 will not be recompiled every time.

**Comment by awick** [comment]
thanks!
