### ISSUE TITLE
change of Document Type from "session" to "_doc"

### ISSUE THREAD

**Issue by ristandi95** [aol/moloch#1537]
```
if (defined $version &&
        exists $version->{"${PREFIX}sessions2_template"} &&
        exists $version->{"${PREFIX}sessions2_template"}->{mappings}->{session} &&
        exists $version->{"${PREFIX}sessions2_template"}->{mappings}->{session}->{_meta} &&
        exists $version->{"${PREFIX}sessions2_template"}->{mappings}->{session}->{_meta}->{molochDbVersion}
    ) {
        $main::versionNumber = $version->{"${PREFIX}sessions2_template"}->{mappings}->{session}->{_meta}->{molochDbVersion};
        return;
    }
```

Hi, since elasticsearch 7.x and above are no longer requires a document type and "_doc" is now a permanent part of the path as described in the [elasticsearch removal of types](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html) documentation. I think moloch mapping should be changed too as well as other code that validate/read the existance of "session" path into "_doc". Currently I'm using moloch version 2.3.1, but when I checked the newest version 2.4.1, the mapping still use "session" as document type, so I don't think upgrading to version 2.4.1 is a solution that I'm looking for.

Thank you

**Comment by awick** [comment]
Moloch 2.4.x still supports ES 6, when we remove ES 6 support we will remove types fully.  If there is a problem you are hitting please open a new issue with details of the error.
