### ISSUE TITLE
SMTP Zip File Attachment Tagging

### ISSUE THREAD

**Issue by eoinmiller** [aol/moloch#177]
Please add the following functionality to Moloch for compressed files sent over SMTP.
- File name extraction of the names of the files within the zip file
- File type fingerprinting of files within of files within the zip file
- MD5 sum of files within the zip file
- Detection and tagging of encrypted zip files

**Comment by 31453** [comment]
Closing because of age and lack of activity. Reopen if there are more users who want this functionality.
