### ISSUE TITLE
SMTP Reply Codes

### ISSUE THREAD

**Issue by eoinmiller** [aol/moloch#180]
Please index the SMTP reply codes. This will help perform searches for say email.fn == *.zip and easily determine which ones were not rejected with 554 codes.

Some examples:

http://www.greenend.org.uk/rjk/tech/smtpreplies.html

**Comment by 31453** [comment]
A user can search for status codes, then tag a session with the reason for the status code. Please reopen with more information if this is a bad workflow and does not meet the requirements of the initial request.
