### ISSUE TITLE
Bi-Directional Traffic Tagging

### ISSUE THREAD

**Issue by schwo** [aol/moloch#195]
Sessions are not assembled, associated, and appropriately tagged across different capture processes on the same monitoring node.  In the case of bi-directional traffic (outbound traffic on eth1 and inbound responses on eth2) a single session is displayed as two different disassociated sessions.  

Bonding the interfaces is not possible when using pf_ring.

I currently have a capture node running two capture processes monitoring two interfaces.  
config.ini snippet:
[node4_eth1]
interface=eth1
[node4_eth2]
interface=eth2

**Comment by awick** [comment]
single process can listen to multiple interfaces now
