### ISSUE TITLE
Sessions view - first row obscured by column headers using MS Edge

### ISSUE THREAD

**Issue by gt2847c** [aol/moloch#2201]
Arkime v4.1.0

Using Microsoft Edge - In the sessions view the first row is partially covered by the headers.  Appears to be specific to MS Edge as Chrome displays properly.

Microsoft Edge :
Version 110.0.1587.57 (Official build) (64-bit)

Screen capture was fully scrolled to the top.
![Arkime-MS Edge First Row Obscured ](https://user-images.githubusercontent.com/8898797/221877016-a99322c9-543b-4c64-a568-1ec6151720c6.png)

Chrome displays properly
![Arkime-Chrome](https://user-images.githubusercontent.com/8898797/221877439-8440ec2c-56a9-4f45-8ed4-afbd641bb599.png)

**Comment by Didr** [comment]
I was able to reproduce this on both Firefox and Edge by using the "Pin graph, map and column headers" feature. Toggling it fixes temporarily.
In my case, 1,5 sessions were hiding under the column bar.
