### ISSUE TITLE
Additional Header Fields

### ISSUE THREAD

**Issue by JeffSoh** [aol/moloch#226]
Add additional index fields for protocol header fields:

IP version, IP header length, IP ID, IP flags, TTL, Embedded Protocol

TCP Header Length, TCP Flags, Checksum, Urgent Pointer

UDP: Length, Checksum

ICMP: Message Type, Message Code, Checksum

**Comment by paulpc** [comment]
to throw my hat in the ring, icmp codes would be pretty useful to have (echo vs ttl exceeded vs echo reply)
