### ISSUE TITLE
when the port reuse,src and dst may be exchanged

### ISSUE THREAD

**Issue by peasfarmer** [aol/moloch#2313]
**Describe the bug**
I saw in arkime that the source port of some http requests is 80, I think there is a mistake here.

I analyzed the pcap packet and found that it was because of port reuse. When the previous session was disconnected, no ack was received from the client. As a result, the previous session did not end. At this time, if a new connection is established, arkime will not put the syc packet As the beginning of the session, instead of fin+ack as the beginning

Currently my tcpTimeout configuration is 600, can it be improved by adjusting it? Or is there any other way to solve this problem

**Arkime/Moloch version**:
v4.2.0-52-g4fd4909f @ 2023/04/12 04:04:28

**OS name and version**:
ubuntu

**Provide logs, stack traces and steps to reproduce**:
![image](https://github.com/arkime/arkime/assets/9895798/58abba64-4433-4e16-974e-069a2e214345)
![image](https://github.com/arkime/arkime/assets/9895798/56e16bd4-0a5a-4494-ac50-8ad8d794862c)

**Comment by awick** [comment]
Please attach or DM on slack a sample pcap
