### ISSUE TITLE
MultiES Crash

### ISSUE THREAD

**Issue by schwo** [aol/moloch#234]
If one of the ES instances configured in MultiES becomes unreachable, multies.js crashes after connection timeout.  Is it possible to display an error message in the UI or fail gracefully?

Request error with node node1.vpn:9200 { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
Tue, 22 Apr 2014 13:31:29 GMT GET /users/user/admin - bytes 600045 ms
Tue, 22 Apr 2014 13:32:38 GMT POST /stats/stat/_search - bytes 600018 ms
POST /stats/stat/_search
Request error with node node1.vpn:9200 { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
Tue, 22 Apr 2014 13:34:38 GMT POST /stats/stat/_search - bytes 600100 ms
POST /stats/stat/_search
Request error with node node1.vpn:9200 { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
Tue, 22 Apr 2014 13:36:38 GMT POST /stats/stat/_search - bytes 600102 ms
POST /stats/stat/_search
Request error with node node1.vpn:9200 { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ETIMEDOUT
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)

**Comment by awick** [comment]
hopefully fixed, open with new trace if not
