### ISSUE TITLE
logging request for dontSaveTags directive

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#239]
I'm looking to validate that the capture process is not dropping sessions we did not intend to throw away.  Can a future capture-process [configurable] log identifiable metrics for sessions that have been dropped?  

i.e.  moloch-capture: ${rootId} dropping packets for ${TAG} total ${X} packets, total ${X} bytes 

I am currently working with a config of:
dontSaveTags=protocol:tls;protocol:ssh

**Comment by 31453** [comment]
Looks like this is implemented with the capture stats page and additional logs when using --debug
