### ISSUE TITLE
Change default Session Tab Search

### ISSUE THREAD

**Issue by wsfloyd** [aol/moloch#246]
When clicking Session tab or launching Moloch, the Session page automatically searches the last hour.  Would like the option to set page to not search anything by default, specially for multies.js.

**Comment by awick** [comment]
"Is there some configuration file where I can setup a view (predefined query) that everyone will be able to have be default?"

**Comment by 31453** [comment]
The Sessions page will not automatically issue a search if the "Issue Query on Page Load" user setting is set to "no"
