### ISSUE TITLE
add by1, by2,  db1, db2, pa1,pa2 to sessions table

### ISSUE THREAD

**Issue by hillar** [aol/moloch#257]
Please add in sessions view into sessions table some more columns, or make it configurable :).

      "friendlyName": "Src Bytes",
      "help": "Total number of raw bytes sent by source in a session",
      "dbField": "by1"
      "friendlyName": "Dst Bytes",
      "help": "Total number of raw bytes sent by destination in a session",
      "dbField": "by2"

      "friendlyName": "Src data bytes",
      "help": "Total number of data bytes sent by source in a session",
      "dbField": "db1"
      "friendlyName": "Dst data bytes",
      "help": "Total number of data bytes sent by destination in a session",
      "dbField": "db2"

      "friendlyName": "Src Packets",
      "help": "Total number of packets sent by source in a session",
      "dbField": "pa1"
      "friendlyName": "Dst Packets",
      "help": "Total number of packets sent by destination in a session",
      "dbField": "pa2"

**Comment by WilliamSalusky** [comment]
Just updated and I love it. However, I've just noticed a peculiarity where if you modify the displayed field set in any way from the default set, the dest port loses right click context. To reproduce, remove any field from the default display set in settings (i.e. remove src port), go to sessions and attempt to right click dst port. NOPE!

Additional enhancement: Any field added to the sessions display should also become right clickable. For example: If destination databytes is added the sessions display, it should be right click context aware to update the query bar with 'databytes.dst==${value}'

@jsarjas @awick
