### ISSUE TITLE
Suricata/Snort Tagging Plugin

### ISSUE THREAD

**Issue by jescar50dx** [aol/moloch#269]
It would be nice to be able to apply signature tags into the session data. Only one I could find is Pigsty but it's not able to keep up with the amount of traffic coming in.

**Comment by paulpc** [comment]
@eoinmiller - any  news with suricata / moloch integration?

**Comment by tamirlancomas** [comment]
how to install suricata on moloch? , (pigsty-moloch-plugin = moloch + suricata  ??)

**Comment by awick** [comment]
I think the new suricata plugin will do what you want
