### ISSUE TITLE
visual indicator in session view graph for capture process restarts

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#271]
A capture process restart loses protocol state awareness and restarts segment counts.  To avoid bad assumptions a visual vertical bar identifying a specific capture process had restarted at that time would be great.

**Comment by awick** [comment]
We are going to save started up time to stats and see if there is anyplace to display that or not

**Comment by 31453** [comment]
@andy is there a started time in capture stats? I don't see it, but I might be missing something. Also, is the capture graph insufficient in determining this?

**Comment by awick** [comment]
i thought i had added it, but looks like i never did :(
If we add a startTime field i was thinking we could just draw a line there, but that would only have the last start Time, do we need more?

**Comment by 31453** [comment]
I'm not sure if we need more. But the minimal case would be to show the last start time. I'm assuming that ideally, we'd want all of the past restarts of the capture process, so a list of start times.

**Comment by awick** [comment]
To add runningTime you would edit db.c moloch_db_update_stats and to the end of the big snprintf.  Then add runningTime field with value currentTime.tv_sec - startTime.tv_sec
