### ISSUE TITLE
WARNING - Only have SPI data, PCAP file no longer available

### ISSUE THREAD

**Issue by ghost** [aol/moloch#274]
server-lp1 has 2 capture processes and 1 viewer
    nodes:server-lp1
    nodes:server-lp1-2

server-lp2 has 1 capture process and 1 viewer
    nodes:server-lp2

each of these servers are going into the same ES cluster.

Getting the following error: WARNING - Only have SPI data, PCAP file no longer available

The pcap file exists on the server:
-rw-r-----. 1 daemon daemon 12884902062 Jul 15 16:53 server-lp2-140715-00223202.pcap

After reviewing the logs I do not think this is due to the viewer process deleting the file document in ES. 

Jul 15 16:51:39 server-lp2 moloch-capture: Jul 15 16:51:38 db.c:1269 moloch_db_create_file(): Creating file 223202 with key >/files/file/server-lp2-223202?refresh=true< using >{"num":223202, "name":"/data/moloch/raw/server-lp2-140715-00223202.pcap", "first":1405443098, "node":"server-lp2", "locked":0}<

Jul 15 16:51:39 server-02 moloch-capture: Jul 15 16:51:38 nids.c:463 moloch_nids_output_thread(): Opening /data/moloch/raw/server-lp2-140715-00223202.pcap

Jul 15 16:51:39 server-lp2 moloch-capture: Jul 15 16:51:38 http.c:340 moloch_http_finish(): Jul 15 16:51:38 26/0/0 0x7fb54748c010 POST ASYNC /files/file/server-lp2-223202?refresh=true 138 0ms 142ms

Jul 15 16:55:57 server-lp2 moloch-viewer: WARNING - Only have SPI data, PCAP file no longer available server-lp2-223202

**Comment by phreakinggeek** [comment]
Did this issue ever crop up again for you? I ran into this issue on a host myself. May just reinstall but figured I'd ask.

**Comment by WilliamSalusky** [comment]
Without specifics of your deployment, one issue comes to mind that bit me
recently. Related to free space management by the capture process. The
config.ini previously contained a large default freeSpace directive of
600G. If you were deployed on a machine that perhaps did not *have* 600G,
the capture process would always remove pcap after the file was
closed/rotated. Recently changed that directive to be a sane percentage
based value vs. a static size.

freeSpaceG = 5%

**Comment by awick** [comment]
Moloch has a min number of files that are required and not deleted, depending on moloch version.  So nothing should be immediate deleted

https://github.com/aol/moloch/wiki/FAQ#pcap-deletion

The reverse is more likely, if a low bandwidth network, it is possible that for recent sessions the SPI data already lives in ES but does not live in the PCAP database because PCAP is written out in chunks controlled by <code>pcapWriteSize </code>

The error message probably should check for that and say something about not in PCAP db YET instead of no longer avail

**Comment by phreakinggeek** [comment]
William,

Thank you so much for that insight, I am investigating it now but I think
you are totally on the right track there.

-Aaron

On Fri, May 29, 2015 at 10:29 AM, William Salusky <notifications@github.com>
wrote:

> Without specifics of your deployment, one issue comes to mind that bit me
> recently. Related to free space management by the capture process. The
> config.ini previously contained a large default freeSpace directive of
> 600G. If you were deployed on a machine that perhaps did not *have* 600G,
> the capture process would always remove pcap after the file was
> closed/rotated. Recently changed that directive to be a sane percentage
> based value vs. a static size.
>
> freeSpaceG = 5%
>
>
> On Thu, May 28, 2015 at 10:43 PM, phreakinggeek <notifications@github.com>
> wrote:
>
> > Did this issue ever crop up again for you? I ran into this issue on a
> host
> > myself. May just reinstall but figured I'd ask.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/aol/moloch/issues/274#issuecomment-106620079>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aol/moloch/issues/274#issuecomment-106846003>.
>



-- 
"Tell me and I forget. Teach me and I remember. Involve me and I learn." -
Ben Franklin
Give a man a fire, he'll have fire for a night. Set a man on fire, he'll
have fire for the rest of his life.
