### ISSUE TITLE
resolve IP's via tooltip in sessions view when clicked

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#28]
When either src or dst IP's are left clicked in the sessions view, a tooltip popup should appear with dns resolution results (maybe other configurable IP related actions down the road).

The NFSen project does this very well.  I will demo the behavior in person.

**Comment by awick** [comment]
use dns.reverse
allow servers to be set in config file if desired

**Comment by awick** [comment]
Also it shouldn't happen automatically, the user should have to do some action since sometimes you don't want to look up ips because that may give away info.
