### ISSUE TITLE
upgrade fails (similar to #237)

### ISSUE THREAD

**Issue by daemondriver** [aol/moloch#291]
Trying to upgrade a moloch box from 10.1 to 11.2 and I'm running into an error very similar to issue #237 Upgrade process fails (v0.9.1 to v0.10.0).  I downloaded the latest moloch-master and followed the upgrade instructions (which I've done before), but when running db.pl, I get this error:

Type "UPGRADE" to continue - do you want to upgrade??
UPGRADE
Starting Upgrade
$VAR1 = bless( {
                 '_protocol' => 'HTTP/1.1',
                 '_content' => '{"error":"IndexAlreadyExistsException[[users_v3] Already exists]","status":400}',
                 '_rc' => '400',
                 '_headers' => bless( {
                                        'client-date' => 'Tue, 02 Sep 2014 18:44:23 GMT',
                                        'content-type' => 'application/json; charset=UTF-8',
                                        'client-response-num' => 1,
                                        'client-peer' => '127.0.0.1:9200',
                                        'content-length' => '79'
                                      }, 'HTTP::Headers' ),
                 '_msg' => 'Bad Request',
                 '_request' => bless( {
                                        '_content' => '
{
  settings: {
    number_of_shards: 1,
    number_of_replicas: 0,
    auto_expand_replicas: "0-2"
  }
}',
                                        '_uri' => bless( do{(my $o = 'http://127.0.0.1:9200/users_v3')}, 'URI::http' ),
                                        '_headers' => bless( {
                                                               'user-agent' => 'libwww-perl/5.833',
                                                               'content-length' => 106
                                                             }, 'HTTP::Headers' ),
                                        '_method' => 'PUT',
                                        '_uri_canonical' => $VAR1->{'_request'}{'_uri'}
                                      }, 'HTTP::Request' )
               }, 'HTTP::Response' );
Couldn't PUT http://127.0.0.1:9200/users_v3  the http status code is 400 are you sure elasticsearch is running/reachable?
{"error":"IndexAlreadyExistsException[[users_v3] Already exists]","status":400} at ../db/db.pl line 126, <STDIN> line 1.

ES is definitely running (I can get to _plugin/head and it shows green), but as per #237 I may be running an older version - it looks like I'm running elasticsearch-0.90.2.  I just built a brand new moloch sensor from scratch today and it's running fine, but I'm not sure how to upgrade ES on this box w/o putting my previous indexes at risk?

Thanks!

**Comment by nnmanobala** [comment]
I would greatly appreciate if I can get help on my moloch install.
db.pl info shows the following 

ES Version:          1.4.4
DB Version:          -1
ES Nodes:            2/2
Session Indices:     0
Sessions:            0 (0 bytes)

Also if I try to run this command "db/db.pl localhost:9200 init". I get the following message,

It is STRONGLY recommended that you stop ALL moloch captures and viewers before proceeding.
There are 2 elastic search data nodes, if you expect more please fix first before proceeding.
This is a fresh Moloch install

ERROR: On node Skinhead machine ROUSSY in file /etc/elasticsearch/elasticsearch.yml
       ADD 'index.fielddata.cache: node'
       ADD 'indices.fielddata.cache.size: 40%'

But I have made the above entries in my elasticsearch.yml file, but it still shows the same error.

What should I do?

**Comment by HillarAarelaid** [comment]
> On 06 Mar 2015, at 19:01, nnmanobala <notifications@github.com> wrote:
> 
> But I have made the above entries in my elasticsearch.yml file, but it still shows the same error.
> 
> What should I do?

Did you restarted elasticsearch nodes ?

Hillar

**Comment by nnmanobala** [comment]
I restarted elasticsearch service, is it the same as restarting the elasticsearch nodes? This is my first attempt working with ELK stack, so I would greatly appreciate it if you could provide brief explanations. Thank you.

**Comment by awick** [comment]
You should try restarting the elasticsearch node on that machine again.  I haven't tried the service script, I usually just use the head plugin to shutdown the node or the kill command

**Comment by nnmanobala** [comment]
Thank you everyone. I have got it working, I failed to shutdown the nodes
leading to the issue. Now it is resolved.
