### ISSUE TITLE
extend query bar support for timestamps and views

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#307]
I would like to be able to specify the begin and end time in the query bar, it would be super winning if it also supported snap-to-time features that Splunk has documented nicely at:

http://docs.splunk.com/Documentation/Splunk/4.2.2/User/ChangeTheTimeRangeOfYourSearch#Specify_relative_time_ranges_in_your_search

The ability to specify a named view via the query bar would be great.

**Comment by WilliamSalusky** [comment]
Bump.  Because this will be awesome.

**Comment by awick** [comment]
* I'm looking more at this because of the cert stuff
* Timestamps are a pain to deal with because of timezones, boo
* Having in the expression will allow multiple timestamps, i assume that is what you want

(startTime > -7d && dns.host == example.com) || (startTime > -1d && dns.host == example2.com)

**Comment by WilliamSalusky** [comment]
What you've mentioned is great, but also being able to specify the start of that given day X number of days ago is pretty important.

where startTime > -7d   ;# will give us an epoch startTime of exactly 604,800 seconds from now();, being able to run a query starting from the relative zero hour of that day is important in this context.  

So we can run a query of startTime>-7d@d   ;# where @d implies the zero hour start of that day seven days ago 00:00:00 [according to local app clock setting]. 

&& endTime<-1d@d ;# one day ago 00:00:00


Support for filters on hour [and minute?] as well.  

(startTime>-5h@h && endTime<-4h@h)
