### ISSUE TITLE
wiseService - administrative view of threat intel

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#315]
For administrative privileged users an admin view into the state of wiseService aggregated intelligence would be a nice to have to avoid querying ES directly.  A page that iterates over every intel type, to display meta [(file|url):type], associated tags, time of last update, number of records in the group, a link to display the raw data contained in ES and maybe a form field to query the intel directly (troubleshooting intel).

url:zeustracker | ${type} | ${tags} | ${last_updated_ts} | ${link_to_view_data_from_ES} | ${Query_field}
url:spyeyetracker | ${type} | ${tags} | ${last_updated_ts} | ${link_to_view_data_from_ES} | ${Query_field}
file:evildoer.txt | ${type} | ${tags} | ${last_updated_ts} | ${link_to_view_data_from_ES} | ${Query_field}
.
.
.

**Comment by WilliamSalusky** [comment]
Just realized this is related to #359

**Comment by awick** [comment]
Added to #548
