### ISSUE TITLE
802.11 packet captures

### ISSUE THREAD

**Issue by futurealecks** [aol/moloch#320]
I recently attempted to import 802.11 packet capture sample files from Wireshark's website to see how Moloch would read the file.  The first file imported was a small packet capture of a wireless device associating with an AP.  It seemed to run through the entire import script but said it imported 0 files.  I'm not sure the 802.11 header throws off the moloch-capture script?  Would it be feasible to support 802.11 captures in Moloch?  It would be great to search for AP's (SSID, BSSID), and view beacons+probes.

Thanks

**Comment by awick** [comment]
added some support in 1.0.1
