### ISSUE TITLE
Index TLS Session ID's

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#326]
http://en.wikipedia.org/wiki/Transport_Layer_Security#Session_IDs

**Comment by awick** [comment]
What is the goal?  Do you want to find sessions where a client resumed a session by using the session id?  If so then we could only include the clienthello session ids.  (Which I don't think happens that often, but could be wrong.)  Or do you truely want all serverhell session ids even though they mostly aren't used?

**Comment by WilliamSalusky** [comment]
Yes, To identify sessions that reuse the session id. This becomes especially interesting on TLS through proxies.
