### ISSUE TITLE
Adding a nickname field

### ISSUE THREAD

**Issue by futurealecks** [aol/moloch#328]
I'm interested in adding nicknames to nodes for easier searching and filtering.  For example, if I come across an IP address (or MAC) of the Microsoft Exchange server I would like to view/search/filter on that specific nickname.  I think this could be done w/ tags and using the action menu to set tags for specific sessions.  The only thing I cannot figure out is how to add a tag to multiple sessions after filtering for a specific IP or MAC.  

Thanks

**Comment by TNogisto** [comment]
you can simply do a tagger file. (you can also create a "nickname" field with tagger and then search like nickname== badbadip) 

More info:
https://github.com/aol/moloch/wiki/TaggerFormat

**Comment by awick** [comment]
Definitely can do this with either the tagger or wise plugin.  I recommend wise since that is the way of the future.  https://github.com/aol/moloch/wiki/WISE

You can also just do it from the UI interface by using the actions menu next to the Search button
