### ISSUE TITLE
setting up tag in moloch

### ISSUE THREAD

**Issue by caspertz** [aol/moloch#331]
we are running moloch version 0.11.2 and we have set up a tag that shows up in the viewer.  We have tried specifying the dontSaveTags=<tag name> with and without a :#.  We are trying to limit the number of "packets" for this one tag as it is very large.  It doesnt seem to have made a change in the number of packets.  Is something not set correctly?

**Comment by awick** [comment]
What is the tag? 
How is it being set?  
How are you checking the number of packets? (the packet count will still go up, just not saved to disk.)

**Comment by caspertz** [comment]
dontSaveTags=milfsprx
we tried it also with a :<number> like :12 and it didnt really make a difference.

**Comment by caspertz** [comment]
As for the # of packets, were checking what was in the main viewer page.  Also noticed that the amount of data for our pcap files has not gone down.  This one destination port that we are trying to limit is rather large and was hoping to increase the number of days of pcap data we are saving.  We used to be able to save 30 days and now down to less than 13 days.

**Comment by awick** [comment]
Sorry wasn't clear, how are you setting the tag on the session?  With a plugin?

**Comment by caspertz** [comment]
plugins=tagger.so; netflow.so
we have this in the config.ini and the tag was added command line to Elasticsearch.  Do we have to do something else as well?  I can do a search on tags = milfsprx in moloch and it shows the events, so that part seems to be working

**Comment by awick** [comment]
If you are setting the tag with tagger it unfortunately doesn't happen until the session is saved.  So the feature you are looking for is a way to limit the number of packets by port?

**Comment by caspertz** [comment]
yes - we have a destination port we want to limit the number of packets with, without using the bpf to filter those out completely.   We have 8 moloch's running on each system and 3 of those are receiving events with that destination port but only 1 of the 3 is the largest in size.

**Comment by caspertz** [comment]
is this something that is available now or is our only option to bpf it out?

**Comment by awick** [comment]
You can now use dontSaveBPFs added in ad2acfd0387522248da948b8f6bcdb85a70c2ec9
