### ISSUE TITLE
Capture crashing with segfault error 7 in libc

### ISSUE THREAD

**Issue by Afturmath** [aol/moloch#332]
I am seeing the following Moloch crash roughly every 20-30 minutes.

    Feb  3 11:26:24 <snip> kernel: [438107.370150] moloch-capture[7775]: segfault at ffffffffffffffff ip 00007f24be182b89 sp 00007fffe9a37198 error 7 in libc-2.19.so[7f24be0ea000+1bb000]
    Feb  3 11:26:28 <snip> kernel: [438110.937245] device em2 left promiscuous mode
    Feb  3 11:26:28 <snip> kernel: [438110.980042] init: moloch-capture main process (7775) killed by SEGV signal

I have audited and tuned the Moloch config per the multiple host FAQ and original installation docs.

We are feeding Moloch ~800mbps. The system configuration is as follows.

Hardware:
* 64GB ECC DDR3
* dual Xeon E5-2640
* onboard BCM5720-based Gigabit NIC for capture
* 10x 1.2TB, 7200RPM disks in RAIDZ-2 (See below)

OS Configuration:
* Ubuntu server 14.04.1 LTS
* OS on bare metal
* Local ZFS array with 10x 1.2TB, 7200 RPM disks (remounted to localhost via NFS because Moloch crashes when writing to ZFS directly) mounted at /moloch/pcap
* 10x 1.2TB, 7200RPM ZFS array on another host mounted via NFS to /moloch/pcap2 (typically causes a disk queue because it's too slow)
* /etc/security/limits.conf set to unlimited memlock, 128000 nofile
* kernel.shmmax = 34359738368
* net.core.rmem_default = 16777216 
* net.core.wmem_default = 16777216 
* No swap

Elasticsearch:
* 2 hosts, 4 nodes
* 32GB RAM per VM
* No swap
* vm.max_map_count=262144
* /etc/security/limits.conf set to unlimited memlock, 128000 nofile

Moloch was built with ```./easybutton-build.sh``` and the libnids, libpcap, yara, and glib configured and compiled manually per the installation guide.

/data/moloch/etc/config.ini:
```
[default]
elasticsearch=<snip>
passwordSecret = <snip>
interface=em2
freeSpaceG = 200
userNameHeader=remote_user
webBasePath = /
viewPort = 8005
viewHost = <snip>
rotateIndex=daily
certFile=/data/moloch/etc/moloch.crt
keyFile=/data/moloch/etc/moloch.key
httpRealm = Moloch
pcapDir = /moloch/pcap;/moloch/pcap2
maxFileSizeG = 10
tcpTimeout = 600
tcpSaveTimeout = 720
udpTimeout = 30
icmpTimeout = 10
maxStreams = 1000000
maxPackets = 10000
geoipFile = /data/moloch/etc/GeoIP.dat
geoipASNFile = /data/moloch/etc/GeoIPASNum.dat
rirFile = /data/moloch/etc/ipv4-address-space.csv
dropUser=moloch
dropGroup=moloch
parseSMTP=true
parseSMB=true
parseQSValue=false
smtpIpHeaders=X-Originating-IP:;X-Barracuda-Apparent-Source-IP:
parsersDir=/data/moloch/capture/parsers
pluginsDir=/data/moloch/capture/plugins
spiDataMaxIndices=5
pcapWriteMethod=thread-direct
pcapWriteSize = 262144
pcapBufferSize = 30000000
dbBulkSize = 300000
dbFlushTimeout = 5
compressES = false
maxESConns = 100
maxESRequests = 1000000
packetsPerPoll = 1000000
antiSynDrop = true
logEveryXPackets = 100000
logUnknownProtocols = false
logESRequests = false
logFileCreation = false
```

I am also using an Upstart script to control the moloch-capture process that is modified based on framework found on the Moloch-FPC Google group.

```
# moloch-capture
# 

description     "moloch capture"
author          "Kevin Dougherty based on framework from acirt"

env TDIR="/data/moloch"
env BIN_FILE="/data/moloch/bin/moloch-capture"
env PID_FILE="/var/run/moloch-capture.pid"
env LOGDIR="/var/log/moloch"

start on (filesystem and networking and openvswitch-switch and runlevel [2345] )
stop on runlevel [!2345]

respawn

script  
        echo $$ > ${PID_FILE}
        cd ${TDIR}/bin
        exec ${BIN_FILE} -c ${TDIR}/etc/config.ini >> ${LOGDIR}/capture.log 2>&1
end script

pre-start script
        if [ -f ${LOGDIR}/capture.log.1 ]; then
                /bin/mv ${LOGDIR}/capture.log.1 ${LOGDIR}/capture.$(date +%Y%m%d-%H%M)
        fi
        if [ -f ${LOGDIR}/capture.log ]; then
                /bin/mv ${LOGDIR}/capture.log ${LOGDIR}/capture.log.1
        else
                touch ${LOGDIR}/capture.log
        fi
        echo "`date '+%b %d %T'` [notice]: moloch-capture Starting" >> ${LOGDIR}/capture.log
end script

pre-stop script
        /bin/rm -f ${PID_FILE}
        echo "`date '+%b %d %T'` [notice]: moloch-capture Stopping" >> ${LOGDIR}/capture.log
end script
```

I have not successfully generated a core dump for debugging. Are there any known issues that may be related to this?

**Comment by awick** [comment]
Don't know of any issues, thanks for the detailed report but really need a core.  

I would guess that you need to ```chmod a+w``` the directory moloch is running in and make sure you do the ```sysctl -w fs.suid_dumpable=2``` - even though the core will be owned by root the OS checks that daemon can write to the directory.

**Comment by Afturmath** [comment]
As soon as I reset my core dump variables and dumped a core, it became evident to me that Moloch Capture is dying from being oomkilled. The Moloch capture process seems to be using 58+GB of virtual RAM. 
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                           
10877 moloch    20   0 58.127g 0.056t   8008 R  91.9 91.4  39:56.47 /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini          
```

Could this be caused by the pcap buffer size setting being too high and filling up RAM with PCAP waiting in the disk queue?

**Comment by awick** [comment]
So you probably want to run moloch-capture with --debug and see what settings it is really using.  I know it is changing some of your values because they are too high, for example maxESRequests has a limit of 5000 vs 1000000 you have set.

I would definitely lower your maxESConns and maxESRequests.  

Would be interesting to grep out the moloch_nids_cb_ip lines and post a few
```
moloch_nids_cb_ip(): packets: 15736800000 current sessions: 183151/196548 oldest: 0 - recv: 2875809922 drop: 0 (0.00) ifdrop: 0 queue: 0 disk: 0
```

Also you could ```grep "Dropping request"``` and see if it is having communication issues.

**Comment by WilliamSalusky** [comment]
Ouch. I cringe at the mention of having to write the flood of pcap via NFS. I can't reproduce that environment, but I would imagine the queue to write into this choke point is central to running OOM.
@Afturmath

**Comment by Afturmath** [comment]
@WilliamSalusky: The queue is without a doubt causing the OOM, and I concur that it's because NFS is too slow. I am in the process of trying to tune NFS, but I'm planning to move to faster storage (true ZFS on FreeBSD via 10gb iSCSI) in the next few weeks. The current platform is limited to ZFS on Linux, so unfortunately iSCSI exports are not possible yet.

@awick: Here is a sample of moloch_nids_cb_ip log entries:
```
Feb  4 16:37:19 nids.c:632 moloch_nids_cb_ip(): packets: 1938000000 current sessions: 497624/508281 oldest: 0 - recv: 2015791415 drop: 58601867 (2.91) ifdrop: 300273 queue: 70 disk: 0
```
Here is a "Dropping request" sample:
```
/var/log/moloch/capture.20150201-0711:Jan 30 18:23:27 http.c:547 moloch_http_send(): ERROR - Dropping request /_bulk of size 298564 queue[1] 5001 is too big
```
There were 6518 "Dropping request" entries in the log on the last day it was dropping (Jan 30th).  

I have tuned my config as follows:
```
maxFileSizeG = 10
tcpTimeout = 600
tcpSaveTimeout = 720
udpTimeout = 30
icmpTimeout = 10
maxStreams = 1000000
maxPackets = 10000
spiDataMaxIndices=5
pcapWriteMethod=thread-direct
pcapWriteSize = 1048576
pcapBufferSize = 1000000
dbBulkSize = 300000
dbFlushTimeout = 5
compressES = false
maxESConns = 8
maxESRequests = 4000
packetsPerPoll = 500000
antiSynDrop = false
logEveryXPackets = 1000000
logUnknownProtocols = false
logESRequests = false
logFileCreation = false
```

I will monitor the logs overnight. It seems way more stable after the first round of changes.

**Comment by awick** [comment]
* Dropping request or queue: > 0 means ES isn't keeping up or some network slowness
* A incrementing ifdrop: is bad all around, means something is overloaded, make sure ethtool stuff is fully configured and interrupts are ok

**Comment by Afturmath** [comment]
The ifdrops were my fault; I threw too much traffic at the box from the tool port. I added two more ES nodes to the cluster and tweaked the NFS settings on the storage host. Moloch has not crashed since, but the writes aren't keeping up. This was clearly a misconfiguration, not a bug, so this "issue" can be closed.

**Comment by Tectract** [comment]
What the F am I looking at? How did I get here? Why is there something called "moloch" in Ubuntu 14.04???

> error 7 in libc-2.19.so

I think this is a hardware error, lol. I'm moving to a different system.

**Comment by Tectract** [comment]
Hey remember that time all the Italian Ubuntu Unity team abandoned ship and invaded the Swiss companyy Monetas? I told you people this would happen. I saw all of this, like an avalanche, starting with the death of Ian Murdock and the takeover of Debian by the RedHat team. I tried to warn you all. Nobody listens.
