### ISSUE TITLE
moloch memory

### ISSUE THREAD

**Issue by caspertz** [aol/moloch#333]
All of our pcap systems are large systems (physical systems not virtual) - 32GB memory, 24 processors.  Each system is running 7-8 moloch-captures - 1 for each interface.  We have one machine in particular that is having issues where the RES value (when I run top) keeps increasing as the day progresses to the point where the system is locked up and can only reboot it.  This is only for a couple of the interfaces not all.  To stop this from happening daily, I stop/restart moloch every morning.  there is no swap defined - as that has been disabled.  I would like to not have to restart moloch on a daily basis.  We are running Moloch 0.11.2 and also suricata.  The system OS is Ubuntu.  The disk is a hardware raid 0 - large 32TB disk.

**Comment by awick** [comment]
How big do the moloch processes get?  How much traffic are you running?  I think the only solution will be to add more memory.

**Comment by caspertz** [comment]
a couple of them got close to 11g that I could see before it locked up.  As for how much traffic, how would I figure that out?  we used to be able to keep the system running for almost 30 days or once a month for patching then it would be rebooted.  Why arent the others experiencing the same issue as this one system.

**Comment by awick** [comment]
Are the others getting the same amount of traffic?  You could look at the stats page for bandwidth.  The more traffic, the more sessions, and the more dropped packets lead to more memory usage.

**Comment by caspertz** [comment]
all 8 interfaces dont get the same amount of traffic - the ones that I see are high do coincide with high traffic - so if memory is the issue - and we have 32GB already - how much more we going to have to add to get it back to a safe mode?  before we were running 0.9.3 and this wasnt happening and we had swap on.

**Comment by awick** [comment]
The documentation recommends 10G per moloch-capture.  Looking at our clusters we use about ~80x what stats says we are doing in bytes per second.  For example one interface is doing 130k/sec and is using about 10G.

moloch-capture will take a while to reach steady state with memory, especially if you have different traffic patterns during the day.

You don't say if you are occasionally seeing disk queuing or ES request queueing, which will cause memory to grow.

As far as why is 0.11 using more memory then 0.9, probably more features etc.  Currently while we watch memory and haven't seen any huge growth, we are more concerned with dropped packets and adding more fields/features.  If there are fields you don't want they can be disabled with the ./db field disable command

**Comment by SchreiverJ** [comment]
![moloch_memory](https://cloud.githubusercontent.com/assets/7882061/6172518/5694b85a-b2af-11e4-84c2-f748929766df.jpg)

We are seeing some interesting things with moloch memory. We reach a steady state at about 80% of our 64GB memory then every couple of days the memory begins a slow rise over a couple of hours until it reaches 100 and we begin swapping and have to restart moloch.

**Comment by awick** [comment]
Lots of improvements in 0.14, can you reopen or open a new issue
e58f89985e801474329eeb46f5ecbe86ab673c77

**Comment by 065673** [comment]
Is there a way to specify 10G/capture ?
