### ISSUE TITLE
pfring failed to build

### ISSUE THREAD

**Issue by raggnar** [aol/moloch#334]
Hi there,
 
Evaluating Moloch and i can't seem to have it work. Did the following steps:
 
#######################
sudo apt-get update
sudo apt-get install openjdk-7-jre-headless --yes
 
apt-get install git
 
git clone https://github.com/aol/moloch.git
 
cd moloch/
 
./easybutton-singlehost.sh
 
####################
 
after a while i will get the error on the subject
 
I am installing the program on ubuntu server 12.04 server
 
Can anyone assist me
 
Thanks

**Comment by awick** [comment]
Please look at the last 10 lines or so and provide those OR if it tells you something to do, then try doing what it suggests.  I just tried on a 12.04 machine with no issue, but I'm guessing you are missing a package.

**Comment by raggnar** [comment]
HI Andy,

Thanks for the reply. Please see below information requested

##############

2015-02-09 11:23:14 (868 KB/s) - ‘PF_RING-6.0.2.tar.gz’ saved [21918993/21918993]

cd kernel; make
make[1]: Entering directory `/home/administrator/moloch/thirdparty/PF_RING-6.0.2/kernel'
********** WARNING WARNING WARNING **********
*
* Compiling PF_RING as root might lead you to compile errors
* Please compile PF_RING as unpriviliged user
*
*********************************************
make -C /lib/modules/3.13.0-32-generic/build SUBDIRS=/home/administrator/moloch/thirdparty/PF_RING-6.0.2/kernel EXTRA_CFLAGS='-I/home/administrator/moloch/thirdparty/PF_RING-6.0.2/kernel ' modules
make[2]: Entering directory `/usr/src/linux-headers-3.13.0-32-generic'
  CC [M]  /home/administrator/moloch/thirdparty/PF_RING-6.0.2/kernel/pf_ring.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/administrator/moloch/thirdparty/PF_RING-6.0.2/kernel/pf_ring.mod.o
  LD [M]  /home/administrator/moloch/thirdparty/PF_RING-6.0.2/kernel/pf_ring.ko
make[2]: Leaving directory `/usr/src/linux-headers-3.13.0-32-generic'
make[1]: Leaving directory `/home/administrator/moloch/thirdparty/PF_RING-6.0.2/kernel'
cd userland; make
make[1]: Entering directory `/home/administrator/moloch/thirdparty/PF_RING-6.0.2/userland'
cd lib; ./configure; make
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking linux/net_tstamp.h usability... yes
checking linux/net_tstamp.h presence... yes
checking for linux/net_tstamp.h... yes
checking librdi.h usability... no
checking librdi.h presence... no
checking for librdi.h... no
checking for pthread_setaffinity_np in -lpthread... yes
checking PF_RING ZC support... yes
checking Zero support... yes
checking if r/w locks are supported... yes
checking DNA support... yes
checking for librdi.h... (cached) no
checking for redisCommand in -lhiredis... no
checking for numa_available in -lnuma... no
checking if libnuma is present... no
Please install libnuma-dev in order to use PF_RING
make[2]: Entering directory `/home/administrator/moloch/thirdparty/PF_RING-6.0.2/userland/lib'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory `/home/administrator/moloch/thirdparty/PF_RING-6.0.2/userland/lib'
make[1]: *** [libpfring] Error 2
make[1]: Leaving directory `/home/administrator/moloch/thirdparty/PF_RING-6.0.2/userland'
make: *** [all] Error 2
MOLOCH: pfring failed to build


##################

thanks

**Comment by awick** [comment]
Not sure if you saw: Please install libnuma-dev in order to use PF_RING

**Comment by raggnar** [comment]
thanks 
apt-get install libnuma-dev

Fixed the issue
