### ISSUE TITLE
Cannot get BPF to load

### ISSUE THREAD

**Issue by hadojae** [aol/moloch#335]
I am trying to load the following BPF at moloch runtime in config.ini:

bpf = not (src net 10.0.0.0/8 and dst net 10.0.0.0/8) 

I dont want to see internal to internal traffic. When viewing with --debug i observe that the rule appears to be parsed ok and is loaded. This is not reflected in viewer. Traffic is still captured and metadata is still parsed. 

When i load the following BPF at moloch runtime in config.ini:

bpf = net 10.0.0.0/8

This works properly. Only traffic belonging to either src or dst in that /8 is captured and displayed properly.

I am not sure how else to further debug this or how to see that the rule is not loaded by libnids or something.

Thanks!

jae

**Comment by WilliamSalusky** [comment]
@hadojae , I suspect [but can't confirm at this moment] that the bpf filter as taken from Moloch's config.ini is not handling the parenthesis properly. I just talked with Andy about this yesterday.

If I didn't think that you want to solely exclude traffic that is both TO and FROM a 10/8 node, I would say try explicitly setting NOT's, but as seen in the following, it would prevent even 10/8 to the internet from being captured.

bpf = not src net 10.0.0.0/8 and not dst net 10.0.0.0/8

:/

**Comment by awick** [comment]
Did you ever get this to work?

**Comment by hadojae** [comment]
I was not able to get src net or dst net to work. :( I ended up filtering the traffic further upstream prior to it hitting the TAP.

**Comment by awick** [comment]
What version of libpcap, kernel, OS?  This libpcap fix might have been the issue

> Summary for 1.5.3 libpcap release
>       Don't let packets that don't match the current filter get to the
>           application when TPACKET_V3 is used. 

https://github.com/the-tcpdump-group/libpcap/issues/331

**Comment by hadojae** [comment]
It was RHEL 6.6 / 2.6.32-504.3.3.el6.x86_64 / libpcap-1.1.1-ring (pfring), kernel is newer now.

Testing with pcount working with ntop devs shows that it appears to be fixed in latest pfring.

Sorry for the late response, thanks! :)
