### ISSUE TITLE
support for payload searches

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#336]
I know it can be crushing to the pcap storage filesystem, but sometimes we HAVE to search the payload.

I find having to do both static and regex string searches of HTTP response bodies, POST bodies and SMTP transactions are very common tasks I need to do. Having Moloch support a search would be wonderful.

Issue a warning that "this may be very bad for your ongoing capture process".

**Comment by hillar** [comment]
+1

**Comment by DigiAngel** [comment]
Wait what?  There's no way to search within the payload currently?

**Comment by awick** [comment]
@ahodgen  has contributed a script, we will be making some optimizations this year

**Comment by seadog007** [comment]
It will be helpful to search the whole payload
