### ISSUE TITLE
ERROR - Couldn't load some dependancies, maybe need to 'npm update' inside viewer directory { [Error: Cannot find module 'express'] code: 'MODULE_NOT_FOUND' }

### ISSUE THREAD

**Issue by SuchitV** [aol/moloch#337]
Even after I run 'npm update' in the viewer folder; I'm getting the following error in viewer.log

ERROR - Couldn't load some dependancies, maybe need to 'npm update' inside viewer directory { [Error: Cannot find module 'express'] code: 'MODULE_NOT_FOUND' }

Here's what I get when I run 'npm update'

npm WARN package.json moloch@0.11.0 No README.md file found!
npm WARN package.json node@0.0.0 No README.md file found!
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/elasticsearch
npm http GET https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/keep-alive-agent
npm http GET https://registry.npmjs.org/fs-ext
npm http GET https://registry.npmjs.org/passport-http
npm http GET https://registry.npmjs.org/passport
npm http GET https://registry.npmjs.org/png
npm http GET http://github.com/awick/node-iniparser/tarball/master
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/stylus
npm http GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/jade
npm http 304 https://registry.npmjs.org/keep-alive-agent
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/elasticsearch
npm http 304 https://registry.npmjs.org/passport-http
npm http 304 https://registry.npmjs.org/passport
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/png
npm http 304 https://registry.npmjs.org/express
npm http 200 http://github.com/awick/node-iniparser/tarball/master
npm http GET https://registry.npmjs.org/transformers/2.1.0
npm http GET https://registry.npmjs.org/commander/2.1.0
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/with
npm http GET https://registry.npmjs.org/character-parser/1.2.0
npm http GET https://registry.npmjs.org/monocle/1.1.51
npm http GET https://registry.npmjs.org/constantinople
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/lodash-node
npm http GET https://registry.npmjs.org/connect/2.14.5
npm http GET https://registry.npmjs.org/commander/1.3.2
npm http GET https://registry.npmjs.org/mkdirp/0.4.0
npm http GET https://registry.npmjs.org/range-parser/1.0.0
npm http GET https://registry.npmjs.org/cookie/0.1.2
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/methods/0.1.0
npm http GET https://registry.npmjs.org/send/0.3.0
npm http GET https://registry.npmjs.org/fresh/0.2.2
npm http GET https://registry.npmjs.org/cookie-signature/1.0.3
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/merge-descriptors/0.0.2
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/passport-strategy
npm http 304 https://registry.npmjs.org/commander/2.1.0
npm http 304 https://registry.npmjs.org/transformers/2.1.0
npm http 304 https://registry.npmjs.org/with
npm http GET https://registry.npmjs.org/promise
npm http GET https://registry.npmjs.org/css
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/fs-ext
npm http 304 https://registry.npmjs.org/monocle/1.1.51
npm http GET https://registry.npmjs.org/readdirp
npm http 304 https://registry.npmjs.org/stylus
npm http 304 https://registry.npmjs.org/constantinople
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/css-parse
npm http GET https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/connect/2.14.5
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/mkdirp/0.4.0
npm http 304 https://registry.npmjs.org/range-parser/1.0.0
npm http GET https://registry.npmjs.org/compression/1.0.0
npm http GET https://registry.npmjs.org/csurf/1.1.0
npm http GET https://registry.npmjs.org/basic-auth-connect/1.0.0
npm http GET https://registry.npmjs.org/express-session/1.0.2
npm http GET https://registry.npmjs.org/cookie-parser/1.0.1
npm http GET https://registry.npmjs.org/connect-timeout/1.0.0
npm http GET https://registry.npmjs.org/method-override/1.0.0
npm http GET https://registry.npmjs.org/morgan/1.0.0
npm http GET https://registry.npmjs.org/errorhandler/1.0.0
npm http GET https://registry.npmjs.org/serve-static/1.1.0
npm http GET https://registry.npmjs.org/raw-body/1.1.4
npm http GET https://registry.npmjs.org/response-time/1.0.0
npm http GET https://registry.npmjs.org/qs/0.6.6
npm http GET https://registry.npmjs.org/serve-index/1.0.1
npm http GET https://registry.npmjs.org/setimmediate/1.0.1
npm http GET https://registry.npmjs.org/bytes/0.3.0
npm http GET https://registry.npmjs.org/multiparty/2.2.0
npm http GET https://registry.npmjs.org/vhost/1.0.0
npm http GET https://registry.npmjs.org/static-favicon/1.0.2
npm http 304 https://registry.npmjs.org/commander/1.3.2
npm http GET https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/character-parser/1.2.0
npm http 304 https://registry.npmjs.org/cookie/0.1.2
npm http 304 https://registry.npmjs.org/buffer-crc32/0.2.1
npm http 304 https://registry.npmjs.org/fresh/0.2.2
npm http 304 https://registry.npmjs.org/methods/0.1.0
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/send/0.3.0
npm http GET https://registry.npmjs.org/debug/0.8.0
npm http GET https://registry.npmjs.org/mime/1.2.11
npm http GET https://registry.npmjs.org/fresh
npm http GET https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/lodash-node
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/merge-descriptors/0.0.2
npm http 304 https://registry.npmjs.org/promise
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/is-promise
npm http 304 https://registry.npmjs.org/passport-strategy
npm http 304 https://registry.npmjs.org/css
npm http 304 https://registry.npmjs.org/readdirp
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/css-parse/1.0.4
npm http GET https://registry.npmjs.org/css-stringify/1.0.5
npm http 304 https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/source-map/0.1.34
npm http GET https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/css-parse
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.3
npm http 304 https://registry.npmjs.org/csurf/1.1.0
npm http GET https://registry.npmjs.org/uid2
npm http GET https://registry.npmjs.org/scmp
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/basic-auth-connect/1.0.0
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/compression/1.0.0
npm http 304 https://registry.npmjs.org/express-session/1.0.2
npm http 304 https://registry.npmjs.org/cookie-parser/1.0.1
npm http GET https://registry.npmjs.org/compressible/1.0.0
npm http GET https://registry.npmjs.org/negotiator/0.3.0
npm http GET https://registry.npmjs.org/bytes/0.2.1
npm http 304 https://registry.npmjs.org/method-override/1.0.0
npm http 304 https://registry.npmjs.org/errorhandler/1.0.0
npm http 304 https://registry.npmjs.org/morgan/1.0.0
npm http GET https://registry.npmjs.org/uid2/0.0.3
npm http GET https://registry.npmjs.org/cookie/0.1.0
npm http GET https://registry.npmjs.org/utils-merge/1.0.0
npm http GET https://registry.npmjs.org/debug/0.7.4
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/bytes
npm http 304 https://registry.npmjs.org/connect-timeout/1.0.0
npm http 304 https://registry.npmjs.org/response-time/1.0.0
npm http 304 https://registry.npmjs.org/serve-static/1.1.0
npm http 304 https://registry.npmjs.org/raw-body/1.1.4
npm http GET https://registry.npmjs.org/parseurl/1.0.1
npm http GET https://registry.npmjs.org/bytes
npm http 304 https://registry.npmjs.org/setimmediate/1.0.1
npm http 304 https://registry.npmjs.org/bytes/0.3.0
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/qs/0.6.6
npm http 304 https://registry.npmjs.org/multiparty/2.2.0
npm http 304 https://registry.npmjs.org/vhost/1.0.0
npm http 304 https://registry.npmjs.org/static-favicon/1.0.2
npm http GET https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/debug/0.8.0
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/inherits
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/serve-index/1.0.1
npm http GET https://registry.npmjs.org/negotiator/0.4.2
npm http GET https://registry.npmjs.org/batch/0.5.0
npm http 304 https://registry.npmjs.org/css-parse/1.0.4
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/css-stringify/1.0.5
npm http 304 https://registry.npmjs.org/mime/1.2.11
npm http 304 https://registry.npmjs.org/fresh
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/is-promise
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/source-map/0.1.34
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/uid2
npm http 304 https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/scmp
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/negotiator/0.3.0
npm http 304 https://registry.npmjs.org/bytes/0.2.1
npm http 304 https://registry.npmjs.org/uid2/0.0.3
npm http 304 https://registry.npmjs.org/cookie/0.1.0
npm http 304 https://registry.npmjs.org/utils-merge/1.0.0
npm http 304 https://registry.npmjs.org/bytes
npm http 304 https://registry.npmjs.org/compressible/1.0.0
npm http 304 https://registry.npmjs.org/bytes
npm http 304 https://registry.npmjs.org/stream-counter
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/debug/0.7.4
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/parseurl/1.0.1
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/negotiator/0.4.2
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/batch/0.5.0
npm http 304 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map/0.0.1

**Comment by awick** [comment]
Try "npm cache clean" first, you might have to try googling for "npm 304"
