### ISSUE TITLE
Additional right click context functionality

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#339]
The white space and ASNUM right click functionality as of commit/960ae70f02e4dcb9cfc0e4ef70bc5a4012d4f0f9 looks good with the minor exception finding one point where %URL% is not being handled.  SPI View -> HTTP -> URI   values are missing right click context.

Other fields for future right click actions are:
HTTP Body MD5
Email MD5
TLS Certificate Serial numbers
MAC Addresses

**Comment by paulpc** [comment]
It would be nice to have this based on a config file in stead of hard coded, to allow the users to put in custom actions based on the fields

**Comment by awick** [comment]
@paulpc The idea of the right click actions is config file based, or maybe I don't understand your comment.  I might change up the current format though and have one huge ini section instead of a section per type.  Still thinking about it

https://github.com/aol/moloch/wiki/Settings#rightclick

**Comment by WilliamSalusky** [comment]
Paul, I felt the same. In my config.ini I have:

includes==/$PATH_TO/right_click.ini

And define all right click context actions there.

W

On Tue, Mar 10, 2015 at 1:43 PM, Paul Poputa-Clean <notifications@github.com

**Comment by paulpc** [comment]
@awick, sorry - i didn't notice the wiki page - a case of RTFM.  I know i am opening a Pandora's box, but can we initiate a script based on the right-click menu. (obviously we should do it as the moloch user and not root).

I found it pretty useful with QRadar, especially to initiate IR functions (orchestrating actions on different tools based on one right click action).

**Comment by WilliamSalusky** [comment]
@paulpc I do this with the just committed right click functionality by passing the value in question over to a php handler on a remote server to process.
