### ISSUE TITLE
wiseService excludeDomains migration to capture process?

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#340]
I'm looking at traffic to the WISE agent and after watching a fair amount of traffic containing records that are dropped by the wiseService excludeDomains directive, I wonder if its better to move this filter up to the moloch-capture process so that exclusions are simply not sent to WISE?

I suppose I can see this just adding to the load of single threaded moloch-capture, but if its not a performance killer is it worth doing?

**Comment by awick** [comment]
So that the domain should be dropped is cached on the moloch capture instances, so it will only hit WISE every few minutes per domain. Of course if there is some kind of scan or whatever the current cache would be useless.

Let me think about it
