### ISSUE TITLE
blank out cleartext passwords

### ISSUE THREAD

**Issue by paulpc** [aol/moloch#341]
on a scale from hard to impossible how hard would it be to blank out passwords (maybe based on regex) in the cleartext traffic before they get written to disk? It would help me feel less like the sixth eye.

**Comment by awick** [comment]
Probably not gonna happen.  The data has already been written to disk before the password is detected.  I've been thinking about pcap viewing vs SPI data viewing should maybe have another right or if you have other security ideas.
