### ISSUE TITLE
allow download of src/dst grey scale bit map visualization

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#342]
The visuals are great, but sometimes I want to download the png to include in a doc.

**Comment by awick** [comment]
So is the ask you want to be able to right click source/destination and then have  a "Open Image in New Tab" link?

**Comment by WilliamSalusky** [comment]
Open Image in New Tab is a decent option, but the option to 'save image to file' is the direct path I'm seeking.

**Comment by awick** [comment]
@31453 will make it so when you click on the image on the mouse over you can do something with it
