### ISSUE TITLE
right-click actions - per user

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#343]
I would like to be able to configure right click actions per user. There are more than a few actions/lookups that only one or several individuals might be able to perform.

**Comment by awick** [comment]
58f02e3df2448b8b6f2193c37b42f30ac79b1b6c  always a "users" field per right click that is a comma separated list of users that can see the right click action.

**Comment by WilliamSalusky** [comment]
Excellent. Approved. Now move it to Settings so we don't have to modify an include file and bounce the viewer process! ;)

**Comment by paulpc** [comment]
@WilliamSalusky part of me wonders if we should relegate some of the right-click actions to a browser plugin versus moloch action

**Comment by WilliamSalusky** [comment]
Considering the support is already there and works great, its just refinement that should happen. But if you build it, I'd probably use it. @paulpc

**Comment by awick** [comment]
right click actions can live in wise which can load changes on the fly
