### ISSUE TITLE
wiseService url config - allow user specified custom "header: value" entries

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#346]
There are services I pull indicators from that are not complex enough to require its own service hander js script, just support for adding custom Header: Values in the http request. Allow for multiple custom headers per each [url:$NAME] section.

* example:

[url:misp_ip]
url=https://my.misp-service.notreal.com/attributes/text/download/ip-src
header="Authorization: long_stupid_key_here_stuff_stuff_stuff"
header="APIUser: MaybeSomeServiceRequiresMultipleHeaders"
tags=misp_ip,misp
type=ip
reload=60

**Comment by awick** [comment]
237bc1339b6af743fb063cb9e7cc5a4440f8b804

headers=Authorization: long_stupid_key_here_stuff_stuff_stuff;APIUser: MaybeSomeServiceRequiresMultipleHeaders
