### ISSUE TITLE
the viewer is not working

### ISSUE THREAD

**Issue by junhui** [aol/moloch#348]
i'm using standalone mode, everything is ok, ES have data, but the viewer is not working, when i am viewing http://localhost:8005, it's no response

the node log have no special, only say 

```
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Express server listening on port 8005 in production mode```

any suggestion?

**Comment by awick** [comment]
did you try https://localhost:8005

**Comment by junhui** [comment]
oh, it works, looks like i didn't read the doc very clearly, thank you @awick
