### ISSUE TITLE
Logging timestamps - consistent ISO 8601

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#353]
Moloch has a number of logs, and there are a few different timestamp formats in use. Should standardize on one, preferably ISO 8601

example:

"2015-03-20T14:30Z" or "2015-03-20T07:30-07:00"

http://en.wikipedia.org/wiki/ISO_8601

**Comment by awick** [comment]
Agree that the timestamps are all over the place.  

I hate 8601 for debugging, especially if logged in GMT, and I hate logging TZ over and over.  Anyway, not sure the solution, otherwise I can make them the same, what I like. :)

**Comment by WilliamSalusky** [comment]
I know you hate TZ, but its important to an analysts and responders especially when working investigations across teams.  Accurate timestamps require TZ. If you go ISO8601, you get to cheat with GMT by appending that 'Z' for zulu time!

**Comment by awick** [comment]
I thought we are talking about logs, shouldnt need those for investigations.   Logs should always been in local time. :)

**Comment by WilliamSalusky** [comment]
Logs are evidence. I'm just looking for consistency.
