### ISSUE TITLE
Display/report additional user specifiable fields in Connections

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#357]
While having D3 visually render multiple fields beyond the basic user selectable src and dst would be great, I do want the ability to select additional fields to get at raw data without having to hit ES directly. If I can only get that via direct /connections.json or /connections.csv handlers, I'm ok with that. My preference is the csv handler.

I regularly hunt through data by doing individual connections visualization against things like:
asset   http.user-agent
asset   host.http
asset   http.uri
src.ip  dst.ip

But I could do so much more if I could add fields and dump the aggregate output like [and not limited to] the following:
asset , http.user-agent, http.referer, host.http, http.uri, sessions, [packets, bytes, databytes]

**Comment by awick** [comment]
Make a global config that can also be overwritten per user
