### ISSUE TITLE
WISE dump $sectionname $section_element_count

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#359]
I would like to be able to query WISE services for /dump/sections/ and be returned a plain-text dump of each sectionname and the count of elements in each named section.

**Comment by awick** [comment]
So you just want a text version instead of the json version?

**Comment by WilliamSalusky** [comment]
No. I'm looking to generate a list of all section names that WISE has in memory. In addition, a count of objects in each section. Not a plain text list of all objects when requesting /dump/sections/.

However, I probably *will* be looking for plain-text /dump/${section}/txt/ eventually.

Better example of what I envision for /dump/sections/

Given a wiseService.ini that contains the following:
##########################################
[file:evil_ips]
file=/data/moloch/etc/evil_ips.txt
type=ip
tags=evil_ip,evil

[file:alexa5000]
file=/data/moloch/etc/alexa5000.csv
type=domain
tags=alexa5000

[url:blaim.ips]
url=http://bl.a.im/ips.txt
headers=API: DERPDERPDERP;User-Agent: MSIE
tags=blaim
type=ip
reload=60

[url:zeus.ips]
url=https://zeustracker.abuse.ch/blocklist.php?download=ipblocklist
tags=zt,ztip,botnet
type=ip
reload=60

[url:zeus.domain]
url=https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
tags=zt,ztdomain,botnet
type=domain
reload=60
##########################################

A request to http://wiseHost:8081/dump/sections/ might return 

"section"           "count"
file:evil_ips       54 (keys)
file:alexa5000   5000 (keys)
url:blaim.ips      23 (keys)
url:zeus.ips       263 (keys)
url:zeus.domain   456 (keys)

The above values are made up, and no need to display the literal '(keys)'.

**Comment by WilliamSalusky** [comment]
In hindsight, for any lookup to the wiseHost:8081 interface, both json and txt,csv should be supported.

**Comment by awick** [comment]
Added to #548
