### ISSUE TITLE
Dumping JSON on stdout - moloch-capture

### ISSUE THREAD

**Issue by adulau** [aol/moloch#364]
We were wondering if there is way to only use moloch-capture to dump JSON on stdout. The idea is basically to rely on moloch-capture capabilities (dissectors) for other data-store.

**Comment by awick** [comment]
Currently you could do a --tests and it would output to stderr, but it doesn't save any pcap so it would only be useful on pcap captured using other methods.

From the capture side the ES backend is mostly in db.c, it wouldn't be too hard to make it so the data-store was plugable if folks wanted that just like what was done for S3 output vs saving to local disk.

The viewer side would be more work.

**Comment by adulau** [comment]
Looks very good, it was exactly what I was looking for.  Thank you.

Is there a kind of official documentation about the field description for each parsers output in the JSON?

**Comment by awick** [comment]
No docs, for now you could save into ES at least once and run

curl 'http://localhost:9200/fields/_search?size=1000&pretty'
