### ISSUE TITLE
Feature request: configurable domain stripping in WISE reverse DNS lookups

### ISSUE THREAD

**Issue by MattCarothers** [aol/moloch#365]
Some of our corporate assets have a standard naming convention, and we don't need the domain part.  Contractors who bring in their own laptops will have different names/domains, however, and we'd like to see those so we can identify what company they're with.

It would be nice if we could do something like ...

[reversedns]
ips=10.0.0.0/8
field=asset
stripdomain=my-company.com

... so a machine in DNS as employee123.my-company.com gets an asset tag of "employee123" while a contractor with a machine named contractor123.some-other-company.com gets an asset tag of "contractor123.some-other-company.com."

**Comment by awick** [comment]
https://github.com/aol/moloch/wiki/WISE#ReverseDNS

**Comment by MattCarothers** [comment]
Awesome!  Thanks for the quick turnaround.
