### ISSUE TITLE
Provide support for user supplied decoder/filter scripts

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#366]
Introduce a framework that allows user supplied scripts to perform decoder / filter actions on raw payload for sessions.

I envision this being similar to how the Decode Gzip option works, along with remembering the script is active when switching between sessions.

Example decoder scripts with sample pcap provided directly.

**Comment by bit-bucket** [comment]
I am interested in this.

**Comment by awick** [comment]
We support decode scripts now, let us know if you need more.

**Comment by 31453** [comment]
Reopen with more information if the current support is insufficient.
