### ISSUE TITLE
Elasticsearch _id field 

### ISSUE THREAD

**Issue by reutherM** [aol/moloch#368]
When you look at the ES-database index for exmaple called "sessions-150415" the id of every ES-entry begins with "150415-" and than some sort of Hash follows, I guess. Can you explain how that value is computed in general?

**Comment by HillarAarelaid** [comment]
> On 16 Apr 2015, at 10:24, reutherM <notifications@github.com> wrote:
> 
> When you look at the ES-database index for exmaple called "sessions-150415" the id of every ES-entry begins with "150415-" and than some sort of Hash follows, I guess. Can you explain how that value is computed in general?

uuid ;)

https://github.com/aol/moloch/blob/4a8fbf58d8267f2340da846d89b38724c73980b6/capture/db.c#L267

**Comment by reutherM** [comment]
I allready stumpled over these lines. What I wonder about is how moloch viewer gets his timestamps out of a ES-entry. I think there is a 36-based long value from the Date() function involved. Would you agree?

https://github.com/aol/moloch/blob/master/viewer/viewer.js#L4943
