### ISSUE TITLE
Integration with Cuckoo

### ISSUE THREAD

**Issue by botherder** [aol/moloch#369]
Cuckoo Sandbox, as you might know, is an open source malware analysis system. When Moloch was still in its early days we've been discussing about the possibility to integrate the two projects in order to create an open source powerful sandnet.
It might be time to revive that discussion.

I opened a ticket on Cuckoo's side here: https://github.com/cuckoobox/cuckoo/issues/523

**Comment by awick** [comment]
So I'm currently working/thinking about #366 which may be related.  Basically a framework to send traffic to scripts/tools when the operator wants to.  Is that the kind of integration you want?

**Comment by botherder** [comment]
Something along those lines. Would Moloch be capable to already extract binary artifacts rather than traffic (e.g. downloaded binaries) or would that be out of the scope of Moloch? I remember conversations with @WilliamSalusky years ago about potentially doing this, and at the time it seemed feasible.
What I envision is Moloch and Cuckoo acting in synergy to automatically extract potentially malicious files from a live network link and analyzing them.

**Comment by bit-bucket** [comment]
I am interested in this.

**Comment by paulpc** [comment]
@awick , it might be interesting to add the file mimetype as a tag where a file download seems to happen, but it would add some interesting complexity as you're writing the pcaps. Not sure real-time submissions to cuckoo would be as easy as doing them in bro scripts.

**Comment by awick** [comment]
This would be a cool feature, but we aren't going to do it, maybe someone from the community could do it.
