### ISSUE TITLE
Time based pcap file rotation failing

### ISSUE THREAD

**Issue by david-watson** [aol/moloch#370]
Easybutton install from git on March 13th. Modified /data/moloch/etc/config.ini and set:

maxFileTimeM = 10

and restarted capture process, tailed capture.log

After 10 minutes, pcap rotation fails with:

Apr 20 18:48:46 http.c:317 moloch_http_read_cb(): Apr 20 18:48:46 0/0 0x7fe497f31010 POST ASYNC /get 655 0ms 0ms 41ms
Apr 20 18:48:47 writer-disk.c:133 writer_disk_output_cb(): Opening //rfixydoxlyu.eu/vna/Us&J/6p7%3DqvEaXacn&jExv4Qf/K2/+=$%26
Apr 20 18:48:47 writer-disk.c:141 writer_disk_output_cb(): ERROR - pcap open failed - Couldn't open file: '//rfixydoxlyu.eu/vna/Us&J/6p7%3DqvEaXacn&jExv4Qf/K2/+=$%26' with No such file or directory  (2)
Apr 20 18:48:47 writer-disk.c:143 writer_disk_output_cb():    Verify that user 'daemon' set by configuration variable dropUser can write and the parent directory exists

and capture process exits.

It appears that the capture process is attempting to use a DNS name/URI path as the new pcap filename!

**Comment by awick** [comment]
Commited a fix, let me know if it works for you

**Comment by david-watson** [comment]
Fix seems to work as expected, thanks.
