### ISSUE TITLE
Indexing of HTTP cookie values and forms

### ISSUE THREAD

**Issue by drahtGitter** [aol/moloch#371]
Moloch is currently indexing cookie keys from HTTP-sessions. I'm wondering if this could be extended fin order to also index cookie values. This would allow searches like: 
http.cookie.key == "*username*" && http.cookie.value == "bob" which I would find quite useful.

In a similar way, I would love to be able to do searches on submitted forms. WIreshark decodes HTML forms with keys and values like this:
"action":"do_login"
"url":"someurl"
"username":"someuser"

It would be quite useful if such data could be extracted in the capturing process, similarly like cookie-data, to allow searches such as:
http.formdata.key == "*user*" && http.formdata.value = "bob" to find out if and when user bob logged in.

Best regards

**Comment by awick** [comment]
Split in two since cookie value parsing was easy to add

**Comment by drahtGitter** [comment]
Simply put: Fantastic! :-)

Thank you very much!
