### ISSUE TITLE
Yara repo change / upgrade from old version

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#378]
Yara moved from googlecode to https://github.com/plusvic/yara/releases

The github repo does not contain the ancient version 1.7 being used currently. Test the impact of upgrading. Migrate easybutton to pull from Github.

**Comment by awick** [comment]
Are folks actually using yara integration?  Any public examples that can be shared

**Comment by WilliamSalusky** [comment]
I use it sparsely due to the massive overhead, if I could limit rule application to specific protocols, etc, other SPI meta I would have tons of examples. Right now I use it to do specific hex pattern, and string matching in POST payloads. The concept of restricting rule application to protocols and SPI meta is pretty much screaming suricata integration. Another plus for engine migration.

**Comment by WilliamSalusky** [comment]
I also use it ONLY in standalone investigator mode deployments where I load specific captures. Any time I run even a single yara rule in a production like / live capture environment it tanks the capture process pretty quickly.

**Comment by awick** [comment]
0.17 should support 3.5 now
