### ISSUE TITLE
sha1 hash generation for SSL certificate

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#388]
generate the sha1 hash and expose it as a meta field in colon delimited output

The equivalent of:
openssl s_client -showcerts -connect bl.a.im:443 </dev/null 2>/dev/null|openssl x509 -outform DER | openssl sha1 -c

**Comment by awick** [comment]
What should the field be called?  cert.hash?   
Why sha1?

**Comment by WilliamSalusky** [comment]
Can you make the field cert.sha1.hash considering there are other hashing algorithms that might be used in the future.

There are a number of repositories that provide indicators for badness based on a sha1 hash of the certificate. Take note that it is a hash of the individual cert issued for actual common servername, and not a hash of the entire chain.

**Comment by awick** [comment]
I'm weary of putting sha1 in the expression name since there is so much sha1 vs sha2 swirl in the cert world right now.

I'm doing a hash per certificate, so if the chain is sent there would be multiple hashes
