### ISSUE TITLE
capture install

### ISSUE THREAD

**Issue by GumpSun** [aol/moloch#390]
Always error when I install moloch/capture,so confused.Expect reply.Thanks a lot.

**Comment by awick** [comment]
Please provide OS, Version, and error output

**Comment by GumpSun** [comment]
centos6.3 I just wanna use capture,I get error when I run easybutton-build.sh,cause I can`t access http://yara-project.googlecode.com/files/yara-1.7.tar.gz.

**Comment by awick** [comment]
I can fetch that URL with no issue
