### ISSUE TITLE
moloch v0.11.2 viewer: Decode Gzip crash.

### ISSUE THREAD

**Issue by cbasnett** [aol/moloch#391]
Molcoh Viewer crashes when attempting to Decode certain gzip data, we can't share a pcap at the moment, we're looking at reproducing it with innocuous data.

Will also check if issue exists on latest release version. More to follow..

ERROR { [Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }

/data/moloch/viewer/viewer.js:2572
    outgoing[r]= {ts: incoming[r].ts, html: "", bytes:0};
                                 ^
TypeError: Cannot read property 'ts' of undefined
    at localSessionDetailReturnFull (/data/moloch/viewer/viewer.js:2572:34)
    at timer._onTimeout (timers.js:216:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by cbasnett** [comment]
Confirmed in 0.11.4:

ERROR { [Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }

/data/moloch/viewer/viewer.js:2724
    outgoing[r]= {ts: incoming[r].ts, html: "", bytes:0};
                                 ^
TypeError: Cannot read property 'ts' of undefined
    at localSessionDetailReturnFull (/data/moloch/viewer/viewer.js:2724:34)
    at timer._onTimeout (timers.js:219:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by awick** [comment]
Can you try in 0.11.5 since the parsing code was totally rewritten.

**Comment by cbasnett** [comment]
Of course. It wouldn't build the other day. Will try shortly.

**Comment by cbasnett** [comment]
I can confirm that this bug doesn't exist on the current git. Looks like there was some junk at the beginning of the response data which i assume caused the bug. Cheers Andy.
