### ISSUE TITLE
building via ./easybutton-build.sh or ./easybutton-singlehost.sh and getting errors 

### ISSUE THREAD

**Issue by slacking42** [aol/moloch#392]
this is a fresh install on AWS ubuntu image.. 

first off the curl download was not working so I manually downloaded it a put it in the thirdparty directory, that got me passed the no curl error.. 

then on later in the easybutton build it threw the below errors

am I missing something environmental? or has something changed? did the curl download throw the whole build off? 

<stdout>
"configure: WARNING: unrecognized options: --with-curl
Makefile:219: warning: overriding commands for target `capture/plugins/Makefile'
Makefile:217: warning: ignoring old commands for target `capture/plugins/Makefile'
Making all in capture
make[1]: Entering directory `/opt/secapps/moloch/capture'
gcc -fPIC -O2 -ggdb -Wall -Wextra -D_GNU_SOURCE -c main.c db.c nids.c yara.c http.c config.c parsers.c plugins.c field.c trie.c writers.c writer-inplace.c writer-disk.c writer-null.c \
            -I/opt/secapps/moloch/thirdparty/libpcap-1.7.2 \
            -Ithirdparty -I/opt/secapps/moloch/thirdparty/glib-2.42.0/glib -I/opt/secapps/moloch/thirdparty/glib-2.42.0 -I/opt/secapps/moloch/thirdparty/glib-2.42.0/gmodule -I/opt/secapps/moloch/thirdparty/glib-2.42.0/gobject -I/opt/secapps/moloch/thirdparty/yara-1.7/libyara -I/opt/secapps/moloch/thirdparty/GeoIP-1.6.0/libGeoIP -I/opt/secapps/moloch/thirdparty/libnids-1.24/src @CURL_CFLAGS@
gcc: error: @CURL_CFLAGS@: No such file or directory
make[1]: *** [all] Error 1
make[1]: Leaving directory `/opt/secapps/moloch/capture'
make: *** [all-recursive] Error 1
MOLOCH: make failed"

**Comment by awick** [comment]
Should be fixed by b6a1aa27cbb13276e12e185bab4fb5f23ddc78fd
