### ISSUE TITLE
moloch make failed at "http.c:370: error: ‘G_SOURCE_REMOVE’ undeclared"

### ISSUE THREAD

**Issue by gugansankar** [aol/moloch#399]
Make failed in moloch compile process. Have someone any idea on what wrong here.

Error: 
Makefile:219: warning: overriding commands for target `capture/plugins/Makefile'
Makefile:217: warning: ignoring old commands for target `capture/plugins/Makefile'
Making all in capture
make[1]: Entering directory `/root/SETUP/moloch/capture'
gcc -fPIC -O2 -ggdb -Wall -Wextra -D_GNU_SOURCE -c main.c db.c nids.c yara.c http.c config.c parsers.c plugins.c field.c trie.c writers.c writer-inplace.c writer-disk.c writer-null.c \
	    -I/usr/include/pcap \
	    -Ithirdparty -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  
http.c: In function ‘moloch_http_curlm_timer_callback’:
http.c:370: error: ‘G_SOURCE_REMOVE’ undeclared (first use in this function)
http.c:370: error: (Each undeclared identifier is reported only once
http.c:370: error: for each function it appears in.)
http.c: In function ‘moloch_http_send’:
http.c:545: error: ‘CURLMOPT_MAX_HOST_CONNECTIONS’ undeclared (first use in this function)
http.c:558: error: ‘CURLOPT_CLOSESOCKETFUNCTION’ undeclared (first use in this function)
http.c:558: warning: type defaults to ‘int’ in declaration of ‘_curl_opt’
http.c:559: error: ‘CURLOPT_CLOSESOCKETDATA’ undeclared (first use in this function)
http.c:559: warning: type defaults to ‘int’ in declaration of ‘_curl_opt’
writer-disk.c: In function ‘writer_disk_init’:
writer-disk.c:421: warning: implicit declaration of function ‘g_thread_new’
make[1]: *** [all] Error 1
make[1]: Leaving directory `/root/SETUP/moloch/capture'
make: *** [all-recursive] Error 1

**Comment by awick** [comment]
I would guess your glib2 is too old, it was added in 2.32

**Comment by awick** [comment]
Looks like your version of curl ibrary is too old also, it was added in 7.21.7
