### ISSUE TITLE
No history or booking for the search bar

### ISSUE THREAD

**Issue by aaronucsd** [aol/moloch#402]
Is there a way to keep track of the history of the search bar? This is important to track how i arrived to my final search query.

**Comment by WilliamSalusky** [comment]
No history available in the browser UI, but take a look at the [default location] -> /data/moloch/logs/viewer.log, filtering on your username and the queries are there.

**Comment by awick** [comment]
The browser history is supposed to track the searches also

**Comment by aaronucsd** [comment]
Thanks for the replies. @awick @WilliamSalusky

**Comment by aaronucsd** [comment]
Be nice to have this as a feature in the UI though. I would have to retype similar queries over and over.

**Comment by awick** [comment]
you can use browser bookmarks or your can use moloch views (they are in settings).  Do you have an example app that does something like you want that we can see the UI of?

**Comment by awick** [comment]
#731 replaces this issue, being worked on now
