### ISSUE TITLE
modify ES version to 1.6.0

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#404]
I've been building/running against ES 1.6.0. Is it time to tweak the default version in the easybutton-singlehost built script yet?

**Comment by awick** [comment]
Waiting til I test on our prod clusters, unless you already have ...
For dev haven't had any issues either.

**Comment by phreakinggeek** [comment]
May want to change that to 1.6.1 or 1.7 0, http://seclists.org/bugtraq/2015/Jul/83

**Comment by awick** [comment]
Joy, two security issues at once https://www.elastic.co/blog/elasticsearch-1-7-0-and-1-6-1-released

Been testing with 1.6.0 in prod so moving to 1.6.1 shouldn't be a big deal.

Hopefully everyone is using iptables, I'm thinking of making easy button ask you to type in "I promise to use iptables" :-)
