### ISSUE TITLE
pf_ring build fails 

### ISSUE THREAD

**Issue by charlesfair** [aol/moloch#406]

**Comment by phreakinggeek** [comment]
works for me

**Comment by slacking42** [comment]
I am having the same issue on a ubuntu 14.04 box, seems to be this error

"./easybutton-build.sh: 147: cd: can't cd to PF_RING-6.0.2"

looks related to the gzip or tar process on the downloaded PF_RING-6.0.2.tar.gz


MOLOCH: Building libpcap with pfring
--2015-07-16 20:18:55--  http://sourceforge.net/projects/ntop/files/PF_RING/PF_RING-6.0.2.tar.gz/download
Resolving sourceforge.net (sourceforge.net)... 54.192.69.238, 54.230.69.100, 54.230.69.116, ...
Connecting to sourceforge.net (sourceforge.net)|54.192.69.238|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://sourceforge.net/#!/projects/ntop/files/PF_RING/PF_RING-6.0.2.tar.gz/download [following]
--2015-07-16 20:18:56--  http://sourceforge.net/
Reusing existing connection to sourceforge.net:80.
HTTP request sent, awaiting response... 200 OK
Length: 639 [text/html]
Saving to: ‘PF_RING-6.0.2.tar.gz’

100%[==================================================================================>] 639         --.-K/s   in 0s

2015-07-16 20:18:56 (29.7 MB/s) - ‘PF_RING-6.0.2.tar.gz’ saved [639/639]


gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
./easybutton-build.sh: 147: cd: can't cd to PF_RING-6.0.2
make: *** No targets specified and no makefile found.  Stop.
MOLOCH: pfring failed to build

**Comment by slacking42** [comment]
also tried without PF_ring (answered no on install ) and got the below

VER=`cat ./VERSION`; \
        MAJOR_VER=`sed 's/\([0-9][0-9]*\)\..*/\1/' ./VERSION`; \
        gcc -shared -Wl,-soname,libpcap.so.$MAJOR_VER  \
            -o libpcap.so.$VER pcap-linux.o pcap-usb-linux.o pcap-can-linux.o pcap-netfilter-linux.o fad-getad.o pcap.o inet.o gencode.o optimize.o nametoaddr.o etherent.o savefile.o sf-pcap.o sf-pcap-ng.o pcap-common.o bpf_image.o bpf_dump.o  scanner.o grammar.o bpf_filter.o version.o
./config.status --file=pcap-config.tmp:./pcap-config.in
config.status: creating pcap-config.tmp
mv pcap-config.tmp pcap-config
chmod a+x pcap-config

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
./easybutton-build.sh: 179: [: Linux: unexpected operator
./easybutton-build.sh: 182: cd: can't cd to libnids-1.24
./easybutton-build.sh: 182: ./easybutton-build.sh: ./configure: not found
make: *** No targets specified and no makefile found.  Stop.
MOLOCH: make failed

**Comment by awick** [comment]
sourceforge is having issues, if you look at the file it actually downloads it says 

"We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later."

You can download it externally and place it where moloch expects it.

I wish pfring would move to github.

**Comment by slacking42** [comment]
Ahhhh that makes sense, thanks

**Comment by DataSquid** [comment]
*shakes fist*SOURCE FORGE!!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: all powerful vogon leaderSent: Thursday, July 16, 2015 4:31 PMTo: aol/molochReply To: aol/molochSubject: Re: [moloch] pf_ring build fails  (#406)Ahhhh that makes sense, thanks
On Jul 16, 2015 16:28, "Andy Wick" <notifications@github.com> wrote:

> sourceforge is having issues, if you look at the file it actually
> downloads it says
>
> "We're sorry -- the Sourceforge site is currently in Disaster Recovery
> mode, and currently requires
> the use of javascript to function. Please check back later."
>
> You can download it externally and place it where moloch expects it.
>
> I wish pfring would move to github.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aol/moloch/issues/406#issuecomment-122079883>.
>


—Reply to this email directly or view it on GitHub.

**Comment by slacking42** [comment]
I know right!
