### ISSUE TITLE
visual highlighting of business/peak hours per node per graph

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#419]
Far reaching wishful thinking to render graphs with highlighting/shading that identify configurable periods of interest like normal business hours. This gets more interesting with node in many different timezones and the need to represent a sliding window of business hours.

**Comment by awick** [comment]
Would be awesome to display behind the graph, will need to convince @31453

**Comment by 31453** [comment]
@awick We could add this as a setting to the settings page. Would only admin users be able to set the "normal business hours"? It would probably be a beginning of business day and end of business day input. How would this work for multiviewers?

**Comment by awick** [comment]
a simple place to start would be per cluster you set this in the config file.  

Where it breaks down is with multi or when a cluster has lots of different time zones.  for example if you have a office cluster that receives data from all offices around the world.  So maybe for those clusters you turn it off (or don't set in config file?)
