### ISSUE TITLE
Add New Init/Recover Option that does not delete Sessions

### ISSUE THREAD

**Issue by SchreiverJ** [aol/moloch#421]
I have found that sometime that ES gets confused and has issue with the Moloch DB structures. When this happens moloch begins crashing, but ES appears to work perfectly fine. 

I have found that by removing the line esDelete("/${PREFIX}sessions*", 1); in the init command for db.pl then running the db.pl init to reset the db structures moloch is able to recover from corruption issue without deleting the session data.

It would be good to have an option that performs a reset to these db structures using the db.pl script. instead of having to do a full reset when things go very very bad.

**Comment by awick** [comment]
This will screw up tags and other things.  What version of ES are you using?  What error is moloch viewer returning?

**Comment by SchreiverJ** [comment]
It also will cause issue with disk because Moloch will no longer knows which pcap to delete so I should note that as well. It just seemed like a better option than taking a full db wipe in an emergency to me. I am using ES 1.3.4 and Moloch 0.11.4.

Moloch capture was also no longer writing to ES, even though cluster status was green. So this was more of an emergency fix than anything. Mostly just thought others might have encountered similar situations. 

Do you know what tags this will corrupt. It seems like everything is ok, my wise tags are at least still there. I can perform checks on other tags if you would like.

Viewer error was:

TypeError: Cannot read property 'nodes' of undefined
    at /data/moloch/viewer/viewer.js:5017:9
    at /data/moloch/viewer/db.js:220:91
    at respond (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:253:9)
    at null.<anonymous> (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:281:7)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15) 

We have used this to recover from other errors as well but I don't have logs. I know recently we received and issue that was something like moloch db version -1 on a separate cluster. I will try to see what I can round up on a true error log for you.

I'm sure you will have a better way! Thanks for your help!

**Comment by awick** [comment]
Tags are stored as a number to string mapping currently and are created as they are needed.  (So basically a join is needed for that field.)  If the tags database is deleted then they will be created in different order and the mapping will be different.  For some of the standard tags they will probably be created in the same order, but most won't.

Sounds like the stats call wasn't responding.  Just restarting the ES cluster might fix it also.  Hard to know with such an old ES version.

**Comment by SchreiverJ** [comment]
Yeah I started with a stop with a rolling start, since typically that takes care of things. But sometimes I can't get recovery to fully take place by doing so.

**Comment by SchreiverJ** [comment]
We are looking to upgrade ES, hopefully that will take care of most the issues

**Comment by awick** [comment]
reopen if still an issue
