### ISSUE TITLE
icmp search results in UDP packets

### ISSUE THREAD

**Issue by JeffSoh** [aol/moloch#424]
When searching for ip.protocol == icmp, getting UDP packets in the results (protocol 17). 

4500 0048 355b 4000 f211 2393 0c44 5b36 E..H5[@...#..D[6
b780 10bc 71be 0035 0034 0000           ...q..5.4..

**Comment by awick** [comment]
I can't seem to reproduce, can you send a sample pcap

**Comment by JeffSoh** [comment]
Closing the issue.The packet was an ICMP dest unreachable and I glanced at the payload. Apologies.
