### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by viks2015** [aol/moloch#426]
Hi,
1. I am trying to install moloch on Ubuntu 15.04 through easybutton-singlehost.sh
2. However I get following error message:
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/libpcap.a(pcap-canusb-linux.o): In function `canusb_close':
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:329: undefined reference to `libusb_close'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:334: undefined reference to `libusb_exit'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/libpcap.a(pcap-canusb-linux.o): In function `canusb_capture_thread':
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:274: undefined reference to `libusb_interrupt_transfer'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:276: undefined reference to `libusb_interrupt_transfer'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:280: undefined reference to `libusb_bulk_transfer'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/libpcap.a(pcap-canusb-linux.o): In function `canusb_activate':
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:346: undefined reference to `libusb_init'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/libpcap.a(pcap-canusb-linux.o): In function `canusb_opendevice':
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:153: undefined reference to `libusb_get_device_list'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:159: undefined reference to `libusb_get_device_descriptor'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:167: undefined reference to `libusb_open'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:169: undefined reference to `libusb_get_string_descriptor_ascii'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:178: undefined reference to `libusb_kernel_driver_active'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:178: undefined reference to `libusb_detach_kernel_driver'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:184: undefined reference to `libusb_set_configuration'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:190: undefined reference to `libusb_claim_interface'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:192: undefined reference to `libusb_close'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:201: undefined reference to `libusb_free_device_list'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/libpcap.a(pcap-canusb-linux.o): In function `canusb_activate':
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:375: undefined reference to `libusb_exit'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/libpcap.a(pcap-canusb-linux.o): In function `canusb_opendevice':
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:197: undefined reference to `libusb_free_device_list'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/libpcap.a(pcap-canusb-linux.o): In function `canusb_clearbufs':
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:316: undefined reference to `libusb_interrupt_transfer'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/libpcap.a(pcap-canusb-linux.o): In function `canusb_findalldevs':
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:97: undefined reference to `libusb_init'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:106: undefined reference to `libusb_get_device_list'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:113: undefined reference to `libusb_get_device_descriptor'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:121: undefined reference to `libusb_open'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:125: undefined reference to `libusb_get_string_descriptor_ascii'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:131: undefined reference to `libusb_close'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:135: undefined reference to `libusb_free_device_list'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:136: undefined reference to `libusb_exit'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:142: undefined reference to `libusb_free_device_list'
/home/user/Desktop/moloch/thirdparty/libpcap-1.7.2/./pcap-canusb-linux.c:143: undefined reference to `libusb_exit'
collect2: error: ld returned 1 exit status
Makefile:36: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/user/Desktop/moloch/capture'
Makefile:233: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
MOLOCH: make failed

3. How do reslove this error

**Comment by awick** [comment]
Can you try changing easybutton-build.sh around line 164 adding --disable-usb --disable-canusb

(cd libpcap-$PCAP; ./configure --disable-dbus --disable-usb --disable-canusb; $MAKE)

**Comment by viks2015** [comment]
Thank you, the changing the easybutton-build.sh  worked. However I have got another issue .
1.Moloch is not logging PORT Scans attacks.

2  I ran wireshark and moloch on same host machine. All packets were captured and displayed by moloch except port scans. The scans were visible in wireshark though.

3. I think moloch is only logging successful TCP/UDP requests and not the dropped packets

**Comment by WilliamSalusky** [comment]
viks,

The capture process manages session state in memory until a session ends.
Long running, high volume data, or stateless [udp and/or scans] sessions
are written in segments based on several factors. I've pasted the
config.ini chunk that governs this behavior.

For TCP
1. X packets [10000 by default],
2. X seconds [ 600 default, 10 minutes]
3. capture process exceeds X number active monitored sessions/streams
4. capture process memory [I'm fuzzy on the limits right now]

With UDP
the difference in time is dropped to 30 seconds of inactivity.

If you are monitoring what is the equivalent of an nmap syn scan for
example, your capture process can wait up to 12 minutes before writing the
meta data and become searchable via the Viewer. If you were to manually
tcpdump on the /data/moloch/raw/*.pcap files, assuming you have traffic
already flushed to disk you should see the raw scan there.

Can you try a manual test and wait it out? I'm not going to lie, excessive
scanning activity past a sniffer has been a headache for myself, and if
that is what your environment will look like on a regular basis, tuning the
timing variables might be something to consider to reduce the time to write
session meta data to the data store.

W

=========

# TCP timeout value.  Moloch writes a session record after this many
seconds
# of inactivity.
tcpTimeout = 600

# Moloch writes a session record after this many seconds, no matter if
# active or inactive
tcpSaveTimeout = 720

# UDP timeout value.  Moloch assumes the UDP session is ended after this
# many seconds of inactivity.
udpTimeout = 30

# ICMP timeout value.  Moloch assumes the ICMP session is ended after this
# many seconds of inactivity.
icmpTimeout = 10

# An aproximiate maximum number of active sessions Moloch/libnids will try
# and monitor
maxStreams = 1000000

# Moloch writes a session record after this many packets
maxPackets = 10000

**Comment by viks2015** [comment]
Hi Thanks for all the help and I really life moloch. 
I have been able to resolve the earlier issue. Now I have some additional queries.
I  make two queries to generate graph where one query is a subset on another. However these results do not match. I can see nmap scan in one and not in the other.
![1](https://cloud.githubusercontent.com/assets/14228623/11064049/a178e916-87e0-11e5-8bdd-37d72c3dcaf5.JPG)
![2](https://cloud.githubusercontent.com/assets/14228623/11064057/aa893588-87e0-11e5-8fcc-676453905f77.JPG)

**Comment by hillar** [comment]
you have "query size = 100" 
just increase it

**Comment by viks2015** [comment]
what should be the ideal size of getting realtime graph

**Comment by viks2015** [comment]
only at "query size = 100000" I can see the scan graph but it is very cluttered
![22](https://cloud.githubusercontent.com/assets/14228623/11064992/be64f848-87e6-11e5-8ea8-f3fb5d7cb9c7.png)

**Comment by awick** [comment]
Reusing a github issue multiple times without changing title is probably not the best way for a conversation.  The mailing list or IRC would be better.

Since you are saying ip.dst:port and looking for a port scan, there will be at least 0xffff circles/lines, one for every port.  Remove the :port if you want just 1 line for the port scan.  If you want a different visual representation maybe file a feature request.

**Comment by viks2015** [comment]
oh sorry for that I will take of it thanks

**Comment by WilliamSalusky** [comment]
Viks,

Try setting the 'Query size' drop down to a larger number. By rendering the
first 100 sessions, you are not going to see everything you want.

W
