### ISSUE TITLE
pf_Ring woes on RHEL

### ISSUE THREAD

**Issue by paulpc** [aol/moloch#438]
in trying to build with PF-RING 6.0.2 i ran into some odd driver issues. First of all there was the numa stuff, which in RHEL you need numactl-dev in stead of libnuma-dev.

The other issue (don't have the output, but it was earily similar to this: http://www.gossamer-threads.com/lists/ntop/misc/34493) I fixed by going to pf_ring 6.2 (I assume it was the newer drivers in the package that fixed the issue).

**Comment by awick** [comment]
0.14 no longer requires building of pfring or linking directly with it
