### ISSUE TITLE
libnids.a references

### ISSUE THREAD

**Issue by lasselj** [aol/moloch#440]
Hi,

I observe when I run the easybuttion-build.sh script that it fails on Fedora 23 with error like: 

gcc -rdynamic -ggdb main.o db.o nids.o yara.o http.o config.o parsers.o plugins.o field.o trie.o writers.o writer-inplace.o writer-disk.o writer-null.o -o moloch-capture \
            -u g_checksum_update -u g_hmac_update \
    /home/lasse/work/tmp/moloch-master/thirdparty/libpcap-1.7.2/libpcap.a \
    /home/lasse/work/tmp/moloch-master/thirdparty/libnids-1.24/src/libnids.a /home/lasse/work/tmp/moloch-master/thirdparty/glib-2.47.4/glib/.libs/libglib-2.0.a /home/lasse/work/tmp/moloch-master/thirdparty/glib-2.47.4/gio/.libs/libgio-2.0.a /home/lasse/work/tmp/moloch-master/thirdparty/glib-2.47.4/gobject/.libs/libgobject-2.0.a /home/lasse/work/tmp/moloch-master/thirdparty/glib-2.47.4/gthread/.libs/libgthread-2.0.a /home/lasse/work/tmp/moloch-master/thirdparty/glib-2.47.4/gmodule/.libs/libgmodule-2.0.a /home/lasse/work/tmp/moloch-master/thirdparty/glib-2.47.4/glib/.libs/libglib-2.0.a /home/lasse/work/tmp/moloch-master/thirdparty/yara-1.7/libyara/.libs/libyara.a /home/lasse/work/tmp/moloch-master/thirdparty/GeoIP-1.6.0/libGeoIP/.libs/libGeoIP.a /home/lasse/work/tmp/moloch-master/thirdparty/curl-7.42.1/lib/.libs/libcurl.a -lrt -lmagic -luuid -lpcre thirdparty/http_parser.o thirdparty/js0n.o thirdparty/patricia.o -ldl -lpthread -lssl -lcrypto \
    -lm -lresolv -lffi -lz
/home/lasse/work/tmp/moloch-master/thirdparty/libnids-1.24/src/libnids.a(libnids.o): In function `gen_ip_frag_proc':
/home/lasse/work/tmp/moloch-master/thirdparty/libnids-1.24/src/libnids.c:375: undefined reference to `ip_fast_csum'
/home/lasse/work/tmp/moloch-master/thirdparty/libnids-1.24/src/libnids.a(libnids.o): In function `process_udp':
/home/lasse/work/tmp/moloch-master/thirdparty/libnids-1.24/src/libnids.c:434: undefined reference to `my_udp_check'
/home/lasse/work/tmp/moloch-master/thirdparty/libnids-1.24/src/libnids.a(tcp.o): In function `process_tcp':
/home/lasse/work/tmp/moloch-master/thirdparty/libnids-1.24/src/tcp.c:742: undefined reference to `my_tcp_check'
/home/lasse/work/tmp/moloch-master/thirdparty/libnids-1.24/src/libnids.a(tcp.o): In function `process_icmp':
/home/lasse/work/tmp/moloch-master/thirdparty/libnids-1.24/src/tcp.c:995: undefined reference to `ip_compute_csum'
collect2: error: ld returned 1 exit status
Makefile:36: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/lasse/work/tmp/moloch-master/capture'
Makefile:233: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
MOLOCH: make failed

So I made a small patch to the libnids checksum.c file as required:

[root@srv02 src]# diff checksum.c.orig checksum.c
123c123
< inline u_short ip_fast_csum(u_char * iph, u_int ihl)
---
> u_short ip_fast_csum(u_char * iph, u_int ihl)
194c194
< inline u_short
---
> u_short
200c200
< inline u_short
---
> u_short
208c208
< inline u_short
---
> u_short
[root@srv02 src]# 

/Lasse

**Comment by Lenny1976** [comment]
Hi Lasse,

Ive come across the same issue whilst trying to install Moloch. The thing is I am totally new to this environment and as such have no idea of what you did above to fix the issue. Is there any chance you could walk me through this fix step by step. Any help is greatly appreciated.
Regards
Paul

**Comment by lasselj** [comment]
Yes, sure. So the problem is that 4 functions in the libnids library are declared inline which when libnids is compiled as a static library as it is in the moloch installation does not expose the functions. So as a solution you can remove the inline declarations. So edit thirdparty/libnids-1.24/src/checksum.c and remove the inline keyword in front of the function declaration on lines 123, 194, 200 and 208. Recompile etc.
C'est tout....
Lasse

**Comment by Lenny1976** [comment]
Hi Lasse, many thanks for your reply. Basically what you are saying is to go to each of the lines above and delete the word 'inline' from it and then return to the terminal and use the command ./easybutton-singlehost.sh?

I've tried this and it hasn't worked, I'm still getting the same makefile error...is there something I've missed or failed to do. Sorry for the ignorance but I'm new to this stuff. Thanks Paul

**Comment by awick** [comment]
libnids is being removed in 0.14
e58f89985e801474329eeb46f5ecbe86ab673c77
