### ISSUE TITLE
easybutton-single host stuck, installing on Myricom SNF

### ISSUE THREAD

**Issue by zalpany2000** [aol/moloch#443]
Hello,
I'm trying to install Moloch via the easybutton, I'm running ubuntu 14.4 with a Myricom NIC and SNF10G, 
the installation get stuck in make all, and I cannot figure out why

here is the terminal response:

Making all in capture
make[1]: Entering directory `/moloch-master/capture'
gcc -c thirdparty/js0n.c -o thirdparty/js0n.o
gcc -ggdb -DNDEBUG -DHTTP_PARSER_STRICT=0 -DHTTP_PARSER_DEBUG=0 -O3 -c thirdparty/http_parser.c -o thirdparty/http_parser.o
gcc -c thirdparty/patricia.c -o thirdparty/patricia.o
gcc -fPIC -O2 -ggdb -Wall -Wextra -D_GNU_SOURCE -c main.c db.c nids.c yara.c http.c config.c parsers.c plugins.c field.c trie.c writers.c writer-inplace.c writer-disk.c writer-null.c \
	    -I/moloch-master/thirdparty/libpcap-1.7.2 \
	    -Ithirdparty -I/moloch-master/thirdparty/glib-2.47.4/glib -I/moloch-master/thirdparty/glib-2.47.4 -I/moloch-master/thirdparty/glib-2.47.4/gmodule -I/moloch-master/thirdparty/glib-2.47.4/gobject -I/moloch-master/thirdparty/yara-1.7/libyara -I/moloch-master/thirdparty/GeoIP-1.6.0/libGeoIP -I/moloch-master/thirdparty/libnids-1.24/src -I/moloch-master/thirdparty/curl-7.42.1/include 
writer-disk.c: In function ‘writer_disk_output_cb’:
writer-disk.c:169:13: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
             (void)ftruncate(outputFd, filelen);
             ^
writer-disk.c: In function ‘writer_disk_output_thread’:
writer-disk.c:247:17: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
                 (void)ftruncate(outputFd, filelen);
                 ^
gcc -rdynamic -ggdb main.o db.o nids.o yara.o http.o config.o parsers.o plugins.o field.o trie.o writers.o writer-inplace.o writer-disk.o writer-null.o -o moloch-capture \
            -u g_checksum_update -u g_hmac_update \
	    /moloch-master/thirdparty/libpcap-1.7.2/libpcap.a \
	    /moloch-master/thirdparty/libnids-1.24/src/libnids.a /moloch-master/thirdparty/glib-2.47.4/glib/.libs/libglib-2.0.a /moloch-master/thirdparty/glib-2.47.4/gio/.libs/libgio-2.0.a /moloch-master/thirdparty/glib-2.47.4/gobject/.libs/libgobject-2.0.a /moloch-master/thirdparty/glib-2.47.4/gthread/.libs/libgthread-2.0.a /moloch-master/thirdparty/glib-2.47.4/gmodule/.libs/libgmodule-2.0.a /moloch-master/thirdparty/glib-2.47.4/glib/.libs/libglib-2.0.a /moloch-master/thirdparty/yara-1.7/libyara/.libs/libyara.a /moloch-master/thirdparty/GeoIP-1.6.0/libGeoIP/.libs/libGeoIP.a /moloch-master/thirdparty/curl-7.42.1/lib/.libs/libcurl.a -lrt -lmagic -luuid -lpcre thirdparty/http_parser.o thirdparty/js0n.o thirdparty/patricia.o -ldl -lpthread -lssl -lcrypto \
	    -lm -lresolv -lffi -lz
/moloch-master/thirdparty/libpcap-1.7.2/libpcap.a(pcap-snf.o): In function `snf_activate':
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:268: undefined reference to `snf_open'
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:283: undefined reference to `snf_ring_open_id'
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:296: undefined reference to `snf_start'
/moloch-master/thirdparty/libpcap-1.7.2/libpcap.a(pcap-snf.o): In function `snf_platform_cleanup':
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:74: undefined reference to `snf_inject_close'
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:76: undefined reference to `snf_ring_close'
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:77: undefined reference to `snf_close'
/moloch-master/thirdparty/libpcap-1.7.2/libpcap.a(pcap-snf.o): In function `snf_pcap_stats':
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:53: undefined reference to `snf_ring_getstats'
/moloch-master/thirdparty/libpcap-1.7.2/libpcap.a(pcap-snf.o): In function `snf_inject':
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:228: undefined reference to `snf_inject_send'
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:220: undefined reference to `snf_inject_open'
/moloch-master/thirdparty/libpcap-1.7.2/libpcap.a(pcap-snf.o): In function `snf_read':
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:156: undefined reference to `snf_ring_recv'
/moloch-master/thirdparty/libpcap-1.7.2/libpcap.a(pcap-snf.o): In function `snf_findalldevs':
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:333: undefined reference to `snf_init'
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:336: undefined reference to `snf_getifaddrs'
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:412: undefined reference to `snf_freeifaddrs'
/moloch-master/thirdparty/libpcap-1.7.2/libpcap.a(pcap-snf.o): In function `snf_create':
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:431: undefined reference to `snf_init'
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:441: undefined reference to `snf_getifaddrs'
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:455: undefined reference to `snf_freeifaddrs'
/moloch-master/thirdparty/libpcap-1.7.2/./pcap-snf.c:455: undefined reference to `snf_freeifaddrs'
collect2: error: ld returned 1 exit status
make[1]: *** [all] Error 1
make[1]: Leaving directory `/moloch-master/capture'
make: *** [all-recursive] Error 1
MOLOCH: make failed

any Ideas ?

**Comment by awick** [comment]
If you go into the capture dir and type "make snf" it might work, I haven't tested for years.  Otherwise you need to add the snf libraries to the link line.
