### ISSUE TITLE
can Moloch support more than one vlan in a session?

### ISSUE THREAD

**Issue by yogch** [aol/moloch#444]

**Comment by awick** [comment]
It should, are you saying it doesn't work?  Can you send a sample pcap.

**Comment by yogch** [comment]
I can't now because I'm not near this specific computer. But I created a sample pcap using:
1. tcprewrite (for the first vlan)
2. using [interface vlan tagging](https://wiki.ubuntu.com/vlan) (for the second vlan)

Although I'm quite sure it's possible to tag twice with he interface (the second option). Just need to capture the first injection ([with tcpdump](http://serverfault.com/questions/490703/vconfig-not-tagging-outgoing-packets-with-vlan-tag-ubuntu))

Sorry for not bringing a valid pcap.

**Comment by yogch** [comment]
Where can I send you a sample pcap?

**Comment by awick** [comment]
andywick gmail.com

**Comment by yogch** [comment]
Sent

**Comment by awick** [comment]
libnids doesn't like the pcap for some reason, I'll have to figure out why

**Comment by yogch** [comment]
Thanks.
Do you have pcap with two vlans which works?

**Comment by yogch** [comment]
The problem is libnids.
This lib supports only one vlan.
Look in src/libnids.c:253.
It's harcodedly checks for next header as 'ip' or 'vlan'. If it's vlan it assumes the header after the vlan header is the ip header. It doesn't check whether there's another vlan after the first vlan.

**Comment by awick** [comment]
ok, well ive added a test case for the libnids removed branch (rearch) and it works

**Comment by yogch** [comment]
Nice. When do you plan to merge the `rearch` branch to the `master` branch?

**Comment by awick** [comment]
e58f89985e801474329eeb46f5ecbe86ab673c77
