### ISSUE TITLE
Errno: 34, code: 'ENOENT'

### ISSUE THREAD

**Issue by SuchitV** [aol/moloch#449]
Moloch is running and capturing packets however; can't get to the viewer via https or http. Checked the viewer.log and saw the following error code.

ERROR -  { [Error: ENOENT, open './views/style.styl'] errno: 34, code: 'ENOENT', path: './views/style.styl' }

Some info about the system; its inside our perimeter and due to policy the Moloch box cannot have access to the internet. So "npm update" is currently not possible.

**Comment by awick** [comment]
Check your permissions that daemon can read that file or enter the directory

**Comment by SuchitV** [comment]
Just verified that daemon does have permission to read the directory. This Moloch instance was up and running for a the past month; however this error just appeared recently. Npm install was run successfully when the system was setup.

**Comment by awick** [comment]
does that file actually exist?  and you checked all parent directories for permissions?

**Comment by SuchitV** [comment]
I resolved the issue; turns out the wrong user was running the viewer script and didn't have access to the file.
