### ISSUE TITLE
RSS load balancing

### ISSUE THREAD

**Issue by yogch** [aol/moloch#451]
Looks like Moloch (or PF_RING?) doesn't send the same connection to the same node when running couple of captures on the same machine, and therefore 2 one-way sessions are created instead of 1.

In the attached picture there are 2 sessions for different nodes (03, 04).
It's the same session, but each node gets 1 side of the connection (03 gets all the A to B packets, and 04 gets all the B to A packets).

![image](https://cloud.githubusercontent.com/assets/13855845/14110076/a3a5a55c-f5cd-11e5-9792-dc83cb2f31cf.png)

This is the conversations statistics for each .pcap file (for each session):

![image](https://cloud.githubusercontent.com/assets/13855845/14110104/c4074d32-f5cd-11e5-93ac-c6b8d7c73c75.png)

Configuration:

![image](https://cloud.githubusercontent.com/assets/13855845/14110174/060b37b6-f5ce-11e5-8f36-34bb9ea998d1.png)

Moloch version: `0.11.5 2015/04/xx`
PF_RING version: `6.0.3`
`ixgbe` ko is loaded.

Is this a known issue?

Thanks

**Comment by awick** [comment]
how packets are routed is controlled by the pfring env vars, how are those set?

You probably want to use PCAP_PF_RING_USE_CLUSTER_PER_FLOW_5_TUPLE and PCAP_PF_RING_RSS_REHASH

http://www.ntop.org/pfring_api/pfring_8h.html

**Comment by awick** [comment]
BTW, 0.11 has security issues, you really should upgrade

**Comment by yogch** [comment]
Thanks,
BTW looks like the parameter `PCAP_PF_RING_USE_CLUSTER_PER_FLOW_5_TUPLE` must come with `PCAP_PF_RING_CLUSTER_ID` according to the code. `pfring.h`:

> if(clusterId = getenv("PCAP_PF_RING_CLUSTER_ID")) {
              if(atoi(clusterId) > 0 && atoi(clusterId) < 255) {
                if(getenv("PCAP_PF_RING_USE_CLUSTER_PER_FLOW"))
                  pfring_set_cluster(handle->ring, atoi(clusterId), cluster_per_flow);
                else if( getenv("PCAP_PF_RING_USE_CLUSTER_PER_FLOW_2_TUPLE"))
                  pfring_set_cluster(handle->ring, atoi(clusterId), cluster_per_flow_2_tuple);
                else if( getenv("PCAP_PF_RING_USE_CLUSTER_PER_FLOW_4_TUPLE"))
                  pfring_set_cluster(handle->ring, atoi(clusterId), cluster_per_flow_4_tuple);
                else if( getenv("PCAP_PF_RING_USE_CLUSTER_PER_FLOW_TCP_5_TUPLE"))
                  pfring_set_cluster(handle->ring, atoi(clusterId), cluster_per_flow_tcp_5_tuple);
                else if( getenv("PCAP_PF_RING_USE_CLUSTER_PER_FLOW_5_TUPLE"))
                  pfring_set_cluster(handle->ring, atoi(clusterId), cluster_per_flow_5_tuple);
