### ISSUE TITLE
Using reader-pfring.so

### ISSUE THREAD

**Issue by yogch** [aol/moloch#452]
How should I load `reader-pfring.so` plugin?
Should I:
1. load it in the in the root plugins:
> rootPlugins=reader-pfring.so

2. Still seems `libpcap` reader is loaded. Should I change hard-coded in the `readers.c` in `moloch_readers_set()` to `pfring`?

3. I did both, and still there are no packets inserted. I saw in `reader-pfring.c` that the running of `reader_pfring_thread()` depends on `for (i = 0; i < config.dontSaveBPFsNum; i++) {`, and `config.dontSaveBPFsNum` is 0.

Am I missing something?

Thanks

**Comment by awick** [comment]
Added a README and good catch with the loop, fixed
