### ISSUE TITLE
ERROR - Moloch requires full packet captures

### ISSUE THREAD

**Issue by yogch** [aol/moloch#453]
> reader-libpcap.c:57 reader_libpcap_pcap_cb(): ERROR - Moloch requires full packet captures caplen: 16384 pktlen: 35570

Is there a way to get packets bigger than `16384` limit?
Or continue with the captured packet, like `libnids` ?

`moloch.h`:
`#define MOLOCH_SNAPLEN 16384`

Looks like `libnids` received the packet as is. Ignored the real length and related to the captured length (in `libnids.c`, `nids_pcap_handler()`, the calls to `call_ip_frag_procs()`).

Thanks.

**Comment by awick** [comment]
have you turned off your offloading? (ethtool -k)
I guess we could make it so the card did the ipfrags instead of  moloch

**Comment by TNogisto** [comment]
Suricata wants offloadings to be off. Would be better to just add the fix to the error. (ethtool -i ethx -k plah plah)

**Comment by awick** [comment]
done
