### ISSUE TITLE
when I import the offline pcap contain large number of DNS protocol session ,the memory up until all the memory of machine ,then crash.

### ISSUE THREAD

**Issue by ghost** [aol/moloch#455]
when I import the offline pcap contain large number of DNS protocol session ,the memory up until all the memory of machine ,then crash.I don't know why ,And I try to configure the dbBulkSize more and run more elasticsearch node,but not work.

**Comment by awick** [comment]
What version of moloch and ES?

**Comment by paopao0** [comment]
es version is 1.7.3 ,moloch version is 0.12.3-GIT

**Comment by awick** [comment]
I fixed a memory issue in the latest 0.14.0-GIT builds.  Can you try that one?  Would it be possible to share a pcap file to andywick @ gmail?

**Comment by paopao0** [comment]
thank you!!!   
I'll try.
yesterday I install the master version at another machine.
After waiting for my manager to agree,I'll share a pcap file to  you

**Comment by paopao0** [comment]
when i use the master version and import the same pcap .I Encountered this problem
Apr  1 17:59:10 reader-libpcap-file.c:330 reader_libpcapfile_pcap_cb(): ERROR - Moloch requires full packet captures caplen: 98 pktlen: 102,what's wrong with me??

**Comment by awick** [comment]
It means when someone captured the packet they didn't capture the whole then.  If using tcpdump make sure you use -s 0

**Comment by paopao0** [comment]
i use the same offline pcap, but the version 0.12.3-GIT is work.

**Comment by awick** [comment]
Correct, 0.12.3 didn't enforce it, and would have incorrect results when the whole packet wasn't capture.

**Comment by paopao0** [comment]
I have sent one pcap to your gmail.thanks

**Comment by awick** [comment]
It looks like the whole packet is there, but the tool that is writing the pcap to disk for you is adding 4 bytes to the pktlen instead of making it the same as caplen.  What tool are you using to write the pcap?  Can it be fixed?

I guess I can add an option to moloch to zero fill missing bytes and try and process the packets anyway if you can not fix the writing tool.

**Comment by paopao0** [comment]
I can't modify the tool. The best is that we can configure it in config.ini and default is 0.

**Comment by awick** [comment]
Added readTruncatedPackets config option in 44ae60fc222aa0dcfb50a7ae989232046dae3bd1

**Comment by awick** [comment]
does it work?

**Comment by awick** [comment]
reopen if still an issue
