### ISSUE TITLE
can't see the detail of the sessions

### ISSUE THREAD

**Issue by benxiaohaiairs** [aol/moloch#460]
**Elasticsearch version**:1.7.3

**Moloch version**:0.14.0

**OS name and version**:centos7

I can't see the detail information of the sessions when I import offline pcap.but the pcap I capture I can

**Comment by awick** [comment]
Check permissions on the file, make sure nobody (or whatever dropUser is) can read the files and directories the file is in.

**Comment by benxiaohaiairs** [comment]
I can import the offline pcap and see every sessions in browser.but I can't see the detail information of the sessions

**Comment by awick** [comment]
I don't understand and you didn't answer the question

1) Can you see the SPI data?
2) Can you see the pcap data?
3) If you CAN see SPI data but you CAN'T see pcap data, then did you check the file permissions?
4) Are you deleting the pcap files after you import them?  If so you must use the --copy option

**Comment by benxiaohaiairs** [comment]
1)I can see the SPI data 
2)I can see the pccap data 
3)
![image 3](https://cloud.githubusercontent.com/assets/18390583/14447674/785cc020-0094-11e6-95f0-e0f80b38fd80.png)
I can't  see the red zone of the picture

**Comment by awick** [comment]
The red zone?  You mean the bottom part where it says "GET /aol/moloch"?  That is the pcap, so I'm confused.

Can you answer question 3 and 4.

**Comment by awick** [comment]
If you don't see the "Start: ... Stop: ... Node: ..." stuff, then that is the SPI data.  What do you see there?
