### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by benxiaohaiairs** [aol/moloch#461]
**Elasticsearch version**:1.7.3

**Moloch version**:0.14.0

**OS name and version**:centos7

when I import offline pcap the moloch_capture Occupied memory until the machine crashed.what shuld I do ?

**Comment by awick** [comment]
The machine crashes or moloch crashes?
Can you please send a gdb back trace https://github.com/aol/moloch/wiki/FAQ#Moloch_capture_crashes
If possible send the pcap to andywick @ gmail

**Comment by benxiaohaiairs** [comment]
The machine

**Comment by awick** [comment]
Are you getting a kernel crash?  Have you turned swap off?  How much memory does the machine have?  Can you send me the pcap?

**Comment by benxiaohaiairs** [comment]
1.I'm get kernel crash
2.I'm turned swap on
3.The machine have 48G
4.The pcaps I import more than 100G

**Comment by awick** [comment]
What kernel are you using?
Turn swap OFF
You may want to run memtest on your machine

**Comment by benxiaohaiairs** [comment]
1.kernel  is Linux version 3.10.0-229.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Fri Mar 6 11:36:42 UTC 2015
2.I'll try it
