### ISSUE TITLE
config.ini prefix

### ISSUE THREAD

**Issue by yogch** [aol/moloch#462]
**Elasticsearch version**: 1.7.3

**Moloch version**: 0.14.0

**OS name and version**: ubuntu 14.04

**Provide logs, stack traces and steps to reproduce**: 

> Apr 13 14:29:15 db.c:1560 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"

Hi,
I added the `prefix` option to the `config.ini` and the capture doesn't work with the following log.
I `init`ed and `wipe`d the ES data.

config.ini:
prefix=prefix1

These are the indices using
`GET _cat/indices?v`

![image](https://cloud.githubusercontent.com/assets/13855845/14496983/da2f694c-019d-11e6-8a43-bbdc8c7017d4.png)

I have the Marvel pugin. I can remove if necessary.

**Comment by awick** [comment]
need to use ./db.pl --prefix host:port init

**Comment by yogch** [comment]
Ok, I did it and now I encounter a small issue:

1. When I `./db.pl --prefix host:port init` it doesn't delete the old indices. As you can see, this is the index status after `init`ing with `--prefix`.
![image](https://cloud.githubusercontent.com/assets/13855845/14519845/0880cff2-022a-11e6-8f9d-7f607b7b4ba0.png)

I overcome this with erasing manually all data from ES, and then `init`ing with `--prefix`. After this, the index stratus is as desired (I guess):
![image](https://cloud.githubusercontent.com/assets/13855845/14519891/3b25c6e2-022a-11e6-9626-1a0fd3aa10d5.png)

**Comment by awick** [comment]
The whole point of --prefix is to have MUTLIPLE Moloch Clusters on a single ES Cluster.  You wouldn't want it to delete anything.  That would be very bad.

You could do a feature request for a db.pl delete command if you want.

**Comment by yogch** [comment]
Ok thanks!
