### ISSUE TITLE
Captured packets out of order in pcap file

### ISSUE THREAD

**Issue by discoduck2x** [aol/moloch#463]
**Elasticsearch version**:

**Moloch version**: 0.12.0

**OS name and version**: Centos 7

**Provide logs, stack traces and steps to reproduce**:

Packets are not saved into the pcap file(s) in correct order , this is observed on a very low rate of packets and no packets show up as dropped and no errors on any switchports etc.
Traffic is coming via cisco span session and when sent/spanned at the same to to another switchport host interface (windows box) which just runs wireshark - there the packets are in the correct order.

Incorrect order observed on Moloch capture - packet no 7 which is a TCP ACK of packet 8 arrives before the data packet:
![image](https://cloud.githubusercontent.com/assets/12600004/14560091/a5758774-030d-11e6-9301-7aa9b84afe80.png)

Correct order of packets - captured at the same time on a windows box, packet 7 is the data, and 8 is the ACK:
![image](https://cloud.githubusercontent.com/assets/12600004/14560110/cbfe3ca6-030d-11e6-87da-85c57264ca28.png)

I have tried the ethtool tweaks to disable offloading etc, but no difference

**Comment by awick** [comment]
Not sure, libnids controls the order in 0.12, interesting that they are the same timestamp.  Maybe the packets are getting fragmented.  0.14 and later is not libnids based anymore and we have some control.  Anyway, won't "fix" for 0.12, feel free to open for 0.14 if you see the same thing.
