### ISSUE TITLE
0.14 Captured packets out of order in pcap file - reopen of #463

### ISSUE THREAD

**Issue by discoduck2x** [aol/moloch#465]
**Elasticsearch version**:  1.7.3

**Moloch version**: 0.14.0

**OS name and version**: centos 7 minimal

**Provide logs, stack traces and steps to reproduce**:

Reopen of #463 

Packet no 9 is TCP ACK of data packet no 10 , thus should not be possible to arrive before data.
![image](https://cloud.githubusercontent.com/assets/12600004/14606073/e0e22810-057b-11e6-8111-1e434792a7cb.png)

Same cisco SPAN session another destination host (windows box running wireshark)
Packet 10 - the TCP ack above arrives in the correct order.
![image](https://cloud.githubusercontent.com/assets/12600004/14606134/11d1d510-057c-11e6-8095-0144b765cae1.png)

Is there anything else to try? possible centos issue? Im running same centos image on same hardware where packet rates succeeds 100k per second (multicast data) and no gapping is occurring there so for me it feels like an issue with capture and not the box itself. 

It is easybutton-singlehost instance but the rate of packets are really not high. No drops observed anywhere on switchports or host interfaces.

**Comment by awick** [comment]
Is this actually causing an issue, or are you just worried?

If its easy to reproduce can you run a tcpdump on the same box as moloch and compare?

**Comment by awick** [comment]
Forgot to point out that at least with this one the timestamps are different, which means it isn't a moloch issue, we just use the libpcap timestamp.  Are you sure you've turned off all offloading on your network card?  (ethtool -k)

**Comment by discoduck2x** [comment]
@awick 

Ive ran tcpdump simultaneously on the centos box and same thing. if used pfring aswell and same behaviour.

The issue is that im using moloch to verify latency spotted in our applications layer a - thus im downloading a segment from moloch and chewing it through some LUA script which parses our internal protocol but as packets are ordered incorrectly it becomes a problem so either i have to adapt the LUA parser to ignore this (might be easy) but still if i cant trust the pcap data on this level (seems ONLY to be TCP`ACKS which gets ordered incorrectly) then i dont know where to start if problems show later down the road..

**Comment by discoduck2x** [comment]
@awick 
Think if disabled what i can:

Features for ens1f1:
rx-checksumming: off
tx-checksumming: off
        tx-checksum-ipv4: off
        tx-checksum-ip-generic: off [fixed]
        tx-checksum-ipv6: off
        tx-checksum-fcoe-crc: on [fixed]
        tx-checksum-sctp: off
scatter-gather: off
        tx-scatter-gather: off
        tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: off
        tx-tcp-segmentation: off
        tx-tcp-ecn-segmentation: off [fixed]
        tx-tcp6-segmentation: off
udp-fragmentation-offload: off [fixed]
generic-segmentation-offload: off
generic-receive-offload: off
large-receive-offload: off [requested on]
rx-vlan-offload: on
tx-vlan-offload: on
ntuple-filters: off
receive-hashing: on
highdma: on [fixed]
rx-vlan-filter: on
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: on [fixed]
tx-gre-segmentation: off [fixed]
tx-ipip-segmentation: off [fixed]
tx-sit-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-mpls-segmentation: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: on
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
busy-poll: on [fixed]

**Comment by awick** [comment]
can you join freenode <code>#moloch-fpc</code>?  would be faster.

So just to confirm on the moloch host, both moloch and tcpdump (when capturing the same traffic) show the same out of order packets?

Are you using vlans?  if so we should get rx-vlan-offload turned off.

**Comment by discoduck2x** [comment]
did a clean install of centos 7 , same issue with tcpdump so will continue to try find reason but ints not moloch related in any way @awick

**Comment by discoduck2x** [comment]
@awick 
after having tried both centos & ubuntu, ixgbe driver from sourceforge, toe off , irqbalance on/off same issue remains.

Installed w2012 on the same box and wireshark 2.0.2 - and it works flawlessly. So nothing is wrong with my hardware/host/span setup.

Im just guessing but feels like its something with ixgbe driver and affinity/numa nodes filtering etc
there´s a few posts about issues similar where rx drops are noted on the interface, but the solutions suggested there havent worked.

Just a shame i cant get it to work coz right now it looks like i have to stop using moloch as primary capture option.
