### ISSUE TITLE
Elasticsearch-2.3.1 integration

### ISSUE THREAD

**Issue by Nevyn579** [aol/moloch#468]
I made the changes to the easybutton-singlehost.sh, ES config, and run_es.sh files.  How do I upload for your review?

**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
Create a pull request  https://help.github.com/articles/using-pull-requests/

Basically
* fork
* create a branch with changes
* create pull request
