### ISSUE TITLE
how can I see the session detail information when the pcap in the another mechine

### ISSUE THREAD

**Issue by benxiaohaiairs** [aol/moloch#469]
**Elasticsearch version**:1.7.3

**Moloch version**:0.14.0

**OS name and version**:centos7

**Provide logs, stack traces and steps to reproduce**:

can I see detail information of the seesion whwn the pcap in another mechine.
I can only see the session detail in localhost.
![_sjsh4gnv0 _5mw0 f 0t0u](https://cloud.githubusercontent.com/assets/18390583/14918490/c81742b4-0e56-11e6-8f25-8ee2a6f53528.png)

**Comment by awick** [comment]
All the nodes need to talk to the same ES cluster.  You need to set a FQDN for the box that isn't localhost.

Look at  https://github.com/aol/moloch/wiki/FAQ#Error_Couldnt_connect_to_remote_viewer_only_displaying_SPI_data
