### ISSUE TITLE
can't see the detail of sessions when the files store in oher node

### ISSUE THREAD

**Issue by benxiaohaiairs** [aol/moloch#470]
**Elasticsearch version**:1.7.3

**Moloch version**:0.14.0

**OS name and version**:centos7

**Provide logs, stack traces and steps to reproduce**:
For example I import offline pcap at 2 mechines,the ip is 192.168.1.1 and 192.168.1.2.
viewer run in 192.1681.1. I can see the sessions detail information form 192.168.1.1,but I can't see the sessions detail information form 192.168.1.2.
what should I do??

**Comment by awick** [comment]
You should get an error either in the logs or on screen?

Without any information this might help
https://github.com/aol/moloch/wiki/FAQ#Error_Couldnt_connect_to_remote_viewer_only_displaying_SPI_data
