### ISSUE TITLE
XSS Vulnerability in Sessions Page

### ISSUE THREAD

**Issue by OpenMalScan** [aol/moloch#471]
**Elasticsearch version**: 1.7.3

**Moloch version**: 0.14.0

**OS name and version**: Centos 6.7

It seems that the sessions page in Moloch viewer contains a reflected XSS vulnerability. The length parameter accepts unvalidated input and causes a vulnerability. An example url is shown in following image :

![image](https://cloud.githubusercontent.com/assets/18718422/15144241/d95c3a6c-16b6-11e6-9b7e-08495182b30c.png)

After visiting this url, if the "Export PCAP" menu item is clicked, the javascript code is executed.

**Comment by awick** [comment]
thanks!
