### ISSUE TITLE
Add more columns to toggle

### ISSUE THREAD

**Issue by awick** [aol/moloch#472]
Would be nice to have more columns to toggle on and off
vlan

**Comment by amaddalena** [comment]
- Tags (when a flow has been tagged)
- FQDN from the info field into its own column
- http.response.code (20x etc)
- protocols (mysql, ssh, etc)
- "User" when detected in SPI data (such as mysql user, http basic auth user, smb user, kerb user, etc)

**Comment by awick** [comment]
0.17 newUI supports any column now.
