### ISSUE TITLE
Problem installing with easybutton-singlehost

### ISSUE THREAD

**Issue by andyv88** [aol/moloch#473]
Easybutton-singlehost. installation fails on Elasticsearch install.

Error:
[INFO  ] [bootstrap             ] es.config is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.

Elasticsearch then fails to start and we are then caught in loop attempting to conncect.

**Elasticsearch version**:  2.3.2

**Moloch version**:  Current

**OS name and version**:  Ubuntu 14.04

**Provide logs, stack traces and steps to reproduce**:

**Comment by AndyDandy321** [comment]
Before installation, edit run_es.sh in the moloch single-host/bin directory and change line 12 to
ES_HEAP_SIZE=ESMEM bin/elasticsearch -Des.insecure.allow.root=true -d
This will both allow the ES 2.3.2 to run (the config location generates an error and is unnecessary for ES 2.x and address the issue of being unable to run ES with root privileges as the easybutton-singlehost.sh is supposed to be run.

**Comment by awick** [comment]
Ya easy button still needs some work to deal with 2.3.2.  I'm tempted to just throw it away, causes more problems then its worth.

**Comment by awick** [comment]
I went back to 2.2.2 since that is what we use in prod still and I've redone the scripts to be closer to what we actually use in prod, should hopefully work now.

**Comment by andyv88** [comment]
Andy,

Thank you so much for your quick response to this issue.   I have retried
the installation with the current source and the install completed without
error.

AndyV.
