### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by cpitscheider** [aol/moloch#474]
Hi,

I am unable to install Moloch.

I have clean Ubuntu 12.04.5 VM with openjdk-7-jdk and all the latests packets from the repository. 
I have cloned the latest git and started the easybutton-singlehost.sh script.

I get an error during the installation of some NPM packets (see error log: npm-debug.txt)

Christian

[npm-debug.txt](https://github.com/aol/moloch/files/268173/npm-debug.txt)

**Comment by AndyDandy321** [comment]
Before installation, edit run_es.sh in the moloch single-host/bin directory and change line 12 to
ES_HEAP_SIZE=_ESMEM_ bin/elasticsearch -Des.insecure.allow.root=true -d
This will both allow the ES 2.3.2 to run (the config location generates an error and is unnecessary for ES 2.x and address the issue of being unable to run ES with root privileges as the easybutton-singlehost.sh is supposed to be run.

**Comment by awick** [comment]
I don't see any errors, did you upload a gist?

**Comment by cpitscheider** [comment]
Sorry, there when something wrong with the file upload.

I have updated the comment: [npm-debug.txt](https://github.com/aol/moloch/files/268173/npm-debug.txt)

**Comment by awick** [comment]
Not really sure.  You could try 
cd /data/moloch/viewer
rm -rf node_modules
npm install

**Comment by cpitscheider** [comment]
The /data/moloch/viewer folder has not yet been created.

I got the error in the /data/moloch/wiseService folder.
When deleting the node_modules folder in wiseService i get a different type of error:
[npm-debug.txt](https://github.com/aol/moloch/files/269748/npm-debug.txt)

**Comment by awick** [comment]
Does your company break ssl?  If so you might need to add the company cert to some keystore or tell npm to ignore cert validation. 

 http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more

**Comment by awick** [comment]
reopen if you have more info
