### ISSUE TITLE
capture crash

### ISSUE THREAD

**Issue by aviadr** [aol/moloch#475]
**Elasticsearch version**:
1.7.3
**Moloch version**:
0.14.0-GIT"
**OS name and version**:
Ubuntu 14.04
**Provide logs, stack traces and steps to reproduce**:
from syslog:
May 17 02:41:40 master1 kernel: [2467986.223187] traps: moloch-capture[32722] trap divide error **ip:453ad7** sp:7fff0337ad30 error:0 in moloch-capture[400000+37b000]

May 17 02:49:25 master1 kernel: [2468450.552743] init: molochcap main process (32722) **killed by FPE signal**
May 17 02:49:25 master1 kernel: [2468450.552762] init: molochcap main process ended, respawning

I run addr2line:
addr2line -e /opt/moloch/bin/moloch-capture 453ad7
/srv/jenkins/workspace/moloch-develop/git_repository/moloch/capture/**db.c:1243**

the code is:
int json_len = snprintf(json, MOLOCH_HTTP_BUFFER_SIZE,
        "{"
        "\"ver\": \"%s\", "
        "\"nodeName\": \"%s\", "
        "\"hostname\": \"%s\", "
        "\"interval\": %d, "
        "\"currentTime\": %" PRIu64 ", "
        "\"freeSpaceM\": %" PRIu64 ", "
        "\"freeSpaceP\": %.2f, "
...

there was also crash file
![image](https://cloud.githubusercontent.com/assets/18512600/15361306/901e8648-1d19-11e6-92e8-12ee44dc20b8.png)

**it seams like diffms is zero**

![image](https://cloud.githubusercontent.com/assets/18512600/15361356/c0a26064-1d19-11e6-8b46-bddaf35a200a.png)

![image](https://cloud.githubusercontent.com/assets/18512600/15361419/147c399e-1d1a-11e6-9755-13d3cc215dba.png)

so 
diffusage*10000/diffms

will cause SIGFPE

**Comment by awick** [comment]
Thanks!

Out of curiosity what tool is that?

**Comment by aviadr** [comment]
I opened the dump file with eclipse CDT (C/C++ Postmortem Debugger)
