### ISSUE TITLE
Viewer process crashes with header error when expanding session

### ISSUE THREAD

**Issue by DataSquid** [aol/moloch#480]
moloch v0.14.1-GIT.  I built an easybutton-singlehost off main after the last commit yesterday, May 31st on an Ubuntu 14.04 box.

After letting it soak overnight, I returned to the Sessions page and attempted to expand one of the entries.  Doing so results in the error in the GUI:  `Couldn't look up SPI data, error for session 160601-KgdWT5FxSNNFxLvgJU6DvBl5 Error: Error loading data for session 160601-KgdWT5FxSNNFxLvgJU6DvBl5
`
And the viewer process exits.

Checking the viewer.log I see the GET and this trace:

```
http.js:724
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:724:11)
    at ServerResponse.header (/data/moloch/viewer/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/data/moloch/viewer/node_modules/express/lib/response.js:163:12)
    at /data/moloch/viewer/viewer.js:3065:18
    at /data/moloch/viewer/viewer.js:2771:18
    at /data/moloch/viewer/viewer.js:2656:9
    at /data/moloch/viewer/pcap.js:157:16
    at Object.wrapper [as oncomplete] (fs.js:466:17)
```

This seems to be reproduceable for every session captured so far.  Tested in Chrome and IE.

**Comment by awick** [comment]
Possibel to send me a pcap at andywick @ gmail?

**Comment by awick** [comment]
I think the crash is fixed, but not the problem.  If I assume you are using a central viewer, it seems like the central viewer can talk to ES but the capture node viewer can't, maybe config issue?
