### ISSUE TITLE
PCAP Search and Tag

### ISSUE THREAD

**Issue by awick** [aol/moloch#485]
Make it possible to schedule a pcap search job that searches all pcap that matches an expression that then tags the session with a user supplied tag.  Would be nice if position is somehow recorded also.  Also need UI to see current searches, and maybe make it smart enough to not search the same thing again.  Should be possible with cron too.

**Comment by jlongman** [comment]
I used to work at a company that made internet acceleration appliances.  I tried to pitch moloch as a PCAP database - I still don't know why it didn't catch, hand-to-mouth at the time, no IT bandwidth - and being able to tag, especially based on searches, would have been useful.

E.g. we accelerated tunnelled traffic, so tags like the tunnelling tech, and then contained traffic - e.g. HTTP, VOIP, etc. - to say nothing of our options - would have allowed QA to find candidates for replay or even lead back to customers with/using those tech.
