### ISSUE TITLE
dontSaveBPFs doesn't seem to actually do anything

### ISSUE THREAD

**Issue by ehmiller** [aol/moloch#486]
**Elasticsearch version**: 2.3.3

**Moloch version**: 0.14.2

**OS name and version**: Ubuntu 12.04 (also tried on an easybutton single host on 14.04)

**Provide logs, stack traces and steps to reproduce**: Not sure this is applicable, let me know what you'd like

I've been trying to get dontSaveBPFs to work, and the result is not as expected.  I've tried variations such as the following:
dontSaveBPFs=port 443:5
dontSaveBPFs = port 443:5
dontSaveBPFs=(tcp and port 443):5

In each case, after restarting the capture process, I will capture streams on 443 all the way up to the 10000 packet limit.  This could be user error, but it seems that I'm following the Settings documentation perfectly.

**Comment by awick** [comment]
How are you checking?  dontSaveBPFs keeps all the SPI data (including packet counts) it just doesn't save the pcap to disk after ~5 packets (in this case).

If you open the session or download the pcap it should only have the ~5 packets.

**Comment by ehmiller** [comment]
That was my thought as well, but if I view the stream I see a ton of data, and if I download the pcap and open it, it does _actually_ have 10000 packets.  Recently I've tried it by adding other ports as well, such as 22 and 80, but it just goes right on capturing the whole session for any of them.

**Comment by awick** [comment]
What reader are you using, or just the default?

I just tried
dontSaveBPFs=port 22:10

with master and it saved 9 packets for each session while the count was in the 10s or 100s.

**Comment by ehmiller** [comment]
Just the default, then I'm downloading the session pcap and opening in Wireshark.

**Comment by awick** [comment]
Can you run moloch-capture with --debug and make sure you see a line like

Jun 10 07:33:21 config.c:120 moloch_config_str_list(): dontSaveBPFs=port 22:10

If you don't then you might have it in the wrong [section]

**Comment by ehmiller** [comment]
Yes -- here it is:
Jun 10 07:37:22 config.c:120 moloch_config_str_list(): dontSaveBPFs=port 443:10

**Comment by justinknox** [comment]
I'm seeing some similar results.
I've built a test VM with ubuntu 16.04 server, elasticsearch 2.3.3, moloch 0.14.2-master (cloned yesterday).
moloch-capture --debug shows:
Jun 10 08:18:20 config.c:120 moloch_config_str_list(): dontSaveBPFs=port 443:5

Since making that configuration change, I see inconsistent results. some pcaps are clearly truncated at 4 frames only, where others seem to be ignoring that setting entirely. I have confirmed that the manually run moloch-capture is the only one running.

**Comment by awick** [comment]
I just tried ubuntu 14.04 and it seems to work for me. :(

Anything special about the interface?  Can you email me your config.ini file?  andywick @ gmail

**Comment by ehmiller** [comment]
Sent you my config file -- it's pretty barebones.  Nothing really special about the interface -- it's an Intel X520 using the ixgbe driver.

**Comment by ehmiller** [comment]
Update: built a "latest and greatest" CentOS 7 (1511) machine and grabbed the latest git.  Ran easybutton-singlehost.sh and added dontSaveBPFs=port 443:10 to the [default] section of config.ini.  Started up capture and... was still grabbing 10000 packets of 443 sessions.  So now, multiple versions of Ubuntu, as well as CentOS... I guess it could be ixgbe, but that's _really_ common.

**Comment by awick** [comment]
Yes I can reproduce in production, but not in dev.  Is the traffic you are trying to drop vlan or gre?

It might be http://www.christian-rossow.de/articles/tcpdump_filter_mixed_tagged_and_untagged_VLAN_traffic.php  although I can't get their solution to work either.

I'm trying 
dontSaveBPFs=tcp port 443 or (vlan and tcp port 443):10
but that doesn't seem to work either.  Its definitely not matching the bpf filter, which I'm trying to learn more about. :)

**Comment by ehmiller** [comment]
It **is** vlan traffic. :) I figured that could be an issue but couldn't exactly figure out **how** it would be causing the issue.
Side-note:  This issue aside, moloch is about this coolest thing I've seen in years!

**Comment by awick** [comment]
ok it does work for, i changed too many things when testing :).  give this a shot
dontSaveBPFs=tcp port 443 or (vlan and tcp port 443):10

**Comment by ehmiller** [comment]
and... it works!  :-D This is awesome!

**Comment by awick** [comment]
great, FAQ added

**Comment by HaroldPoling** [comment]
I have this same issue and my server has 4 NIC's is there someone that can take a look at my config file?

Neither work for me

dontSaveBPFs=tcp port 443 or (vlan and tcp port 443):5
#dontSaveBPFs=vlan and tcp port 443:10

**Comment by awick** [comment]
Same problem as first reply above, must look at the pcap not the UI counts.
