### ISSUE TITLE
Feature Request: Extract ThreatStream "Source" Field to SPI Data

### ISSUE THREAD

**Issue by amaddalena** [aol/moloch#491]
Allow querying of threatstream "source" field from SPI data. 

**Current Extracted Fields:**
-  Confidence
-  Confidence Cnt
-  Id
-  Id Cnt
-  Malware Type
-  Malware Type Cnt
-  Severity
-  Severity Cnt
-  Type
-  Type Cnt

**Add Field**
-  "Source"

**Comment by awick** [comment]
added in 6ecbfcf0e7570b74af22b5d47b79296e6f1ee95c

**Comment by amaddalena** [comment]
thanks!
