### ISSUE TITLE
Base64 decode SPI view

### ISSUE THREAD

**Issue by amaddalena** [aol/moloch#494]
Would it be possible to add base64 decode as a right click integration in the SPI View?

**Comment by awick** [comment]
is cyberchef enough or do you want something else?

**Comment by amaddalena** [comment]
Something like the open in new session button would be nice for the base64 decode, maybe have it open into a cyberchef window? Ideally I would love for it to happen on the fly when a decode button is clicked within the session view pane without having to goto a new pane of glass. 

With basic auth we capture the BASIC string in front of the b64 encoded auth string within that field. I am not sure how feasible it would be to break the "BASIC" part of the http.authorization field out into a new field so the auth string is in its own field alone. After breaking it out being able to click something (like the XOR decode option) within the sessions view would be fantastic.

**Comment by awick** [comment]
got it.  so we will make it so you can register javascript functions to expressions that will add translations, kind of like how currently you can register urls

**Comment by awick** [comment]
With click of basic auth and cyberchef integration, I think this is done.  Feel free to open a new issue with new features
