### ISSUE TITLE
Allow pcapDir to be a template

### ISSUE THREAD

**Issue by awick** [aol/moloch#496]
th0ny on IRC asked pcapDir to be a template so could use subdirs based on timestamps.  In theory could use strftime or could invent our own if we want other things to be template-able.  Would need to make sure all the parent directories are created each time. Also need to figure out GMT vs local :(

**Comment by hillar** [comment]
-S <num>
          Allows to specify an additional directory sub hierarchy to store the
          data files. The default is 0, no  sub  hierarchy,  which  means  the
          files  go  directly  in  the base directory (-l). The base directory
          (-l) is concatenated with the specified sub hierarchy format to form
          the final data directory.  The following hierarchies are defined:
            0 default     no hierarchy levels
            1 %Y/%m/%d    year/month/day
            2 %Y/%m/%d/%H year/month/day/hour
            3 %Y/%W/%u    year/week_of_year/day_of_week
            4 %Y/%W/%u/%H year/week_of_year/day_of_week/hour
            5 %Y/%j       year/day-of-year
            6 %Y/%j/%H    year/day-of-year/hour
            7 %Y-%m-%d    year-month-day
            8 %Y-%m-%d/%H year-month-day/hour
