### ISSUE TITLE
Glib-WARNING in capture logs 

### ISSUE THREAD

**Issue by josh-lane** [aol/moloch#500]
**Elasticsearch version**:  ES 1.7.3

**Moloch version**:  0.12.1

**OS name and version**:  Ubuntu 12.04.5 LTS

**Provide logs, stack traces and steps to reproduce**:  Seeing an issue where suddenly the capture log files start to grow to over 100GB very rapidly and are filling up with the message below about 5 times a second which causes the system to become unstable:

**Glib-WARNING**:poll(2) failed due to: Invalid argument.**

This happens on multiple systems at random times when no configuration changes are made to Moloch deployment.  Only solution thus far has been to restart the capture but looking for more elegant solution.

**Comment by awick** [comment]
Unfortunately this is 5 versions behind.  Hopefully its been fixed.  I would try a newer version.
