### ISSUE TITLE
Incorrect number of indices being removed with db maint - w/hourly indices 

### ISSUE THREAD

**Issue by jbagel2** [aol/moloch#501]
**Elasticsearch version**: 2.3.3

**Moloch version**: v0.14.2

**OS name and version**: CentOS Linux release 7.2.1511

**Provide logs, stack traces and steps to reproduce**:

every morning looking at the data in the viewer the spi data is only available starting at 4:00am, so at 8:00am I only have about 4 hours worth of spi data. Through the day the spi data will build without issue. By the end of the day the I still have SPI data all the way back to 4:00am that same morning.

I currently have the db expire job set up to run every 2 hours to reduce the time to completion as the system is always under pretty heavy load. Was also testing if running more frequently would reduce the number of indices needing to be deleted each time. Noticing the expire logs the number of indices being deleted is not what I would expect when passing in 20 hours as the retaining number, and it checking every 2 hours. It seems once the time hits about 6:00pm, the number of indices being deleted seems to increase each check until it peaks at deleting 5 every 2 hours (which doesn't make sense to me). It then drops back down starting at about 6:00am. Now maybe this is just me not understanding how to properly configure the db script. If so please let me know what I need to do to correct.
```
db expire script:
------------
ESHOSTPORT=myremoteESServer:9200
RETAINNUMHOURS=20
echo "-------------------" >> /srv/moloch/db/daily.log
echo "$(date)" >> /srv/moloch/db/daily.log
/srv/moloch/db/db.pl $ESHOSTPORT expire hourly $RETAINNUMHOURS
-------------

here is snippet of the db expire job logs:

Mon Jul 11 14:00:01 MDT 2016
Optimizing Admin Indices

Expiring 0 indices, optimizing 10
-------------------
Mon Jul 11 16:00:01 MDT 2016
Optimizing Admin Indices

Expiring 0 indices, optimizing 12
-------------------
Mon Jul 11 18:00:01 MDT 2016
Optimizing Admin Indices

Expiring 1 indices, optimizing 13
-------------------
Mon Jul 11 20:00:01 MDT 2016
Optimizing Admin Indices

Expiring 4 indices, optimizing 11
-------------------
Mon Jul 11 22:00:02 MDT 2016
Optimizing Admin Indices

Expiring 5 indices, optimizing 9
-------------------
Tue Jul 12 00:00:01 MDT 2016
Optimizing Admin Indices

Expiring 5 indices, optimizing 7
-------------------
Tue Jul 12 02:00:01 MDT 2016
Optimizing Admin Indices

Expiring 5 indices, optimizing 5
-------------------
Tue Jul 12 04:00:01 MDT 2016
Optimizing Admin Indices

Expiring 5 indices, optimizing 3
-------------------
Tue Jul 12 06:00:01 MDT 2016
Optimizing Admin Indices

Expiring 3 indices, optimizing 3
-------------------
Tue Jul 12 08:00:01 MDT 2016
Optimizing Admin Indices

Expiring 1 indices, optimizing 4
```

**Comment by awick** [comment]
Ouch, thats a bad bug.  To fix quick change line 1778 of db.pl to

```return sprintf("${PREFIX}sessions-%02d%02d%02dh%02d", $t[5] % 100, $t[4]+1, $t[3], $t[2]);```

**Comment by jbagel2** [comment]
That fixed part of it, it still seemed to be ignoring the int value being passed in and locked to 12 indexes.  See the below fixes, that took care of all the issues for me. mktime seemed to be what was mucking up the @startTime value. Also the subtraction was trying to happen to the scalar not the array, and before the scalar was declared anyway. I would have just created a pull request but my fork is a little behind.

----------------------------------------------------
index 03f70c2..a10506e 100755
--- a/db/db.pl
+++ b/db/db.pl
@@ -39,6 +39,7 @@ use HTTP::Request::Common;
 use LWP::UserAgent;
 use JSON;
 use Data::Dumper;
+use Time::Local;
 use POSIX;
 use strict;
 
@@ -1988,19 +1989,19 @@ if ($ARGV[1] =~ /^users-?import$/) {
 
     my @startTime = gmtime;
     if ($ARGV[2] eq "hourly") {
-        $startTime[2] -= int($ARGV[3]);
+        @startTime[2] -= int($ARGV[3]);
     } elsif ($ARGV[2] eq "daily") {
-        $startTime[3] -= int($ARGV[3]);
+        @startTime[3] -= int($ARGV[3]);
     } elsif ($ARGV[2] eq "weekly") {
-        $startTime[3] -= 7*int($ARGV[3]);
+        @startTime[3] -= 7*int($ARGV[3]);
     } elsif ($ARGV[2] eq "monthly") {
-        $startTime[4] -= int($ARGV[3]);
+        @startTime[4] -= int($ARGV[3]);
     }
 
     parseArgs(4);
 
     my $optimizecnt = 0;
-    my $startTime = mktime(@startTime);
+    my $startTime = timegm(@startTime);
     while ($startTime <= $endTime) {
         my $iname = time2index($ARGV[2], $startTime);
         if (exists $indices->{$iname}) {

**Comment by jbagel2** [comment]
ended up with an issue on the above when the day rolled over. Have made a change to go a different direction so end of day/month will have issues in calculation.
