### ISSUE TITLE
FEATURE REQUEST - Dropping the SPI data being sent to ES

### ISSUE THREAD

**Issue by gilblg** [aol/moloch#505]
I'm using the tagger plugin, and interested in keeping only the specific data that is being tagged.
I'm interested in dropping unnecessary SPI data before it is being sent to ES during 'tagger_plugin_save' execution for a particular session.
Preferably, enable this option from within 'tagger_plugin_save' execution, by marking the session somehow, or use a special API.

In order to do so, I'd like to request to add the following feature to the plugins infrastructure - 
(1) API to mark a session as unwanted - "not to be saved to ES".
(2) this API could be used from within each plugin, in particular from 'tagger_plugin_save'

Thanks in advance

**Comment by awick** [comment]
Can use dontSaveSPI=1 now
