### ISSUE TITLE
Feature Request - Add TCP Flags to SPI 

### ISSUE THREAD

**Issue by BaconFries** [aol/moloch#506]
I'd like to be able to see is the tcp session flag count in the SPI data.  This would be useful in knowing if the session was not normal; such as only syn or reset flags.

**Comment by awick** [comment]
Can you give more details on what you want to see and how you would use it?  This kind of overlaps with #226 but we never did.

**Comment by BaconFries** [comment]
I was thinking to treat it the same way protocols are currently treated. Just a count of the flags seen during the session. 

syn(1), syn-ack(1), ack(18), push-ack(2), fin-ack(2)
