### ISSUE TITLE
Feature Request - Provide a View to Show Total Traffic Per Hour/Day/Week/etc

### ISSUE THREAD

**Issue by jwilczek** [aol/moloch#507]
To help identify issues with the network collection itself as well as identify anomalies in traffic flow, it would be helpful to have a view (maybe on the Stats page) that shows the total number of bytes/megabytes/gigabytes collected by hour/day/week/etc (both of these options would be user configurable).

This data is almost available through the web frontend now, but the aggregation of bytes by different ranges doesn't appear to be possible.

Thank you!

Josh

**Comment by bientt210** [comment]
is this resolved, everyone?

**Comment by awick** [comment]
You can use Kibana for these kind of stats.
