### ISSUE TITLE
NPM Error while installing

### ISSUE THREAD

**Issue by SuchitV** [aol/moloch#508]
Installing from scratch and I'm getting the following error.

> hashtable@0.5.3 install /data/moloch/wiseService/node_modules/hashtable
> node-gyp configure build

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at Object.afterConnect [as oncomplete] (net.js:896:19)
gyp ERR! System Linux 2.6.32-642.3.1.el6.x86_64
gyp ERR! command "node" "/data/moloch/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /data/moloch/wiseService/node_modules/hashtable
gyp ERR! node -v v0.10.45
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 2.6.32-642.3.1.el6.x86_64
npm ERR! argv "/data/moloch/bin/node" "/data/moloch/bin/npm" "update"
npm ERR! node v0.10.45
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! hashtable@0.5.3 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashtable@0.5.3 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the hashtable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hashtable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls hashtable
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/moloch/wiseService/npm-debug.log
make[2]: *** [install] Error 1
make[2]: Leaving directory `/home/drifter/moloch/capture/plugins'
make[1]: *** [installdirs] Error 2
make[1]: Leaving directory `/home/drifter/moloch/capture'
make: *** [install-recursive] Error 1
ERROR - 'make install' in moloch directory failed

**Comment by awick** [comment]
Maybe you don't have a c++ compiler installed?
You've tried multiple times? (sometimes npm is flakey)
Is the machine on the internet?
What OS?

**Comment by SuchitV** [comment]
I have the following; the machine is on the internet but its limited access due to company policy. However; 443 and 80 access has been granted to registry.npmjs.org and I have attempted this multiple times.
gcc-c++.x86_64  4.4.7-17.el6 @rhel-x86_64-server-6
Red Hat Enterprise Linux Server release 6.8 (Santiago)

**Comment by awick** [comment]
Sorry I don't really know.  I just tried on a 6.8 machine and it worked fine.  There might be a debug log there.

**Comment by SuchitV** [comment]
not sure why npm wouldn't install hashtable but I downloaded the package and placed the directory in /data/moloch/wiseService/node_modules/ and that seemed to work.
