### ISSUE TITLE
Couldn't look up SPI data, error for session

### ISSUE THREAD

**Issue by wlayzer** [aol/moloch#509]
Hello, I have done everything right and double-check everything, but in viewer I get this error.
"Couldn't look up SPI data, error for session 16072 Error: Error loading data for session 16072"
This is the line from viewer.js where the error comes from and I don't undestand it.
```
if (err && session === null) {
      return res.end("Couldn't look up SPI data, error for session " + req.params.id + " Error: " +  err);
    }
```
Thanks for your help

**Comment by TNogisto** [comment]
Do you have a singlehost or a multihost enviroment?
Usually those errors are caused by incorrect server clocks.

**Comment by wlayzer** [comment]
The problem has been solved, I was listening to a vlan, where the problem came from,

**Comment by whitetiger21022014** [comment]
Hi,
Couldn't look up SPI data, error for session ...   Error: Error loading data for session ...

When clients access to websites via open proxy,  https://zend2.com/ ,  **uncheck:  Allow Cookies**

![cookies_tmp](https://cloud.githubusercontent.com/assets/22853600/19917207/a541d79c-a0f3-11e6-8c30-ffecbb5dd27a.png)

**Comment by fofo13** [comment]
I have the same problem! 

Couldn't look up SPI data, error for session 170512-WfdfdfdfdjfdsjfdhjfsdkfdFVr Error: Error loading data for session 170512-dsjkdsdsasssjsad
