### ISSUE TITLE
Feature Request -- Export Info Field

### ISSUE THREAD

**Issue by SuchitV** [aol/moloch#511]
It would be helpful if we could export the "Info" field as well in the CSV. So when someone asks to see DNS requests to specific domains or specific URI/URLs those can be provided along with the Source/Destination IP info.

Thank you,

Suchit

**Comment by 31453** [comment]
This has been implemented. The csv now contains the columns that are displayed in the sessions table. So, if the info column is present when exporting the csv, all the fields that are displayed in the info column will be in the csv. 

Please let me know if this does not address your issue.
