### ISSUE TITLE
elasticsearch ssl problem

### ISSUE THREAD

**Issue by qinyz** [aol/moloch#517]
**Elasticsearch version**:2.3.3
**Moloch version**:0.14.1
**OS name and version**:Ubuntu 14.04

error: 
http.c:190 moloch_http_send_sync(): libcurl failure https://*.*.*.*:9200/dstats/version/version/_source error 'Peer certificate cannot be authenticated with given CA certificates'

how to use self-signed certificate?

**Comment by TNogisto** [comment]
option no1:
make your Ubuntu machine trust your CA.

This might help you with it:
http://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu

option no2:
get trusted certificates :) . 

option no3:
use http (bad option).

There might be (and probably are) some others, but these seem the most logical to me.

**Comment by qinyz** [comment]
ths
