### ISSUE TITLE
New Feature Request - Disable PCAP download in viewer

### ISSUE THREAD

**Issue by SUBRON6** [aol/moloch#519]
It would be helpful to be able to control the ability to download PCAP on a per user basis

**Comment by eoinmiller-sfdc** [comment]
Interesting. Would you also want to stop the display of the session/packet contents through the viewer?

**Comment by SUBRON6** [comment]
If possible yes but if so can we split that out into 2 separate controls?

**Comment by awick** [comment]
added to #957
