### ISSUE TITLE
replace iptrie for WiSE

### ISSUE THREAD

**Issue by awick** [aol/moloch#526]
Not supported by recent versions of node, maybe https://github.com/kotarou3/node-ip-router will work?

**Comment by awick** [comment]
don't need to do, there is a new version

**Comment by matoro** [comment]
@awick Hi, iptrie is again broken under recent versions of node (v10+), I have created a small patch at https://github.com/matoro/iptrie which gets it to compile though I haven't run integration tests to see if it works yet.

**Comment by awick** [comment]
Yes we will be moving to node 10 for moloch 2.0.  Your github link doesn't work.

**Comment by matoro** [comment]
@awick woops, shouldn't have typed that from memory.  I haven't checked to make sure the fix actually works beyond compiling, but if so feel free to fork so that you're not just pulling a tarball from some random repo.

**Comment by 31453** [comment]
Looks like iptrie is working for WISE
