### ISSUE TITLE
How to not write PCAP

### ISSUE THREAD

**Issue by SUBRON6** [aol/moloch#528]
May sound a bit crazy but we would like to keep the metadata and be able to not write the PCAP to disk.  An ideal solution would be an ini file change and a capture restart to enable or disable recording PCAP on demand.

Thoughts?

**Comment by awick** [comment]
Use the dontSaveBPFs feature with :1

https://github.com/aol/moloch/wiki/Settings#basic-settings

**Comment by SUBRON6** [comment]
awesome thank you

**Comment by SUBRON6** [comment]
Tested that out and we don't see anything in SPI data.  We still want it to parse the data and write to ES, we just don't want it to write PCAP to disk.

**Comment by awick** [comment]
Yep thats what it should do.  Can you share what you used.

**Comment by SUBRON6** [comment]
"dontSaveBPFs = :1"
so any way to still have it index all the packets and simply not write the PCAP to disk?

**Comment by awick** [comment]
Thats not a valid bpf

**Comment by SUBRON6** [comment]
OK, do you have one we can test?  Or do we need a port X:1 for every port we want to drop?

**Comment by awick** [comment]
not off the top of my head, man tcpdump or man bpf

**Comment by SUBRON6** [comment]
Then would this be a feature request?  We have a specific use case where the search-ability in Moloch is very useful but we do not need to write the PCAP to disk.  In order for that to work we still need Moloch to parse the traffic and write to ES

**Comment by awick** [comment]
this is what dontSaveBPFs is for.

**Comment by jescar50dx** [comment]
Try pcapWriteMethod=null

**Comment by SUBRON6** [comment]
OK we will test both

**Comment by awick** [comment]
yep that will definitely work if you never want to record anything, dontSaveBPFs allows you to control what you record and don't.

**Comment by SUBRON6** [comment]
Null seems to be working the way we wanted so thank you very much, this is promising

**Comment by awick** [comment]
So looking at the code dontSaveBPFs requires 1 packet to be saved, so :2 would work but would save the first packet of each session, not what you want.  null may give you some weirdness in viewer.

**Comment by SUBRON6** [comment]
So if we need to use BPF then we would need to identify every port that we want to not save so that it does parse the traffic first?

**Comment by awick** [comment]
no, something like "ip:2" would work

**Comment by SUBRON6** [comment]
OK, will try that out

**Comment by SUBRON6** [comment]
we have this in the ini file right now and we see capture run and consume all available RAM until it runs out and capture stops.  No errors in the logs though with debug logging enabled
dontSaveBPFs = ip:2;ip6:2;arp:2;udp:2;icmp:2;icmp6:2

**Comment by SUBRON6** [comment]
testing a few combinations and noticed that with the filter I posted  in place but write method null the memory consumption did not appear to be an issue.   Also noticed that with the filter in place and write method simple the disk queue numbers steadily climbed but we did not see the same queue numbers in iostat

**Comment by awick** [comment]
So probably should move this to a new issue, or even better might be to head over to slack.

Did you try the dd command from the FAQ?  https://github.com/aol/moloch/wiki/FAQ#What_kind_of_packet_capture_speeds_can_molochcapture_handle
