### ISSUE TITLE
Multiple capture crashes on Centos 6.6

### ISSUE THREAD

**Issue by cbboggs** [aol/moloch#539]
Capture seemed to be stable for quite some time, but lately we are experiencing random crashes at odd times throughout the day.  Wasn't a big deal but we had 3 in short succession (about a 30 min window) today, and I finally got core dumps working properly.

**Elasticsearch version**:  2.3.3

**Moloch version**: 0.14.2

**OS name and version**: CentOS 6.6

**Provide logs, stack traces and steps to reproduce**:  
Here is the backtrace from one of the crashes, will grab the others later tonight.
[backtrace.txt](https://github.com/aol/moloch/files/507245/backtrace.txt)

**Comment by awick** [comment]
I think this was fixed in 0.15.  Reopen if you are still having issues.
