### ISSUE TITLE
Accept-Encoding Missing from POST

### ISSUE THREAD

**Issue by BaconFries** [aol/moloch#542]
Accept-Encoding Missing from POST

**Elasticsearch version**:
2.3.5
**Moloch version**:
moloch v0.15.1-GIT
**OS name and version**:
2.6.32-504.30.3.el6.centos.plus.x86_64
**Provide logs, stack traces and steps to reproduce**:

First, thanks for adding the TCP flags and all the other works that's been done.
I've been pushing moloch very hard and getting over 100k documents per second into elasticsearch. The network quickly became a bottleneck. After enabling compression the outbound traffic dropped significantly but return traffic was still rather high, as shown here.
![screenshot 2016-10-08 13 29 42](https://cloud.githubusercontent.com/assets/20371065/19215843/fe37a1b4-8d76-11e6-9841-6bbaef06ba3a.png)

I noticed that the Accept-Encoding was not being set in the POST so I made the following change.

diff --git a/capture/http.c b/capture/http.c
index c5273d6..5213fc2 100644
--- a/capture/http.c
+++ b/capture/http.c
@@ -540,6 +540,7 @@ gboolean moloch_http_send(void *serverV, const char *method, const char *key, ui
         z_strm.next_out   = (unsigned char *)buf;
         ret = deflate(&z_strm, Z_FINISH);
         if (ret == Z_STREAM_END) {
+            request->headerList = curl_slist_append(request->headerList, "Accept-Encoding: gzip, deflate");
             request->headerList = curl_slist_append(request->headerList, "Content-Encoding: deflate");
             MOLOCH_SIZE_FREE(buffer, data);
             data_len = data_len - z_strm.avail_out;

Bandwidth on response traffic dropped dramatically. 
![screenshot 2016-10-08 14 35 10](https://cloud.githubusercontent.com/assets/20371065/19215845/029003b4-8d77-11e6-9951-51539dfc0a48.png)

Hopefully this helps.

**Comment by awick** [comment]
Thanks for pointing that out.  Made a slight change where we now add that to every request in the curl recommended way. Let me know if you see any issues.
