### ISSUE TITLE
FreeBSD 10.3 support

### ISSUE THREAD

**Issue by fabianfrz** [aol/moloch#549]
configure does not find the pcre lib but it is installed.

**Moloch version**:
Git commit  f2a082a

**OS name and version**:
FreeBSD 10.3 (OPNsense 16.7)

**Provide logs, stack traces and steps to reproduce**:

```
./configure
```

**Comment by fabianfrz** [comment]
``` bash
./configure --includedir=/usr/local/include/ --libdir= /usr/local/lib/
```

Error:
checking for main in -lpcre... no
configure: error: please install PCRE library


PCRE:
/usr/local/lib/libpcre.so
libpcre.a is in the same directory
Header file does exist as well:
/usr/local/include/pcre.h

**Comment by awick** [comment]
Not sure, its using just the default automake rules, nothing special.  Maybe this thread will help you

https://groups.google.com/forum/#!topic/moloch-fpc/LVbsXXgH7Mg

**Comment by fabianfrz** [comment]
I have tried to compile it using the following command:
``` bash
./configure CFLAGS="-I/usr/local/include -I/usr/include -I/usr/include/" LDFLAGS="-L/usr/local/lib"
```
It fails now at
```
checking for main in -luuid... no
configure: error: please install uuid library
```

man 3 uuid says that this is in the c standard library and used via "-lc" so I think the check is wrong.

**Comment by awick** [comment]
Ya looks like there are many things wrong with compiling on FreeBSD unfortunately.  I'll go ahead and remove FreeBSD supported from all the pages.
