### ISSUE TITLE
Friendly name for attachment of http traffic

### ISSUE THREAD

**Issue by whitetiger21022014** [aol/moloch#551]
Hi there,
Is it possible to show file name of attached file in sesstionDetail tab (http traffic) ?  like email traffic
Ex: Send/receive attachment via http traffic, I see only fileN.pellet, can we show friendly name as **file_name aaabbb.doc (original name) or file_name aaabbb.pellet**

Thanks,

**Comment by awick** [comment]
So most http responses don't have a file name in them, so I assume you are suggesting just use whatever the GET/POST request filename was?

If you are doing something automated already, that filename can be whatever you want, it doesn't have to be .pellet

**Comment by whitetiger21022014** [comment]
- It is very helpful if it can shows friendly name of file for GET/POST  HTTP method
- With POP3 protocol. Currently, it does not show any pellet name or friendly name when sending attached files

- if it can NOT detect friendly name, it can show with the correct file extension (ex: .doc, .zip,...). And at the end,  if it can not recognize attached file it will show .pellet

Then indexing friendly name/file extension to ES and we can search/filter with friendly name/file extension 

If you need pcap i can send to you
Thank you,

**Comment by awick** [comment]
> It is very helpful if it can shows friendly name of file for GET/POST HTTP method

Well it already shows the url, which is what the "friendly name" will be I guess.

> With POP3 protocol. Currently, it does not show any pellet name or friendly name when sending attached files

Yep, no pop3 decoding currently.  can you open a feature request

> 
> if it can NOT detect friendly name, it can show with the correct file extension (ex: .doc, .zip,...). And at the end, if it can not recognize attached file it will show .pellet


It uses .pellet on purpose because the last thing you want when downloading malware is for it to auto launch.  I could see future versions of the UI allowing you to rename the file so it didn't have a .pellet.




> Then indexing friendly name/file extension to ES and we can search/filter with friendly name/file extension

The uri is already indexed.  I guess I'm still confused what you mean by friendly name.


> If you need pcap i can send to you

sure

> Thank you,

**Comment by whitetiger21022014** [comment]
Thank for your time, so i ask the last question
- Friendly name (or original name), ex. I download file http://www.tldp.org/LDP/nag2/nag2.pdf , Moloch will show in http file1.pellet , **Can it show nag2.pellet?**, and then we can search file name like nag2.pellet

- May i use Moloch API for downloading pellet file?
Thanks

**Comment by awick** [comment]
> Friendly name (or original name), ex. I download file http://www.tldp.org/LDP/nag2/nag2.pdf , Moloch will show in http file1.pellet , Can it show nag2.pellet?, and then we can search file name like nag2.pellet

Yes I understand the feature requet you want is having the url populated with the file name.  So it will probably be nag2.pdf.pellet.  

I don't understand your search request, you can already do "http.uri.path = *nag2.pdf" for example.


> May i use Moloch API for downloading pellet file?

Yes it is already like

https://moloch/molochnode/161028-fFJ2Phy70v1Jr6pqT8fQfGdI/body/file/1/file1.pellet

And it already supports just changing to 

https://moloch/molochnode/161028-fFJ2Phy70v1Jr6pqT8fQfGdI/body/file/1/nag1.pdf


The only change I'm looking at doing now, is the changing the file1.pellet to nag1.pdf.pellet for you

**Comment by whitetiger21022014** [comment]
I forgot,  I will use feature http.uri.path = *... 
when you change file1.pellet to nag1.pdf.pellet, Moloch will be perfect and we will close this request
Thank you

**Comment by whitetiger21022014** [comment]
I just use your commit, but it is still show as old, 
ref image below 

![original_name_pellet](https://cloud.githubusercontent.com/assets/22853600/19843826/a898c9ba-9f58-11e6-95fa-86584b11d106.png)
