### ISSUE TITLE
Disable cookies: Couldn't look up SPI data, error for session ...

### ISSUE THREAD

**Issue by whitetiger21022014** [aol/moloch#553]
Hi,
Error: Couldn't look up SPI data, error for session ... Error: Error loading data for session

When clients access to websites via open proxy, https://zend2.com/ , **Uncheck: Allow Cookies**

![cookies_tmp](https://cloud.githubusercontent.com/assets/22853600/19917334/ea830bd6-a0f4-11e6-8808-c653278688c9.png)

**Comment by awick** [comment]
You are saying moloch viewer doesn't work if you turn off cookies in your browser?  Do we care?

**Comment by whitetiger21022014** [comment]
I mentioned about  viewer
I use tcpdump now, double check and there is no problem, maybe it was my mistake
So I close this issue
Thank you
