### ISSUE TITLE
iptrie fails to install on single-host build

### ISSUE THREAD

**Issue by daemondriver** [aol/moloch#555]
**Elasticsearch version**: NA (new install)

**Moloch version**: Yesterday

**OS name and version**: CentOS 6.8 Final

**Provide logs, stack traces and steps to reproduce**:

I can reproduce the error by trying to install iptrie by hand:

[root@mgs moloch-master]# /data/moloch/bin/npm install iptrie@0.0.6
npm WARN engine iptrie@0.0.6: wanted: {"node":"0.2 || 0.4 || 0.5 || 0.6 || 0.8 || 0.10"} (current: {"node":"4.6.0","npm":"2.15.9"})

> iptrie@0.0.6 install /usr/local/moloch-master/node_modules/iptrie
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/moloch-master/node_modules/iptrie/.node-gyp"
make: Entering directory `/usr/local/moloch-master/node_modules/iptrie/build'
  CXX(target) Release/obj.target/iptrie/src/iptrie.o
In file included from ../src/iptrie.cc:35:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:336: error: expected unqualified-id before ‘using’
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:353: error: ‘nullptr’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:360: error: ‘nullptr’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:364: error: ‘nullptr’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:430: error: ‘nullptr’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: At global scope:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:469: error: expected unqualified-id before ‘using’
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:790: error: ‘nullptr’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:815: error: ‘nullptr’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:827: error: ‘nullptr’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: At global scope:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:852: error: expected unqualified-id before ‘using’
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:1089: error: ‘nullptr’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:1095: error: ‘nullptr’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:3205: error: ‘nullptr’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:7164: error: ‘nullptr’ was not declared in this scope
../src/iptrie.cc: At global scope:
../src/iptrie.cc:42: error: expected class-name before ‘{’ token
../src/iptrie.cc:46: error: ‘v8::Handle’ has not been declared
../src/iptrie.cc:46: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/iptrie.cc:81: error: ‘Handle’ has not been declared
../src/iptrie.cc:81: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/iptrie.cc:151: error: ISO C++ forbids declaration of ‘Handle’ with no type
../src/iptrie.cc:151: error: expected ‘;’ before ‘<’ token
../src/iptrie.cc:160: error: expected ‘;’ before ‘static’
../src/iptrie.cc:160: error: ISO C++ forbids declaration of ‘Handle’ with no type
../src/iptrie.cc:160: error: expected ‘;’ before ‘<’ token
../src/iptrie.cc:245: error: expected ‘;’ at end of input
../src/iptrie.cc:245: error: expected ‘}’ at end of input
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In static member function ‘static void IPTrie::Initialize(int)’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:885: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/iptrie.cc:47: error: within this context
../src/iptrie.cc:49: error: ‘New’ was not declared in this scope
../src/iptrie.cc:50: error: no matching function for call to ‘v8::PersistentBase<v8::FunctionTemplate>::New(v8::Local<v8::FunctionTemplate>&)’
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:7181: note: candidates are: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::FunctionTemplate]
../src/iptrie.cc:51: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >’
../src/iptrie.cc:52: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >’
../src/iptrie.cc:52: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/iptrie.cc:54: error: argument of type ‘int (IPTrie::)(const char*, int, int)’ does not match ‘void (*)(const v8::FunctionCallbackInfo<v8::Value>&)’
../src/iptrie.cc:55: error: argument of type ‘int (IPTrie::)(const char*, int)’ does not match ‘void (*)(const v8::FunctionCallbackInfo<v8::Value>&)’
../src/iptrie.cc:56: error: argument of type ‘IPTrie::obj_baton_t* (IPTrie::)(const char*)’ does not match ‘void (*)(const v8::FunctionCallbackInfo<v8::Value>&)’
../src/iptrie.cc:59: error: ‘target’ was not declared in this scope
../src/iptrie.cc:59: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/iptrie.cc:60: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >’
../src/iptrie.cc: In static member function ‘static void IPTrie::delete_baton(void*)’:
../src/iptrie.cc:71: error: ‘class v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >’ has no member named ‘Dispose’
../src/iptrie.cc: In constructor ‘IPTrie::IPTrie()’:
../src/iptrie.cc:75: error: class ‘IPTrie’ does not have any field named ‘tree4’
../src/iptrie.cc:75: error: class ‘IPTrie’ does not have any field named ‘tree6’
../src/iptrie.cc: In destructor ‘IPTrie::~IPTrie()’:
../src/iptrie.cc:77: error: ‘tree4’ was not declared in this scope
../src/iptrie.cc:78: error: ‘tree6’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In member function ‘int IPTrie::Add(const char*, int, int)’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:885: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/iptrie.cc:82: error: within this context
../src/iptrie.cc:100: error: ‘dv’ was not declared in this scope
../src/iptrie.cc:102: error: ‘tree4’ was not declared in this scope
../src/iptrie.cc:103: error: ‘tree6’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In member function ‘int IPTrie::Del(const char*, int)’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:885: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/iptrie.cc:108: error: within this context
../src/iptrie.cc:124: error: ‘tree4’ was not declared in this scope
../src/iptrie.cc:125: error: ‘tree6’ was not declared in this scope
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h: In member function ‘IPTrie::obj_baton_t* IPTrie::Find(const char*)’:
/usr/local/moloch-master/node_modules/iptrie/.node-gyp/4.6.0/include/node/v8.h:885: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/iptrie.cc:129: error: within this context
../src/iptrie.cc:146: error: ‘tree4’ was not declared in this scope
../src/iptrie.cc:147: error: ‘tree6’ was not declared in this scope
../src/iptrie.cc: At global scope:
../src/iptrie.cc:148: error: expected unqualified-id at end of input
make: *** [Release/obj.target/iptrie/src/iptrie.o] Error 1
make: Leaving directory `/usr/local/moloch-master/node_modules/iptrie/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/moloch/node-v4.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-642.6.2.el6.x86_64
gyp ERR! command "/data/moloch/node-v4.6.0-linux-x64/bin/node" "/data/moloch/node-v4.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/moloch-master/node_modules/iptrie
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/data/moloch/node-v4.6.0-linux-x64/bin/node" "/data/moloch/bin/npm" "install" "iptrie@0.0.6"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! iptrie@0.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iptrie@0.0.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iptrie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iptrie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls iptrie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/moloch-master/npm-debug.log

**Comment by awick** [comment]
Couple issues
* Looks like the wrong version of iptrie, if you did a git pull and are trying to build on top of a previous version wipe out the node_modules directories and try again

* Centos 6 builds now require newer versions of g++, you can fix by doing a
yum install devtoolset-3-toolchain
scl enable devtoolset-3 bash ;# or your favorite shell
command you want to run

* easy button is going away, you  might want to switch to the RPM/DEBs
