### ISSUE TITLE
Moloch Capture dies after x minuts

### ISSUE THREAD

**Issue by honey4sec** [aol/moloch#556]
**Elasticsearch version**:

 moloch-capture 0.16.0-GIT 

RHEL7 - 3.10.0-327.28.3.el7.x86_64

(gdb) run  -c /etc/moloch/etc/config.ini > /var/log/ids/kargud_temp/capture.log 2>&1
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /etc/moloch/bin/moloch-capture -c /etc/moloch/etc/config.ini > /var/log/ids/kargud_temp/capture.log 2>&1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff0912700 (LWP 92384)]
[New Thread 0x7fffebfff700 (LWP 92385)]
[New Thread 0x7fffeb7fe700 (LWP 92386)]
[New Thread 0x7fffeaffd700 (LWP 92387)]
[New Thread 0x7fffea7fc700 (LWP 92388)]
[New Thread 0x7fffe9ffb700 (LWP 92389)]
[New Thread 0x7fffe97fa700 (LWP 92390)]
[New Thread 0x7fffc3a91700 (LWP 92391)]
[New Thread 0x7fffc3290700 (LWP 92392)]
[New Thread 0x7fffc2a8f700 (LWP 92393)]

Program received signal SIGSEGV, Segmentation fault.
0x00000000006143dd in addbyter ()
(gdb) bt
#0  0x00000000006143dd in addbyter ()
#1  0x0000000000614723 in dprintf_formatf ()
#2  0x0000000000615975 in curl_mvsnprintf ()
#3  0x000000000060a7ce in Curl_failf ()
#4  0x0000000000602957 in Curl_resolv_timeout ()
#5  0x00000000326de256 in ?? ()
#6  0x0000000001a0245c in ?? ()
#7  0x00000000006034bf in Curl_pgrsUpdate ()
#8  0x5b3a226d7265742d in ?? ()
#9  0x7471222c5d225952 in ?? ()
#10 0x6e632d6d7265742d in ?? ()
#11 0x7265742d65646f63 in ?? ()
#12 0x455551225b3a226d in ?? ()
#13 0x6e632d6d7265742d in ?? ()
#14 0x706f222c313a2274 in ?? ()
#15 0x2c5d22524f525245 in ?? ()
#16 0x2d65646f63706f22 in ?? ()
#17 0x0000000000000000 in ?? ()

**Comment by awick** [comment]
Can you try master, I think this has been fixed
