### ISSUE TITLE
Feature requests: extract attached file for remaining protocol

### ISSUE THREAD

**Issue by whitetiger21022014** [aol/moloch#558]
Moloch already extracted attached file for HTTP, SMTP, .....
Please add feature for extracting attached file for **remaining protocol** eg POP3, IMAP, voice traffic,... and can get attached file in another tab (eg. Other tab)
ex: If detects attached file in payload, Moloch will extract
Thanks

**Comment by awick** [comment]
Depends on #186, #286,
