### ISSUE TITLE
Elasticsearch v5 Support

### ISSUE THREAD

**Issue by keithjjones** [aol/moloch#561]
I upgraded ES from 2.4 to 5 and the viewer component dies.  Is this due to changes in ES v5?

**Comment by awick** [comment]
ES 5 is only just barely supported by 0.17.0, see the change log :)

  - Initial ES 5.0 support (do not use in production!)

**Comment by keithjjones** [comment]
@awick Why did you close this?  Is there somewhere we can follow to see when/where/how v5 will be supported?  v5 is not supported yet, so it seems like keeping this issue open for others to find and contribute to throughout the v5 implementation would make sense.

**Comment by awick** [comment]
Because it was written as a bug report and not a feature request.

**Comment by keithjjones** [comment]
How do you want me submit it to make it a "feature request"?

You can assign a feature request within Github issues as a project owner.

**Comment by awick** [comment]
We can reopen it, I'm just saying I didn't look at the title and read the text "I upgraded ES from 2.4 to 5 and the viewer component dies. Is this due to changes in ES v5?" which is a bug report on a feature that doesn't exist so I naturally closed it.

**Comment by awick** [comment]
Add support for ES 5

**Comment by keithjjones** [comment]
Your issue template said to remove the bug block and describe the feature, which is exactly what I did.

**Comment by awick** [comment]
You are right, I am wrong
