### ISSUE TITLE
World Map Hit Counter Callouts

### ISSUE THREAD

**Issue by cclements** [aol/moloch#564]
On the world map, it would be nice to be able to toggle on counters for all matched countries with non-zero hits.  Would also be nice to be able to be able to download the current map view directly.

**Comment by 31453** [comment]
Can you describe your use case? Would this output differ from the output of "Export Unique Src/Dst Country with counts" column menu item?

**Comment by cclements** [comment]
Hey Elyse, yes, different from the column export.  Currently, the world map shows darker/lighter green depending on the number of GeoIP matches.  It would be nice if it were possible to toggle appearance of the actual number of connections on top of the countries directly on the map graphic as data labels.  Also along these lines, having varying colors for each country with an associated legend / table would also be helpful.  

My goal in this is a straight forward to export the world graphic with either data labels on the country or at least an easy to reference src/dst totals table.  Think of something like a "top 10 source countries by sessions, data, etc." dashboard.  I can do this manually, but currently I have to enlarge the world map, then take a screen shot, then export and manually count sessions/data, then create my own reference table with this info and try my best to match the darker/lighter green color coding.

Would be glad to provide mock ups if I haven't communicated clearly!

**Comment by 31453** [comment]
Ok. I think I understand what you're getting at. I'm going to look into this. 

Currently, in the map library that we are using, the country data does not include the coordinates of the center of each country, which is needed in order to place the count appropriately.

**Comment by 31453** [comment]
So, I have implemented a possible solution: I did not add the counts directly on top of countries for a few reasons, (1) I do not have the data for the center of each country, and (2) it would hide small countries entirely. I did, however, add a "Top 10" area that describes the top 10 countries with their counts and corresponding color.

Please reopen this issue if this is not an appropriate solution.
