### ISSUE TITLE
bug -- capture

### ISSUE THREAD

**Issue by Lfengjie** [aol/moloch#567]
**Elasticsearch version**: 2.4

**Moloch version**:  0.16

**OS name and version**: Ubuntu 14.04.4 LTS

**Provide logs, stack traces and steps to reproduce**:

Dec 14 10:22:25 reader-libpcap.c:58 reader_libpcap_pcap_cb(): ERROR - Moloch requires full packet captures caplen: 16384 pktlen: 19094
turning offloading off may fix, something like 'ethtool -K INTERFACE tx off sg off gro off gso off lro off tso off'

I think the code need to avoid this question？

**Comment by awick** [comment]
What do you mean?

**Comment by Lfengjie** [comment]
Thank you for your reply!

I mean in this case, the program will crash！

**Comment by awick** [comment]
It doesn't crash, it exits because it wants you to fix the problem.
