### ISSUE TITLE
Capture double free or corruption error

### ISSUE THREAD

**Issue by SUBRON6** [aol/moloch#568]
this capture error was seen in testing 15.0 and now in testing 16.1 also.  Even odds that there will no error in the debug log file and the other half of the time we see the error below.  Nothing needed to reproduce the error it happens rather frequently

**Elasticsearch version**: 2.3.0

**Moloch version**:15 and 16.1

**OS name and version**:COS 7.1

**Provide logs, stack traces and steps to reproduce**:
*** Error in `/cork/moloch-0.16.1/bin/moloch-capture': double free or corruption (fasttop): 0x00007fe2d13a78c0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7d053)[0x7febac5a9053]
/cork/moloch-0.16.1/bin/moloch-capture(clear_marks+0x48)[0x5d0eb8]
/cork/moloch-0.16.1/bin/moloch-capture(yr_scan_mem_blocks+0x80)[0x5ccc00]
/cork/moloch-0.16.1/bin/moloch-capture(moloch_yara_execute+0x4e)[0x45082e]
/cork/moloch-0.16.1/bin/moloch-capture(moloch_packet_tcp_finish+0xd7)[0x461e97]
/cork/moloch-0.16.1/bin/moloch-capture[0x462e9e]
/cork/moloch-0.16.1/bin/moloch-capture[0x49765f]
/lib64/libpthread.so.0(+0x7dc5)[0x7febad884dc5]
/lib64/libc.so.6(clone+0x6d)[0x7febac622ced]

**Comment by awick** [comment]
Please reopen if that doesn't fix
