### ISSUE TITLE
undefined symbol - Couldn't load parser 0.17.0

### ISSUE THREAD

**Issue by wr2mem** [aol/moloch#574]
Not having much luck compiling 0.17.0. Every time capture starts, I get this. Viewer starts fine.

*.so and *.jade, etc are in shown path

<..snippet..>

Dec 22 19:39:45 config.c:69 moloch_config_str(): magicMode=libmagic
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser dns.so from '/data/moloch/parsers/dns.so'
/data/moloch/parsers/dns.so: undefined symbol: g_free
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser http.so from '/data/moloch/parsers/http.so'
/data/moloch/parsers/http.so: undefined symbol: pluginsCbs
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser irc.so from '/data/moloch/parsers/irc.so'
/data/moloch/parsers/irc.so: undefined symbol: moloch_parsers_classifier_register_tcp_internal
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser krb5.so from '/data/moloch/parsers/krb5.so'
/data/moloch/parsers/krb5.so: undefined symbol: moloch_parsers_classifier_register_tcp_internal
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser ldap.so from '/data/moloch/parsers/ldap.so'
/data/moloch/parsers/ldap.so: undefined symbol: moloch_parsers_classifier_register_tcp_internal
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser misc.so from '/data/moloch/parsers/misc.so'
/data/moloch/parsers/misc.so: undefined symbol: moloch_parsers_classifier_register_tcp_internal
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser mysql.so from '/data/moloch/parsers/mysql.so'
/data/moloch/parsers/mysql.so: undefined symbol: moloch_parsers_classifier_register_tcp_internal
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser oracle.so from '/data/moloch/parsers/oracle.so'
/data/moloch/parsers/oracle.so: undefined symbol: moloch_parsers_classifier_register_tcp_internal
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser postgresql.so from '/data/moloch/parsers/postgresql.so'
/data/moloch/parsers/postgresql.so: undefined symbol: moloch_parsers_classifier_register_tcp_internal
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser quic.so from '/data/moloch/parsers/quic.so'
/data/moloch/parsers/quic.so: undefined symbol: moloch_parsers_classifier_register_udp_internal
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser radius.so from '/data/moloch/parsers/radius.so'
/data/moloch/parsers/radius.so: undefined symbol: moloch_field_int_add
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser smb.so from '/data/moloch/parsers/smb.so'
/data/moloch/parsers/smb.so: undefined symbol: config
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser smtp.so from '/data/moloch/parsers/smtp.so'
/data/moloch/parsers/smtp.so: undefined symbol: userField
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser ssh.so from '/data/moloch/parsers/ssh.so'
/data/moloch/parsers/ssh.so: undefined symbol: moloch_parsers_classifier_register_tcp_internal
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser tds.so from '/data/moloch/parsers/tds.so'
/data/moloch/parsers/tds.so: undefined symbol: moloch_parsers_classifier_register_tcp_internal
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser tls.so from '/data/moloch/parsers/tls.so'
/data/moloch/parsers/tls.so: undefined symbol: moloch_char_to_hexstr
Dec 22 19:39:45 parsers.c:613 moloch_parsers_init(): ERROR - Couldn't load parser socks.so from '/data/moloch/parsers/socks.so'
/data/moloch/parsers/socks.so: undefined symbol: moloch_parsers_classifier_register_tcp_internal
Dec 22 19:39:45 session.c:606 moloch_session_init(): session hash size 1092757
Dec 22 19:39:47 plugins.c:101 moloch_plugins_load(): ERROR - Couldn't load plugin tagger.so from '/data/moloch/plugins/tagger.so'
/data/moloch/plugins/tagger.so: undefined symbol: moloch_string_cmp
Dec 22 19:39:47 plugins.c:111 moloch_plugins_load(): WARNING - plugin 'tagger.so' not found
Dec 22 19:39:47 main.c:488 moloch_ready_gfunc(): maxField = 9
Dec 22 19:39:47 config.c:69 moloch_config_str(): pcapWriteMethod=simple
Dec 22 19:39:47 config.c:69 moloch_config_str(): simpleEncoding=(null)
Dec 22 19:39:47 config.c:69 moloch_config_str(): simpleKEKId=(null)
Dec 22 19:39:47 reader-libpcap.c:74 reader_libpcap_thread(): THREAD 0x7f4df366e700
Dec 22 19:39:47 reader-libpcap.c:74 reader_libpcap_thread(): THREAD 0x7f4ec1ffb700
Dec 22 19:39:47 reader-libpcap.c:74 reader_libpcap_thread(): THREAD 0x7f4ec2ffd700
Dec 22 19:39:47 reader-libpcap.c:74 reader_libpcap_thread(): THREAD 0x7f4ec17fa700
Dec 22 19:39:47 reader-libpcap.c:74 reader_libpcap_thread(): THREAD 0x7f4ec37fe700
Dec 22 19:39:47 reader-libpcap.c:74 reader_libpcap_thread(): THREAD 0x7f4ec27fc700
Dec 22 19:39:47 reader-libpcap.c:74 reader_libpcap_thread(): THREAD 0x7f4df3e6f700
Dec 22 19:39:47 reader-libpcap.c:74 reader_libpcap_thread(): THREAD 0x7f4ec0ff9700
Dec 22 19:39:47 writer-simple.c:277 writer_simple_thread(): THREAD 0x7f4ec3fff700
Dec 22 19:39:47 packet.c:923 moloch_packet_ip(): Initial Packet = 1482435584
Dec 22 19:39:47 packet.c:924 moloch_packet_ip(): 0 Initial Dropped = 0

**Comment by awick** [comment]
Can you provide from the bug template **OS name and version**:
and the also how you got moloch (did you build yourself, rpm, singlebutton, ...)

**Comment by wr2mem** [comment]
CentOS 3.10.0-327.28.2.el7.x86_64 was used. Compiled using packages recommended. Same procedure was used in 0.16.1 and worked and below versions. Any ideas?

**Comment by awick** [comment]
Not really since the undefined symbols are from all over the place.  The first one g_free looks like maybe you linked against a different version of glib then the include file.  Almost seems like the moloch-capture binary is a different version then the parsers.
