### ISSUE TITLE
moloch-capture premature file read

### ISSUE THREAD

**Issue by craigsmooth** [aol/moloch#575]
**Elasticsearch version**:
2.4.0
**Moloch version**:
0.15.1
0.16.1
**OS name and version**:
Ubuntu 14.04
**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
singlehost
**Provide logs, stack traces and steps to reproduce**:
For some reason, my pcaps are getting read via moloch-capture too early. I am getting incomplete session data in elastic as a result. I can manually run capture against the file after it has been closed out and all the data is intact. However, running capture to recursively monitor a directory always results in incomplete PCAP files. Please let me know what additional information you might need to troubleshoot. This monitored directory currently resides on a separate LVM managed disk formatted as ext4.

**Comment by awick** [comment]
Should be fixed in 0.17 commit 894179875c9e405e30957427c668db8203e1ac10
