### ISSUE TITLE
UTC/GMT Timestamp not working with newUI

### ISSUE THREAD

**Issue by jescar50dx** [aol/moloch#576]
**Elasticsearch version**: 2.3.4

**Moloch version**: moloch v0.17.0-GIT

**OS name and version**: Centos 6.6

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) RPM

**Provide logs, stack traces and steps to reproduce**:

Doesn't look like the UTC/GMT timestamp option is working with the newUI. The start and stop times are showing in my local timezone. GMT timezone is selected under settings. Works ok on the oldUI.

**Comment by 31453** [comment]
Should be fixed in 0.17 commit dec96dfee284f697db2882e4fc4a4a609b3b5210
