### ISSUE TITLE
configure can't find yara on arm64

### ISSUE THREAD

**Issue by mellotron** [aol/moloch#581]
Hello,

On a arm64 box of mine, configure fails to locate the yara library/binary that's installed on the system:

$ sudo apt-get install libyara-dev yara
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libyara-dev is already the newest version (3.4.0+dfsg-2build1).
yara is already the newest version (3.4.0+dfsg-2build1).
...

$ ./configure
...
checking for yara... configure: error: yara not found

Specifying --without-yara returns:

$ ./configure
...
checking for nl_handle_alloc in -lnl... no
checking for yara... no
checking for GeoIP... yes
checking for glib2... yes
...

And the build can continue with 'make'.

**Comment by awick** [comment]
What OS and moloch version?  (Filling out the bug template would be most helpful)

**Comment by awick** [comment]
it build for me on arm64 so closing without more info

**Comment by rahultyagi** [comment]
I am getting the same error . I am trying to install on Ubuntu 16.04 LTS and the latest Moloch Version

**Comment by jhanna01** [comment]
I am also getting this same error following the same method as specified by mellotron
