### ISSUE TITLE
configure doesn't properly check for glib/curl

### ISSUE THREAD

**Issue by mellotron** [aol/moloch#583]
Hello,

I was compiling moloch when this came up with ./configure:

$ ./configure
checking for glib2... Package gio-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gio-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gio-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
Package gthread-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gthread-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gthread-2.0' found
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gmodule-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gmodule-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gmodule-2.0' found
Package gio-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gio-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gio-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
Package gthread-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gthread-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gthread-2.0' found
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gmodule-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gmodule-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gmodule-2.0' found
yes
checking for curl... Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
yes
checking for lua... yes
checking for magic... checking for main in -lmagic... yes
yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating capture/Makefile
config.status: creating capture/plugins/Makefile
config.status: creating capture/plugins/daq/Makefile
config.status: creating capture/plugins/pfring/Makefile
config.status: creating capture/plugins/snf/Makefile
config.status: creating capture/plugins/lua/Makefile
config.status: creating capture/parsers/Makefile
config.status: creating db/Makefile
config.status: creating tests/plugins/Makefile
config.status: creating viewer/Makefile
config.status: creating viewer/version.js
config.status: creating capture/molochconfig.h
config.status: executing depfiles commands
$ make
Makefile:219: warning: overriding recipe for target 'capture/plugins/Makefile'
Makefile:217: warning: ignoring old recipe for target 'capture/plugins/Makefile'
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
Making all in capture
make[1]: Entering directory '/home/ubuntu/moloch-0.17.0/capture'
gcc -c thirdparty/js0n.c -o thirdparty/js0n.o
gcc -ggdb -DNDEBUG -DHTTP_PARSER_STRICT=0 -DHTTP_PARSER_DEBUG=0 -O3 -c thirdparty/http_parser.c -o thirdparty/http_parser.o
gcc -c thirdparty/patricia.c -o thirdparty/patricia.o
gcc -fPIC -O2 -ggdb -Wall -Wextra -D_GNU_SOURCE -c main.c db.c yara.c http.c config.c parsers.c plugins.c field.c trie.c writers.c writer-inplace.c writer-disk.c writer-null.c writer-simple.c readers.c reader-libpcap-file.c reader-libpcap
.c reader-tpacketv3.c packet.c session.c molochmagic.c \
    -I/usr/include/pcap \
    -Ithirdparty  
In file included from main.c:18:0:
moloch.h:35:18: fatal error: glib.h: No such file or directory
compilation terminated.
In file included from db.c:18:0:
moloch.h:35:18: fatal error: glib.h: No such file or directory
compilation terminated.
moloch.h:35:18: fatal error: glib.h: No such file or directory
compilation terminated.
In file included from yara.c:17:0:
moloch.h:35:18: fatal error: glib.h: No such file or directory
compilation terminated.
http.c:27:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
In file included from config.c:19:0:
moloch.h:35:18: fatal error: glib.h: No such file or directory
compilation terminated.

configure should bail if a dependency isn't found.

**Comment by 31453** [comment]
Looks like this is working. Please reopen if you encounter this issue in the future.
