### ISSUE TITLE
Local elasticsearch fails to start using .deb package on Ubuntu 16.04

### ISSUE THREAD

**Issue by obilodeau** [aol/moloch#587]
**Elasticsearch version**: 2.4.0
**Moloch version**: 0.17.0
**OS name and version**: Ubuntu 16.04
**How was Moloch built/installed:** deb
**Provide logs, stack traces and steps to reproduce**:

```
Jan 20 11:52:47 GS00RD01 systemd[1]: Started Moloch Demo Elasticsearch.
Jan 20 11:52:47 GS00RD01 su[12851]: Successful su for nobody by root
Jan 20 11:52:47 GS00RD01 su[12851]: + ??? root:nobody
Jan 20 11:52:47 GS00RD01 su[12851]: pam_unix(su:session): session opened for user nobody by (uid=0)
Jan 20 11:52:48 GS00RD01 systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Jan 20 11:52:48 GS00RD01 systemd[1]: elasticsearch.service: Unit entered failed state.
Jan 20 11:52:48 GS00RD01 systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
Jan 20 11:52:48 GS00RD01 systemd[1]: elasticsearch.service: Service hold-off time over, scheduling restart.
Jan 20 11:52:48 GS00RD01 systemd[1]: Stopped Moloch Demo Elasticsearch.
```

1st problem is that no error output is provided by startup script. I tried altering systemd unit file's `StandardError=` to journal and it didn't work.

Running systemd ExecStart statement directly:

```
sudo /data/moloch/elasticsearch/bin/elasticsearch -Des.default.path.conf=/data/moloch/etc                    
Exception in thread "main" java.lang.IllegalArgumentException: Could not resolve placeholder 'ES_HTTP_PORT'
        at org.elasticsearch.common.property.PropertyPlaceholder.parseStringValue(PropertyPlaceholder.java:128)
        at org.elasticsearch.common.property.PropertyPlaceholder.replacePlaceholders(PropertyPlaceholder.java:81)
        at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1179)
        at org.elasticsearch.node.internal.InternalSettingsPreparer.initializeSettings(InternalSettingsPreparer.java:131)
        at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:100)
        at org.elasticsearch.bootstrap.Bootstrap.initialSettings(Bootstrap.java:218)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:257)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

Copying the values of the environment variables from `/data/moloch/etc/elasticsearch.systemd.service` to `/data/moloch/etc/elasticsearch.yml` and changing `{ES_PATH}` to `/data/moloch/` worked.

**Comment by problematiq** [comment]
I'm having a similar problem running Ubuntu 16.04. Looking into /var/log/syslog i find this: 
`systemd[2992]: elasticsearch.service: Failed at step EXEC spawning /usr/bin/su: No such file or directory
systemd[1]: elasticsearch.service: Main process exited, code=exited, status=203/EXEC
systemd[1]: elasticsearch.service: Unit entered failed state.
systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
systemd[1]: elasticsearch.service: Service hold-off time over, scheduling restart.`
Of course  "/usr/bin/su" does not exsist in Ubuntu 16.04

**Comment by problematiq** [comment]
I am also having problems with ES not using the environmental variables in `/data/moloch/etc/elasticsearch.systemd.service`

**Comment by obilodeau** [comment]
@problematiq `sudo` doesn't behave like `su`. Change `/usr/bin/su` to `/bin/su` or symlink `/bin/su` into `/usr/bin/su`. This should be filed as a separate bug I guess...

**Comment by problematiq** [comment]
I will leave it there and create a new post.

**Comment by awick** [comment]
0.17.1 released
