### ISSUE TITLE
New UI - Up/Down arrow keys don't work in auto complete for column selector

### ISSUE THREAD

**Issue by awick** [aol/moloch#597]
and they are screaming in pain

**Comment by 31453** [comment]
**Standardize field typeaheads!**

Everywhere there is a field typeahead, they should have the same behavior:

1. Should be grouped
2. Should be able to traverse with up/down keys
3. Should be able to escape with the escape key
4. Should be able to select a field with the enter key (or clicking the field in the list)

**Comment by 31453** [comment]
Fixed with the Vue UI.
