### ISSUE TITLE
Secondary Query

### ISSUE THREAD

**Issue by awick** [aol/moloch#605]
Will:

I would like to be able to highlight specific times on the sessions graph with a secondary query that is specific to highlighting but does NOT filter any results from the display. 

Example case. Suspicious activity destined for IP 1.2.3.4

I then want to pivot on the source address for that same time frame, but based solely on the source IP of 5.6.7.8, and have vertical colored lines (RED?) show where my "highlighter query" of ip==1.2.3.4 took place so that I can focus on event immediately prior or post highlighted network event. It would be next step awesome to also highlight the actual session in the results table, not just on the graph.

**Comment by 31453** [comment]
Check out the baseline comparison feature in the connections graph. You could also open two different browser tabs and do this comparison that way.

Please reopen if neither of these solutions is sufficient.
