### ISSUE TITLE
Problem with Elasticsearch starting  (Deb package installiation for Ubuntu 16.04)

### ISSUE THREAD

**Issue by problematiq** [aol/moloch#608]
I am having problems with ES complaining in `/var/log/syslog` that it cannot find `/usr/bin/su` (not in Ubuntu 16.04) so I went into `/etc/systemd/system/elasticsearch.service` and changed it from `/usr/bin/su` to `/bin/su` It was suggested also I could create a symlink `/bin/su` into `/usr/bin/su`. ~Thanks obilodeau

After making that change I now have a problem where Elasticsearch does not listen on port 9200 and 9300.
If I change it to /usr/bin/sudo it works.

**Comment by awick** [comment]
0.17.1 released
