### ISSUE TITLE
Capture crash when monitoring multiple interfaces

### ISSUE THREAD

**Issue by stoomart** [aol/moloch#610]
**Elasticsearch version**: 2.4.0

**Moloch version**: v0.17.0

**OS name and version**: CentOS 7.3.1611 x86_64

**How was Moloch built/installed**: rpm

**Provide logs, stack traces and steps to reproduce**:

Capture service crashes on startup when monitoring traffic from two interfaces, works fine when configured for one or the other. Did not crash during initial setup when configured to capture on all 3 interfaces, but only 1 was actually receiving traffic.  Tried applying the last 3 sections of the [High Performance Settings](https://github.com/aol/moloch/wiki/Settings#High_Performance_Settings) without success.

**/var/log/messages info**:
`kernel: moloch-pkt3[5647]: segfault at 0 ip 0000000000446d88 sp 00007f8e77ffe8d0 error 4 in moloch-capture[400000+1e6000]]`

**BT info**:
```
#0  moloch_packet_thread (threadp=0x2) at packet.c:508
#1  0x000000000049db8f in g_thread_proxy (data=0x3288ca0) at gthread.c:784
#2  0x00007f8508c09dc5 in start_thread () from /lib64/libpthread.so.0
#3  0x00007f850778973d in clone () from /lib64/libc.so.6
```

**/etc/rc.local interface settings**:
```
ethtool -G ens3x rx 4096 tx 4096
ethtool -K ens3x tx off rx off tso off gso off gro off sg off
ip link set ens3x promisc on
```

**molochcapture.service limits config**:
```
LimitCORE=infinity
LimitMEMLOCK=infinity
```

**iostats (6 hours)**:
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           1.48    0.00    0.84    1.08    0.00   96.60
```

**ifstats (6 hours)**:
```
Interface        RX Pkts/Rate    TX Pkts/Rate    RX Data/Rate    TX Data/Rate
                 RX Errs/Drop    TX Errs/Drop    RX Over/Rate    TX Coll/Rate
ens32            102487K 0             0 0         1246M 0             0 0
                       0 0             0 0             0 0             0 0
ens34                  0 0             0 0             0 0             0 0
                       0 0             0 0             0 0             0 0
ens35            195116K 0             0 0        96380K 0             0 0
                       0 512           0 0             0 0             0 0
```

**Comment by awick** [comment]
Which reader are you using?

**Comment by stoomart** [comment]
Whatever the default is, I commented out the first three sections listed in the High Performance Settings. Sorry, still getting familiar with the tool and terminology.

**Comment by awick** [comment]
0.17.1 released

**Comment by stoomart** [comment]
Upgraded and now capturing on both interfaces, nice work!
