### ISSUE TITLE
Elasticsearch does not listen on port 9200 upon reboot. (Deb package installiation for Ubuntu 16.04)

### ISSUE THREAD

**Issue by problematiq** [aol/moloch#611]
After installing Moloch with the .deb file and installing elasticsearch with the demo install, if I start the services via `systemctl start elasticsearch.service` they work just fine. But doing a `systemctl enable elasticsearch.service` upon reboot it fails to listen on port 9200 even if the service is running.

**Comment by awick** [comment]
it works for me.

What do your mean "even if the service is running?"

Make sure you dont have both /etc/init  and /etc/systemd versions of the startup script installed.

**Comment by problematiq** [comment]
I apologize as you can tell I'm not the sharpest when it comes to linux. Unfortunately our Linux god is on vacation this week and is unable to help. The `/etc/init` version is not running. After installing moloch via the .deb I can start the services manually via sudo and they run correctly, but if I set the services to start automatically via `systemctl enable elasticsearch.service` upon reboot of the system and doing a `systemctl status elasticsearch.service` it shows it as "active (running)" but using `lsof -i -n -P` the service is not listening on port 9200. It's looking more like a permissions thing to me but then again I'm not super fluent in linux.

**Comment by awick** [comment]
And this is with 0.17.1?

**Comment by problematiq** [comment]
This was an attempt to update an existing moloch. When doing a fresh install it works perfectly fine.

**Comment by awick** [comment]
great
