### ISSUE TITLE
New UI - Missing World mini-map on Sessions page in 0.17.1

### ISSUE THREAD

**Issue by DrJohn1** [aol/moloch#612]
Hi,

I am checking the New UI Sessions page but the minimap is no longer visible (there is only a button to see the large map).

Is there an option to enable the mini-map on the New UI sessions page?

Thanks!

**Comment by awick** [comment]
Currently no plans to add it back.  You want it visible at all times?  How do you use that feature?

**Comment by DrJohn1** [comment]
Served mostly as a quick overview while filtering/reviewing data, specially in cases of computers/servers suspected of being infected with malware. It would have been nice to have it as an option (or toggle).

Is it possible if I add the older one and include it in the new view without recompiling AngularJS?

Thanks for the quick answer regardless!

**Comment by 31453** [comment]
Fixed in commit e909b6a
