### ISSUE TITLE
Make Configure support multiple interfaces

### ISSUE THREAD

**Issue by awick** [aol/moloch#613]
If you say eth0;eth1 it should generate the ethool stuff for both.

**Comment by problematiq** [comment]
Can confirm semi-colon separated interfaces work.

**Comment by problematiq** [comment]
Just did an upgrade on a Moloch box with the 0.17.1-3 .deb and using semi-colons and it did not work. 
`  Process: 12648 ExecStartPre=/sbin/ethtool -K em1;em2;em3;em4;p4p1;p4p2;p4p3 lro off (code=exited, status=1/FAILURE)`
When doing a `systemctl status molochcapture.service` it shows all the  ethtool change attemps as FAILURE.
It's strange though, the moloch machine I did with the 0.17.1-1 .deb and using semi-colons worked fine even though the molochcapture.service file looks the same with the exception the interface names.

**Comment by awick** [comment]
If you enter multiple interfacees into Configure, it will create the create config.ini however the systemd/upstart scripts will have incorrect commands in them currently.  They will still start, however what it is trying to do will not work.

This issue is here so someday it is fully supported.

**Comment by problematiq** [comment]
Yeah, just noticed, even with a single interface it's not working. not a problem i'll add it back to the interfaces config. Thanks! Also if you find yourself in OKC USA, sorry, also theres a lot of people here that would like to buy you a beer.

**Comment by awick** [comment]
Fixed in 0.18.2 - c47c784ae8f077e08fc441ac468f1e9a27a50843
