### ISSUE TITLE
v0.18.0 doens't display files sizes

### ISSUE THREAD

**Issue by a3ilson** [aol/moloch#621]
New [FILES] UI doesn't display file sizes.

**Elasticsearch version**: 5.2.0

**Moloch version**: 0.18.0

**OS name and version**: Ubuntu 16.04

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) deb

**Provide logs, stack traces and steps to reproduce**: Followed Basic Install

**Comment by awick** [comment]
its never recorded them unless the file was locked or it would go back if the viewer was on the same instance.  now it should record them for future files.  For old files you can use ./db.pl sync-files if you want, or just wait for them to age out.

If capture crashes it still wont have the right file size for those files.
