### ISSUE TITLE
Right Click - Open in New Tab - of Extracted SPI Data opens a blank Sessions tab

### ISSUE THREAD

**Issue by amaddalena** [aol/moloch#652]
When right-click an SPI Extracted item within a session (example the ID value) and selecting open in new tab a blank session is opened instead of a sessions tab with a query of the id == blah.

**Comment by 31453** [comment]
Are you looking for different behavior than the Permalink button? Or is this the same basic functionality as the Permalink button, just in a new tab instead of the current?

If no the the above, do you expect this to happen for all values? For example, if you right click a protocol value to open in a new tab, do you want to open a new sessions tab with a query of `protocols == blah`?

**Comment by amaddalena** [comment]
It would be great for it to happen with all values as you stated in the
latter, if i right click a protocol and select open in new tab i would like
the new session to contain a query of "protocols == blah". I couldn't
remember if this was allowable in the pre-revision version.

VR
Art Maddalena, CISSP
Sr. Technical Security Engineer // *AOL*
o: 703.265.2292

**Comment by 31453** [comment]
@amaddalena: If there is an existing search expression, should that stay in the new sessions tab? For example, if the search expression is `ip.src == 0.0.0.0`, then you open a new tab for tcp protocol, should it open a sessions tab with `ip.src == 0.0.0.0 && protocols == tcp` or just `protocols == tcp`?

**Comment by amaddalena** [comment]
Yes. I think it should capture the current query as well.

**Comment by 31453** [comment]
I added an open in new tab menu item rather than relying on right clicking. Let me know if this works for you!

**Comment by amaddalena** [comment]
Looks good! Would this be too complicated to add as a menu option on the sessions page as well (instead of just from the SPI view?) I like the naming of open in sessions from the SPI view as well.

As always, thank you!!!

**Comment by 31453** [comment]
Yes, the open in new sessions tab is available from both the sessions, spiview, and spigraph pages.
