### ISSUE TITLE
Moloch UI - Change Tab order from search bar

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#653]
Please make it so that the first tab out of the search bar goes to the Search button

**Comment by 31453** [comment]
What's the use case here? Is it to issue the query after entering an expression? Enter should issue the query. Do you want both options to issue the query?

**Comment by WilliamSalusky** [comment]
Sometimes hitting the enter key does not work. suspect its related to the odd regex/event loop/digest whatever
