### ISSUE TITLE
New UI no longer keeps session stats visible when scrolling down into sessions

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#655]
i.e.
"Showing 1 to 100 of 718 entries (filtered from 3,022,528 total entries)"

![image](https://cloud.githubusercontent.com/assets/125899/23601061/7c66ce86-0241-11e7-8e5a-a50557a74cda.png)

**Comment by 31453** [comment]
@WilliamSalusky Should this also be the case for the spiview tab?
