### ISSUE TITLE
enabling tpacketv3 setting makes moloch drop all traffic

### ISSUE THREAD

**Issue by johnklasa** [aol/moloch#658]
**Elasticsearch version**:
5.1.2
**Moloch version**:
0.17.1
**OS name and version**:
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
3.10.0-514.6.1.el7.x86_64 #1 SMP Sat Dec 10 11:15:38 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
rpm
**Provide logs, stack traces and steps to reproduce**:
Before enabling tpacketv3 setting I can see this in the capture.log and the GUI reports it's capturing and indexing traffic with NO drops. 

Mar  8 10:14:51 packet.c:961 moloch_packet_ip(): packets: 6213800001 current sessions: 9116/10829 oldest: 0 - recv: 1984030561 drop: 41 (0.00) queue: 2 disk: 0 packet: 0 close: 34 ns: 0 frags: 0/0
Mar  8 10:14:51 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 183460/482 0ms 382ms
Mar  8 10:14:52 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 157712/204 0ms 392ms
Mar  8 10:14:52 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 185901/633 0ms 528ms
Mar  8 10:14:52 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 160789/204 0ms 510ms
Mar  8 10:14:52 http.c:269 moloch_http_curlm_check_multi_info(): 7/30 ASYNC 200 http://172.24.5.25:9200/_bulk 196847/924 0ms 330ms
Mar  8 10:14:52 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148441/203 0ms 323ms
Mar  8 10:14:52 http.c:269 moloch_http_curlm_check_multi_info(): 7/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148683/200 0ms 254ms
Mar  8 10:14:52 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148485/202 0ms 160ms
Mar  8 10:14:52 packet.c:961 moloch_packet_ip(): packets: 6213900000 current sessions: 9114/10752 oldest: 0 - recv: 1984130965 drop: 41 (0.00) queue: 5 disk: 0 packet: 0 close: 35 ns: 0 frags: 0/0
Mar  8 10:14:52 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 196662/825 0ms 240ms
Mar  8 10:14:52 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148281/201 0ms 208ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 207805/942 0ms 471ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://172.24.5.25:9200/_bulk 158821/202 0ms 513ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 217130/977 0ms 652ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 163382/320 0ms 247ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 149134/234 0ms 253ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 7/30 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 697/139 0ms 13ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/dstats/dstat/molsto01-898-5 697/142 0ms 13ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 156287/277 0ms 254ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 164578/320 0ms 150ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 143748/201 0ms 85ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://172.24.5.25:9200/_bulk 158022/201 0ms 224ms
Mar  8 10:14:53 packet.c:961 moloch_packet_ip(): packets: 6214000000 current sessions: 9113/10764 oldest: 0 - recv: 1984231358 drop: 41 (0.00) queue: 5 disk: 0 packet: 0 close: 40 ns: 0 frags: 0/0
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 146029/204 0ms 261ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 7/30 ASYNC 200 http://172.24.5.25:9200/_bulk 153132/200 0ms 96ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 7/30 ASYNC 200 http://172.24.5.25:9200/_bulk 143498/202 0ms 113ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 7/30 ASYNC 200 http://172.24.5.25:9200/_bulk 192329/887 0ms 148ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 160817/203 0ms 139ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148331/203 0ms 128ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148406/201 0ms 164ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 158724/203 0ms 236ms
Mar  8 10:14:53 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 146182/202 0ms 218ms
Mar  8 10:14:54 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148228/202 0ms 251ms
Mar  8 10:14:54 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148268/201 0ms 280ms

and after enabling tpacketv3 and moloch doesn't get any packets at all. 
You can see the restarting of the service in the logs here

Mar  8 10:17:39 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 182043/425 0ms 221ms
Mar  8 10:17:39 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 172273/488 0ms 211ms
Mar  8 10:17:39 packet.c:961 moloch_packet_ip(): packets: 6234500000 current sessions: 9069/10635 oldest: 0 - recv: 2004812964 drop: 41 (0.00) queue: 5 disk: 0 packet: 0 close: 68 ns: 0 frags: 0/0
Mar  8 10:17:39 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 157718/200 0ms 250ms
Mar  8 10:17:39 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 157129/320 0ms 265ms
Mar  8 10:17:39 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148684/202 0ms 245ms
Mar  8 10:17:39 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 157718/205 0ms 233ms
Mar  8 10:17:39 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 697/140 0ms 33ms
Mar  8 10:17:39 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 183382/523 0ms 342ms
Mar  8 10:17:39 http.c:269 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://172.24.5.25:9200/_bulk 157978/201 0ms 362ms
Mar  8 10:17:39 http.c:269 moloch_http_curlm_check_multi_info(): 2/30 ASYNC 200 http://172.24.5.25:9200/_bulk 158753/201 0ms 501ms
Mar  8 10:17:40 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 143176/202 0ms 356ms
Mar  8 10:17:40 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 223171/336 0ms 394ms
Mar  8 10:17:40 packet.c:961 moloch_packet_ip(): packets: 6234600000 current sessions: 9068/10696 oldest: 0 - recv: 2004913161 drop: 41 (0.00) queue: 4 disk: 0 packet: 0 close: 75 ns: 0 frags: 0/0
Mar  8 10:17:40 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 215186/811 0ms 411ms
Mar  8 10:17:40 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 179680/499 0ms 328ms
Mar  8 10:17:40 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 157982/198 0ms 329ms
Mar  8 10:17:40 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 141130/203 0ms 311ms
Mar  8 10:17:40 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148276/202 0ms 386ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 157367/200 0ms 463ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148247/202 0ms 372ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 173433/436 0ms 398ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 7/30 ASYNC 200 http://172.24.5.25:9200/_bulk 221806/598 0ms 337ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148167/204 0ms 134ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 697/140 0ms 47ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 173839/339 0ms 178ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 162601/202 0ms 155ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 171141/442 0ms 238ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 153992/200 0ms 219ms
Mar  8 10:17:41 packet.c:961 moloch_packet_ip(): packets: 6234700000 current sessions: 9068/10760 oldest: 0 - recv: 2005013691 drop: 41 (0.00) queue: 2 disk: 0 packet: 0 close: 82 ns: 0 frags: 0/0
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 4/30 ASYNC 200 http://172.24.5.25:9200/_bulk 154248/202 0ms 401ms
Mar  8 10:17:41 http.c:269 moloch_http_curlm_check_multi_info(): 3/30 ASYNC 200 http://172.24.5.25:9200/_bulk 160789/203 0ms 349ms
Mar  8 10:17:42 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 158157/201 0ms 282ms
Mar  8 10:17:42 http.c:269 moloch_http_curlm_check_multi_info(): 6/30 ASYNC 200 http://172.24.5.25:9200/_bulk 159126/297 0ms 263ms
Mar  8 10:17:42 http.c:269 moloch_http_curlm_check_multi_info(): 5/30 ASYNC 200 http://172.24.5.25:9200/_bulk 148606/202 0ms 181ms
Mar  8 10:17:42 main.c:595 main(): THREAD 0x7f88e06fa880
Mar  8 10:17:42 config.c:184 moloch_config_int(): INFO: Reseting pcapWriteSize since 262143 is less then the min 262144
Mar  8 10:17:42 main.c:573 moloch_mlockall_init(): WARNING: memlock in limits.conf must be unlimited or at least 4000000, currently 64
Mar  8 10:17:42 http.c:225 moloch_http_send_sync(): 1/1 SYNC 200 http://172.24.5.25:9200/dstats/version/version/_source 0/15 0ms 1ms
Mar  8 10:17:42 http.c:225 moloch_http_send_sync(): 1/1 SYNC 200 http://172.24.5.25:9200/sequence/sequence/fn-molsto01 0/88 0ms 1ms
Mar  8 10:17:42 http.c:225 moloch_http_send_sync(): 1/1 SYNC 200 http://172.24.5.25:9200/sequence/sequence/fn-molsto01 2/158 0ms 1ms
Mar  8 10:17:42 http.c:225 moloch_http_send_sync(): 1/1 SYNC 200 http://172.24.5.25:9200/tags/tag/_search?size=3000 0/7121 0ms 1ms
Mar  8 10:17:42 http.c:225 moloch_http_send_sync(): 1/1 SYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 0/791 0ms 0ms
Mar  8 10:17:42 http.c:225 moloch_http_send_sync(): 1/1 SYNC 200 http://172.24.5.25:9200/fields/field/_search?size=3000 0/58157 0ms 8ms
Mar  8 10:17:42 writer-simple.c:280 writer_simple_thread(): THREAD 0x7f88b1556700
Mar  8 10:17:42 packet.c:935 moloch_packet_ip(): Initial Packet = 1488964662
Mar  8 10:17:42 packet.c:936 moloch_packet_ip(): 0 Initial Dropped = 0
Mar  8 10:17:42 packet.c:935 moloch_packet_ip(): Initial Packet = 1488964662
Mar  8 10:17:42 packet.c:936 moloch_packet_ip(): 68 Initial Dropped = 0
Mar  8 10:17:42 packet.c:935 moloch_packet_ip(): Initial Packet = 1488964662
Mar  8 10:17:42 packet.c:936 moloch_packet_ip(): 121 Initial Dropped = 0
Mar  8 10:17:42 packet.c:935 moloch_packet_ip(): Initial Packet = 1488964662
Mar  8 10:17:42 packet.c:936 moloch_packet_ip(): 169 Initial Dropped = 0
Mar  8 10:17:42 db.c:1687 moloch_db_create_file_full(): Creating file 146 with key >/files/file/molsto01-146?refresh=true< using >{"num":146, "name":"/data/moloch/raw/molsto01-170308-00000146.pcap", "first":1488964662, "node":"molsto01", "locked":0}<
Mar  8 10:17:42 http.c:430 moloch_http_curl_watch_open_callback(): Connected 2/0 - 172.24.5.25:9200   39990->172.24.5.25:9200 - fd:9
Mar  8 10:17:42 http.c:430 moloch_http_curl_watch_open_callback(): Connected 2/1 - 172.24.5.25:9200   39992->172.24.5.25:9200 - fd:11
Mar  8 10:17:42 http.c:225 moloch_http_send_sync(): 1/1 SYNC 200 http://172.24.5.25:9200/sequence/sequence/fn-molsto01 2/158 0ms 3ms
Mar  8 10:17:42 db.c:1687 moloch_db_create_file_full(): Creating file 147 with key >/files/file/molsto01-147?refresh=true< using >{"num":147, "name":"/data/moloch/raw/molsto01-170308-00000147.pcap", "first":1488964662, "node":"molsto01", "locked":0}<
Mar  8 10:17:42 http.c:269 moloch_http_curlm_check_multi_info(): 3/2 ASYNC 200 http://172.24.5.25:9200/sequence/sequence/fn-molsto01 2/140 0ms 4ms
Mar  8 10:17:42 http.c:225 moloch_http_send_sync(): 1/1 SYNC 200 http://172.24.5.25:9200/sequence/sequence/fn-molsto01 2/158 0ms 1ms
Mar  8 10:17:42 db.c:1687 moloch_db_create_file_full(): Creating file 149 with key >/files/file/molsto01-149?refresh=true< using >{"num":149, "name":"/data/moloch/raw/molsto01-170308-00000149.pcap", "first":1488964662, "node":"molsto01", "locked":0}<
Mar  8 10:17:42 http.c:225 moloch_http_send_sync(): 1/1 SYNC 200 http://172.24.5.25:9200/sequence/sequence/fn-molsto01 2/158 0ms 1ms
Mar  8 10:17:42 db.c:1687 moloch_db_create_file_full(): Creating file 150 with key >/files/file/molsto01-150?refresh=true< using >{"num":150, "name":"/data/moloch/raw/molsto01-170308-00000150.pcap", "first":1488964662, "node":"molsto01", "locked":0}<
Mar  8 10:17:42 http.c:225 moloch_http_send_sync(): 1/1 SYNC 200 http://172.24.5.25:9200/sequence/sequence/fn-molsto01 2/158 0ms 1ms
Mar  8 10:17:42 db.c:1687 moloch_db_create_file_full(): Creating file 151 with key >/files/file/molsto01-151?refresh=true< using >{"num":151, "name":"/data/moloch/raw/molsto01-170308-00000151.pcap", "first":1488964662, "node":"molsto01", "locked":0}<
Mar  8 10:17:42 http.c:430 moloch_http_curl_watch_open_callback(): Connected 5/2 - 172.24.5.25:9200   39994->172.24.5.25:9200 - fd:13
Mar  8 10:17:42 http.c:430 moloch_http_curl_watch_open_callback(): Connected 5/3 - 172.24.5.25:9200   39996->172.24.5.25:9200 - fd:17
Mar  8 10:17:42 http.c:430 moloch_http_curl_watch_open_callback(): Connected 5/4 - 172.24.5.25:9200   39998->172.24.5.25:9200 - fd:18
Mar  8 10:17:42 http.c:269 moloch_http_curlm_check_multi_info(): 5/5 ASYNC 201 http://172.24.5.25:9200/files/file/molsto01-146?refresh=true 119/150 0ms 49ms
Mar  8 10:17:42 http.c:269 moloch_http_curlm_check_multi_info(): 4/5 ASYNC 201 http://172.24.5.25:9200/files/file/molsto01-147?refresh=true 119/150 0ms 45ms
Mar  8 10:17:42 http.c:269 moloch_http_curlm_check_multi_info(): 3/5 ASYNC 201 http://172.24.5.25:9200/files/file/molsto01-149?refresh=true 119/150 0ms 42ms
Mar  8 10:17:42 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 201 http://172.24.5.25:9200/files/file/molsto01-150?refresh=true 119/149 0ms 42ms
Mar  8 10:17:42 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 201 http://172.24.5.25:9200/files/file/molsto01-151?refresh=true 119/149 0ms 42ms
Mar  8 10:17:44 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 691/140 0ms 9ms
Mar  8 10:17:44 packet.c:961 moloch_packet_ip(): packets: 100000 current sessions: 1724/1872 oldest: 0 - recv: 222298 drop: 0 (0.00) queue: 0 disk: 0 packet: 0 close: 9 ns: 0 frags: 0/0
Mar  8 10:17:45 packet.c:961 moloch_packet_ip(): packets: 200000 current sessions: 2338/2520 oldest: 0 - recv: 381040 drop: 0 (0.00) queue: 0 disk: 0 packet: 0 close: 12 ns: 0 frags: 0/0
Mar  8 10:17:46 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 693/139 0ms 12ms
Mar  8 10:17:46 packet.c:961 moloch_packet_ip(): packets: 300000 current sessions: 2902/3192 oldest: 0 - recv: 504293 drop: 0 (0.00) queue: 0 disk: 0 packet: 0 close: 16 ns: 0 frags: 0/0
Mar  8 10:17:47 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 200 http://172.24.5.25:9200/dstats/dstat/molsto01-933-5 694/143 0ms 14ms
Mar  8 10:17:47 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 200 http://172.24.5.25:9200/_bulk 119514/200 0ms 297ms
Mar  8 10:17:47 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 200 http://172.24.5.25:9200/_bulk 119534/200 0ms 371ms
Mar  8 10:17:48 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/_bulk 117347/202 0ms 500ms
Mar  8 10:17:48 packet.c:961 moloch_packet_ip(): packets: 400000 current sessions: 3491/3856 oldest: 0 - recv: 633804 drop: 0 (0.00) queue: 0 disk: 0 packet: 0 close: 16 ns: 0 frags: 0/0
Mar  8 10:17:48 http.c:269 moloch_http_curlm_check_multi_info(): 4/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 694/139 0ms 18ms
Mar  8 10:17:48 http.c:269 moloch_http_curlm_check_multi_info(): 3/5 ASYNC 200 http://172.24.5.25:9200/_bulk 117335/201 0ms 267ms
Mar  8 10:17:48 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 200 http://172.24.5.25:9200/_bulk 123650/202 0ms 266ms
Mar  8 10:17:48 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/_bulk 115881/202 0ms 469ms
Mar  8 10:17:49 packet.c:961 moloch_packet_ip(): packets: 500000 current sessions: 3915/4323 oldest: 0 - recv: 754961 drop: 0 (0.00) queue: 0 disk: 0 packet: 0 close: 13 ns: 0 frags: 0/0
Mar  8 10:17:49 http.c:269 moloch_http_curlm_check_multi_info(): 4/5 ASYNC 200 http://172.24.5.25:9200/_bulk 4891/275 0ms 118ms
Mar  8 10:17:49 http.c:269 moloch_http_curlm_check_multi_info(): 3/5 ASYNC 200 http://172.24.5.25:9200/_bulk 124341/201 0ms 280ms
Mar  8 10:17:49 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 200 http://172.24.5.25:9200/_bulk 119244/206 0ms 279ms
Mar  8 10:17:49 http.c:269 moloch_http_curlm_check_multi_info(): 3/5 ASYNC 200 http://172.24.5.25:9200/_bulk 120320/202 0ms 255ms
Mar  8 10:17:50 http.c:269 moloch_http_curlm_check_multi_info(): 3/5 ASYNC 200 http://172.24.5.25:9200/_bulk 124055/201 0ms 345ms
Mar  8 10:17:50 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 200 http://172.24.5.25:9200/_bulk 125684/203 0ms 394ms
Mar  8 10:17:50 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 200 http://172.24.5.25:9200/_bulk 125882/200 0ms 446ms
Mar  8 10:17:50 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 699/139 0ms 25ms
Mar  8 10:17:52 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 687/139 0ms 28ms
Mar  8 10:17:52 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/dstats/dstat/molsto01-934-5 700/143 0ms 28ms
Mar  8 10:17:54 http.c:269 moloch_http_curlm_check_multi_info(): 5/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 687/139 0ms 32ms
Mar  8 10:17:54 http.c:269 moloch_http_curlm_check_multi_info(): 4/5 ASYNC 200 http://172.24.5.25:9200/_bulk 124042/198 0ms 434ms
Mar  8 10:17:54 http.c:269 moloch_http_curlm_check_multi_info(): 3/5 ASYNC 200 http://172.24.5.25:9200/_bulk 125969/199 0ms 434ms
Mar  8 10:17:54 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 200 http://172.24.5.25:9200/_bulk 121234/202 0ms 484ms
Mar  8 10:17:54 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/_bulk 120025/201 0ms 484ms
Mar  8 10:17:56 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 687/139 0ms 37ms
Mar  8 10:17:57 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/dstats/dstat/molsto01-935-5 687/143 0ms 39ms
Mar  8 10:17:58 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 687/140 0ms 41ms
Mar  8 10:18:00 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 687/139 0ms 44ms
Mar  8 10:18:02 http.c:269 moloch_http_curlm_check_multi_info(): 2/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 687/139 0ms 47ms
Mar  8 10:18:02 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/dstats/dstat/molsto01-936-5 687/143 0ms 47ms
Mar  8 10:18:04 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 687/140 0ms 51ms
Mar  8 10:18:06 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 687/139 0ms 5ms

**Comment by awick** [comment]
The drop:  lines mean it IS getting packets.  Such as
```Mar 8 10:17:48 packet.c:961 moloch_packet_ip(): packets: 400000 current sessions: 3491/3856 oldest: 0 - recv: 633804 drop: 0 (0.00) queue: 0 disk: 0 packet: 0 close: 16 ns: 0 frags: 0/0```

Wrong log file?

if still having issues please provide the output of --debug

**Comment by johnklasa** [comment]
no it's  the correct logfile. I showed before I enabled tpacketv3 and after.
After enabling tpacketv3 the logfile does not log any entries like these: 
Mar 8 10:14:53 packet.c:961 moloch_packet_ip(): packets: 6214000000 current sessions: 9113/10764 oldest: 0 - recv: 1984231358 drop: 41 (0.00) queue: 5 disk: 0 packet: 0 close: 40 ns: 0 frags: 0/0

After enabling tpacketv3 the capture.log file only show log entires like these: 
Mar 8 10:18:04 http.c:269 moloch_http_curlm_check_multi_info(): 1/5 ASYNC 200 http://172.24.5.25:9200/stats/stat/molsto01 687/140 0ms 51ms

And stats web GUI shows NO packets in and just packet/drops

**Comment by awick** [comment]
What time did you restart it?  As far as I can tell it was at 

Mar 8 10:17:42

the log entry I posted was

Mar 8 10:17:48

Anyway, can you post JUST the log file of the failure with --debug please

**Comment by johnklasa** [comment]
[capture.zip](https://github.com/aol/moloch/files/827854/capture.zip)
![drops-2](https://cloud.githubusercontent.com/assets/25666109/23707606/4b87c04e-0413-11e7-8867-cc49af297322.png)

**Comment by johnklasa** [comment]
![no-drops](https://cloud.githubusercontent.com/assets/25666109/23707836/1a6868f0-0414-11e7-86dc-e1e9974fa4f2.PNG)

**Comment by awick** [comment]
looks like an issue with multiple interfaces and tpacketv3.

**Comment by johnklasa** [comment]
it's there a workaround? Can I start several molochcapture instances?

**Comment by awick** [comment]
i thought you said you had libpcap working? can you use that for now?  I haven't had time to really dig into the problem yet.

**Comment by johnklasa** [comment]
yes sorry of course. I meant workaround for tpacketv3 and multiple interfaces

**Comment by awick** [comment]
i'm only guessing what the issue is.  you could run multiple instances of capture.  you could verify that this is actually the issue by seeing if it works with just one interface.

**Comment by johnklasa** [comment]
This seems to have fixed it. running separate instances for each interface fixed it. Thanks.
