### ISSUE TITLE
LINKTYPE_RAW value

### ISSUE THREAD

**Issue by lhmerino** [aol/moloch#661]
**Elasticsearch version**: 2.4.0

**Moloch version**:0.18.0-GIT

**OS name and version**: Ubuntu 16.04

**How was Moloch built/installed:**: easybutton-singlehost

In packet.c, I believe case 12 (RAW) for the switch(pcapFileHeader.linktype) should be instead case 101.

The link below is from tcpdump.org specifying that LINKTYPE_RAW has value 101. 
http://www.tcpdump.org/linktypes.html

Regards

**Comment by awick** [comment]
I'm sure 12 was added because it was seen somewhere.  Are you having an issue or is this just theoretical?

**Comment by lhmerino** [comment]
Hello, 

Yes I did have issues with my interface. I kept getting "Error - Unsupported pcap link type 101". I decided to examined packet.c and saw that there was no case for 101 so I decided to find out what 101 was. Searching for 101 online, I found the website link above from tcpdump indicating that it was link type RAW. Then I did a tcpdump on the same interface and it specifically said it was Link Type RAW (just to confirm).  Looking at moloch's packet.c, I found the comment for RAW but with case 12 so I decided to replace 12 with 101. Now, it works perfectly fine.

P.S. As a future request, could Link type NFLOG be added as well since dropped packets from the firewall are never seen by the interface on the way out.

Regards

**Comment by awick** [comment]
nflog capture works, but viewer won't show the packets.  This won't be implemented until pcapng is better.

**Comment by lhmerino** [comment]
Thank you very much!

**Comment by pavja2** [comment]
Related to this issue, I had the same unsupported PCAP link type error for type 228 (Raw IPv4). I was able to correct the error by manually editing the 20th byte of my PCAP file from 0xe4 to 0x65 but this could probably be added to the packet.c switch statement as well.
