### ISSUE TITLE
Attempt with easybutton-singlehost.sh

### ISSUE THREAD

**Issue by Kame160** [aol/moloch#663]
Hi,

I am looking for a quick way to install a simple, single host version of moloch for test purpose.
I attempt to install a singlehost version by launching the easybutton-singlehost on a Ubuntu 16.04.2 LTS xenial server. 

Just to be clear a new ubuntu 16.04, after update of apt-get and install of git & default-jdk & jre, I just clone https://github.com/aol/moloch.git & then launch easybutton-singlehost.sh & answer yes to the question "use pfring pcap bridge" which return a fatal error "prfing.h no such file".
log and printscreen attached
[npm-debug.txt](https://github.com/aol/moloch/files/851896/npm-debug.txt)
<img width="377" alt="printscreen moloch" src="https://cloud.githubusercontent.com/assets/6997425/24064807/07ce4778-0b67-11e7-8d6c-ac7ccafd781d.PNG">

I would like to be able to set up a standalone working station but if anyone could provide me with a working vm for testing purpose - it could also be a starting solution.

Thanks in advance,

**Comment by awick** [comment]
whats wrong with the rpm or deb?

**Comment by Kame160** [comment]
I did'n dl nor the rpm nor the deb but cloned the all git (https://github.com/aol/moloch.git) and then simply launch your easybutton-singlehost.sh script

**Comment by awick** [comment]
ok try those
