### ISSUE TITLE
Themes 1.0

### ISSUE THREAD

**Issue by awick** [aol/moloch#665]
We will get this wrong, so don't worry about perfect

* Think Slack themes
* There should be a few predefined themes
* A user should be able to create a custom theme
  * There should be 4-6 colors that are specified
  * Lighter/darker versions of the colors should be generated
* Basic preview

Future functionality
* Themes include more than just colors
* Admin can set default theme that user can override
* Create/Save themes
* Share themes

**Comment by 31453** [comment]
Implemented in commit 9837c21
