### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by smersh2009** [aol/moloch#666]
**Elasticsearch version*5.2*:

**Moloch version*0.18.1*:

**OS name and version* ubuntu 16*:

**How was Moloch built/installed:**, singlehost built,
clear build ubuntu 16
first run  easybutton_build.sh

lua.c:82:31: fatal error: readline/readline.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'lua.o' failed
make[2]: *** [lua.o] Error 1
make[2]: Leaving directory '/home/server/moloch/thirdparty/lua-5.3.4/src'
Makefile:110: recipe for target 'linux' failed
make[1]: *** [linux] Error 2
make[1]: Leaving directory '/home/server/moloch/thirdparty/lua-5.3.4/src'
Makefile:55: recipe for target 'linux' failed
make: *** [linux] Error 2
MOLOCH: make failed

second run easybutton_build.sh -> OK

error run make install
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in bindin                                          g.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.j                                          s:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                          s.js:200:12)
gyp ERR! System Linux 4.4.0-63-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /data/moloch/wiseService/node_modules/hashtable
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 4.4.0-63-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashtable@2.0.2 install script 'node-gyp configure build'                                          .
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hashtable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hashtable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hashtable
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/moloch/wiseService/npm-debug.log
Makefile:22: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/home/server/moloch/capture/plugins'
Makefile:58: recipe for target 'installdirs' failed
make[1]: *** [installdirs] Error 2
make[1]: Leaving directory '/home/server/moloch/capture'
Makefile:321: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by awick** [comment]
I think node 4.2.6 might be too old, and looks like we need to add a readline dep

**Comment by awick** [comment]
should be fixed now
