### ISSUE TITLE
Large messages causing ES queue jam

### ISSUE THREAD

**Issue by stoomart** [aol/moloch#667]
**Elasticsearch version**:  2.4

**Moloch version**:  0.17.1

**OS name and version**:  CentOS 7.3.1611 x86_64

**How was Moloch built/installed:** rpm

**Provide logs, stack traces and steps to reproduce**:  Moloch ran well on version 0.17.1 for a couple months here, but over the last few weeks the ES queue has been backing up, requiring a restart of the capture service. Review of the ES and capture logs shows the appearance of the following two log events at the time the issue began yesterday. The ES log event corresponded to the queue filling up 4 times this week, and this morning the capture log event seemed to cause the same queue buildup without the presence of the ES log event.

molochcapture.log:

`Mar 22 13:09:20 db.c:1082 moloch_db_save_session(): WARNING - 170322-6T-c2h6CwvBP16Kqyj-HemRS BIGGER then expected json 27374 60607`

elasticsearch\Moloch.log:

`[2017-03-22 13:09:52,483][DEBUG][action.bulk]...java.lang.IllegalArgumentException: Document contains at least one immense term in field="rawus" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[removed]...', original message: bytes can be at most 32766 in length; got 50157`

[full_es_event.txt](https://github.com/aol/moloch/files/865470/full_es_event.txt)
[http_event.txt](https://github.com/aol/moloch/files/865469/http_event.txt)

**Comment by awick** [comment]
should be fixed now

**Comment by stoomart** [comment]
Upgrading to 0.18.0 and ES 5.2.2 has our system running very well, even without the truncation fix in yet. Thanks again for your excellent work.
