### ISSUE TITLE
Other Decodings

### ISSUE THREAD

**Issue by SparkyNZL** [aol/moloch#670]
**Elasticsearch version**: 5.2

**Moloch version**: 18.1

**OS name and version**: Ubuntu 16.04

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) deb package, single host

**Provide logs, stack traces and steps to reproduce**:

The "Other Decodings" is no longer working  when looking at the packet data :(

**Comment by awick** [comment]
Ya, known issue and on the list to add back.  For now you can use /sessions.old to get the old interface
