### ISSUE TITLE
SPI View: Elasticsearch error

### ISSUE THREAD

**Issue by pwo** [aol/moloch#671]
**Elasticsearch version**: 5.2.2

**Moloch version**: 0.18.2-GIT

**OS name and version**: CentOS 7

**How was Moloch built/installed:** rpm

**Provide logs, stack traces and steps to reproduce**:
SPI View / dns / try to load "ASN Tokens" results in:
Elasticsearch error: [illegal_argument_exception] Fielddata is disabled on text fields by default. Set fielddata=true on [asdnsip] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory

![image](https://cloud.githubusercontent.com/assets/506619/24675334/031059c6-197f-11e7-95e6-2bbf9eec755e.png)

**Comment by awick** [comment]
This is an ES 5 upgrade issue.  The plan is to just remove tokens from moloch everywhere.  Would you have an issue with that?

**Comment by pwo** [comment]
None whatsoever.

**Comment by awick** [comment]
Fix in 1.0
