### ISSUE TITLE
Connections: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pwo** [aol/moloch#674]
**Elasticsearch version**: 5.2.2

**Moloch version**: 0.18.2-GIT

**OS name and version**: CentOS 7

**How was Moloch built/installed:** rpm

**Provide logs, stack traces and steps to reproduce**:
Connections / Src: ip.src | Dst: asn.dst
results in: Error retrieving data: TypeError: Cannot read property 'length' of undefined

![image](https://cloud.githubusercontent.com/assets/506619/24676225/74dc4e9a-1982-11e7-8c69-a1fbdef58f80.png)

**Comment by 31453** [comment]
What is your query expression in the search bar?

What is the response from connections.json in the Network tab of the browser's console window?

**Comment by 31453** [comment]
This commit provides a better error message for the connections page: 5db63ad
