### ISSUE TITLE
Viewer - stats page tabs

### ISSUE THREAD

**Issue by BaconFries** [aol/moloch#682]
I'm running 0.18.2. In the stats view with a large number of nodes (over 150) the page gets unwieldy. It falls behind on updates and is slow to respond.

 It would be useful to be able to adjust the update frequency. It would also help to break each section apart into their own tabs. I think this would help keep it updating quickly and prevent the browser from blowing up as well as let you focus on just what you want to see.

**Comment by awick** [comment]
* I think a no refresh/5/10/30 type options for refresh interval would be useful
* Section top tabs would be good, although I kind of like the graph and table for nodes in one view, but I can understand switching.  Maybe collapsable sections?  See what @31453  says. :)
* I think need a node search filter for the graph section (or if keeping the table and graph together they should use the same search) would really help.

**Comment by BaconFries** [comment]
All great ideas. Thanks!

**Comment by 31453** [comment]
Please provide feedback on this fix if necessary.
