### ISSUE TITLE
Viewer - crash/restart

### ISSUE THREAD

**Issue by packetrevolt** [aol/moloch#687]
**Elasticsearch version**: 5.4.0

**Moloch version**: 0.18.2

**OS name and version**: CentOS 7

**How was Moloch built/installed:** rpm

**Provide logs, stack traces and steps to reproduce**:

View the default view on the Stats tab.

Mon, 08 May 2017 19:49:15 GMT - ^[[1mGET^[[0m ^[[33m/stats.json?desc=false&length=50&sortField=nodeName&start=0^[[0m 200 936 bytes 10.611 ms
/data/moloch/viewer/viewer.js:2391
        read = Math.ceil((node.fs.io_stats.total.read_kilobytes - oldnode.fs.io_stats.total.read_kilobytes)/timediffsec*1024);
                                                ^

TypeError: Cannot read property 'read_kilobytes' of undefined
    at /data/moloch/viewer/viewer.js:2391:49
    at /data/moloch/viewer/node_modules/async/dist/async.js:3824:9
    at /data/moloch/viewer/node_modules/async/dist/async.js:460:16
    at iterateeCallback (/data/moloch/viewer/node_modules/async/dist/async.js:965:24)
    at /data/moloch/viewer/node_modules/async/dist/async.js:944:16
    at /data/moloch/viewer/node_modules/async/dist/async.js:3821:13
    at apply (/data/moloch/viewer/node_modules/async/dist/async.js:21:25)
    at /data/moloch/viewer/node_modules/async/dist/async.js:56:12
    at /data/moloch/viewer/db.js:272:91
    at respond (/data/moloch/viewer/node_modules/elasticsearch/src/lib/transport.js:310:9)
Express server listening on port 8005 in development mode

**Comment by awick** [comment]
This was fixed in 0.18.3 hopefully.  Let us know if you still have issues
