### ISSUE TITLE
Doesn't add quotes around ASN from SPI view

### ISSUE THREAD

**Issue by barrelman70** [aol/moloch#694]
**Elasticsearch version**: 2.4

**Moloch version**: 0.18.2

**OS name and version**: Ubuntu 16.04

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) easybutton

**Provide logs, stack traces and steps to reproduce**:
When including or excluding an ASN name from SPI, it doesn't put quotes around the entry.  This causes a search error.

```
 Error retrieving data: Error: Parse error on line 1:
...& asn.dst != AS7743 JPMorgan Chase & Co.
-----------------------^
Expecting 'EOF', '&&', '||', ')', got 'STR' 
```

it does appear to work (it adds the quotes) when doing it from the session screen

**Comment by barrelman70** [comment]
Seems to also apply to the quic useragent in SPI and the http useragent in both SPI and Sessions.  Trying to think of what other fields may have spaces in them...

**Comment by barrelman70** [comment]
In case this is a per field fix, here are some more

cert issuer cn
cert subject on
cert issuer on
email asn
email content-type
email subject
email x-mailer header
ssh version
http xff asn

**Comment by 31453** [comment]
👍  Thanks for the details!
