### ISSUE TITLE
Fix for: elasticsearch error: [illegal_argument_exception] Fielddata is disabled on text fields by default.  set field data=true on [g1]

### ISSUE THREAD

**Issue by Capitolxx** [aol/moloch#696]
**Elasticsearch version**: 5.2.2

**Moloch version**: 0.19

**OS name and version**: CentOS 7

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) : single host with git clone easy button build. New build with out existing DB from a earlier build.

**Provide logs, stack traces and steps to reproduce**:
Moloch Viewer -> Session is blank, below error occures on SPI Graph and SPI View.
elasticsearch error: [illegal_argument_exception] Fielddata is disabled on text fields by default.  set field data=true on [g1]

I fixed this with the following command:

curl -XPUT http://localhost:9200/fields_v1/field/country.src -d '{
 "friendlyName": "Src Country",
"group": "general",
            "help": "Source Country",
            "type": "uptermfield",
            "dbField": "g1",
            "category": "country",
             "fielddata": true
    
    }'

**Comment by awick** [comment]
That shouldn't actually do anything because you are setting fielddata inside the record moloch uses to describe fields and not the mapping itself.

**Comment by awick** [comment]
Moloch 1.0 no longer has text fields
