### ISSUE TITLE
extend API to allow file extractions using md5 

### ISSUE THREAD

**Issue by c040** [aol/moloch#703]
Extend the API to allow file extraction using MD5 hash value.

Pass an MD5 hash value as a request and return the file metadata with raw file

**Comment by VitorFalcao** [comment]
Hi, I would like to start contributing to this project and this issue seems interesting. Could someone please confirm that this feature should be implemented and give me some pointers on how to do so? Thank you

**Comment by awick** [comment]
Added in 1.6.0
