### ISSUE TITLE
SSL/TLS client fingerprinting integration with capture

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#706]
https://github.com/salesforce/ja3

@awick

**Comment by WilliamSalusky** [comment]
Store each of the generated fields uniquely in addition to the md5 hash of the CSV record set per each SSL/TLS session. 

SSLVersion,Cipher,SSLExtension,EllipticCurve,EllipticCurvePointFormat

No trailing or intermediary whitespace should be factored into hash generation. Important for compatibility with original bro, python and future suricata implementation.

Second phase will be to support tagging of SSL/TLS sessions based on shared/discovered JA3 hashes.

**Comment by awick** [comment]
first version done
