### ISSUE TITLE
Feature/Enhancement Request: Copy to clipboard in the drop down menu's.

### ISSUE THREAD

**Issue by problematiq** [aol/moloch#707]
Taking an IP address or MAC or any other field that is now a drop down menu is still possible but it ends up grabbing extra spaces or characters or becomes a bit of a pain. It would be nice that at the bottom of the drop down menu's, there would be a button "Copy to clipboard".

**Comment by problematiq** [comment]
The only options I get are copy link location. Using Chrome on windows 7 and windows 10 machines. In sessions tab when trying to copy a MAC or a IP or ect.

**Comment by awick** [comment]
Looks like a windows only issue, will look into it
