### ISSUE TITLE
Feature/Enhancement Request: Option to turn off auto complete.

### ISSUE THREAD

**Issue by problematiq** [aol/moloch#708]
Auto complete has been a god sent for our newer guys. Our guys that know the syntax by heart on the other hand it annoys just be cause there is a slight lag when typing as it tries to refill the auto complete window after every key stroke. It would be great to be able to have a check box in the settings window to turn that off. I apologize if there is an option and i'm just not seeing it.

OS: Windows 7 / 10
Browser: Chrome

**Comment by awick** [comment]
I would rather fix it so it works better, but if we can't get it there then an option to turn off might be the last resort

**Comment by 31453** [comment]
I have removed a bit of the lagginess in the autocomplete typeahead in commit 9b66f2f. Please let me know if this fixes your issues or if you would still prefer to have a "toggle" for autocomplete results.
