### ISSUE TITLE
S3 viewer plugin not included in latest RPM package

### ISSUE THREAD

**Issue by slapula** [aol/moloch#716]
I've been trying to implement the S3 functionality over the past couple days and I found my viewer node was unable to read data on S3.  I checked `viewer.log` and saw that the service was complaining about being unable to find the S3 viewer plugin `writer-s3/index.js`.  I talked to @awick on Slack and he mentioned that the related files are missing from the RPM.

**Moloch version**:
0.19.1

**OS name and version**:
CentOS 7

**How was Moloch built/installed:** 
RPM

**Provide logs, stack traces and steps to reproduce**:
Duplicating this simply requires one to install Moloch using RPM then follow the instructions in the Wiki. You will not be able  to view S3 data with a valid configuration and if you check `viewer.log` the error message is pretty explicit.

**Comment by awick** [comment]
fixed in nightly

**Comment by slapula** [comment]
Thanks!
