### ISSUE TITLE
ERROR - Moloch requires full packet captures

### ISSUE THREAD

**Issue by DrJohn1** [aol/moloch#721]
**Elasticsearch version**: 2.4.5
**Moloch version**: 0.19.1
**OS name and version**: Ubuntu 16.04.2 Server
**How was Moloch built/installed:** deb
**Provide logs, stack traces and steps to reproduce**: random, upon receiving a truncated package.

One of our moloch-capture nodes randomly shuts down displaying the following error message on the log:
```
Jul 17 08:19:42 reader-libpcap.c:58 reader_libpcap_pcap_cb(): ERROR - Moloch requires full packet captures caplen: 16384 pktlen: 16446
turning offloading off may fix, something like 'ethtool -K INTERFACE tx off sg off gro off gso off lro off tso off'
```

We have identified it is caused by truncated packets, however using **readTruncatedPackets** in "_etc/config.ini_" does not work.

As a fix/workaround we found that **readTruncatedPackets** is used on _capture/reader-libpcap-file.c_ but not on _capture/reader-libpcap.c_. By adding the _same_ checks (`if (!config.readTruncatedPackets) {`,) to the file _capture/reader-libpcap.c_, the crash no longer occurs. 

I show the changes I mean in the following lines (**52**, **56-60**):

```
...
49 void reader_libpcap_pcap_cb(u_char *batch, const struct pcap_pkthdr *h, const u_char *bytes)
50 {
51    if (unlikely(h->caplen != h->len)) {
52        if (!config.readTruncatedPackets) {
53            LOGEXIT("ERROR - Moloch requires full packet captures caplen: %d pktlen: %d\n"
54            "turning offloading off may fix, something like 'ethtool -K INTERFACE tx off sg off gro off gso off lro off tso off'",
55            h->caplen, h->len);
56        }
57        packet->pktlen     = h->caplen;
58    } else {
59        packet->pktlen     = h->len;
60    }
...
```
and removing:
```
...
66    packet->pktlen = h->len;
...
```

I post it in case it can be useful and implemented or if a better solution may be possible.

Thanks!!

**Comment by awick** [comment]
While this is documented several places I've combined into a FAQ answer https://github.com/aol/moloch/wiki/FAQ#Moloch_requires_full_packet_captures_error

**Comment by KrishnaPG** [comment]
Thanks for the FAQ. I am getting the same error while loading a saved pcap file (I have no control over the capturing process). So, tried the below option
````
If you are reading from a file you can set readTruncatedPackets=true in the config file, this is the only solution for saved .pcap files
````
But no change in the error. What am I doing wrong?

- I have set the `readTruncatedPackets=true` option in the `/data/moloch/etc/config.ini` file - is this the correct config file?
- I have restarted the viewer and capture services (using the `systemctl restart` command) and then run the capture command to load the pcap file (`/moloch-capture -r <pcap-file-path> `)

**Comment by awick** [comment]
* What version of moloch
* What is the full error
* Use --debug with capture and make sure it sees readTruncatedPackets as true

**Comment by KrishnaPG** [comment]
This is latest `Moloch 0.19.1` downloaded from http://molo.ch/#downloads on fresh ubuntu 16.04

I used the `--debug` option and to my surprise it says 
````
Aug  8 11:32:29 config.c:244 moloch_config_boolean(): readTruncatedPackets=false
````
But I could see the setting value to be set to true in the `data/moloch/etc/config.ini` file. I have set the below line at the end of that filie
````
readTruncatedPackets=true
````

For some reason the `moloch-capture` application is not using that setting. I am running the capture with the below command:
````
./moloch-capture --debug -r ~/shark/audio.pcap
````

The full error is:
````
Aug  8 11:32:29 reader-libpcap-file.c:369 reader_libpcapfile_pcap_cb(): ERROR - Moloch requires full packet captures caplen: 50 pktlen: 92. If using tcpdump use the "-s0" option, or set readTruncatedPackets in ini file
````

**Comment by awick** [comment]
Remember its an ini file, the end of the file might end up in a different section
