### ISSUE TITLE
Disable capture ENTIRELY & only read PCAP files

### ISSUE THREAD

**Issue by wjhendr** [aol/moloch#722]
Hello,

I want to run the moloch-capture daemon, but have it ONLY read PCAP files that I manually give it.  I do not want it to do LIVE packet capture.  I leave "interface=" blank in config.ini, I am not sure if that is the proper way to do it (could find no documentation related to this).

I don't know if this is related, but when I run moloch-capture this way, I see:

> writer-simple.c:390 writer_simple_init(): INFO: Reseting pcapWriteSize to 22144 since it must be a multiple of 4096

and then it segfaults.

CentOS 7.3.1611/64-bit
moloch-0.19.1-1
elasticsearch-5.4.3-1

**Comment by awick** [comment]
https://github.com/aol/moloch/wiki/FAQ#How_do_I_import_existing_PCAPs  should help

**Comment by wjhendr** [comment]
Andy,

Thanks for the speedy and helpful reply.  I've run across that before and I
do use that syntax manually.  However, I'd like the moloch-capture daemon
always be running, and have it ingest the PCAP files whenever they are put
into the monitored dir.  So is "interface=" in config.ini the right way to
go?

Also, should I open a new ticket regarding the segfault question?

Thanks,
-bill

**Comment by awick** [comment]
You want the monitor option from the help

```
Usage:
  moloch-capture [OPTION?] - capture

Help Options:
  -h, --help         Show help options

Application Options:
  -c, --config       Config file name, default '/data/moloch/etc/config.ini'
  -r, --pcapfile     Offline pcap file
  -R, --pcapdir      Offline pcap directory, all *.pcap files will be processed
  -m, --monitor      Used with -R option monitors the directory for closed files
  --delete           In offline mode delete files once processed, requires --copy
  -s, --skip         Used with -R option and without --copy, skip files already processed
  --recursive        When in offline pcap directory mode, recurse sub directories
  -n, --node         Our node name, defaults to hostname.  Multiple nodes can run on same host
  -t, --tag          Extra tag to add to all packets, can be used multiple times
  --op               FieldExpr=Value to set on all session, can be used multiple times
  -v, --version      Show version number
  -d, --debug        Turn on all debugging
  -q, --quiet        Turn off regular logging
  --copy             When in offline mode copy the pcap files into the pcapDir from the config file
  --dryrun           dry run, nothing written to databases or filesystem
  --flush            In offline mode flush streams between files
```
