### ISSUE TITLE
Add Globe (Geo Location) Map Back to Session Tab

### ISSUE THREAD

**Issue by a3ilson** [aol/moloch#724]
**Elasticsearch version**: 5.5.1

**Moloch version**: 19.1

**OS name and version**: Ubuntu 17.04

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) RPM

**Provide logs, stack traces and steps to reproduce**: n/a

Preferred the Geo Map Globe on the Session Tab...any chance it can be in both tabs...I find it useful in both locations.

**Comment by 31453** [comment]
There should still be a map on the Sessions Tab. However, if the map is collapsed/hidden/closed, there should be a button (with a globe icon) to show the map on the top right corner of the sessions graph. Do you not see this button? Maybe a screenshot would help to visualize your problem.

Also, what do you mean by "be in both tabs" and "useful in both locations"? Which other tab/location are you referring to?

**Comment by a3ilson** [comment]
I've attached referenced screen captures.  The session tab does not contain the map nor a globe icon but they are present on the SPI tab.

Please advise.


![spi](https://user-images.githubusercontent.com/16884679/28995728-e35d7b4a-79be-11e7-88d5-9996ea84c975.png)
![session tab](https://user-images.githubusercontent.com/16884679/28995727-e35cc4e8-79be-11e7-9f12-16d0c130fe9e.png)

**Comment by 31453** [comment]
Thanks for the screen shots! This issue has been fixed in a previous commit: f166115

Please let me know if that does not fix your problem!
