### ISSUE TITLE
Parser/Classifier for yara-matching session data 

### ISSUE THREAD

**Issue by jpvlsmv** [aol/moloch#726]
Wishlist item -- extend yara scan beyond a single packet as discussed in Slack.

"do it as a parser/classifier that just watched everything" [that] would probably be easier, compared to my suggestion of a plugin similar to parsers/http.c

**Comment by jpvlsmv** [comment]
Here are some pcaps and yara rules for testing:

yara-eicar-{http,netcat}.pcap should hit on "eicar".  This was just "grab a file over an easy network protocol"

yara-execs-ftp.pcap should hit on just about everything.  I transferred many files over ftp.



[yara-examples.zip](https://github.com/aol/moloch/files/1209303/yara-examples.zip)

**Comment by awick** [comment]
These seem to already work with the current yara implementation

**Comment by awick** [comment]
@jpvlsmv do you have examples that don't work?

**Comment by awick** [comment]
Closing for now, feel free to reopen with more info
