### ISSUE TITLE
Disk IO issues and segmentation faults AFTER upgrading from 0.18.2 -> 0.19.1

### ISSUE THREAD

**Issue by ccpptt** [aol/moloch#727]
Just upgraded from 0.18.2 to 0.19.1 and I'm having issues getting it back up and running.

On 0.18.2 everything had been running smoothly since release up until a few hours ago when I decided to upgrade to 0.19.1. Now I'm getting disk IO related packet loss. 

The capture logs are filled with disk IO warnings like:

> Aug 9 15:46:57 writer-disk.c:305 writer_disk_flush(): WARNING - 20800 output buffers waiting, disk IO system too slow?

Which eventually lead to segfaults like:

> 
> Segmentation fault (core dumped)
> Aug  9 15:47:12 main.c:609 main(): THREAD 0x7f5de16c7780
> Aug  9 15:47:16 writer-disk.c:404 writer_disk_init(): WARNING - pcapWriteMethod of thread is depreciated, please switch to pcapWriteMethod=simple

> Aug  9 16:51:27 packet.c:969 moloch_packet_ip(): WARNING - Packet Q 12 is overflowing, total dropped 1, increase packetThreads or maxPacketsInQueue
Segmentation fault (core dumped)

We have been using pcapWriteMethod=thread without issue since it was provided as a suggestion by Andy in [1] due to our ZFS setup.

Our config file: 

```
Number of threads processing packets
packetThreads = 16
tpacketv3NumThreads = 4
maxPacketsInQueue = 200000

pcapWriteSize = 262144
```

And here's a DD on the disk (just want to re-iterate here that everything was functioning perfectly before the upgrade):

```
sudo dd bs=256k count=50k if=/dev/zero of=/data/test
51200+0 records in
51200+0 records out
13421772800 bytes (13 GB, 12 GiB) copied, 3.05173 s, 4.4 GB/s
```

[1] https://groups.google.com/forum/#!searchin/moloch-fpc/simple%7Csort:relevance/moloch-fpc/EDMhZ0WXRzY/sYqafe3RCgAJ

**Elasticsearch version**: 5.2.2

**Moloch version**: 0.19.1

**OS name and version**: Ubuntu 16.04

**How was Moloch built/installed:** deb

**Provide logs, stack traces and steps to reproduce**:

Upgraded our perfectly working instance from 0.18.2 to 0.19.1 via the prebuilt .deb from molo.ch.

Starting capture now results in large volumes of disk IO warnings which eventually lead to segfaults. Considerable amount of packet drops stemming from these new disk IO issues. 

Some logs:

> Aug  9 16:45:03 main.c:609 main(): THREAD 0x7f3e9760f780
> Aug  9 16:45:04 writer-disk.c:404 writer_disk_init(): WARNING - pcapWriteMethod of thread is depreciated, please switch to pcapWriteMethod=simple
> Aug  9 16:45:04 writer-disk.c:205 writer_disk_output_thread(): THREAD 0x7f3e520ce700
> Aug  9 16:45:04 packet.c:933 moloch_packet_ip(): Initial Packet = 1502253903
> Aug  9 16:45:04 packet.c:934 moloch_packet_ip(): 0 Initial Dropped = 0
> ...
> ...
> ...
> Aug  9 16:45:12 packet.c:959 moloch_packet_ip(): packets: 7000000 current sessions: 19069/99988 oldest: 0 - recv: 7044308 drop: 0 (0.00) queue: 5 disk: 297 packet: 259 close: 7498 ns: 0 frags: 0/219
> Aug  9 16:45:12 writer-disk.c:305 writer_disk_flush(): WARNING - 300 output buffers waiting, disk IO system too slow?
> Aug  9 16:45:12 writer-disk.c:305 writer_disk_flush(): WARNING - 300 output buffers waiting, disk IO system too slow?
> Aug  9 16:45:13 writer-disk.c:305 writer_disk_flush(): WARNING - 350 output buffers waiting, disk IO system too slow?
> Aug  9 16:45:13 writer-disk.c:305 writer_disk_flush(): WARNING - 400 output buffers waiting, disk IO system too slow?
> Aug  9 16:45:13 writer-disk.c:305 writer_disk_flush(): WARNING - 400 output buffers waiting, disk IO system too slow?

>Aug  9 16:51:27 packet.c:969 moloch_packet_ip(): WARNING - Packet Q 12 is overflowing, total dropped 1, increase packetThreads or maxPacketsInQueue
Segmentation fault (core dumped)

**Comment by ccpptt** [comment]
I think I fixed the immediate issue...

Commented out tpacketv3NumThreads and maxPacketsInQueue

Now capture logs appear to be sane.

**Comment by ccpptt** [comment]
Re-opening this. After commenting out tpacketv3NumThreads and maxPacketsInQueue, it worked "OK" for an evening, and then segfaulted too.

So I'm returning back to the config I know was working in 0.18.2 but shitting itself in 0.19.1, so let's try this again:

pcapWriteMethod = thread
pcapReadMethod=tpacketv3
packetThreads=12
tpacketv3NumThreads=4
pcapWriteSize = 262144

Starting capture with these settings on 0.19.1 results in the 'disk IO system too slow' warnings until eventually there's a segfault. While these warnings are appearing, I note there's very little actual packet drop (0%) but the disk value in the capture.log file is very high (e.g. 2500). 

(As an side, I do have a seperate config which I'm testing (on 0.19.1) which seems to work fine up to 5Gbit/s, but (possibly coincidentally) starts becoming problematic at higher rates. I'll leave this overnight to see where it gets to, but it involves not specifying tpacketv3.)

**Comment by awick** [comment]
Try changing pcapWriteMethod to "simple" or just delete that line.

Can you also provide the output of "./moloch-capture --version" and a stack trace https://github.com/aol/moloch/wiki/FAQ#moloch-capture-crashes

**Comment by ccpptt** [comment]
We are using 'thread' as the method as per your suggestion here (due to our setup using ZFS):

https://groups.google.com/forum/#!topic/moloch-fpc/EDMhZ0WXRzY

Output:

Aug 15 11:08:20 main.c:609 main(): THREAD 0x7f2ea1bcc780
moloch-capture 0.19.1/v0.19.1 session size=384 packet size=88
glib2: 2.52.2
libpcap: libpcap version 1.8.1
curl: libcurl/7.54.1 OpenSSL/1.0.2g zlib/1.2.8
pcre: 8.31 2012-07-06
yara: 3.6.1
GeoIP: 1.6.11

At this stage capture has survived overnight, in a few hours when our traffic hits ~7Gbit/s it's likely to crash, at which stage I will revert back to 'simple' and also the not-working 0.18.2 config and capture the exact error and stack traces for you.

Just want to state again, the current config I have that's been working overnight on 0.19.1 is:

packetThreads = 12
pcapWriteSize = 262143

Most other things are commented out (specifically pcapReadMethod and maxPacketsInQueue)

**Comment by awick** [comment]
Ah if using zfs then try simple-nodirect

**Comment by ccpptt** [comment]
Two identically spec'd machines with different network feeds have now been operating "fine" for about 24 hours  on 0.19.1 with these minimal configs: 

Machine 1) up to 7Gbit using pcapWriteMethod=thread, and packetThreads = 12 

> Aug 16 13:36:06 packet.c:959 moloch_packet_ip(): packets: 57707000000 current sessions: 1508120/1517695 oldest: 0 - recv: 1874760032 drop: 1986659 (0.11) queue: 20 disk: 0 packet: 1179 close: 9575 ns: 0 frags: 0/0

Machine 2) up to 2Gbit using pcapWriteMethod=simple-nodirect, and packetThreads = 12

> Aug 16 13:40:56 packet.c:959 moloch_packet_ip(): packets: 7122800000 current sessions: 287330/290104 oldest: 0 - recv: 2828055552 drop: 10513 (0.00) queue: 0 disk: 0 packet: 0 close: 2774 ns: 0 frags: 0/0

------

For machine 1, I'm trying to determine why CPU usage doesn't creep beyond ~400% (16 core machine), and ~16GB memory usage (48GB RAM available), and whether those values can be pushed higher to further "tune" it (I can see some minimal packet loss in peak time -- see screenshot). 

![screen shot 2017-08-16 at 1 44 35 pm](https://user-images.githubusercontent.com/3753357/29344015-25079422-8289-11e7-85cd-635888e6bb99.png)

**Comment by awick** [comment]
did you ever figure out what was going on?
