### ISSUE TITLE
History phase 2

### ISSUE THREAD

**Issue by awick** [aol/moloch#734]
- [x] Make field names match whats in the ui (pathname => api, maybe others)
- [x] History in main bar, even for admins, should only show your stuff by default
- [x] From users tab should be able to open history directly for a user
- [x] fix history button color on users page
- [x] ./db.pl info shows stats
- [x] Multies support
- [x] Use query_string instead of simple_query_string for more power
- [x] Time Range column size smaller and userId bigger
- [x] add execution time of the query
- [x] filter by a time range
- [x] show the whole url when opening a history item
- [x] save the body of the request (careful with passwords!)
- [x] add help

**Comment by 31453** [comment]
Completed in 6633f5c
