### ISSUE TITLE
WISE Threat Intel...Kept adding threat intel sources until....well.....

### ISSUE THREAD

**Issue by scottlsattler** [aol/moloch#737]
<--- Last few GCs --->

   90953 ms: Scavenge 1386.9 (1456.6) -> 1386.9 (1456.6) MB, 10.7 / 0 ms (+ 2.7 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   93480 ms: Mark-sweep 1386.9 (1456.6) -> 1386.9 (1456.6) MB, 2526.1 / 0 ms (+ 3.7 ms in 2 steps since start of marking, biggest step 2.7 ms) [last resort gc].
   95995 ms: Mark-sweep 1386.9 (1456.6) -> 1386.9 (1456.6) MB, 2515.8 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3f4201eb4629 <JS Object>
    2: __write [/data/moloch/wiseService/node_modules/csv-parse/lib/index.js:469] [pc=0x167889ed7dab] (this=0x2dd1c5a15681 <JS Object>,chars=0x24c4eac04101 <Very long string[59405374]>,end=0x3f4201e04251 <false>)
    3: _read [_stream_transform.js:~162] [pc=0x167889e51451] (this=0x2dd1c5a15681 <JS Object>,n=16)
    4: _write [_stream_transform.js:155] [pc=0x167889ed3ab0] (this=0x2dd1c5a15681 <J...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)

**Comment by awick** [comment]
Try adding `--max_old_space_size=2000000` right after node and before wiseService.js

**Comment by scottlsattler** [comment]
yes, should have googled first...can probably close...thanks
