### ISSUE TITLE
Protocol with Port based filtering/packet capture

### ISSUE THREAD

**Issue by techwizardg** [aol/moloch#743]
This is not a bug but asking how would we achieve the same. Not sure where to post and hence posting it here

a) We would not want all packets to be captured but instead capture certain ports with in TCP/UDP so that we capture only relevant packets and not all packets coming in and emnating out of the box. How do we achieve the same? This would help us have our storage optimal too

**Comment by awick** [comment]
Best place to post is the slack group https://slackinvite.molo.ch/

Lots of different ways, I would start with bpf filters or rules.  https://github.com/aol/moloch/wiki/FAQ#Life_of_a_packet and https://github.com/aol/moloch/wiki/RulesFormat might help
