### ISSUE TITLE
Feature Request: Integrate tshark protocol decodes into session viewer

### ISSUE THREAD

**Issue by patrickstjohn** [aol/moloch#746]
Based on an Andy Wick comment in the Slack channel and didn't want it lost in the shuffle as I thought it was a great idea. We have lots of odd protocols in our environment and it would be great if tshark could be used to display some of the more esoteric ones in a more readable fashion besides the current defaults. Performance would make this difficult to do for everything but individual session decodes when you look at them likely wouldn't be too bad.

**Comment by killolol** [comment]
And maybe It wouldn't be so hard to implement, since tshark support JSON output, which you can put to ES.

https://www.elastic.co/blog/analyzing-network-packets-with-wireshark-elasticsearch-and-kibana

**Comment by 31453** [comment]
I'm not sure this is worth the added complexity and additional UI that needs to be supported. A user can download pcap and use tshark to analyze it themselves.

Please reopen if there is a larger consensus that this would benefit the software and the community.
