### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jpvlsmv** [aol/moloch#752]
As reported on Slack,

I'm getting a `TypeError: Cannot read property '0' of undefined` on the main page, v0.19.1
In the div margin-for-main-navbar, a `<span ng-if="$ctrl.message">`

Kyle asked about a similar error that went away yesterday.  Concidence?  :)

@elyse, let me know if there's anything more I can debug

**Comment by 31453** [comment]
Please reopen this issue if the problem persists
