### ISSUE TITLE
Viewer can't find module "./lib/"

### ISSUE THREAD

**Issue by jpvlsmv** [aol/moloch#758]
ES 2.4.3 (from .deb) Moloch 0.20.0 (from .deb) both on Ubuntu 16.04.03

molochviewer fails to start with errors:
```Nov 01 14:26:19 stlloginet004 systemd[1]: Started Moloch Viewer process.
Nov 01 14:26:19 stlloginet004 node[90372]: ERROR - Couldn't load some dependancies, maybe need to 'npm update' inside viewer directory { Error: Cannot find module './lib/'
Nov 01 14:26:19 stlloginet004 node[90372]:     at Function.Module._resolveFilename (module.js:469:15)
Nov 01 14:26:19 stlloginet004 node[90372]:     at Function.Module._load (module.js:417:25)
Nov 01 14:26:19 stlloginet004 node[90372]:     at Module.require (module.js:497:17)
Nov 01 14:26:19 stlloginet004 node[90372]:     at require (internal/module.js:20:19)
Nov 01 14:26:19 stlloginet004 node[90372]:     at Object.<anonymous> (/data/moloch/viewer/node_modules/express/node_modules/qs/index.js:1:80)
Nov 01 14:26:19 stlloginet004 node[90372]:     at Module._compile (module.js:570:32)
Nov 01 14:26:19 stlloginet004 node[90372]:     at Object.Module._extensions..js (module.js:579:10)
Nov 01 14:26:19 stlloginet004 node[90372]:     at Module.load (module.js:487:32)
Nov 01 14:26:19 stlloginet004 node[90372]:     at tryModuleLoad (module.js:446:12)
Nov 01 14:26:19 stlloginet004 node[90372]:     at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
Nov 01 14:26:19 stlloginet004 systemd[1]: molochviewer.service: Main process exited, code=exited, status=1/FAILURE
Nov 01 14:26:19 stlloginet004 systemd[1]: molochviewer.service: Unit entered failed state.
Nov 01 14:26:19 stlloginet004 systemd[1]: molochviewer.service: Failed with result 'exit-code'.
```

I verified that everything was intact with dpkg's --verify, and forced a re-installation, which did not change the behavior.

I took the suggestion in the ERROR code, got a lot of npm output but got to a state that runs.  Transcript of that is attached as 'npm update.log'.  I first run an `npm ls` to see what's going on before.  There's some oddities in "extraneous" modules, and some that are missing (sub?)module package.json files.

`npm update` starts at line 325.  It looks like it's installed Chromium and missing some package.json files again.

But at the end of the hour, I'm back and running.
[npm update.log](https://github.com/aol/moloch/files/1435310/npm.update.log)

**Comment by awick** [comment]
I just tried with no issue. Was this a fresh box?  If not what version was installed previously

For a faster npm install next time you can use `npm install --production`

**Comment by jpvlsmv** [comment]
This has happened on 2 of 18 systems (so far?), all are base install of Ubuntu 16.04.01, moloch-0.19.1.deb then moloch-0.19.2.deb, then moloch-0.20.deb

Before I "fixed" the second one, I ran md5sum recursively on the viewer directory.  The only changes under /viewer/ were the deletion of `node_modules/something/node_module/somethingelse/...` files, this suggests it's a subdependency?

The next time it happens, I'll look into all the files it deleted.  (tar rather than md5sum)

**Comment by awick** [comment]
on these boxes have you previously done npm installs manually like above?

Really the package upgrade should remove everything in node_modules and then install the new files.  But if you ran npm installs previously without the `--production` option, I bet things are getting confused.

**Comment by awick** [comment]
closing, reopen if you still have issues
