### ISSUE TITLE
Different retention periods for capture nodes?

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#76]
Is it possible to enable a longer retention period for a sensor known to have significantly less traffic than other capture nodes?  i.e. a mail sniffer vs. arbitrary internet access.  The mail sniffer could easily see less traffic and benefit from a longer retention period.

**Comment by awick** [comment]
For pcap it just fills up the disk until "full" as defined by config.
For SPI data it isn't possible, best you could do is set up a separate moloch "cluster" and use a multi viewer.
