### ISSUE TITLE
WISE enhancement : CertStream monitor to autotag suspicious domains

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#764]
Run a CT certstream monitor and feed a real time WISE channel with suspicious domains based on certificate creation for autotagging

https://github.com/x0rz/phishing_catcher

**Comment by awick** [comment]
Its GPLv3 so we can't use.  Not sure what you really want to do.  Seems like you could just look at when certs were created and have a list of words and score without needing certstream.

**Comment by awick** [comment]
did you decide what you actually want moloch to do with the cert data?  otherwise can we close

**Comment by awick** [comment]
reopen if you decide what you actually want
