### ISSUE TITLE
Support MaxMind GeoIP2 data files

### ISSUE THREAD

**Issue by MattCarothers** [aol/moloch#771]
Feature request: support MaxMind GeoIP2 data files in addition to the legacy files.

Data files: https://dev.maxmind.com/geoip/geoip2/geolite2/
APIs: https://dev.maxmind.com/geoip/geoip2/downloadable/#MaxMind_APIs

**Comment by awick** [comment]
Moloch 1.x will use geoip2 stuff, this also means we will now be using 2 char country codes.  When the old data is reindexed it will change from 3 char to 2 char.
