### ISSUE TITLE
Moloch not flushing data into PCAP

### ISSUE THREAD

**Issue by tfplenum** [aol/moloch#777]
**Elasticsearch version**: 5.6.4

**Moloch version**: v0.20.2-GIT

**OS name and version**: Red Hat 7.4

**How was Moloch built/installed:** singlehost built

[capture_log.txt](https://github.com/aol/moloch/files/1504119/capture_log.txt)
[moloch_config.txt](https://github.com/aol/moloch/files/1504125/moloch_config.txt)

I built Moloch with DAG support and am running it on an Endace DAG. One of the issues I am now having is that everything works, except Moloch isn't flushing to disk when I run it as a service. Moloch generates the PCAP, but it remains empty. If I run molochcapture on its own and then hit ctrl+C, it terminates and properly flushes data to disk. I've looked through the config file and searched around for settings that would allow me to control this. 

**Desired Behavior:** The behavior I want is that it uses the memory buffer unless a timer is reached. For example: Write when memory buffer is full OR every 30 seconds, whichever comes first.

**Comment by awick** [comment]
Yep, this is how it works because of direct disk writes.  Currently the best you can do is lower your pcapWriteSize and set packetThreads to 1.  I guess in non direct mode a timer could be added.

https://github.com/aol/moloch/wiki/FAQ#zero-byte-pcap-files

**Comment by grantcurell** [comment]
Ah, that is very helpful!

Is it normal that when I view the traffic in Molochviewer it throws an error for the PCAP data? I can see all the header data, but it tells me the PCAP data is unavailable. Does this mean trying to access the PCAP data does not trigger a write to disk? If so, then is it just a matter of waiting for the buffer to fill up and then that data will become available?

**Comment by awick** [comment]
What error are you seeing?  It might already be referenced in the FAQ.

The viewer and capture components don't talk to each other.

**Comment by grantcurell** [comment]
![error](https://user-images.githubusercontent.com/1595564/33244128-50505faa-d2b7-11e7-94c3-435f6a2fb41f.png)

**Comment by grantcurell** [comment]
+1 for a feature which lets me do the desired behavior in the OP.

If I get some free time, I'll write it in.

**Comment by awick** [comment]
Yep, we can leave the issue open.  As I mentioned above in non direct mode a timer could be added.
