### ISSUE TITLE
moloch init error

### ISSUE THREAD

**Issue by lenghuazhang** [aol/moloch#782]
**Elasticsearch version**:6.0

**Moloch version**:0.20

**OS name and version**:Centos 7.2

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...):rpm

**Provide logs, stack traces and steps to reproduce**:
When I run /data/moloch/db/db.pl http://ESHOST:9200 init, appear this error:Couldn't PUT http://ela:9200/tags_v3  the http status code is 406 are you sure elasticsearch is running/reachable?
{"error":"Content-Type header [] is not supported","status":406} at /data/moloch/db/db.pl line 180.

 curl http://ela:9200  test elasticsearch work normal.
install and test  elasticsearch  head plugs ,work normal.

**Comment by awick** [comment]
ES 6 in't supported

**Comment by lenghuazhang** [comment]
Thank you very much! I reinstall ES 5.6,all OK.
