### ISSUE TITLE
Cannot get device ring settings: No such device

### ISSUE THREAD

**Issue by andreyferriyan** [aol/moloch#784]
Hi, I have this problem after upgrade to v0.20.2-GIT. 

OS name: GNU/Linux Ubuntu 16.04.3 LTS

Elasticsearch version: 5.6.0

Moloch build using easybutton-build.sh

Elasticsearch and moloch in the same server

I think the problem is from molochcapture. First time when I try upgrade manually from git, this error is show up multiple times and then molochcapture is down. Then I try to make it with clean installation (delete all existing moloch and any nodejs installation) and whenever I run for the first time, the error show up and still the same but on second try, I can start molochcapture

**Comment by awick** [comment]
What is your interface setting?

**Comment by andreyferriyan** [comment]
My interface is **enp0s3** and I already put it the same interface at **/data/moloch/etc/config.ini**

**Comment by andreyferriyan** [comment]
Okay, it works using this configuration 
https://github.com/aol/moloch/wiki/FAQ#Network_Card_Config

But I believe I had done this configuration before the upgrade version.

Thank you
