### ISSUE TITLE
Cubism only displays local timezone

### ISSUE THREAD

**Issue by 31453** [aol/moloch#787]
Original note by Andy: "Stats graph bar thingy doesn't honor GMT setting, always shows in local"

**Comment by 31453** [comment]
I'm not sure that Cubism allows for anything but local timezone: https://github.com/square/cubism/issues/37

Maybe we should try a new library or implement this on the dstats.json endpoint?

**Comment by awick** [comment]
I think you can use something like

context.axis().focusFormat(d3.time.format.utc("%I:%M:%S %pZ"))
