### ISSUE TITLE
PCAP "Linux Cooked" not processed?

### ISSUE THREAD

**Issue by xme** [aol/moloch#791]
**Elasticsearch version**: 5.5.2

**Moloch version**: 0.18.2

**OS name and version**: Ubuntu 16.04-LTS

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) Docker

**Provide logs, stack traces and steps to reproduce**:
# moloch-capture -r boogey-201801091248.pcap -d
....
Jan  9 12:55:59 session.c:596 moloch_session_init(): session hash size 500009
Jan  9 12:55:59 main.c:517 moloch_ready_gfunc(): maxField = 88
Jan  9 12:55:59 reader-libpcap-file.c:188 reader_libpcapfile_next(): Processing boogey-201801091248.pcap
Jan  9 12:55:59 session.c:661 moloch_session_exit(): sessions: 0 tcp: 0 udp: 0 icmp: 0
Jan  9 12:55:59 main.c:638 main(): Final cleanup
# file boogey-201801091248.pcap
boogey-201801091248.pcap: tcpdump capture file (little-endian) - version 2.4 (Linux "cooked", capture length 262144)

I'm capturing traffic into PCAP files (split into files of 100MB). Those files are transferred to the server running a Moloch docker using scp. The tcpdump command used to capture the traffic uses "-i any" to capture from all interfaces.  PCAP files are read but no data is indexed! And no error returned!?
Any tip?

**Comment by awick** [comment]
Please provide a sample pcap, you can send to andywick gmail if you don't want to post here.

**Comment by xme** [comment]
Mail sent!
