### ISSUE TITLE
make install fails on Parliament

### ISSUE THREAD

**Issue by hackdefendr** [aol/moloch#796]
**Elasticsearch version**:
5.2.0
**Moloch version**:
Git Latest
**OS name and version**:
Debian 9 (stretch)
**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
Compiled from source
**Provide logs, stack traces and steps to reproduce**:

/bin/cp -pr views public bundle /data/moloch/viewer
(cd /data/moloch/viewer ; npm update --production)
make[1]: Leaving directory '/home/hackdef/moloch/viewer'
Making install in parliament
make[1]: Entering directory '/home/hackdef/moloch/parliament'
/usr/bin/install -c *.js package.json /data/moloch/parliament
npm update
npm run build

> parliament@0.0.0 build /home/hackdef/moloch/parliament
> ng build --prod

module.js:471
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/hackdef/moloch/parliament/node_modules/@angular-devkit/schematics/src/tree/virtual.js:10:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.9.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! parliament@0.0.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parliament@0.0.0 build script 'ng build --prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parliament package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parliament
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parliament
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hackdef/moloch/parliament/npm-debug.log
Makefile:11: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/hackdef/moloch/parliament'
Makefile:326: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by hackdefendr** [comment]
Additionally...I just emailed the listed owner for Parliament and he said he hasn't maintained that project is over 3 years.  Why would moloch depend on something that isn't maintained?

Better question, is there an alternative to Parliament?

**Comment by awick** [comment]
parliament lives in the moloch directory, not sure who you emailed.  Can you attach /home/hackdef/moloch/parliament/npm-debug.log

**Comment by hackdefendr** [comment]
npm ERR! npm owner ls parliament

That is where I got the owner from.  

[npm-debug.log](https://github.com/aol/moloch/files/1649926/npm-debug.log)

**Comment by awick** [comment]
Ya that is a bad suggestion, its having you find out the owner for the parliament package.

Looks like @31453 forgot to check in a file

`Error: Cannot find module '@angular-devkit/core'`

**Comment by hackdefendr** [comment]
OK cool...So I will wait until that is corrected and try again.

Thanks.
