### ISSUE TITLE
Moloch fails to build due to Hashtable failure.

### ISSUE THREAD

**Issue by hackdefendr** [aol/moloch#797]
**Elasticsearch version**:
5.6.6
**Moloch version**:
Git-latest
**OS name and version**:
Ubuntu 16.04
**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
Build from source using Easybutton.
**Provide logs, stack traces and steps to reproduce**:

> hashtable@2.0.2 install /data/moloch/wiseService/node_modules/hashtable
> node-gyp configure build

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/data/moloch/wiseService/node_modules/hashtable/build'
gyp ERR! System Linux 4.13.0-31-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /data/moloch/wiseService/node_modules/hashtable
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashtable@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cuckoo/.npm/_logs/2018-01-23T17_17_34_745Z-debug.log
Makefile:22: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/home/cuckoo/moloch/capture/plugins'
Makefile:61: recipe for target 'installdirs' failed
make[1]: *** [installdirs] Error 2
make[1]: Leaving directory '/home/cuckoo/moloch/capture'
Makefile:326: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by awick** [comment]
node 8 isn't supported yet

**Comment by hackdefendr** [comment]
Apparently neither is node 3.5.2 which is the default in Ubuntu.  
I received the same failure with that version.
What version should I be using?

**Comment by awick** [comment]
See https://github.com/aol/moloch/blob/master/CHANGELOG

You were using 6 before, I would suggest you continue with that.
