### ISSUE TITLE
Moloch fails to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by hackdefendr** [aol/moloch#798]
**Elasticsearch version**:
5.6.6
**Moloch version**:
Git
**OS name and version**:
Ubuntu 16.04
**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
Compiled from Source using Easybutton
**Provide logs, stack traces and steps to reproduce**:

$ sudo make install
Making install in capture
make[1]: Entering directory '/home/cuckoo/moloch/capture'
/usr/bin/install -c -d /data/moloch/bin
(cd parsers; make install)
make[2]: Entering directory '/home/cuckoo/moloch/capture/parsers'
/usr/bin/install -c *.so *.jade /data/moloch/parsers
make[2]: Leaving directory '/home/cuckoo/moloch/capture/parsers'
(cd plugins; make install)
make[2]: Entering directory '/home/cuckoo/moloch/capture/plugins'
/usr/bin/install -c taggerUpload.pl /data/moloch/bin
/usr/bin/install -c *.so *.jade *.js /data/moloch/plugins
/usr/bin/install -c wiseService/*.js wiseService/wiseService.ini.sample wiseService/package.json /data/moloch/wiseService
(cd /data/moloch/wiseService ; npm update)
npm WARN excluding symbolic link index.js -> iptrie.js
npm WARN excluding symbolic link index.js -> iptrie.js
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN excluding symbolic link index.js -> iptrie.js

> iptrie@0.0.6 install /data/moloch/wiseService/node_modules/iptrie
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
gyp ERR! stack     at TLSSocket.g (events.js:292:16)
gyp ERR! stack     at emitNone (events.js:91:20)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:974:12)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:104:9)
gyp ERR! System Linux 4.13.0-31-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/moloch/wiseService/node_modules/iptrie
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
WISE@0.16.0 /data/moloch/wiseService
├── async@2.6.0
├── bson@0.5.7
├── connect-timeout@1.9.0
├── console-stamp@0.2.6
├── csv@1.2.1
├── elasticsearch@13.3.1
├── express@4.16.2
├── glob@7.1.2
├── hashtable@2.0.2
├── iniparser@1.0.5
├── lru-cache@4.1.1
├── morgan@1.9.0
├── native-dns@0.7.0
├── redis@2.8.0
├── request@2.83.0
├── sqlite3@3.1.13
└── unzip@0.1.11

npm ERR! Linux 4.13.0-31-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! iptrie@0.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iptrie@0.0.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iptrie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iptrie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iptrie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/moloch/wiseService/npm-debug.log
Makefile:22: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/home/cuckoo/moloch/capture/plugins'
Makefile:61: recipe for target 'installdirs' failed
make[1]: *** [installdirs] Error 2
make[1]: Leaving directory '/home/cuckoo/moloch/capture'
Makefile:326: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by awick** [comment]
* Is there a reason you want to build yourself instead of using the deb?
*Maybe join the slack channel instead of opening a new issue for each compile issue you hit?

Anyway, probably need the debug log.  It looks like it might be trying to make a https call to something and failing?

```
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
gyp ERR! stack     at TLSSocket.g (events.js:292:16)
gyp ERR! stack     at emitNone (events.js:91:20)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:974:12)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:104:9)
```

Also since you are changing node versions, did you blow away the node_modules directory first?  You should also do a `npm cache clean`

**Comment by hackdefendr** [comment]
I blew away the entire /data directory and the moloch source directory before trying again.

I'm building myself because the deb package doesn't link to libssl properly causing Moloch to not even startup.  This happened on both Debian Stretch and Ubuntu Xenial.

The debug log only shows the exact thing I already pasted in my original post.  

I can't use Slack at work.

**Comment by hackdefendr** [comment]
[npm-debug.log](https://github.com/aol/moloch/files/1657247/npm-debug.log)

**Comment by awick** [comment]
What do you mean it doesn't link properly on 16.04?  Seems like we should fix that if you could share the issue or how to reproduce. We are building every commit on it with no issue, and it has to startup because it runs tests.

Anyway, I don't see anything obvious in the log, so not sure whats going on.  Are you building this on a VM/docker image so I can try and repo?

**Comment by hackdefendr** [comment]
I'm getting a different error now when using the deb package.

$ sudo /bin/sh -c /data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini
Jan 23 13:13:05 main.c:609 main(): THREAD 0x7f84aadd6780
Jan 23 13:13:05 main.c:160 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps, use the --host option - cuckoo
Jan 23 13:13:05 main.c:587 moloch_mlockall_init(): WARNING: memlock in limits.conf must be unlimited or at least 4000000, currently 64
Jan 23 13:13:05 http.c:240 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/dstats/version/version/_source 0/15 0ms 2ms
Jan 23 13:13:05 http.c:240 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/sequence/sequence/fn-cuckoo 0/87 0ms 1ms
Jan 23 13:13:05 http.c:240 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/sequence/sequence/fn-cuckoo 2/157 0ms 4295024ms
Jan 23 13:13:05 http.c:240 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/tags/tag/_search?size=3000 0/611 0ms 3ms
Jan 23 13:13:05 http.c:240 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/stats/stat/cuckoo 0/710 0ms 1ms
Jan 23 13:13:05 http.c:240 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/fields/field/_search?size=3000 0/59936 0ms 11ms
Jan 23 13:13:05 writer-simple.c:391 writer_simple_init(): INFO: Reseting pcapWriteSize to 262144 since it must be a multiple of 4096
Jan 23 13:13:05 reader-libpcap.c:69 reader_libpcap_thread(): THREAD 0x7f8489f65700
Jan 23 13:13:05 reader-libpcap.c:69 reader_libpcap_thread(): THREAD 0x7f8498d61700
Jan 23 13:13:05 reader-libpcap.c:69 reader_libpcap_thread(): THREAD 0x7f848a766700
Jan 23 13:13:05 packet.c:983 moloch_packet_ip(): Initial Packet = 1516734785
Jan 23 13:13:05 packet.c:984 moloch_packet_ip(): 0 Initial Dropped = 0
Jan 23 13:13:05 packet.c:983 moloch_packet_ip(): Initial Packet = 1516734785
Jan 23 13:13:05 packet.c:984 moloch_packet_ip(): 16 Initial Dropped = 0
Jan 23 13:13:05 reader-libpcap.c:54 reader_libpcap_pcap_cb(): ERROR - Moloch requires full packet captures caplen: 16384 pktlen: 24514
See https://github.com/aol/moloch/wiki/FAQ#Moloch_requires_full_packet_captures_error

The link in the error message does not exist!

**Comment by awick** [comment]
https://github.com/aol/moloch/wiki/FAQ#moloch-requires-full-packet-captures-error

Looks like when we switched from mediawiki to ascii doc it changed _ to -, how annoying.  Glad the deb package is working for you now.

**Comment by awick** [comment]
ok fixed it so the old link works again
