### ISSUE TITLE
Change Working Directory 

### ISSUE THREAD

**Issue by alienzoX** [aol/moloch#800]
Hi Guys,
I've install the Moloch and by default it goes to /data/moloch/...

So all the data save in under root and I don't have enough space in root:

Filesystem      Size  Used Avail Use% Mounted on
/dev/md2         20G   13G  5.8G  69% /
/dev/md1          487M   69M  389M  15% /boot
/dev/md3        1.8T  109M  1.7T   1% /home

/dev/sda1  *          4096    1050623              1046528  511M fd Linux raid autodetect
/dev/sda2          1050624   42008575          40957952 19.5G fd Linux raid autodetect
/dev/sda3         42008576 3905972223      3863963648  1.8T fd Linux raid autodetect
/dev/sda4       3905972224 3907018751     1046528  511M 82 Linux swap / Solaris

I've plan to move everything to /dev/md3    /home  which is 1.7TB
How can I do that ? 

Is there anyway in configuration to change the storage area ?!

I am using Ubuntu Server 17.04 LTS
and moloch version v0.50.0

**Comment by alienzoX** [comment]
Hi Guys,
I've install the Moloch and by default it goes to /data/moloch/...

So all the data save in under root and I don't have enough space in root:

Filesystem      Size  Used Avail Use% Mounted on
/dev/md2         20G   13G  5.8G  69% /
/dev/md1          487M   69M  389M  15% /boot
/dev/md3        1.8T  109M  1.7T   1% /home


/dev/sda1  *          4096    1050623              1046528  511M fd Linux raid autodetect
/dev/sda2          1050624   42008575          40957952 19.5G fd Linux raid autodetect
/dev/sda3         42008576 3905972223      3863963648  1.8T fd Linux raid autodetect
/dev/sda4       3905972224 3907018751     1046528  511M 82 Linux swap / Solaris

I've plan to move everything to /dev/md3    /home  which is 1.7TB
How can I do that ? 

Is there anyway in configuration to change the storage area ?!

I am using Ubuntu Server 17.04 LTS
and moloch version v0.50.0

**Comment by awick** [comment]
you can either make a link for the raw directory or you can change pcapDir in the config file.
