### ISSUE TITLE
add a show frames option

### ISSUE THREAD

**Issue by awick** [aol/moloch#805]
for W

**Comment by 31453** [comment]
What does this even mean? More info please!

**Comment by awick** [comment]
* Some kind of option in session view to show packets instead of the reassembled traffic
* Then for each packet show either natural/hex/.. value 
* If show timestamp is selected also show the tcp headers in the timestamp info
* not sure if we need a different end point or not

**Comment by andersonreloaded** [comment]
When we export the pcap data fromm Moloch, the timestamp in wireshark starts from 0. Instead, can we have the captured timestamps ?

**Comment by awick** [comment]
For first pass if you select show frames it should for tcp it should
* have a "header" with 
  * the time stamp
  * the length
  * if tcp the tcp flags
* Then show the packet payload data like the current hex does.

**Comment by andersonreloaded** [comment]
We are using for UDP. Currently data for all UDP packets in a session are shown at once. Instead it can be shown on per packet basis.
