### ISSUE TITLE
Session(s) page does not render in Firefox 52.x

### ISSUE THREAD

**Issue by skBeyond** [aol/moloch#809]
**Elasticsearch version 5.5.3**:

**Moloch 0.50**:

**Window 7 v6.1.76**:
**Firefox 52.6.0**:

**How was Moloch built/installed:** rpm

Firefox 52.6 renders navigation bar background color body content and nav links themselves are gone, only text visible is at the top right hand corner and it's variable noting the moloch version " v{{:$ctrl.molochVersion}}

**Comment by kaktis** [comment]
same problem

**Comment by awick** [comment]
We are probably going to have to increase our min Firefox version.  Are you stuck on that version?

**Comment by 31453** [comment]
This is fixed in Firefox versions 54.x and greater.
