### ISSUE TITLE
Export Unique Dst IP/Export Unique Src IP with Ports doesn't return results

### ISSUE THREAD

**Issue by kaktis** [aol/moloch#811]
When attempting to export Unique IPs with Port information of any kind from either the Src IP/ Country or Dst IP / Country fields returns a blank page with no results. This issue is comes up any time an option with Ports is selected for export from these two fields.

**Comment by 31453** [comment]
I am unable to reproduce this issue without a little more info. Can you please provide the following:

- Elasticsearch version
- Moloch version
- OS name and version
- Browser name and version
- Any logs, stack traces, or browser console output

Thanks!

**Comment by kaktis** [comment]
es version 5.6
Moloch version 1.0.0beta
OS is redhat7
browser is chrome, not sure on version though
Don't have any logs where I'm at right now, have to post that later

**Comment by kaktis** [comment]
To add a little back story, I was using Moloch .20 on a single ES node, but we decided to do a cluster so I set up an 8 node ES cluster of the same ES version, and upgraded Moloch to 1.0.0beta, every thing else is the same, and it worked for me when I was running single node ES with v0.20 moloch

**Comment by problematiq** [comment]
I've had an issue like this before. Try removing everything from your URL except the host and port and redoing the search, then try the unique export again. Sometimes it seem like the URL gets a bit long and complicated, and the unique export stops working.

**Comment by kaktis** [comment]
I'm not even applying filters though

**Comment by kaktis** [comment]
this may be a stupid question, but if I installed 1.0.0 from RPM, what is the easiest way to get these commits implemented on my stack?

**Comment by awick** [comment]
There is a build after every commit that is copied to aws, I've added a link to https://molo.ch/#oneoh
