### ISSUE TITLE
easy button install npm issue

### ISSUE THREAD

**Issue by kaktis** [aol/moloch#812]
while doing the easy button install, once the script has ran and you attempt to run make install it always fails to find npm, is there any way that the /data/moloch/bin path can be added to the $PATH variable during the easy button script so this wouldn't have to be done manually.

**Comment by problematiq** [comment]
A lot of us use Ansible and some of use use docker containers. You can write a script is Shell or whatever scripting language you prefer. Also, if you have a lot of questions like this, feel free to join the slack channel. There are a lot of experienced users there that are more than happy to help.

**Comment by awick** [comment]
It is not possible for a shell script to modify its parents env.  I've added a --install option to easybutton or you could just edit your profile and permanently add /data/moloch/bin to your PATH.
