### ISSUE TITLE
Moloch 1.0.0 not exporting all unique Dst IPs with Ports

### ISSUE THREAD

**Issue by kaktis** [aol/moloch#815]
This issue is very closely related to issue #811 , which had a commit pushed to fix it, I've installed the nightly version from 3/3/18 and went to verify the issue I was having with exporting the 'Src IP / Country' and ' Dst IP / Country' fields when exporting with port information. From the testing that I was doing, the Src IP /Country export with ports is fixed, but when I go to export IP with Port info from Dst IP / Country it only returns one result, but when exporting from the same drop down without port information there are thousands of results. I am performing this export with no filters active as well.

Moloch Version: Moloch 1.0.0
Browser Version: Firefox Quantum v58
OS: CentOS7
ES Version: ES 5.6.2

**Comment by awick** [comment]
so when I tried it I was getting viewer crashes in viewer.log?  are you?

If thats what you were getting that is fixed now

**Comment by kaktis** [comment]
The error i'm getting off the viewer.log is something to the effect of "RangeError: Maximum call stack size exceeded" if that sounds like what you're referring to.

**Comment by awick** [comment]
yep, so this is fixed now

**Comment by kaktis** [comment]
copy, thanks, i'll update
