### ISSUE TITLE
OOM after capture gets hit by unknown protocol errors

### ISSUE THREAD

**Issue by wr2mem** [aol/moloch#820]
Running out of memory after capture gets hit by unknown protocol errors

**Elasticsearch version**:
2.4
**Moloch version**:
0.17

**OS name and version**:
CentOS 7

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
Built

**Provide logs, stack traces and steps to reproduce**:

While Moloch Capture sees large amounts of this type of traffic, it runs out of memory causing capture crash. If traffic is filtered, capture continues to work. 

Debug logs show:

<DATE> <TIME> packet.c:714 moloch_packet_gre4(): Unknown GRE protocol 0x0000(0)
<DATE> <TIME> packet.c:714 moloch_packet_gre4(): Unknown GRE protocol 0x0001(1)
<DATE> <TIME> packet.c:714 moloch_packet_gre4(): Unknown GRE protocol 0x0002(2)
<DATE> <TIME> packet.c:714 moloch_packet_gre4(): Unknown GRE protocol 0x0003(3)
<DATE> <TIME> packet.c:714 moloch_packet_gre4(): Unknown GRE protocol 0x0801(2049)
<DATE> <TIME> packet.c:714 moloch_packet_gre4(): Unknown GRE protocol 0x8200(33280)
<DATE> <TIME> packet.c:714 moloch_packet_gre4(): Unknown GRE protocol 0x9000(36864)

Inside GRE header of the packet, Protocol Type are shown in hex(dec) above

Many of the Protocol Types above are not defined in the respective RFCs but Wiresharks seems to be aware of them. See links,

https://github.com/wireshark/wireshark/blob/fe219637a6748130266a0b0278166046e60a2d68/epan/dissectors/packet-gre.h

https://github.com/wireshark/wireshark/blob/aeca321f36935204e0ffb901c7252805d954b18d/epan/dissectors/packet-gre.c

The undefined types should not cause the issue. BSB*?

Also observing below errors which are also be leading to crash/memory consumption

<DATE> <TIME> packet.c:1083 moloch_packet_ip4(): Unknown protocol 103
<DATE> <TIME> packet.c:1083 moloch_packet_ip4(): Unknown protocol 50

/var/log/messages shows:

<DATE> <TIME> <HOST> kernel: Out of memory: Kill process <PID> (moloch-capture) scored 786 or sacrifice child

<DATE> <TIME> <HOST> Killed process <PID> (moloch-capture) total-vm:207634988kB, anon-rss:150525184kB, file-rss:56637276kB, shmem-rss:0kB

**Comment by awick** [comment]
0.17 is over a year old, please upgrade to at least 0.20.2 and try again
