### ISSUE TITLE
Replica upgrade fla does not working

### ISSUE THREAD

**Issue by wr2mem** [aol/moloch#823]
**Elasticsearch version**:
5.6.4
**Moloch version**:
0.50.0
**OS name and version**:
CentOS
**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
Built
**Provide logs, stack traces and steps to reproduce**:

After init and capturing traffic. not able to upgrade replicas. even after the index is deleted.
The only way to do it is "init" with the replicas. Worked on 0.17 not working on 0.50

**Comment by awick** [comment]
Can  you provide more details, what command are you running?  Any errors in elasticsearch logs?

**Comment by wr2mem** [comment]
My mistake. None issue.
