### ISSUE TITLE
SCTP (132) protocol

### ISSUE THREAD

**Issue by vanwesm** [aol/moloch#828]
I would like to record packets using SCTP (132) protocol but I don't need to be able to filter inside this protocol. Filtering on IP address would be enought.

Will it be possible to tell moloch to keep packets with unknown protocol?

**Comment by problematiq** [comment]
If you have pcaps and/or break down of the protocol, you might add this as a request for protocol parsing instead of just a generic unknown. Help out the next guy :)

**Comment by vanwesm** [comment]
You are right.

Here is a pcap file containing packets using Stream Control Transmission Protocol.
[isup.zip](https://github.com/aol/moloch/files/1878955/isup.zip)

Some other pcap files can be found here:
https://pcapr.net/browse?proto=sctp

The protocol as a basic common header and a nice break down can be found at the following link.
https://en.wikipedia.org/wiki/SCTP_packet_structure

**Comment by vanwesm** [comment]
Thank you for the update. 
I will give it a try.

**Comment by awick** [comment]
reopen if issue
