### ISSUE TITLE
Download PCAP outputs empty(0byte) file

### ISSUE THREAD

**Issue by Sunpyo** [aol/moloch#830]
Hi, 
my ES, Capture/Viewer machines are running ok. but
whenever I try to export sessions in PCAP format in Viewer, it fails.
It doesn't make any error message and makes empty(0byte) PCAP file.
I could get 'session get error' message in 'viewer.log' file.
that says do not support fields any more.. something like that.

Raw files exist and I checked file and parent directory permissions.
Do you have any clue about this?

Here is the log messages from 'viewer.log'

session get error { [Error: [illegal_argument_exception] the parameter [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or [_source] to load the field from _source]
  status: 400,
  displayName: 'BadRequest',
  message: '[illegal_argument_exception] the parameter [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or [_source] to load the field from _source',
  path: '/sessions-180403/session/180403-GwjD0DAntLhBt538VW-_CKTa',
  query: { fields: 'no,ps,psl' },
  body: undefined,
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"the parameter [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or [_source] to load the field from _source"}],"type":"illegal_argument_exception","reason":"the parameter [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or [_source] to load the field from _source"},"status":400}',
  toString: [Function],
  toJSON: [Function] } { error:
   { root_cause: [ [Object] ],
     type: 'illegal_argument_exception',
     reason: 'the parameter [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or [_source] to load the field from _source' },
  status: 400 }
writePcap Session not found

**Elasticsearch version**: 5.5.1
**Moloch version**: 0.17.0
**OS name and version**: ubuntu
**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) singlehost
**Provide logs, stack traces and steps to reproduce**: session get error

**Comment by awick** [comment]
0.17.0 doesn't support ES 5.
