### ISSUE TITLE
Named pipe mode for moloch-capture.

### ISSUE THREAD

**Issue by DrKewp** [aol/moloch#833]
I've been working for some time on a project to integrate moloch with the suricata IDS.

My original plan was to use the offline monitor mode to read the pcap files exported from the individual moloch threads from tmpfs partitions.  The command being:

moloch-capture -R /var/tmp/pool --recursive -m --copy --delete

The /var/tmp/pool directory contains a subdirectory for each suricata thread; ./t1, ./t2, ./t3, etc.

Unfortunately, while moloch-capture does read the pcap files and copy/delete them, the ensuing stored session pcaps very often contain out of order packets.  Reviewing the session pcap in wireshark shows that the timestamp produced by suricata is correct, however the order of stored packets is incorrect.

This appears to happen regardless of number of the number of threads or size of the pcap files.  

What I would like propose is to create a new option (--pipe) to replace --delete in this use case.  This treats the files in the directory as named pipes and then opens one thread per file to read it.  Moloch-capture is started first as a reader and then suricata is configured to write to each named pipe.

The maximum number of threads should be increased as well to allow for this particular configuration.  Hopefully this will address the out-of-order packet issue.

Of course, its possible I've missed something obvious in the config.ini, if that's the case please let me know.

**Comment by awick** [comment]
Can you explain the goal?   Having both suricata and moloch read the packets from the kernel (using afpacket for example) will be better/more efficient then suricata reading and then writing the packets and then having moloch read the packets.

Or is suricata doing some kind of packet reduction/packet munging that you want to take advantage of?  If so probably still better to just reimplement in moloch.

**Comment by DrKewp** [comment]
I've had a long-time goal to develop an architecture that uses suricata to log packets off a 10-100G capture mechanism, sample enough packets from each flow to extract the metadata (e.g. 64kb); then pass it moloch for storage/indexing.  Suricata can also be configured to prune tls sessions so only the ssl handshake is stored. 

I know moloch was moving in this direction in the past, but at the time I wasn't able to get both programs listening to the same interface.  However, it does appear moloch can now monitor the same af_packet interface that suricata does (if suricata is started first!).

I've done some experimenting and it looks like I can get a similar effect using a 64 packet bpf/session limit.  Moloch-capture also works well when pinned to the same cores/NUMA node that I'm using for RSS.

**Comment by awick** [comment]
We've never had an issue of which is started first.  What are you seeing?

**Comment by DrKewp** [comment]
Bear in mind I'm on an older AMD Piledriver system, which lacks the advanced caching architecture of the newer Intel systems.  This seems to seriously impact performance on 10G deployments.  

What happens is that moloch starts normally, however when suricata starts the moloch threads peg the cpu at 100% in kernel space (red in htop).  I didn't dig into the issue as it works fine when suricata is started first.
