### ISSUE TITLE
Index the unencrypted 802.11 Data Frame

### ISSUE THREAD

**Issue by qingxp9** [aol/moloch#834]
When a wifi set up with OPEN (No-password), the unencrypted data can be read directly using a monitor mode wifi adapter.

![wx20180408-190421](https://user-images.githubusercontent.com/2822242/38466692-c4a2a5c8-3b5f-11e8-8839-29fedfdf029f.png)

But Moloch seems not index them. I think this feather is good and you can add it.

**Comment by awick** [comment]
please provide a sample pcap that can be used for tests and checked in

**Comment by qingxp9** [comment]
@awick 
This is a pcap file captured with the monitor mode wifi adapter. 
[test1.pcapng.zip](https://github.com/aol/moloch/files/1887413/test1.pcapng.zip)

**Comment by awick** [comment]
thanks, unfortunately this is missing the tcp syn and other things that would make it a good tcp test case.  Can you provide one that has an entire tcp session?

**Comment by qingxp9** [comment]
[unfilter.pcapng.zip](https://github.com/aol/moloch/files/1888328/unfilter.pcapng.zip)
This is an unfiltered Pcap file.

Please know that when I use the monitor mode it will capture all 802.11 raw data from all surrounding wireless access points and clients on a special channel, and sometimes it may also use the "channel hopping" to change the channel. So we may not capture all entire TCP sessions.

I used to use the filter keyword "HTTP" to observe what are people looking.

**Comment by awick** [comment]
seems to work

**Comment by qingxp9** [comment]
@awick 
I tested it again, but it seems not working.
Moloch Version 1.1.0

I install the new version again, select the wlan0 to monitor. Then I started my USB Wi-Fi card with monitor mode like this.

```
sudo ifconfig wlan0 down
sudo iwconfig wlan0 mode monitor
sudo ifconfig wlan0 up
sudo iwconfig wlan0 channel 11
```

```
sudo iw dev wlan0 info       
Interface wlan0
	ifindex 4
	wdev 0x100000001
	addr 44:94:fc:xx:xx:xx
	type monitor
	wiphy 1
	channel 11 (2462 MHz), width: 20 MHz (no HT), center1: 2462 MHz
	txpower 20.00 dBm
```


I can find http packets in Wireshark, but it doesn't show in moloch.
![_ _20180522135155](https://user-images.githubusercontent.com/2822242/40344444-6a830e40-5dc7-11e8-9879-59ab6fdcfdd1.png)

**Comment by awick** [comment]
Can you provide a sample pcap, it works for the pcaps I found.  You can send to andywick gmail

**Comment by qingxp9** [comment]
I send a sample pcap before, and I don't think it will be different if I capture a new one.
https://github.com/aol/moloch/files/1888328/unfilter.pcapng.zip
Have you tested it with a monitor mode Wi-Fi card?
I think maybe the issue is related to the special interface mode

**Comment by awick** [comment]
> I send a sample pcap before, and I don't think it will be different if I capture a new one. https://github.com/aol/moloch/files/1888328/unfilter.pcapng.zip

Yep, I converted to a .pcap file and extracted just the ip traffic and it works fine.

> Have you tested it with a monitor mode Wi-Fi card? I think maybe the issue is related to the special interface mode

No, and I don't have plans to at this point.  If you can send pcap files that aren't working (not pcapng would be best) I can try and figure out whats wrong.
