### ISSUE TITLE
capture unable to recognize dag stream as interface

### ISSUE THREAD

**Issue by kaktis** [aol/moloch#835]
**Elasticsearch version**: 5.6
**Moloch version**: 1.0.0
**OS name and version**:centos 7
**How was Moloch built/installed**:easybutton install

I am trying to install moloch 1.0.0 with DAG functionality, I have referred to issue #681, but the fix they suggested doesn't seem to fix my issue, when I go through the entire setup process with their steps either it fails to recognize dag0:0 as a device and references one of the reader_pcap shared objects or it won't even execute the capture binary in dryrun, and complains that it can't locate my libdag shared objects. Has anyone figured out a sound method of building moloch 1.0.0 to support DAG interfaces? I seem to remember there may used to have been a with-dag option when running ./configure in the moloch directory when you untar the source code. Thanks in advance for any input.

**Comment by awick** [comment]
Oh, I was getting daq and dag confused.  We have a daq reader https://github.com/aol/moloch/wiki/Settings#Reader_daq_Settings

Make sure you are linking against the dag libpcap file, and if it can find stuff when running try setting your LD_LIBRARY_PATH

**Comment by kaktis** [comment]
How much would it break if i forced it to use libpcap-1.7.x instead of 1.8.1? I've tried building 1.8.1 --with-dag and then built moloch off of that but it always fails to recognize the interface.

**Comment by kaktis** [comment]
Also, does the capture binary build completely off of libpcap.so?

**Comment by awick** [comment]
It shouldn't break anything.  You just need to rebuild libpcap your self with dag and then make sure it all links.

**Comment by kaktis** [comment]
what would be the easiest way to point moloch at my libpcap during the build process, seems like there are a lot of moving parts inside the easybutton script

**Comment by awick** [comment]
Something like:
1) edit easybutton-build and change the libpcap build line to include the options you need
2) edit the capture/Makefile.in and add -ldag after the -lyaml 
3) run easybutton-build

you could also just go build libpcap manually after running once with no mods

**Comment by kaktis** [comment]
I tried doing the build normally, then go back and rebuild libpcap --with-dag and then running make install and make config, and it still doesn't recognize the interface

**Comment by awick** [comment]
after rebuilding libpcap you have to rebuild moloch-capture since its using the static version of libpcap.  If you are I can't really help since I don't use dag.  you can do a `nm moloch-capture | grep dag` and make sure you see stuff, if you don't it probably hasn't actually linked against the dag library.

**Comment by kaktis** [comment]
on the plus side i did get a ton of results from the nm command

**Comment by sfd** [comment]
I just chanced across this, so I expect the thread is cold. Did you contact Endace support?
Libpcap 1.8.1 has a bug building against the DAG libraries. You can either use libpcap 1.7.4, or Github master. Unfortunately we have been waiting a long time for a new stable libpcap release.
Does the libpcap 'findalldevstest' test program find the card?
