### ISSUE TITLE
moloch-capture: /lib64/libcrypto.so.10: version 'OPENSSL_1.0.2' not found (required by moloch-capture)

### ISSUE THREAD

**Issue by jeffthejeffert** [aol/moloch#837]
**Elasticsearch version**: 6.2.4

**Moloch version**: 1.0.0

**OS name and version**:CentOS 7.3

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) Installed with the CentOS 7 RPM.

**Provide logs, stack traces and steps to reproduce**:
I try to run the "moloch-capture --help" it returns with the following error message:
moloch-capture: /lib64/libcrypto.so.10: version 'OPENSSL_1.0.2' not found  (required by moloch-capture)

CentOS is by defeult provided with OpenSSL 1.0.1e. Ive upgraded it to 1.0.2. with the sources(configure, make, make install etc)
If i execute the "openssl version" it returns with the new openssl version 1.0.2, but some how the moloch-capture wil not reconize it..

I see that the service molochcapture is not running also, if i try to start it, ik wil.l go in failure state, looking in the moloch log files is see the same error message.
Whats wrong ? , plz help.

**Comment by awick** [comment]
moloch rpm is built against 7.4, just upgrade your OS.  If you can't upgrade to 7.4 (or 7.5 which was released 2 weeks ago) then you will need to build moloch yourself.

**Comment by jeffthejeffert** [comment]
Thanks, i updated to openssl 1.0.2k and included the openssl-devel and the openssl-libs package of 1.0.2k as well,. Now it seems to work, Wil start testing now.

Thanks for the help.
