### ISSUE TITLE
Feature request: index pcaps with Frame-Relay link type

### ISSUE THREAD

**Issue by ka2rpa** [aol/moloch#838]
Greetings!
Would it be possible to add capture support for Frame-Relay link type (link type 107)?
Plain support for IPv4 over Frame-Relay (4B FR header, last 2B == 0x0800) would be enough.

Here are few pcaps with IPv4 over Frame-Relay
http://packetlife.net/captures/OSPF_point-to-point_adjacencies.cap
http://packetlife.net/captures/ICMP_across_frame_relay.cap
https://pcapr.net/view/neteng/2010/9/0/18/frame-relay-fragmentation-encap-IETF.html

more pcaps here:
http://packetlife.net/captures/protocol/fr/
and here:
https://pcapr.net/browse?proto=fr

Thank you

![image](https://user-images.githubusercontent.com/38723625/39245018-d759c346-4892-11e8-9fc5-ce0676d74ed5.png)

**Comment by awick** [comment]
above commit seems to work, reopen if issues
