### ISSUE TITLE
Moloch fails to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by lovekernel** [aol/moloch#845]
**Elasticsearch version**:

**Moloch version**: 1.1.0

**OS name and version**: ubuntu-server-16.04

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
easybutton-build.sh

**Provide logs, stack traces and steps to reproduce**:

> hashtable@2.0.2 install /data/moloch/wiseService/node_modules/hashtable
> node-gyp configure build

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at _errnoException (util.js:1022:11)
gyp ERR! stack     at TLSWrap.onread (net.js:628:25)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/data/moloch/node-v8.11.1-linux-x64/bin/node" "/data/moloch/node-v8.11.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /data/moloch/wiseService/node_modules/hashtable
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashtable@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-05-05T14_03_27_963Z-debug.log

**Comment by awick** [comment]
ECONNRESET usually means it can't download something I would guess.  Maybe try again?  or use the 16 .deb we provide?

Otherwise can you attach the full .npm log.

**Comment by lovekernel** [comment]
10081 info lifecycle request-promise@4.2.2~install: request-promise@4.2.2
10082 silly install sqlite3@3.1.13
10083 info lifecycle sqlite3@3.1.13~install: sqlite3@3.1.13
10084 verbose lifecycle sqlite3@3.1.13~install: unsafe-perm in lifecycle false
10085 verbose lifecycle sqlite3@3.1.13~install: PATH: /data/moloch/node-v8.11.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/moloch-1.1.0/node_modules/sqlite3/node_modules/.bin:/opt/moloch-1.1.0/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/data/moloch/node-v8.11.1-linux-x64/bin/
10086 verbose lifecycle sqlite3@3.1.13~install: CWD: /opt/moloch-1.1.0/node_modules/sqlite3
10087 silly lifecycle sqlite3@3.1.13~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
10088 silly lifecycle sqlite3@3.1.13~install: Returned: code: 1  signal: null
10089 info lifecycle sqlite3@3.1.13~install: Failed to exec install script
10090 verbose unlock done using /home/user/.npm/_locks/staging-4ec596790910b94e.lock for /opt/moloch-1.1.0/node_modules/.staging
10091 silly saveTree moloch@1.0.0
10091 silly saveTree ├─┬ async@2.6.0
10091 silly saveTree │ └── lodash@4.17.10
10091 silly saveTree ├─┬ body-parser@1.18.2
10091 silly saveTree │ ├── bytes@3.0.0
10091 silly saveTree │ ├── content-type@1.0.4
10091 silly saveTree │ ├─┬ debug@2.6.9
10091 silly saveTree │ │ └── ms@2.0.0
10091 silly saveTree │ ├── depd@1.1.2
10091 silly saveTree │ ├─┬ http-errors@1.6.3
10091 silly saveTree │ │ ├── inherits@2.0.3
10091 silly saveTree │ │ ├── setprototypeof@1.1.0
10091 silly saveTree │ │ └── statuses@1.5.0
10091 silly saveTree │ ├── iconv-lite@0.4.19
10091 silly saveTree │ ├─┬ on-finished@2.3.0
10091 silly saveTree │ │ └── ee-first@1.1.1
10091 silly saveTree │ ├── qs@6.5.1
10091 silly saveTree │ ├─┬ raw-body@2.3.2
10091 silly saveTree │ │ ├─┬ http-errors@1.6.2
10091 silly saveTree │ │ │ ├── depd@1.1.1
10091 silly saveTree │ │ │ └── setprototypeof@1.0.3
10091 silly saveTree │ │ └── unpipe@1.0.0
10091 silly saveTree │ └─┬ type-is@1.6.16
10091 silly saveTree │   ├── media-typer@0.3.0
10091 silly saveTree │   └─┬ mime-types@2.1.18
10091 silly saveTree │     └── mime-db@1.33.0
10091 silly saveTree ├── bson@0.5.7
10091 silly saveTree ├─┬ connect-timeout@1.9.0
10091 silly saveTree │ └── on-headers@1.0.1
10091 silly saveTree ├─┬ console-stamp@0.2.6
10091 silly saveTree │ ├─┬ chalk@1.1.3
10091 silly saveTree │ │ ├── ansi-styles@2.2.1
10091 silly saveTree │ │ ├── escape-string-regexp@1.0.5
10091 silly saveTree │ │ ├─┬ has-ansi@2.0.0
10091 silly saveTree │ │ │ └── ansi-regex@2.1.1
10091 silly saveTree │ │ ├── strip-ansi@3.0.1
10091 silly saveTree │ │ └── supports-color@2.0.0
10091 silly saveTree │ ├─┬ dateformat@1.0.12
10091 silly saveTree │ │ ├── get-stdin@4.0.1
10091 silly saveTree │ │ └─┬ meow@3.7.0
10091 silly saveTree │ │   ├─┬ camelcase-keys@2.1.0
10091 silly saveTree │ │   │ ├── camelcase@2.1.1
10091 silly saveTree │ │   │ └── map-obj@1.0.1
10091 silly saveTree │ │   ├── decamelize@1.2.0
10091 silly saveTree │ │   ├─┬ loud-rejection@1.6.0
10091 silly saveTree │ │   │ ├─┬ currently-unhandled@0.4.1
10091 silly saveTree │ │   │ │ └── array-find-index@1.0.2
10091 silly saveTree │ │   │ └── signal-exit@3.0.2
10091 silly saveTree │ │   ├── map-obj@1.0.1
10091 silly saveTree │ │   ├── minimist@1.2.0
10091 silly saveTree │ │   ├─┬ normalize-package-data@2.4.0
10091 silly saveTree │ │   │ ├── hosted-git-info@2.6.0
10091 silly saveTree │ │   │ ├─┬ is-builtin-module@1.0.0
10091 silly saveTree │ │   │ │ └── builtin-modules@1.1.1
10091 silly saveTree │ │   │ ├── semver@5.5.0
10091 silly saveTree │ │   │ └─┬ validate-npm-package-license@3.0.3
10091 silly saveTree │ │   │   ├─┬ spdx-correct@3.0.0
10091 silly saveTree │ │   │   │ ├─┬ spdx-expression-parse@3.0.0
10091 silly saveTree │ │   │   │ │ ├── spdx-exceptions@2.1.0
10091 silly saveTree │ │   │   │ │ └── spdx-license-ids@3.0.0
10091 silly saveTree │ │   │   │ └── spdx-license-ids@3.0.0
10091 silly saveTree │ │   │   └── spdx-expression-parse@3.0.0
10091 silly saveTree │ │   ├── object-assign@4.1.1
10091 silly saveTree │ │   ├─┬ read-pkg-up@1.0.1
10091 silly saveTree │ │   │ ├─┬ find-up@1.1.2
10091 silly saveTree │ │   │ │ ├─┬ path-exists@2.1.0
10091 silly saveTree │ │   │ │ │ └─┬ pinkie-promise@2.0.1
10091 silly saveTree │ │   │ │ │   └── pinkie@2.0.4
10091 silly saveTree │ │   │ │ └── pinkie-promise@2.0.1
10091 silly saveTree │ │   │ └─┬ read-pkg@1.1.0
10091 silly saveTree │ │   │   ├─┬ load-json-file@1.1.0
10091 silly saveTree │ │   │   │ ├── graceful-fs@4.1.11
10091 silly saveTree │ │   │   │ ├─┬ parse-json@2.2.0
10091 silly saveTree │ │   │   │ │ └─┬ error-ex@1.3.1
10091 silly saveTree │ │   │   │ │   └── is-arrayish@0.2.1
10091 silly saveTree │ │   │   │ ├── pify@2.3.0
10091 silly saveTree │ │   │   │ └─┬ strip-bom@2.0.0
10091 silly saveTree │ │   │   │   └── is-utf8@0.2.1
10091 silly saveTree │ │   │   └── path-type@1.1.0
10091 silly saveTree │ │   ├─┬ redent@1.0.0
10091 silly saveTree │ │   │ ├─┬ indent-string@2.1.0
10091 silly saveTree │ │   │ │ └─┬ repeating@2.0.1
10091 silly saveTree │ │   │ │   └─┬ is-finite@1.0.2
10091 silly saveTree │ │   │ │     └── number-is-nan@1.0.1
10091 silly saveTree │ │   │ └── strip-indent@1.0.1
10091 silly saveTree │ │   └── trim-newlines@1.0.0
10091 silly saveTree │ └── merge@1.2.0
10091 silly saveTree ├─┬ csv@1.2.1
10091 silly saveTree │ ├── csv-generate@1.1.2
10091 silly saveTree │ ├── csv-parse@1.3.3
10091 silly saveTree │ ├─┬ csv-stringify@1.1.2
10091 silly saveTree │ │ └── lodash.get@4.4.2
10091 silly saveTree │ └── stream-transform@0.2.2
10091 silly saveTree ├─┬ elasticsearch@13.3.1
10091 silly saveTree │ ├── agentkeepalive@2.2.0
10091 silly saveTree │ ├── lodash.isempty@4.4.0
10091 silly saveTree │ ├── lodash.trimend@4.5.1
10091 silly saveTree │ └── lodash@2.4.2
10091 silly saveTree ├─┬ express@4.16.3
10091 silly saveTree │ ├─┬ accepts@1.3.5
10091 silly saveTree │ │ └── negotiator@0.6.1
10091 silly saveTree │ ├── array-flatten@1.1.1
10091 silly saveTree │ ├── content-disposition@0.5.2
10091 silly saveTree │ ├── cookie-signature@1.0.6
10091 silly saveTree │ ├── cookie@0.3.1
10091 silly saveTree │ ├── encodeurl@1.0.2
10091 silly saveTree │ ├── escape-html@1.0.3
10091 silly saveTree │ ├── etag@1.8.1
10091 silly saveTree │ ├─┬ finalhandler@1.1.1
10091 silly saveTree │ │ ├── parseurl@1.3.2
10091 silly saveTree │ │ └── statuses@1.4.0
10091 silly saveTree │ ├── fresh@0.5.2
10091 silly saveTree │ ├── merge-descriptors@1.0.1
10091 silly saveTree │ ├── methods@1.1.2
10091 silly saveTree │ ├── parseurl@1.3.2
10091 silly saveTree │ ├── path-to-regexp@0.1.7
10091 silly saveTree │ ├─┬ proxy-addr@2.0.3
10091 silly saveTree │ │ ├── forwarded@0.1.2
10091 silly saveTree │ │ └── ipaddr.js@1.6.0
10091 silly saveTree │ ├── range-parser@1.2.0
10091 silly saveTree │ ├── safe-buffer@5.1.1
10091 silly saveTree │ ├─┬ send@0.16.2
10091 silly saveTree │ │ ├── destroy@1.0.4
10091 silly saveTree │ │ ├── mime@1.4.1
10091 silly saveTree │ │ └── statuses@1.4.0
10091 silly saveTree │ ├── serve-static@1.13.2
10091 silly saveTree │ ├── statuses@1.4.0
10091 silly saveTree │ ├── utils-merge@1.0.1
10091 silly saveTree │ └── vary@1.1.2
10091 silly saveTree ├── font-awesome@4.7.0
10091 silly saveTree ├─┬ glob@7.1.2
10091 silly saveTree │ ├── fs.realpath@1.0.0
10091 silly saveTree │ ├─┬ inflight@1.0.6
10091 silly saveTree │ │ ├─┬ once@1.4.0
10091 silly saveTree │ │ │ └── wrappy@1.0.2
10091 silly saveTree │ │ └── wrappy@1.0.2
10091 silly saveTree │ ├─┬ minimatch@3.0.4
10091 silly saveTree │ │ └─┬ brace-expansion@1.1.11
10091 silly saveTree │ │   ├── balanced-match@1.0.0
10091 silly saveTree │ │   └── concat-map@0.0.1
10091 silly saveTree │ ├── once@1.4.0
10091 silly saveTree │ └── path-is-absolute@1.0.1
10091 silly saveTree ├── iniparser@1.0.5
10091 silly saveTree ├── moment@2.22.1
10091 silly saveTree ├─┬ morgan@1.9.0
10091 silly saveTree │ └── basic-auth@2.0.0
10091 silly saveTree ├─┬ pug@2.0.3
10091 silly saveTree │ ├─┬ pug-code-gen@2.0.1
10091 silly saveTree │ │ ├─┬ constantinople@3.1.2
10091 silly saveTree │ │ │ ├── @types/babel-types@7.0.1
10091 silly saveTree │ │ │ ├── @types/babylon@6.16.2
10091 silly saveTree │ │ │ ├─┬ babel-types@6.26.0
10091 silly saveTree │ │ │ │ ├─┬ babel-runtime@6.26.0
10091 silly saveTree │ │ │ │ │ ├── core-js@2.5.5
10091 silly saveTree │ │ │ │ │ └── regenerator-runtime@0.11.1
10091 silly saveTree │ │ │ │ ├── esutils@2.0.2
10091 silly saveTree │ │ │ │ └── to-fast-properties@1.0.3
10091 silly saveTree │ │ │ └── babylon@6.18.0
10091 silly saveTree │ │ ├── doctypes@1.1.0
10091 silly saveTree │ │ ├── js-stringify@1.0.2
10091 silly saveTree │ │ ├─┬ pug-attrs@2.0.3
10091 silly saveTree │ │ │ └── pug-runtime@2.0.4
10091 silly saveTree │ │ ├── pug-error@1.3.2
10091 silly saveTree │ │ ├── pug-runtime@2.0.4
10091 silly saveTree │ │ ├── void-elements@2.0.1
10091 silly saveTree │ │ └─┬ with@5.1.1
10091 silly saveTree │ │   ├─┬ acorn-globals@3.1.0
10091 silly saveTree │ │   │ └── acorn@4.0.13
10091 silly saveTree │ │   └── acorn@3.3.0
10091 silly saveTree │ ├─┬ pug-filters@3.1.0
10091 silly saveTree │ │ ├─┬ clean-css@4.1.11
10091 silly saveTree │ │ │ └── source-map@0.5.7
10091 silly saveTree │ │ ├─┬ jstransformer@1.0.0
10091 silly saveTree │ │ │ ├── is-promise@2.1.0
10091 silly saveTree │ │ │ └─┬ promise@7.3.1
10091 silly saveTree │ │ │   └── asap@2.0.6
10091 silly saveTree │ │ ├── pug-walk@1.1.7
10091 silly saveTree │ │ ├─┬ resolve@1.7.1
10091 silly saveTree │ │ │ └── path-parse@1.0.5
10091 silly saveTree │ │ └─┬ uglify-js@2.8.29
10091 silly saveTree │ │   ├── uglify-to-browserify@1.0.2
10091 silly saveTree │ │   └─┬ yargs@3.10.0
10091 silly saveTree │ │     ├── camelcase@1.2.1
10091 silly saveTree │ │     ├─┬ cliui@2.1.0
10091 silly saveTree │ │     │ ├─┬ center-align@0.1.3
10091 silly saveTree │ │     │ │ ├─┬ align-text@0.1.4
10091 silly saveTree │ │     │ │ │ ├─┬ kind-of@3.2.2
10091 silly saveTree │ │     │ │ │ │ └── is-buffer@1.1.6
10091 silly saveTree │ │     │ │ │ ├── longest@1.0.1
10091 silly saveTree │ │     │ │ │ └── repeat-string@1.6.1
10091 silly saveTree │ │     │ │ └── lazy-cache@1.0.4
10091 silly saveTree │ │     │ ├── right-align@0.1.3
10091 silly saveTree │ │     │ └── wordwrap@0.0.2
10091 silly saveTree │ │     └── window-size@0.1.0
10091 silly saveTree │ ├─┬ pug-lexer@4.0.0
10091 silly saveTree │ │ ├─┬ character-parser@2.2.0
10091 silly saveTree │ │ │ └─┬ is-regex@1.0.4
10091 silly saveTree │ │ │   └─┬ has@1.0.1
10091 silly saveTree │ │ │     └── function-bind@1.1.1
10091 silly saveTree │ │ └─┬ is-expression@3.0.0
10091 silly saveTree │ │   └── acorn@4.0.13
10091 silly saveTree │ ├── pug-linker@3.0.5
10091 silly saveTree │ ├── pug-load@2.0.11
10091 silly saveTree │ ├─┬ pug-parser@5.0.0
10091 silly saveTree │ │ └── token-stream@0.0.1
10091 silly saveTree │ ├── pug-runtime@2.0.4
10091 silly saveTree │ └── pug-strip-comments@1.0.3
10091 silly saveTree ├─┬ redis@2.8.0
10091 silly saveTree │ ├── double-ended-queue@2.1.0-0
10091 silly saveTree │ ├── redis-commands@1.3.5
10091 silly saveTree │ └── redis-parser@2.6.0
10091 silly saveTree ├─┬ request-promise@4.2.2
10091 silly saveTree │ ├── bluebird@3.5.1
10091 silly saveTree │ ├── request-promise-core@1.1.1
10091 silly saveTree │ ├── stealthy-require@1.1.1
10091 silly saveTree │ └─┬ tough-cookie@2.3.4
10091 silly saveTree │   └── punycode@1.4.1
10091 silly saveTree ├─┬ request@2.85.0
10091 silly saveTree │ ├── aws-sign2@0.7.0
10091 silly saveTree │ ├── aws4@1.7.0
10091 silly saveTree │ ├── caseless@0.12.0
10091 silly saveTree │ ├─┬ combined-stream@1.0.6
10091 silly saveTree │ │ └── delayed-stream@1.0.0
10091 silly saveTree │ ├── extend@3.0.1
10091 silly saveTree │ ├── forever-agent@0.6.1
10091 silly saveTree │ ├─┬ form-data@2.3.2
10091 silly saveTree │ │ └── asynckit@0.4.0
10091 silly saveTree │ ├─┬ har-validator@5.0.3
10091 silly saveTree │ │ ├─┬ ajv@5.5.2
10091 silly saveTree │ │ │ ├── co@4.6.0
10091 silly saveTree │ │ │ ├── fast-deep-equal@1.1.0
10091 silly saveTree │ │ │ ├── fast-json-stable-stringify@2.0.0
10091 silly saveTree │ │ │ └── json-schema-traverse@0.3.1
10091 silly saveTree │ │ └── har-schema@2.0.0
10091 silly saveTree │ ├─┬ hawk@6.0.2
10091 silly saveTree │ │ ├─┬ boom@4.3.1
10091 silly saveTree │ │ │ └── hoek@4.2.1
10091 silly saveTree │ │ ├─┬ cryptiles@3.1.2
10091 silly saveTree │ │ │ └── boom@5.2.0
10091 silly saveTree │ │ ├── hoek@4.2.1
10091 silly saveTree │ │ └── sntp@2.1.0
10091 silly saveTree │ ├─┬ http-signature@1.2.0
10091 silly saveTree │ │ ├── assert-plus@1.0.0
10091 silly saveTree │ │ ├─┬ jsprim@1.4.1
10091 silly saveTree │ │ │ ├── extsprintf@1.3.0
10091 silly saveTree │ │ │ ├── json-schema@0.2.3
10091 silly saveTree │ │ │ └─┬ verror@1.10.0
10091 silly saveTree │ │ │   └── core-util-is@1.0.2
10091 silly saveTree │ │ └─┬ sshpk@1.14.1
10091 silly saveTree │ │   ├── asn1@0.2.3
10091 silly saveTree │ │   ├─┬ bcrypt-pbkdf@1.0.1
10091 silly saveTree │ │   │ └── tweetnacl@0.14.5
10091 silly saveTree │ │   ├── dashdash@1.14.1
10091 silly saveTree │ │   ├─┬ ecc-jsbn@0.1.1
10091 silly saveTree │ │   │ └── jsbn@0.1.1
10091 silly saveTree │ │   ├── getpass@0.1.7
10091 silly saveTree │ │   ├── jsbn@0.1.1
10091 silly saveTree │ │   └── tweetnacl@0.14.5
10091 silly saveTree │ ├── is-typedarray@1.0.0
10091 silly saveTree │ ├── isstream@0.1.2
10091 silly saveTree │ ├── json-stringify-safe@5.0.1
10091 silly saveTree │ ├── oauth-sign@0.8.2
10091 silly saveTree │ ├── performance-now@2.1.0
10091 silly saveTree │ ├── stringstream@0.0.5
10091 silly saveTree │ ├── tunnel-agent@0.6.0
10091 silly saveTree │ └── uuid@3.2.1
10091 silly saveTree ├─┬ sqlite3@3.1.13
10091 silly saveTree │ ├── nan@2.7.0
10091 silly saveTree │ └─┬ node-pre-gyp@0.6.38
10091 silly saveTree │   ├─┬ hawk@3.1.3
10091 silly saveTree │   │ ├─┬ boom@2.10.1
10091 silly saveTree │   │ │ └── hoek@2.16.3
10091 silly saveTree │   │ ├── cryptiles@2.0.5
10091 silly saveTree │   │ ├── hoek@2.16.3
10091 silly saveTree │   │ └── sntp@1.0.9
10091 silly saveTree │   ├─┬ mkdirp@0.5.1
10091 silly saveTree │   │ └── minimist@0.0.8
10091 silly saveTree │   ├─┬ nopt@4.0.1
10091 silly saveTree │   │ ├── abbrev@1.1.1
10091 silly saveTree │   │ └─┬ osenv@0.1.4
10091 silly saveTree │   │   ├── os-homedir@1.0.2
10091 silly saveTree │   │   └── os-tmpdir@1.0.2
10091 silly saveTree │   ├─┬ npmlog@4.1.2
10091 silly saveTree │   │ ├─┬ are-we-there-yet@1.1.4
10091 silly saveTree │   │ │ ├── delegates@1.0.0
10091 silly saveTree │   │ │ └─┬ readable-stream@2.3.3
10091 silly saveTree │   │ │   ├── core-util-is@1.0.2
10091 silly saveTree │   │ │   ├── inherits@2.0.3
10091 silly saveTree │   │ │   ├── isarray@1.0.0
10091 silly saveTree │   │ │   ├── process-nextick-args@1.0.7
10091 silly saveTree │   │ │   ├── safe-buffer@5.1.1
10091 silly saveTree │   │ │   ├── string_decoder@1.0.3
10091 silly saveTree │   │ │   └── util-deprecate@1.0.2
10091 silly saveTree │   │ ├── console-control-strings@1.1.0
10091 silly saveTree │   │ ├─┬ gauge@2.7.4
10091 silly saveTree │   │ │ ├── aproba@1.2.0
10091 silly saveTree │   │ │ ├── has-unicode@2.0.1
10091 silly saveTree │   │ │ ├── object-assign@4.1.1
10091 silly saveTree │   │ │ ├── signal-exit@3.0.2
10091 silly saveTree │   │ │ ├─┬ string-width@1.0.2
10091 silly saveTree │   │ │ │ ├── code-point-at@1.1.0
10091 silly saveTree │   │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
10091 silly saveTree │   │ │ │ │ └── number-is-nan@1.0.1
10091 silly saveTree │   │ │ │ └─┬ strip-ansi@3.0.1
10091 silly saveTree │   │ │ │   └── ansi-regex@2.1.1
10091 silly saveTree │   │ │ ├── strip-ansi@3.0.1
10091 silly saveTree │   │ │ └── wide-align@1.1.2
10091 silly saveTree │   │ └── set-blocking@2.0.0
10091 silly saveTree │   ├─┬ rc@1.2.1
10091 silly saveTree │   │ ├── deep-extend@0.4.2
10091 silly saveTree │   │ ├── ini@1.3.4
10091 silly saveTree │   │ ├── minimist@1.2.0
10091 silly saveTree │   │ └── strip-json-comments@2.0.1
10091 silly saveTree │   ├─┬ request@2.81.0
10091 silly saveTree │   │ ├── aws-sign2@0.6.0
10091 silly saveTree │   │ ├── aws4@1.6.0
10091 silly saveTree │   │ ├── caseless@0.12.0
10091 silly saveTree │   │ ├─┬ combined-stream@1.0.5
10091 silly saveTree │   │ │ └── delayed-stream@1.0.0
10091 silly saveTree │   │ ├── extend@3.0.1
10091 silly saveTree │   │ ├── forever-agent@0.6.1
10091 silly saveTree │   │ ├─┬ form-data@2.1.4
10091 silly saveTree │   │ │ ├── asynckit@0.4.0
10091 silly saveTree │   │ │ └─┬ mime-types@2.1.17
10091 silly saveTree │   │ │   └── mime-db@1.30.0
10091 silly saveTree │   │ ├─┬ har-validator@4.2.1
10091 silly saveTree │   │ │ ├─┬ ajv@4.11.8
10091 silly saveTree │   │ │ │ ├── co@4.6.0
10091 silly saveTree │   │ │ │ └─┬ json-stable-stringify@1.0.1
10091 silly saveTree │   │ │ │   └── jsonify@0.0.0
10091 silly saveTree │   │ │ └── har-schema@1.0.5
10091 silly saveTree │   │ ├─┬ http-signature@1.1.1
10091 silly saveTree │   │ │ ├── assert-plus@0.2.0
10091 silly saveTree │   │ │ ├─┬ jsprim@1.4.1
10091 silly saveTree │   │ │ │ ├── assert-plus@1.0.0
10091 silly saveTree │   │ │ │ ├── extsprintf@1.3.0
10091 silly saveTree │   │ │ │ ├── json-schema@0.2.3
10091 silly saveTree │   │ │ │ └─┬ verror@1.10.0
10091 silly saveTree │   │ │ │   └── assert-plus@1.0.0
10091 silly saveTree │   │ │ └─┬ sshpk@1.13.1
10091 silly saveTree │   │ │   ├── asn1@0.2.3
10091 silly saveTree │   │ │   ├── assert-plus@1.0.0
10091 silly saveTree │   │ │   ├─┬ bcrypt-pbkdf@1.0.1
10091 silly saveTree │   │ │   │ └── tweetnacl@0.14.5
10091 silly saveTree │   │ │   ├─┬ dashdash@1.14.1
10091 silly saveTree │   │ │   │ └── assert-plus@1.0.0
10091 silly saveTree │   │ │   ├─┬ ecc-jsbn@0.1.1
10091 silly saveTree │   │ │   │ └── jsbn@0.1.1
10091 silly saveTree │   │ │   ├─┬ getpass@0.1.7
10091 silly saveTree │   │ │   │ └── assert-plus@1.0.0
10091 silly saveTree │   │ │   ├── jsbn@0.1.1
10091 silly saveTree │   │ │   └── tweetnacl@0.14.5
10091 silly saveTree │   │ ├── is-typedarray@1.0.0
10091 silly saveTree │   │ ├── isstream@0.1.2
10091 silly saveTree │   │ ├── json-stringify-safe@5.0.1
10091 silly saveTree │   │ ├── mime-types@2.1.17
10091 silly saveTree │   │ ├── oauth-sign@0.8.2
10091 silly saveTree │   │ ├── performance-now@0.2.0
10091 silly saveTree │   │ ├── qs@6.4.0
10091 silly saveTree │   │ ├── stringstream@0.0.5
10091 silly saveTree │   │ ├─┬ tough-cookie@2.3.3
10091 silly saveTree │   │ │ └── punycode@1.4.1
10091 silly saveTree │   │ ├── tunnel-agent@0.6.0
10091 silly saveTree │   │ └── uuid@3.1.0
10091 silly saveTree │   ├─┬ rimraf@2.6.2
10091 silly saveTree │   │ └─┬ glob@7.1.2
10091 silly saveTree │   │   ├── fs.realpath@1.0.0
10091 silly saveTree │   │   ├─┬ inflight@1.0.6
10091 silly saveTree │   │   │ ├─┬ once@1.4.0
10091 silly saveTree │   │   │ │ └── wrappy@1.0.2
10091 silly saveTree │   │   │ └── wrappy@1.0.2
10091 silly saveTree │   │   ├─┬ minimatch@3.0.4
10091 silly saveTree │   │   │ └─┬ brace-expansion@1.1.8
10091 silly saveTree │   │   │   ├── balanced-match@1.0.0
10091 silly saveTree │   │   │   └── concat-map@0.0.1
10091 silly saveTree │   │   ├── once@1.4.0
10091 silly saveTree │   │   └── path-is-absolute@1.0.1
10091 silly saveTree │   ├── semver@5.4.1
10091 silly saveTree │   ├─┬ tar-pack@3.4.0
10091 silly saveTree │   │ ├─┬ debug@2.6.9
10091 silly saveTree │   │ │ └── ms@2.0.0
10091 silly saveTree │   │ ├─┬ fstream-ignore@1.0.5
10091 silly saveTree │   │ │ └─┬ fstream@1.0.11
10091 silly saveTree │   │ │   └── graceful-fs@4.1.11
10091 silly saveTree │   │ ├── fstream@1.0.11
10091 silly saveTree │   │ ├─┬ tar@2.2.1
10091 silly saveTree │   │ │ └── block-stream@0.0.9
10091 silly saveTree │   │ └── uid-number@0.0.6
10091 silly saveTree │   └── tar@2.2.1
10091 silly saveTree ├─┬ stylus@0.54.5
10091 silly saveTree │ ├── css-parse@1.7.0
10091 silly saveTree │ ├── glob@7.0.6
10091 silly saveTree │ ├─┬ mkdirp@0.5.1
10091 silly saveTree │ │ └── minimist@0.0.8
10091 silly saveTree │ ├── sax@0.5.8
10091 silly saveTree │ └─┬ source-map@0.1.43
10091 silly saveTree │   └── amdefine@1.0.1
10091 silly saveTree ├─┬ unzip@0.1.11
10091 silly saveTree │ ├─┬ binary@0.3.0
10091 silly saveTree │ │ ├── buffers@0.1.1
10091 silly saveTree │ │ └─┬ chainsaw@0.1.0
10091 silly saveTree │ │   └── traverse@0.3.9
10091 silly saveTree │ ├─┬ fstream@0.1.31
10091 silly saveTree │ │ ├─┬ graceful-fs@3.0.11
10091 silly saveTree │ │ │ └── natives@1.1.3
10091 silly saveTree │ │ └── rimraf@2.6.2
10091 silly saveTree │ ├─┬ match-stream@0.0.2
10091 silly saveTree │ │ └─┬ readable-stream@1.0.34
10091 silly saveTree │ │   ├── isarray@0.0.1
10091 silly saveTree │ │   └── string_decoder@0.10.31
10091 silly saveTree │ ├─┬ pullstream@0.4.1
10091 silly saveTree │ │ ├── over@0.0.5
10091 silly saveTree │ │ ├── setimmediate@1.0.5
10091 silly saveTree │ │ └── slice-stream@1.0.0
10091 silly saveTree │ ├── readable-stream@1.0.34
10091 silly saveTree │ └── setimmediate@1.0.5
10091 silly saveTree ├── vue-router@3.0.1
10091 silly saveTree ├─┬ vue-server-renderer@2.5.16
10091 silly saveTree │ ├── hash-sum@1.0.2
10091 silly saveTree │ ├── he@1.1.1
10091 silly saveTree │ ├─┬ lodash.template@4.4.0
10091 silly saveTree │ │ ├── lodash._reinterpolate@3.0.0
10091 silly saveTree │ │ └── lodash.templatesettings@4.1.0
10091 silly saveTree │ ├── lodash.uniq@4.5.0
10091 silly saveTree │ ├── serialize-javascript@1.5.0
10091 silly saveTree │ └── source-map@0.5.6
10091 silly saveTree └── vue@2.5.16
10092 verbose stack Error: sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
10092 verbose stack Exit status 1
10092 verbose stack     at EventEmitter.<anonymous> (/data/moloch/node-v8.11.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
10092 verbose stack     at emitTwo (events.js:126:13)
10092 verbose stack     at EventEmitter.emit (events.js:214:7)
10092 verbose stack     at ChildProcess.<anonymous> (/data/moloch/node-v8.11.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
10092 verbose stack     at emitTwo (events.js:126:13)
10092 verbose stack     at ChildProcess.emit (events.js:214:7)
10092 verbose stack     at maybeClose (internal/child_process.js:925:16)
10092 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
10093 verbose pkgid sqlite3@3.1.13
10094 verbose cwd /opt/moloch-1.1.0
10095 verbose Linux 4.4.0-116-generic
10096 verbose argv "/data/moloch/node-v8.11.1-linux-x64/bin/node" "/data/moloch/node-v8.11.1-linux-x64/bin/npm" "install"
10097 verbose node v8.11.1
10098 verbose npm  v5.6.0
10099 error code ELIFECYCLE
10100 error errno 1
10101 error sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
10101 error Exit status 1
10102 error Failed at the sqlite3@3.1.13 install script.
10102 error This is probably not a problem with npm. There is likely additional logging output above.
10103 verbose exit [ 1, true ]

**Comment by awick** [comment]
Can you attach the full npm log

**Comment by awick** [comment]
I can't reproduce.  Every check in is built on ubuntu 16 automatically it works fine.  Maybe some dev tools are missing on your box?  You might try deleting the /data/moloch, and .npm directories and trying again.
