### ISSUE TITLE
Is it possible to replace pfring into DPDK

### ISSUE THREAD

**Issue by lovekernel** [aol/moloch#846]
Is it possible to replace pfring into DPDK?

**Comment by awick** [comment]
not sure what you are asking.  In general we recommend folks use afpacket.

**Comment by lovekernel** [comment]
How can I make Moloch support the speed of the gigabit network?

**Comment by awick** [comment]
Can you join the slack channel for general questions instead of using issues?

moloch out of the box will support gigabit network.

If you mean > 1Gbps
https://github.com/aol/moloch/wiki/Architecture
https://github.com/aol/moloch/wiki/Settings#High_Performance_Settings
