### ISSUE TITLE
the wiki of the "multiple Host HOWTO"

### ISSUE THREAD

**Issue by lovekernel** [aol/moloch#847]
If you can update the wiki of the "multiple Host HOWTO", I have tried to deploy multiple probes on the system, but I have encountered difficulties.
I find that the wiki's instructions are still not clear enough.

**Comment by awick** [comment]
yes those were very old instructions, I've deleted most of it.  Not sure the page even needs to exist anymore.

**Comment by lovekernel** [comment]
How to implement multiple-machine deployment Moloch through a unified page management? Is there a detailed manual configuration description?
