### ISSUE TITLE
API unique.txt Wiki description is wrong

### ISSUE THREAD

**Issue by codex38** [aol/moloch#850]
**Elasticsearch version**: 6.4

**Moloch version**: 1.1.0

**OS name and version**: Ubuntu 16.04

**How was Moloch built/installed:** deb

**Provide logs, stack traces and steps to reproduce**:

When requesting the unique data of a field, according to the Wiki the API call should be:
**/unique.txt?field=ip.src**
which does not return anything.

The when getting the data over the viewer (Main View/Sessions -> Click on arrow next to src IP -> Export unique src ips) it calls unique.txt with different arguments
**unique.txt?counts=0&exp=ip.src**
This returns the wanted results.

Hence there must be something wrong with the API description in the wiki.

**Comment by awick** [comment]
The wiki wasn't wrong, but it was missing the exp description, I've added.  field=ip.src doesn't work because ip.src isn't a database field name.  You would use either field=a1 or field=srcIp depending which version of moloch you are running, or exp=ip.src
