### ISSUE TITLE
Feature request: tags based on filename in offline pcap directory mode

### ISSUE THREAD

**Issue by packetrevolt** [aol/moloch#857]
When running in offline pcap directory mode, have an option that would add tags using parts from the filename.  This way moloch-capture service can be left running monitoring a directory and have custom tags added to each pcap import based on filename.  Useful when automatically importing pcaps from other programs into moloch.

When running:
`moloch-capture -R /data/moloch/import/ -m --delete --copy`

```
/data/moloch/import/suricata.233424.pcap
/data/moloch/import/suricata.090983.pcap
```

The first pcap would have `suricata` and `233424` added as tags when imported.
The second pcap would have `suricata` and `090983` added as tags when imported.

**Comment by awick** [comment]
Will be in next major release
