### ISSUE TITLE
"Info" boolean search filter?

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#86]
Not sure if this is currently possible.  For SPI records that display meta in the 'Info' field of the sessions tab, can we make it query-able so that either ONLY records with meta information to display in the 'Info' column are returned to the view, likewise for records withOUT meta information to display in the 'Info' column.

info.display == true    ; ?
info.display == false   ; or whatever works

I see both cases being of interest during forensic deep dives.

**Comment by 31453** [comment]
Not sure this is useful given each user could have a different set of fields. It might be better for a user to just list the fields that they want to exist. For example, `http.uri == EXISTS! && cert.alt == EXISTS!`.

Please reopen if this specific functionality is desired and worth the effort.
