### ISSUE TITLE
No network data

### ISSUE THREAD

**Issue by bubaiwantong** [aol/moloch#861]
**Elasticsearch version**:6.2.4

**Moloch version**:1.1.0

**OS name and version**:Centos7

**How was Moloch built/installed:rpm

**Provide logs, stack traces and steps to reproduce**:
ISSUE:No date
![image](https://user-images.githubusercontent.com/33851803/40640242-c972fde0-6347-11e8-8c84-1c6a72c72d82.png)

em2 is span，have data
![image](https://user-images.githubusercontent.com/33851803/40640330-2010b6d8-6348-11e8-96ee-860292f34d05.png)

config.ini
![image](https://user-images.githubusercontent.com/33851803/40640362-459f394c-6348-11e8-95a3-9dba65023215.png)
![image](https://user-images.githubusercontent.com/33851803/40640387-60a2c5e2-6348-11e8-8f3d-1489f0bdc2df.png)

Please help me,thank you

**Comment by awick** [comment]
* Try it without the pfring reader
* make sure you wait at least 10 minutes to see if the data shows up
* https://github.com/aol/moloch/wiki/FAQ#moloch-is-not-working
