### ISSUE TITLE
Error after sudo make install

### ISSUE THREAD

**Issue by thiagogilis** [aol/moloch#862]
This link wasn't working here http://slackinvite.molo.ch/

**Elasticsearch version**: 5.6.7

**Moloch version**: Last one from Github at time of writing

**OS name and version**: Ubuntu 16.04 LTS

**How was Moloch built/installed:** sudo ./easybutton-build.sh --install

**Provide logs, stack traces and steps to reproduce**: 
Fresh Ubuntu install.
Using the deb it wouldn't work, so I'm trying to build from source.
I followed the steps from Github.
Installed ES 5.6.7, installed Node.js version 6.x and ran sudo npm install on viewer directory.
Errors at the end (yes, first I had already launched sudo ./easybutton-build.sh):

netkia@netkia-pc:/data/moloch$ sudo ./easybutton-build.sh --install
MOLOCH: Installing Dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
bison is already the newest version (2:3.0.4.dfsg-1).
dh-autoreconf is already the newest version (11).
flex is already the newest version (2.6.0-11).
g++ is already the newest version (4:5.3.1-1ubuntu1).
gettext is already the newest version (0.19.7-2ubuntu3).
libbz2-dev is already the newest version (1.0.6-8).
libffi-dev is already the newest version (3.2.1-4).
libgeoip-dev is already the newest version (1.6.9-1).
libjson-perl is already the newest version (2.90-1).
libmagic-dev is already the newest version (1:5.25-2ubuntu1).
libpcre3-dev is already the newest version (2:8.38-3.1).
libpng12-dev is already the newest version (1.2.54-1ubuntu1).
libreadline-dev is already the newest version (6.3-8ubuntu2).
libsocket6-perl is already the newest version (0.25-1build2).
libtool is already the newest version (2.4.6-0.1).
libwww-perl is already the newest version (6.15-1).
libyaml-dev is already the newest version (0.1.6-3).
make is already the newest version (4.1-6).
pkg-config is already the newest version (0.29.1-0ubuntu1).
xz-utils is already the newest version (5.1.1alpha+20120614-2ubuntu2).
curl is already the newest version (7.47.0-1ubuntu2.8).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.12).
uuid-dev is already the newest version (2.27.1-6ubuntu3.4).
wget is already the newest version (1.17.1-1ubuntu1.4).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
The following packages were automatically installed and are no longer required:
  ant ant-optional antlr ca-certificates-java default-jre-headless groovy2 gyp ivy java-common java-wrappers
  javascript-common junit4 libantlr-java libapache-pom-java libasm4-java libbsf-java libbsh-java libcommons-cli-java
  libcommons-logging-java libcommons-parent-java libelasticsearch1.7-java libgpars-groovy-java libhamcrest-java
  libhawtjni-runtime-java libhyperic-sigar-java libjansi-java libjansi-native-java libjcommander-java libjcsp-java
  libjline2-java libjna-java libjna-jni libjs-inherits libjs-jquery libjs-node-uuid libjs-underscore libjsr166y-java
  libjts-java libllvm3.8 liblog4j-extras1.2-java liblog4j1.2-java liblucene4.10-java libmircommon5 libnetty-3.9-java
  libqdox-java libqmi-glib1 libqpdf17 libservlet2.5-java libspatial4j-0.4-java libuv1 libuv1-dev libxpp3-java
  libxstream-java libyaml-snake-java node-abbrev node-ansi node-ansi-color-table node-archy node-async node-block-stream
  node-combined-stream node-cookie-jar node-delayed-stream node-forever-agent node-form-data node-fstream
  node-fstream-ignore node-github-url-from-git node-glob node-graceful-fs node-gyp node-inherits node-ini
  node-json-stringify-safe node-lockfile node-lru-cache node-mime node-minimatch node-mkdirp node-mute-stream node-node-uuid
  node-nopt node-normalize-package-data node-npmlog node-once node-osenv node-qs node-read node-read-package-json
  node-request node-retry node-rimraf node-semver node-sha node-sigmund node-slide node-tar node-tunnel-agent
  node-underscore node-which openjdk-8-jre-headless testng ubuntu-core-launcher
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
MOLOCH: Downloading and building static thirdparty libraries
MOLOCH: Not rebuilding glib
MOLOCH: Not rebuilding yara
MOLOCH: Not rebuilding libmaxmind
MOLOCH: NOT rebuilding libpcap
MOLOCH: Not rebuilding curl
MOLOCH: Not rebuilding lua
MOLOCH: Building capture
./configure --prefix=/data/moloch --with-libpcap=/data/moloch/thirdparty/libpcap-1.8.1 --with-yara=thirdparty/yara/yara-3.7.1 --with-maxminddb=thirdparty/libmaxminddb-1.3.2 --with-glib2=thirdparty/glib-2.54.3 --with-curl=thirdparty/curl-7.59.0 --with-lua=thirdparty/lua-5.3.4
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking for git... git
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/inotify.h usability... yes
checking sys/inotify.h presence... yes
checking for sys/inotify.h... yes
checking for main in -lpcre... yes
checking for main in -luuid... yes
checking for main in -lrt... yes
checking for main in -lnet... no
checking for main in -ldl... yes
checking for main in -lresolv... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for pfring... no
checking for libpcap... /data/moloch/thirdparty/libpcap-1.8.1
checking for nl_socket_alloc in -lnl-3... no
checking for nl_socket_alloc in -lnl... no
checking for nl_handle_alloc in -lnl... no
checking for yara... thirdparty/yara/yara-3.7.1
checking for maxminddb... thirdparty/libmaxminddb-1.3.2
checking for glib2... thirdparty/glib-2.54.3
checking for curl... thirdparty/curl-7.59.0
checking for lua... thirdparty/lua-5.3.4
checking for magic... checking for main in -lmagic... yes
yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating capture/Makefile
config.status: creating capture/plugins/Makefile
config.status: creating capture/plugins/daq/Makefile
config.status: creating capture/plugins/pfring/Makefile
config.status: creating capture/plugins/snf/Makefile
config.status: creating capture/plugins/lua/Makefile
config.status: creating capture/parsers/Makefile
config.status: creating db/Makefile
config.status: creating tests/plugins/Makefile
config.status: creating viewer/Makefile
config.status: creating viewer/version.js
config.status: creating parliament/Makefile
config.status: creating release/Makefile
config.status: creating capture/molochconfig.h
config.status: capture/molochconfig.h is unchanged
config.status: executing depfiles commands
Making all in .
make[1]: Entering directory '/data/moloch'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/data/moloch'
Making all in capture
make[1]: Entering directory '/data/moloch/capture'
gcc -fPIC -g -O2 -Wall -Wextra -D_GNU_SOURCE -c main.c db.c yara.c http.c config.c parsers.c plugins.c field.c trie.c writers.c writer-inplace.c writer-disk.c writer-null.c writer-simple.c readers.c reader-libpcap-file.c reader-libpcap.c reader-tpacketv3.c packet.c session.c molochmagic.c rules.c drophash.c \
    -I/data/moloch/thirdparty/libpcap-1.8.1 \
    -Ithirdparty -I/data/moloch/thirdparty/glib-2.54.3/glib -I/data/moloch/thirdparty/glib-2.54.3 -I/data/moloch/thirdparty/glib-2.54.3/gmodule -I/data/moloch/thirdparty/glib-2.54.3/gobject -I/data/moloch/thirdparty/yara/yara-3.7.1/libyara/include -I/data/moloch/thirdparty/libmaxminddb-1.3.2/include -I/data/moloch/thirdparty/curl-7.59.0/include \
    -DBUILD_VERSION='"v1.1.0-76-g4cd28a1"'
db.c: In function ‘moloch_db_load_oui’:
db.c:1818:22: warning: ‘str’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         node->data = g_strdup(str);
                      ^
field.c: In function ‘moloch_field_parse_ip’:
field.c:716:9: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         ((uint32_t *)v->s6_addr)[0] = 0;
         ^
field.c: In function ‘moloch_field_ip4_add’:
field.c:797:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((uint32_t *)v->s6_addr)[0] = 0;
     ^
writer-disk.c: In function ‘writer_disk_output_cb’:
writer-disk.c:180:13: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
             (void)ftruncate(outputFd, filelen);
             ^
writer-disk.c: In function ‘writer_disk_output_thread’:
writer-disk.c:251:17: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
                 (void)ftruncate(outputFd, filelen);
                 ^
writer-simple.c: In function ‘writer_simple_thread’:
writer-simple.c:339:13: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
             ftruncate(info->file->fd, info->file->pos);
             ^
gcc -rdynamic -ggdb main.o db.o yara.o http.o config.o parsers.o plugins.o field.o trie.o writers.o writer-inplace.o writer-disk.o writer-null.o writer-simple.o readers.o reader-libpcap-file.o reader-libpcap.o reader-tpacketv3.o packet.o session.o molochmagic.o rules.o drophash.o -o moloch-capture \
            -u g_checksum_update -u g_hmac_update -u g_uri_unescape_segment \
    /data/moloch/thirdparty/libpcap-1.8.1/libpcap.a \
    /data/moloch/thirdparty/glib-2.54.3/glib/.libs/libglib-2.0.a /data/moloch/thirdparty/glib-2.54.3/gio/.libs/libgio-2.0.a /data/moloch/thirdparty/glib-2.54.3/gobject/.libs/libgobject-2.0.a /data/moloch/thirdparty/glib-2.54.3/gthread/.libs/libgthread-2.0.a /data/moloch/thirdparty/glib-2.54.3/gmodule/.libs/libgmodule-2.0.a /data/moloch/thirdparty/glib-2.54.3/glib/.libs/libglib-2.0.a /data/moloch/thirdparty/yara/yara-3.7.1/libyara/.libs/libyara.a /data/moloch/thirdparty/libmaxminddb-1.3.2/src/.libs/libmaxminddb.a /data/moloch/thirdparty/curl-7.59.0/lib/.libs/libcurl.a -lrt -luuid -lpcre thirdparty/http_parser.o thirdparty/js0n.o thirdparty/patricia.o -ldl -lpthread -lssl -lcrypto -lyaml \
    -lm -lresolv -lmagic -lffi -lz
(cd parsers; make)
make[2]: Entering directory '/data/moloch/capture/parsers'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/data/moloch/capture/parsers'
(cd plugins; make)
make[2]: Entering directory '/data/moloch/capture/plugins'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/data/moloch/capture/plugins'
make[1]: Leaving directory '/data/moloch/capture'
Making all in db
make[1]: Entering directory '/data/moloch/db'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/data/moloch/db'
Making all in viewer
make[1]: Entering directory '/data/moloch/viewer'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/data/moloch/viewer'
Making all in parliament
make[1]: Entering directory '/data/moloch/parliament'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/data/moloch/parliament'
Making all in release
make[1]: Entering directory '/data/moloch/release'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/data/moloch/release'
make: '../lua.so' is up to date.
Making install in .
make[1]: Entering directory '/data/moloch'
make[2]: Entering directory '/data/moloch'
npm install
/usr/bin/install -c -D package.json /data/moloch/package.json
/usr/bin/install: 'package.json' and '/data/moloch/package.json' are the same file
Makefile:748: recipe for target 'install-exec-local' failed
make[2]: *** [install-exec-local] Error 1
make[2]: Leaving directory '/data/moloch'
Makefile:640: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/data/moloch'
Makefile:326: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
MOLOCH: Installed, now type sudo make config'
netkia@netkia-pc:/data/moloch$ sudo make config
/data/moloch/bin/Configure
/bin/bash: /data/moloch/bin/Configure: No such file or directory
Makefile:753: recipe for target 'config' failed
make: *** [config] Error 127

Thanks.

**Comment by awick** [comment]
* Thanks for the slackinvite ping, will look into it

* What do you mean the deb doesn't work?

* It looks like you are trying to build in /data/moloch, which won't work.  You need to check out into a different directory and install there.  I would wipe out or rename /data/moloch

**Comment by thiagogilis** [comment]
Thanks, I've already managed to install it using the deb!

**Comment by moooooooo** [comment]
sudo -s
then run the commands
peter
