### ISSUE TITLE
Moloch Capture Not Shipping Data and Capture looks constantly restart

### ISSUE THREAD

**Issue by jvernon214** [aol/moloch#863]
**Elasticsearch version**:
6.2.4 using Elastic Cloud
**Moloch version**:
Moloch 1.1.1
**OS name and version**:
centos-release-6-9.el6.12.3.x86_64
**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
rpm
**Provide logs, stack traces and steps to reproduce**:
No logs generated, checked at /data/moloch/logs/capture.log

I can connect to elasticsearch and it looks like the fields index was created successfully.  I don't see any moloch capture data when I look directly in ES or using moloch viewer.  tailing the capture log I don't see any errors generated. I did notice by using top that the molochcapture process is constantly restarting.  This is also hosted on a VPS.  Any help would be appreciated

**Comment by awick** [comment]
Did you run thru the FAQ?  https://github.com/aol/moloch/wiki/FAQ#moloch-is-not-working

**Comment by jvernon214** [comment]
I did follow that.  I noticed this in my /var/log/messages
Jun  5 14:51:19 server init: molochcapture main process ended, respawning
Jun  5 14:51:56 server init: molochcapture main process (20326) terminated with status 1
Jun  5 14:51:56 server init: molochcapture main process ended, respawning

**Comment by jvernon214** [comment]
# Semicolon ';' seperated list of interfaces to listen on for traffic
interface=lo;venet0;

Should I have a ; at the end of this?

**Comment by awick** [comment]
Shouldn't matter.   Try the FAQ list, or if its crashing submit a crash report

https://github.com/aol/moloch/wiki/FAQ#moloch-capture-crashes

**Comment by awick** [comment]
reopen if you have more details
