### ISSUE TITLE
gh0st protocol detection

### ISSUE THREAD

**Issue by florin2528** [aol/moloch#867]
**Elasticsearch version**:
 "version" : {
    "number" : "5.6.8",
    "build_hash" : "688ecce",
    "build_date" : "2018-02-16T16:46:30.010Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },

**Moloch version**:
moloch-capture 0.50.0/v0.50.0 
glib2: 2.52.3
libpcap: libpcap version 1.8.1
curl: libcurl/7.55.0 OpenSSL/1.0.2k zlib/1.2.8
pcre: 8.31 2012-07-06
yara: 3.6.3

**OS name and version**:
Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
deb

**Provide logs, stack traces and steps to reproduce**:
It has been notice that Moloch detects gh0st protocol, but with an investigation regarding this we found out that actually it's matching this protocol on DCE/RPC packets based on the HEX below:
payload8.dst.hex == 05000c0710000000

Can I kindly ask you to confirm this. 

Kind Regards,
Florin

**Comment by awick** [comment]
I'm confused what you want to confirm?  Sounds like its doing what you said.

**Comment by florin2528** [comment]
But the traffic which Moloch is capturing as gh0st protocol actually it's not.

**Comment by awick** [comment]
Many of the protocol labels are just best moloch can determine

**Comment by florin2528** [comment]
thank you for clarifying this issue.
