### ISSUE TITLE
Incorrect TCP Sequence number in dumped pcap files

### ISSUE THREAD

**Issue by aminlatifi** [aol/moloch#870]
I'm testing Moloch to measure it's accuracy. Suddenly, I found out that there is some difference in the traffic data dumped in Moloch dumped PCAP files (in /data/moloch/raw) with the origin traffic sent to interface Moloch is capturing on.
I used tcpreplay tools to send bigFlows.pcap file (https://s3.amazonaws.com/tcpreplay-pcap-files/bigFlows.pcap) with rate 800 Mbps to interface Moloch is capturing on. I extracted and sorted information of packets saved in pcap files, both origin bigFlows.pcap file and PCAP files dumped by Moloch. Unfortunately, the TCP sequence number packets are different in some cases.
I attached extracted information. For example, packet with identification of 0x000010ff, and session info of below has different sequence number in these two files. The order of information is protocol, source IP, destination IP, TCP source port, TCP destination port.
eth:ethertype:ip:tcp    107.20.158.52   172.16.133.153  8080    56545
[captured.zip](https://github.com/aol/moloch/files/2165359/captured.zip)
[origin.zip](https://github.com/aol/moloch/files/2165362/origin.zip)

**Elasticsearch version**:

**Moloch version**: 1.1.1

**OS name and version**: Debian 9.4

**How was Moloch built/installed:  singlehost built

**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
Not sure I fully understand the test.  Moloch doesn't change the packet data, some things I would look at
* run tcpdump and moloch on the same interface and see if the local tcpdump has the same issue
* make sure you've turned off ALL features of network cards

**Comment by awick** [comment]
Can't reproduce, if you can provide more info can reopen.  What I tried:
* loaded `bigFlows.pcap` into moloch
* exported single session matching your above `(ip == 107.20.158.52   && ip == 172.16.133.153  && port == 8080    && port == 56545)`
* `tcpdump -n -r session.pcap > /tmp/1`
* `tcpdump -n -r bigFlows.pcap host 107.20.158.52   and host 172.16.133.153  and port 8080    and port 56545 > /tmp/2`
* `diff /tmp/1 /tmp/2`

No difference

**Comment by aminlatifi** [comment]
Sorry for late response.
Actually it was tcpdump and tshark behavior than make me think there is some problem. I used tcpdump with --absolute-tcp-sequence-numbers flag and everything is OK.
Thanks for your response.
