### ISSUE TITLE
Configure script change for updating GEO files

### ISSUE THREAD

**Issue by johnklasa** [aol/moloch#871]
**Moloch version**:
v1.1.1

**OS name and version**:
RedHat Enterprise Linux Server 7.4

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm

Small improvement to Configure script when running that and the server doesn't have Internet connection.

################################################################################
echo "Do you want to update GEO files yes/no"
read -r INET
if [ "$INET" == "yes" ]; then
echo "Moloch - Downloading GEO files"
$MOLOCH_INSTALL_DIR/bin/moloch_update_geo.sh > /dev/null
        else echo "No internet connection NOT updating GEO files"
fi

**Comment by mmguero** [comment]
I modified the script locally to look like this. That way if the `wget` fails for whatever reason, it leaves the old files in place.

```
#!/bin/sh

cd "/data/moloch/etc"

wget -nv --no-check-certificate -O ipv4-address-space.csv_new https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.csv && \
  mv -f ipv4-address-space.csv_new ipv4-address-space.csv || \
  rm -f ipv4-address-space.csv_new

wget -nv -O GeoLite2-Country.mmdb.gz 'https://updates.maxmind.com/app/update_secure?edition_id=GeoLite2-Country' && \
  (/bin/rm -f GeoLite2-Country.mmdb && zcat GeoLite2-Country.mmdb.gz > GeoLite2-Country.mmdb) || \
  rm -f GeoLite2-Country.mmdb.gz

wget -nv -O GeoLite2-ASN.mmdb.gz 'https://updates.maxmind.com/app/update_secure?edition_id=GeoLite2-ASN' && \
  (/bin/rm -f GeoLite2-ASN.mmdb && zcat GeoLite2-ASN.mmdb.gz > GeoLite2-ASN.mmdb) || \
  rm -f GeoLite2-ASN.mmdb.gz

wget -nv -O oui.txt_new https://raw.githubusercontent.com/wireshark/wireshark/master/manuf && \
  mv -f oui.txt_new oui.txt || \
  rm -f oui.txt_new
```

**Comment by johnklasa** [comment]
PR done
