### ISSUE TITLE
Typo in install script - elaticsearch

### ISSUE THREAD

**Issue by andyhouse90** [aol/moloch#872]
CentOS 7 - updated

wget ht[ ]tps://files.molo.ch/builds/centos-7/moloch-1.1.1-1.x86_64.rpm 

Installed, using DEMO elastic install

Error during install
/data/moloch/bin/Configure: line 151: /etc/elaticsearch/elasticsearch.yml: No such file or directory

Typo in "elaticsearch"

Appears this missed the index_not_found_exception flag not being configured, not sure what else was missed.

**Comment by awick** [comment]
removing the file and just using what ships with elasticsearch now
