### ISSUE TITLE
SPI Graph field change not handled by Open Sessions sub-menu

### ISSUE THREAD

**Issue by jolan78** [aol/moloch#874]
**Elasticsearch version**: 5.6.9

**Moloch version**: 1.1.1

**OS name and version**: Ubuntu 18.04

**How was Moloch built/installed:** moloch_1.1.1-1_amd64.deb

**Provide logs, stack traces and steps to reproduce**:
- in SPI Graph, change the "SPI Graph" field (from "node" to "tags" in this exemple) and hit enter
- from the drop-down menu of a graph title, select "Open New Sessions Tab"
- the new tab opens with a "node == tagname" query instead of "tags == tagname"

note that opening SPI graph again with "tags" already set in SPI Graph field works corretly.

**Comment by awick** [comment]
already fixed in next version, thanks!
