### ISSUE TITLE
Moloch UI

### ISSUE THREAD

**Issue by lengrongfu** [aol/moloch#885]
**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

i want ask ,first 'Moloch UI' What is it? second i want before arch,I use multiple machines, how do I use one view?
![image](https://user-images.githubusercontent.com/15009201/43258812-b08683dc-9106-11e8-8ae5-707675018cd9.png)

**Comment by awick** [comment]
For support questions use https://moloch-fpc.slack.com (sign up at http://slackinvite.molo.ch/)
or the google group https://groups.google.com/forum/#!forum/moloch-fpc instead of opening an issue
