### ISSUE TITLE
Can't add tags.

### ISSUE THREAD

**Issue by Eric-L90** [aol/moloch#888]
Moloch: 1.5.2
Q1: I use "Upload" to upload a pcap file, and i add a tag "upload" to "Tags". But there are no tags in sessions.
I checked viewer.js,and then changed
`if (req.body.tag) {
    var t = req.body.tag.replace(/[^-a-zA-Z0-9_:,]/g, '').split(',');`
to
`if (req.body.tags) {
    var t = req.body.tags.replace(/[^-a-zA-Z0-9_:,]/g, '').split(',');`.
Then it worded well.

**Comment by awick** [comment]
thanks
