### ISSUE TITLE
How to send some sessions to another cluster?

### ISSUE THREAD

**Issue by Eric-L90** [aol/moloch#890]
Moloch: 1.5.2
Elasticsearch: 6.3.0
`cronQueries = true
[moloch-clusters]
cluster2=url:http://10.10.10.1:8005;passwordSecret:test;name:cluster2`

Hi, guys.I need your help.
I have two moloch clusters,one is cluster1,the other one is cluster2.
Now, i want send some sessions from cluster1 to cluster2.
I have tried CronQuery and Action. I found some questions.
Q1: CronQuery can send sessions to cluster2.But can't add tags to sessions. And the time range of query is not incremental, so the time range will be bigger and bigger.
Q2: "Send Session to ***" command is not avaliable, the reasion is that "cluster:req.body.cluster" is undefined.
So,Could you give me some advice? Are these bugs?

**Comment by 31453** [comment]
Thanks for pointing out these issues!

- Q2 is definitely a bug and is fixed in this commit: 0290510
- I need to look into Q1 further

**Comment by Eric-L90** [comment]
Ok, thanks.

**Comment by Eric-L90** [comment]
Hello guys, Is there any conclusion for Q1?

**Comment by 31453** [comment]
Q2 was also a bug. Thanks for finding and reporting it! Let me know if you have any further issues and I'll reopen the issue.
