### ISSUE TITLE
Moloch SPI DATA support output Redis or Kafka?

### ISSUE THREAD

**Issue by Canon88** [aol/moloch#891]
Moloch: 1.5.2
Elasticsearch: 6.3.0

Hi, guys.I need your help.
I have a question. I read the manuals and configuration files on the wiki. Moloch's SPI data can be sent to ElasticSearch, but my network data is relatively large. To prevent data loss, I want to send it to the cache queue first. For example: Reids or Kafka, this is the best. Can Moloch now support this? Anybody can help me? Thank you.

**Comment by awick** [comment]
No, moloch doesn't support it
