### ISSUE TITLE
File carving in viewer

### ISSUE THREAD

**Issue by 31453** [aol/moloch#893]
Feature request from @ejclark1:

In other tools, such as Netwitness, it is possible to carve files out of pcap directly, without downloading the pcap, ingesting it into wireshark, and then clicking export files. Being able to explore something like an SMB session and click export file on file name, hash, or what have you would definitely speed up incident response time.

**Comment by awick** [comment]
Everything but SMB already supports this.  Is this really a SMB only issue?

**Comment by ejclark1** [comment]
Yes, this is SMB specific.
