### ISSUE TITLE
Unable to change replica

### ISSUE THREAD

**Issue by rubenrodr-versia** [aol/moloch#895]
```
ES Version:                     5.6.10
DB Version:                         51
ES Nodes:                            3/4
Session Indices:                     8
Sessions2:                  24,420,398 (43,044,107,645 bytes)
Session Density:               763,137 (1,345,128,363 bytes)
History Indices:                     2
Histories:                       3,596 (1,507,191 bytes)
History Density:                   449 (188,398 bytes)
stats_v3:                            1 (23,575 bytes)
files_v5:                        1,272 (197,148 bytes)
users_v5:                            1 (15,196 bytes)
```

```
Moloch 1.5.2-1
```
```
Ubuntu 16.04.5 LTS
```
```
deb package
```

With capture and viewer stopped if i try to change replica (actually 3 shards and 3 replica):
```
# /data/moloch/db/db.pl http://10.190.14.42:9200 upgrade --shards 3 --replicas 2
It is STRONGLY recommended that you stop ALL moloch captures and viewers before proceeding.

There are 3 elastic search data nodes, if you expect more please fix first before proceeding.

Trying to upgrade from version 51 to version 51.

Type "UPGRADE" to continue - do you want to upgrade??
UPGRADE
Starting Upgrade
Updating sessions2 mapping for 8 indices

Finished
```

The indexes are still 3x3.

![image](https://user-images.githubusercontent.com/24841626/44015218-42342452-9ed0-11e8-9333-00a18a433573.png)

Thanks.
Best regards.

**Comment by rubenrodr-versia** [comment]
The new sessions indexes are still being created as 3x3:
![image](https://user-images.githubusercontent.com/24841626/44074413-c1ef6134-9f98-11e8-8221-32189cd692b3.png)

**Comment by awick** [comment]
upgrade will only change future sessions2
expire will change current sessions2 or you can use the _settings api to change current session2

**Comment by awick** [comment]
I can't reproduce.  If you do
`curl 'http://localhost:9200/_template/*sessions2*?pretty' | grep number_of`

you should see
        "number_of_shards" : "3",
        "number_of_replicas" : "2"

if you don't, try doing the upgrade again and then the curl and see if it changes.
