### ISSUE TITLE
SMB traffic missing SPI data or not correctly ingested

### ISSUE THREAD

**Issue by ejclark1** [aol/moloch#898]
**Elasticsearch version**:
6.3.2

**Moloch version**:
1.5.2
**OS name and version**:
CentOS 7.5
**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm
**Provide logs, stack traces and steps to reproduce**:
none

SMB traffic passing across the wire is not logging much  of the spi data for much of the SMB pcap we are seeing. Attached is a screenshot showing the fields not being populated. 
<img width="797" alt="smb" src="https://user-images.githubusercontent.com/32842321/44220098-a3f28800-a14b-11e8-8901-29a2bb563bff.png">

Additionally, files carved out by identity by Bro are not identified in Moloch spi data; for instance, in the above screenshot, there are gpt.ini files,. but no mention of other files in the transaction, such as Registry.xml. 

The pcap used for bro analysis was pulled directly from Moloch, using the moloch id associated with the smb traffic. This was to get an apples to apples comparison. There were 147 packets in the session, so I did not hit the 10k mark and spread the traffic across multiple pcaps.

**Comment by awick** [comment]
All the pcaps you sent me are missing packets.  If you feel moloch is dropping packets please run a parallel tcpdump and we can compare.
