### ISSUE TITLE
Should we check if the pcap file exists in the file index?

### ISSUE THREAD

**Issue by Eric-L90** [aol/moloch#901]
Moloch: 1.5.2
Elasticsearch: 6.3.0

I found a problem. When a new pcap file is generated by moloch-capture, the file name should be indexed to es,but sometimes it won't be indexed successfully. Therefore,when the free space is less than 10%, the delete task will be triggered,but this will only delete the file whose file name existed in es, and other files won't be deleted.so there will be more and more unindexed pcap files, and then they will cause a proplem:"No space left on device".
So should we add a task to deal with this kind of problem?
a crontab reindex task? or a delete task?

**Comment by awick** [comment]
This should rarely, if ever happen.  When it does usually it means that the ES server is overloaded and you are dropping ES requests, is that the case?

./db.pl sync-files can repair the problem

**Comment by Eric-L90** [comment]
I can add a crontab task  to resolve the problem.Thanks.
