### ISSUE TITLE
unexpected packet drop

### ISSUE THREAD

**Issue by mtesar-rh** [aol/moloch#911]
Hello guys - I experienced an unwanted packet drop on OS (rx_dropped counter in ethtool -S) I noticed that this is because the moloch in reader-tpacketv3.c at line 264 sets all the sockaddr_ll to zero and not fill the member ll_pkttype to anything useful like PACKET_HOST | PACKET_MULTICAST | PACKET_OTHERHOST | PACKET_BROADCAST. But there stays zero which means PACKET_HOST only. This causes drops of packets which are mirrored to the box/moloch. Like for example multicast which no local NIC is group member. What do you think?

**Comment by awick** [comment]
As we talked about on slack, I don't think this works like this.
