### ISSUE TITLE
Feature Request - Parliament Dashboard Only

### ISSUE THREAD

**Issue by 31453** [aol/moloch#917]
Start Parliament with a `--dasboardOnly` option to use Parliament as a dashboard of Moloch's that are running. This option would:
1. Hide the login button
2. Hide the settings page

**Comment by 31453** [comment]
@srinathman would love to hear your feedback on this! Specifically, since you cannot interact with the issues or change the default removal of issues time, it might make sense to not display issues at all.

**Comment by srinathman** [comment]
Doing a quick test here. It works great !
And even on read only mode, we actually want users and admins to be able to see nodes/cluster with issues. I set "removeIssuesAfter" to a low value and I believe that only persistent errors will show on the dashboard.

I suggest that not displaying issues being another setting, like this people can pick and choose what they need.

**Comment by 31453** [comment]
Glad to hear it works like you wanted. Thanks for the feedback!
