### ISSUE TITLE
files_v5 index doesn't accumulate pcap information in real time

### ISSUE THREAD

**Issue by bibibibit** [aol/moloch#921]
**Elasticsearch version**: 
5.6.5

**Moloch version**: 
1.6.0

**OS name and version**: 
CentOS 7.3.1611

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
with RPM

**Provide logs, stack traces and steps to reproduce**:
![image](https://user-images.githubusercontent.com/43563363/45994767-04bc9b00-c0d0-11e8-9925-e3bacd17d264.png)

I have question regarding accumulation of pcap files in real time.

The option "moloch-capture -R -m -s" was used to monitor the directory where the pcap files were created in real time.
The session information is generated in real time, however the pcap information generated in files_v5 is indexed when the number of pcap is cumulative such as 256, 512.
And it stopped in 512 pcaps.
In moloch 1.1.1 files_v4, pcap files have accumulated in real time, but I wonder why files_v5 is not created in real time.

**Comment by awick** [comment]
I would check what the "files" alias points to, it should point to v5

**Comment by awick** [comment]
feel free to reopen if you have more info
