### ISSUE TITLE
cleaner moloch-capture output for pcap load

### ISSUE THREAD

**Issue by philhagen** [aol/moloch#923]
When loading a pcap file, the default output is very verbose and difficult to make sense of.
I suggest that the current output be displayed only with a "verbose" output mode, or something similar.  It would be helpful if progress of some sort was indicated.  Not sure if that would be a progress-bar type indicator or just "loaded 'x' packets/MB/GB so far" message.  Ideally, the message would stay on the same line, such even loading a large pcap doesn't cause the terminal to scroll.  (I'm imagining the way the `--progress` option to rsync, or the output to the `scp` command looks.)

Idea: (I am not a UI/UX person, so please don't laugh...)
```
$ moloch-capture -r foo.pcap
Loading foo.pcap: 1,151MB of 5,157MB loaded...
```

**Comment by philhagen** [comment]
I thought I'd followed up on this but forgot :(. Sorry!
This looks great - thank you!

**Comment by 31453** [comment]
Looks like this has been mostly implemented. Please reopen with suggestions if there is more to be done.
