### ISSUE TITLE
How to GTP protocol analyze with moloch

### ISSUE THREAD

**Issue by TECLIPSE** [aol/moloch#926]
What can i do?
Sample packet  link :
https://www.cloudshark.org/captures/374cf36574b6

**Comment by TECLIPSE** [comment]
@awick can i use your code of plugin type?

**Comment by awick** [comment]
please reopen if change didn't work

**Comment by aminlatifi** [comment]
Why GTP detunneling is only implemented for IPv4 packets?
AFIN there is no such restriction and IPv6 and PPP also can transport  GTP packets.

**Comment by awick** [comment]
@aminlatifi its not just implemented for ipv4, please provide or DM me a sample packet that doesn't work

**Comment by aminlatifi** [comment]
I don't have any sample packet.
I see it's just implemented at `moloch_packet_ip4` function in packet.c file. So, it seems the code does is not called for IPv6 GTP tunneled packets for example.

**Comment by aminlatifi** [comment]
The code is

>         
        if (udphdr->uh_dport == 0x6808 && len > ip_hdr_len + (int)sizeof(struct udphdr) + 12) {
            int rem = len - ip_hdr_len - sizeof(struct udphdr *);
            uint8_t *buf = (uint8_t *)ip4 + ip_hdr_len + sizeof(struct udphdr *);
            if ((buf[0] & 0xf0) == 0x30 && buf[1] == 0xff && (buf[2] << 8 | buf[3]) == rem - 8) {
                return moloch_packet_ip4_gtp(batch, packet, buf, rem);
            }
        }

**Comment by awick** [comment]
Ah the outside is ipv6?, I thought you were talking about the inside being ipv6, which if you look inside of moloch_packet_ip4_gtp it does support.

Anyway, if you find a sample pcap we can fix.

**Comment by aminlatifi** [comment]
By the protocol definition it's possible the outside be IPv6.

**Comment by awick** [comment]
Agree, but I need a packet.  I've opened #1034 since this issue is closed.

**Comment by aminlatifi** [comment]
Sessions of GTP does not have "udp" in their protocol field. 
Since GTP tunnel is over UDP, it makes sense to UDP is mentioned too. What's your idea?

**Comment by aminlatifi** [comment]
I suggest transport protocols (UDP, TCP, etc.) be added to protocol field as the way tunnel protocols (GRE, PPP, etc.) are added. I mean define a variable, set flags on it and process it latter.
