### ISSUE TITLE
hunt packet search jobs should skip sessions for which no PCAP exists

### ISSUE THREAD

**Issue by mmguero** [aol/moloch#946]
**Elasticsearch version**: 6.4.1

**Moloch version**: 1.6.0

**OS name and version**: Linux, debian testing (buster)

**How was Moloch built/installed:** easybutton inside of docker

**Provide logs, stack traces and steps to reproduce**:

1. Create session entries in the database with no associated PCAP file (for example, insert data via logstash or some other way)
2. Go to the hunts tab, and submit a hunt packet search job

You will see the viewer app crash, with the following backtrace:

```
Tue, 30 Oct 2018 14:08:12 GMT analyst POST /hunt 200 369 bytes 856.047 ms
url.js:103
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at /data/moloch/viewer/viewer.js:707:20
    at /data/moloch/viewer/viewer.js:651:14
    at exports.get (/data/moloch/viewer/db.js:465:7)
    at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:327:9)
    at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)
    at IncomingMessage.wrapper (/data/moloch/node_modules/lodash/lodash.js:4949:19)
    at emitNone (events.js:111:20)
```

After some experimentation, this seems to be quite similar to issue #878 (see also commit 4cdc44108e). It looks like the hunt job should skip sessions with no fileids set.

**Comment by awick** [comment]
hunt should do the ES query with an exists fileId sot it only process sessions with files associated

**Comment by mmguero** [comment]
I tested this patch, seems to fix the problem for me.

[hunt_fileid_exists_patch_946.txt](https://github.com/aol/moloch/files/2531098/hunt_fileid_exists_patch_946.txt)

**Comment by 31453** [comment]
@mmguero Thank you so much for figuring out the cause of the bug and providing a fix! Do you want to submit a pull request with that fix for the fake internet points?

**Comment by mmguero** [comment]
> @mmguero Thank you so much for figuring out the cause of the bug and providing a fix! Do you want to submit a pull request with that fix for the fake internet points?

Sure, I'll submit a pull request.
