### ISSUE TITLE
Multies.js - Please provide configuration option for Self signed certs.

### ISSUE THREAD

**Issue by nbhatia77** [aol/moloch#952]
For Multi- viewer - Please provide configuration options to use Self-signed/PKI certs for Multi-viewer. Currently, to make multi-viewer work, I had to modify multies.js and made the following changes under 
-----
//first connect:
//ssl: {rejectUnauthorized: !Config.insecure}
   ssl: {rejectUnauthorized: false}
---
And run, "npm config set strict-ssl false"

**Comment by awick** [comment]
feel free to reopen with more info
