### ISSUE TITLE
moloch-capture error: libssl.so.1.1: cannot open shared object file

### ISSUE THREAD

**Issue by geniusbabak** [aol/moloch#962]
**Elasticsearch version**: 
6.5.0

**Moloch version**: 
1.6.1

**OS name and version**: 
Ubuntu 16.04.5 LTS (Amazon EC2 m5xlarge)

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) 
deb (Followed readme files step by step)

**Provide logs, stack traces and steps to reproduce**:
I have Moloch Viewer running, but not showing any activity, so I checked the log files:
root@ip-72-31-22-77:~/pcapfiles# cat /data/moloch/logs/capture.log                                                  /data/moloch/bin/moloch-capture: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/data/moloch/bin/moloch-capture: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/data/moloch/bin/moloch-capture: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/data/moloch/bin/moloch-capture: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by awick** [comment]
I would guess you need to install libssl or openssl

**Comment by geniusbabak** [comment]
Fix:
On Ubunto 16.x, openssl or libssl-dev versions 1.0.2 are available and Moloch needs version 1.1.0.

**Comment by geniusbabak** [comment]
In that case it might be Amazon Ubuntu AMI problem! I had to purge the version available and clone OpenSLL git repository and build it locally. 
Then I reinstalled everything and capture service started to work.

**Comment by awick** [comment]
Are you sure you didn't install the 18 build on 16?  

Here is the output of ldd on 16, as you can see libssl 1.0.0 is required.
```
ldd /data/moloch/bin/moloch-capture
	linux-vdso.so.1 =>  (0x00007ffdd89d7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0f69d8e000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f0f69b89000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0f69985000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0f69768000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f0f694ff000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f0f690bb000)
	libyaml-0.so.2 => /usr/lib/x86_64-linux-gnu/libyaml-0.so.2 (0x00007f0f68e9c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0f68b93000)
	libmagic.so.1 => /usr/lib/x86_64-linux-gnu/libmagic.so.1 (0x00007f0f68973000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0f68759000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0f6838f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0f69f96000)```

**Comment by geniusbabak** [comment]
Oh oh! I'm feeling stupid now! Yup that's the case!
