### ISSUE TITLE
Connections tab's "ip.dst:port" field does not exist, preventing interactive search string

### ISSUE THREAD

**Issue by philhagen** [aol/moloch#965]
**Elasticsearch version**:
5.6.13

**Moloch version**:
1.6.1

**OS name and version**:
CentOS 7.5 (kernel 3.10.0-862.14.4.el7.x86_64

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
RPM

**Provide logs, stack traces and steps to reproduce**:
No logs, but the following steps to reproduce:
- Use "Connections" tab
- Select "Dst IP:Port" as a node type
- Hover over an IP:Port node and select "AND" to create/augment search string
- Syntax of "`ip.dst:port == 155.6.4.100:80`" is created, but this is not a valid field
- Error message of "`Unknown field: ip.dst:port`"

Suggested behaviors (I believe either one would work):
- Create a meta-field (something like a scripted field perhaps?) that allows the `ip.dst:port` field name
- When creating/augmenting a search string from an "IP:Port" node type, use a search string of e.g. `(ip.dst == 1.2.3.4 && port.dst == 80)`

**Comment by awick** [comment]
ya, this is a fake field for spi graph that I added quick because I needed it. :) . need to figure out how to do a combined feature.

btw, ip.dst already supports ip:port, so you just need to change "ip.dst:port == 155.6.4.100:80" to "ip.dst == 155.6.4.100:80" for now.

**Comment by awick** [comment]
Added in b0ec4ce152239290da77262cb2b02562ecdf2adc as alias to ip.dst
