### ISSUE TITLE
Feature Request: Index based on "Community ID"

### ISSUE THREAD

**Issue by moshekaplan** [aol/moloch#966]
Corelight (the company behind Bro/Zeek) published a project describing a "Community ID" - a separate specification for generating a likely-unique identifier for a network connection. This is implemented for both Bro/Zeek and Suricata. It would be great if moloch also supported the Community ID, so as to ease cross-referencing between Bro logs and Suricata logs with the network traffic indexed by moloch.

For more information, see https://github.com/corelight/community-id-spec and http://icir.org/christian/talks/2018-11-suricon-communityid.pdf

**Comment by awick** [comment]
was already on the list in my head, thanks for opening an issue

**Comment by EbolaWare** [comment]
I am looking forward to this feature. Thanks!

**Comment by patrickstjohn** [comment]
Looking forward to this as well. Will be great to have a hard pivot between Moloch, Bro and Suricata data.

**Comment by ckreibich** [comment]
I'm very late to the party here, but wanted to say thanks to everyone for adding this! I've added a link to in the known-implementations section over on the spec page:
https://github.com/corelight/community-id-spec#production-implementations
