### ISSUE TITLE
Add a threshold for when parliament will report a node as "not receiving packets"

### ISSUE THREAD

**Issue by srinathman** [aol/moloch#968]
When nodes are quiet, especially during off business hours, Parliament will create "No Packets" issues, but that does not necessarily represent a problem. 
It will be nice to have a configurable threshold when creating this kind of issue.

**Comment by srinathman** [comment]
I don't see how this commit solves the issue described. 
It seems to be solving another problem: "lower than expected packets per second"

You are checking:
`stat.deltaPacketsPerSec < getGeneralSetting('noPackets')`

But I was proposing to have the time frame configurable, i. e., Packets per X seconds delta.  

For example, create the issue when no packets were seen in the last 60 seconds. (60 being configurable)

**Comment by 31453** [comment]
Let me know if this works for you @srinathman. If not, feel free to reopen this issue with a comment about why it isn't the correct solution.
