### ISSUE TITLE
Segmentation Fault after new installation db.c no such file or directory

### ISSUE THREAD

**Issue by crwdawg** [aol/moloch#969]
Followed directions for installing at http://blog.infosecmatters.net/2017/05/moloch-fpc.html with newer packages.  I have initialized the database, and my config.ini file shows elasticsearch=http://127.0.0.1:9200

Elasticsearch version:  5.6.8
Moloch version:  1.6.0-1
jre - 8u192-Linux-x64
OS Name:  CentOS 7 (3.10.0-862.x86_64
Installed via RPM

Stack Trace.
[root@localhost bin]# gdb /data/moloch/bin/moloch-capture
<snip>
Reading symbols from /data/moloch/bin/moloch-capture...done.
(gdb) run /data/moloch/bin/moloch-capture debuginfo-install moloch-1.6.0-1.x86_64
Starting program: /data/moloch/bin/moloch-capture /data/moloch/bin/moloch-capture debuginfo-install moloch-1.6.0-1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Dec  3 07:53:09 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://127.0.0.1:9200/_template/sessions2_template?filter_path=**._meta 0/80 1ms 6ms
Dec  3 07:53:09 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://127.0.0.1:9200/sequence/sequence/fn-localhost 0/90 0ms 5ms
Dec  3 07:53:51 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://127.0.0.1:9200/sequence/sequence/fn-localhost 2/160 0ms 42034ms
Dec  3 07:53:51 http.c:283 moloch_http_send_sync(): 1/1 SYNC 404 http://127.0.0.1:9200/stats/stat/localhost 0/68 0ms 3ms
Dec  3 07:53:51 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://127.0.0.1:9200/fields/field/_search?size=3000 0/13157 0ms 6ms

Program received signal SIGSEGV, Segmentation fault.
0x0000000000427165 in moloch_db_load_oui (name=name@entry=0x18ef7c0 "/data/moloch/etc/oui.txt") at db.c:1925
1925    db.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install moloch-1.6.0-1.x86_64

**Comment by awick** [comment]
> Followed directions for installing at http://blog.infosecmatters.net/2017/05/moloch-fpc.html 

FYI, these instructions aren't written or supported by us.

I think this was already fixed with 1.6.1
