### ISSUE TITLE
MolochCapture will not start "ERROR - OUI file /data/moloch/etc/oui.txt bad line"

### ISSUE THREAD

**Issue by crwdawg** [aol/moloch#970]
I have initialized the database, and my config.ini file shows elasticsearch=http://127.0.0.1:9200

Elasticsearch version: 5.6.8
Moloch version: 1.6.1-1
jre - 8u192-Linux-x64
OS Name: CentOS 7 (3.10.0-862.x86_64
Installed via RPM

Stack Trace.

[root@localhost etc]# **gdb /data/moloch/bin/moloch-capture**
<snip>
Reading symbols from /data/moloch/bin/moloch-capture...done.
(gdb) **run /data/moloch/bin/moloch-capture**
Starting program: /data/moloch/bin/moloch-capture /data/moloch/bin/moloch-capture
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe2b3d700 (LWP 3120)]
[Thread 0x7fffe2b3d700 (LWP 3120) exited]
Dec  3 09:55:18 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/_template/sessions2_template?filter_path=**._meta 0/80 6ms 29ms
Dec  3 09:55:18 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/sequence/sequence/fn-localhost 0/91 0ms 3ms
Dec  3 09:55:18 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/sequence/sequence/fn-localhost 2/161 0ms 35ms
Dec  3 09:55:18 http.c:283 moloch_http_send_sync(): 1/1 SYNC 404 http://localhost:9200/stats/stat/localhost 0/68 0ms 5ms
Dec  3 09:55:18 http.c:283 moloch_http_send_sync(): 1/1 SYNC 200 http://localhost:9200/fields/field/_search?size=3000 0/13157 0ms 8ms
Dec  3 09:55:18 db.c:1900 moloch_db_load_oui(): **ERROR - OUI file /data/moloch/etc/oui.txt bad line '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">'**
[Inferior 1 (process 3116) exited with code 01]
Missing separate debuginfos, use: debuginfo-install moloch-1.6.1-1.x86_64

**Comment by awick** [comment]
I would suggest deleting the bad line.  Please come over to slack for questions since this isn't a bug.

**Comment by crwdawg** [comment]
Full error is:
ERROR - OUI file /data/moloch/etc/oui.txt bad line '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">'

**Comment by awick** [comment]
Looks like the file didn't get downloaded correctly, you could try running `moloch_update_geo.sh` again
