### ISSUE TITLE
How can I get full payload from Moloch

### ISSUE THREAD

**Issue by Show-Cheng** [aol/moloch#971]
I try to get full payload from Moloch by python2.7
but I only find scrPayload8 and dstPayload8(first eight byte of payload) in elasticsearch
where is the location of full payload in elasticsearch? 
Thanks a lot.

moloch version is 1.6.1
elasticsearch version is 6.4.2

**Comment by awick** [comment]
Please use slack for questions, github is for bugs/feature requests.

The full payload is not in elasticsearch, you have to use sessions.pcap on the viewer to get pcap.
