### ISSUE TITLE
Timeline does not honor GMT directive from non-UTC browser

### ISSUE THREAD

**Issue by philhagen** [aol/moloch#977]
**Elasticsearch version**: 5.6.14

**Moloch version**: 1.6.2

**OS name and version**: CentOS 7-6.1810

**How was Moloch built/installed:** rpm

The timeline does not reflect GMT/UTC time when that configuration option is set.  The session listing is fine.

Reference the two attached screenshots.  Both are from the same URL on the same Moloch Instance.  One from a browser where the system is set to EST, the other from a UTC browser.

![2018-12-17_06-57-56](https://user-images.githubusercontent.com/428886/50095013-81987600-01e2-11e9-98bb-8cdb5f214c92.png)

![2018-12-17_09-56-37](https://user-images.githubusercontent.com/428886/50095017-84936680-01e2-11e9-81c9-7e19b31e2472.png)

The earliest session is properly listed within the specified time frame, but the timeline is off.

**Comment by awick** [comment]
So there are a couple of timezone bugs here and just how moloch works bugs
1) The Start/End Entries need to be fixed to work in timezone selected instead of local
2) (not shown) the SPI data doesn't always convert to timezone selected
3) As far as the first item in the graph not matching, thats because its graphing last packet time.  I can't if you switch the pull down from lastpacket to firstpacket if it will graph first packet time or not, but maybe? :)

**Comment by philhagen** [comment]
I just confirmed the errant behavior exists with both firstpacket and lastpacket bounding.

for the time being, I can avoid the problem by directing users to a VM that's set to UTC, so local===UTC always.

**Comment by awick** [comment]
I guess I don't understand #3 then.  Do you have a url with demo.molo.ch that might help?

**Comment by philhagen** [comment]
I just realized I was totally missing what you were saying about the first session displayed.  My mistake...  I get it now, and that should not be a validating factor.  I hope that the clarification below will be better - and I think this is completely captured by your item 1.  (I realized my total misinterpretation after putting the stuff below together, so I'm including it in the event that it's helpful.  If not, please feel free to ignore.  Sorry for the confusion!)

Setup:
- Set system running Moloch to UTC time zone and clock
- Create user with "GMT" as time zone preference

UTC test:
- Log in as user from host with system time zone and clock set to UTC
- Set start time to `2017/11/06 22:45:00` in Moloch UI
- URL becomes `/sessions?graphType=lpHisto&seriesType=bars&stopTime=1510015649&startTime=1510008300`
```
$ date -u -d @1510008300
Mon Nov  6 22:45:00 UTC 2017
```
- Results are as shown:
![2018-12-20_10-27-39](https://user-images.githubusercontent.com/428886/50293572-eac9f480-0441-11e9-98ea-e0692714eb8c.png)

EST test:
- Log in as user from host with system time zone and clock set to EST
- Paste URL from UTC system into browser
- Results are shown:
![2018-12-20_10-29-07](https://user-images.githubusercontent.com/428886/50293666-1c42c000-0442-11e9-8a5c-f8861b7dc721.png)

**Comment by 31453** [comment]
Let me know if this does not address the problem and we can reopen the issue.
