### ISSUE TITLE
Detect browsers without required features and show error

### ISSUE THREAD

**Issue by awick** [aol/moloch#980]
On app load detect browsers that don't have the features required, such as class and such and show them an error and a link to the support browsers FAQ entry. https://github.com/aol/moloch/wiki/FAQ#what-browsers-are-supported

Looks like https://kangax.github.io/compat-table/es6/ has suggested checks for each thing by clicking on the (c).

vue suggests https://github.com/vuejs/vue/issues/770 looking for `typeof Object['__defineSetter__'] === 'function';`  also

**Comment by 31453** [comment]
added in 88c9b9a
