### ISSUE TITLE
moloch-capture attributing sessions to the wrong pcap file

### ISSUE THREAD

**Issue by jakup** [aol/moloch#984]
**Elasticsearch version**: 5.6
**Moloch version**: v1.6.2
**OS name and version**: CentOS-7.4
**How was Moloch built/installed:** rpm built via release/{Vagrantfile,build.yml}

**Provide logs, stack traces and steps to reproduce**:

Background: We're using moloch to process a large amount of pcap files, `moloch-capture --pcapdir _DIR_ --skip --recursive --monitor`, 

After deploying v1.6.2 we observed moloch-capture attributing sessions to the wrong pcap file.  This behavior only starts after moloch-capture has been running for some amount of time.  Restarting moloch-capture would fix the problem temporarily but after some amount of time it would resume.

Files processed and attributed to the wrong pcap file did not have a document inserted into /files_v5 index and as a result would be reprocessed again and again with each restart of moloch-capture.

We believe the problem is caused when  reader-libpcap-file.c calls `moloch_free_later(readerFileName[readerPos], ...` and then recycles `readerFileName[readerPos]` for use with a new pcap filename.  The problem occurs because writer-inplace.c maintains a mapping of readerPos to files_v5 `num` field in the `LOCAL uint32_t outputIds[]` variable but is unaware that readerPos now refers to a different file.  This results in writer_inplace_write failing to call writer_inplace_create/moloch_db_create_file and sessions being attributed to the wrong file.

We developed a quick band-aid to reset writer-inplace.c:outputIds[pos] to 0 when readerFileName[pos] is overwritten:

```
diff --git a/capture/moloch.h b/capture/moloch.h
index bcdd06d5..e10603e3 100644
--- a/capture/moloch.h
+++ b/capture/moloch.h
@@ -1139,6 +1139,8 @@ void moloch_writers_init();
 void moloch_writers_start(char *name);
 void moloch_writers_add(char *name, MolochWriterInit func);
 
+void writer_inplace_reset_outputId(uint8_t id);
+
 /******************************************************************************/
 /*
  * readers.c
diff --git a/capture/reader-libpcap-file.c b/capture/reader-libpcap-file.c
index ebcac2dd..7a4a0201 100644
--- a/capture/reader-libpcap-file.c
+++ b/capture/reader-libpcap-file.c
@@ -510,8 +510,10 @@ LOCAL void reader_libpcapfile_opened()
     }
 
     readerPos++;
-    if (readerFileName[readerPos])
+    if (readerFileName[readerPos]) {
         moloch_free_later(readerFileName[readerPos], g_free);
+        writer_inplace_reset_outputId(readerPos);
+    }
     readerFileName[readerPos] = g_strdup(offlinePcapFilename);
 
     int fd = pcap_fileno(pcap);
diff --git a/capture/writer-inplace.c b/capture/writer-inplace.c
index 8ed1fc55..54d5987a 100644
--- a/capture/writer-inplace.c
+++ b/capture/writer-inplace.c
@@ -88,3 +88,8 @@ void writer_inplace_init(char *UNUSED(name))
     else
         moloch_writer_write    = writer_inplace_write;
 }
+void writer_inplace_reset_outputId(uint8_t id) {
+    MOLOCH_LOCK(filePtr2Id);
+    outputIds[id] = 0;
+    MOLOCH_UNLOCK(filePtr2Id);
+}
```

**Comment by awick** [comment]
Good find, thanks!
