### ISSUE TITLE
Sessions stuck in buffer of moloch capture

### ISSUE THREAD

**Issue by RichardAHoward** [aol/moloch#987]
**Elasticsearch version**:
6.5.3
**Moloch version**:
1.6.2
**OS name and version**:
Centos 7
**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm
**Provide logs, stack traces and steps to reproduce**:
[capture2.log](https://github.com/aol/moloch/files/2737560/capture2.log)

**Comment by awick** [comment]
Fixed in dbab273e222a5b9860c6ceaa2fcb49eac0d7d0eb
