### ISSUE TITLE
Feature Request: Option button to display only Source or Destination packets on session

### ISSUE THREAD

**Issue by noperle** [aol/moloch#991]
Sometimes it is very handy to only look at src packets when you have a very long session. For example where you only want to look at POST from the HTTP session.

**Comment by awick** [comment]
Can you use the destination raw and source raw buttons?  If not how is this different?

**Comment by noperle** [comment]
Raw buttons will only download the packets and not display it. It would be nice to display directly. I´m thinking about a button side by |natural|ascii|utf8|hex| + |source|destination|

**Comment by awick** [comment]
It used to display it, have to see what changed.  There are already many buttons, have to figure out how to reduce.

**Comment by noperle** [comment]
Okey thanks :)

**Comment by noperle** [comment]
Awesome! Thank you Elyse =D
